### ISSUE TITLE
[EVENT] PaleoHackWeek 3

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1032]
### Summary

The PaleoHackWeek community is running another hackathon in about 10 days! This is similar to the previous hackathon's that they've run (though it will be 3 days instead of 2).

Note that this hub is already running at https://paleohack2021.hackathon.2i2c.cloud/, but we'll probably need to ready the hub for another scale-up event, so creating this issue so that we can track it.

In addition, @CommonClimate and @khider were hoping to do a **trial run on March 9th** where they'd ask the attendees to try logging in to make sure the scaling worked (even though they plan to start on March 10th).

### Event Info

- **Community Representative:** @commonclimate and @khider
- **Event begin:** March 9th
- **Event end:** March 11th
- **Active times:** Roughly working hours on US/Pacific
- **Number of attendees:** ~60
- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Hub info

- **Hub URL**: https://paleohack2021.hackathon.2i2c.cloud/hub/login?next=%2Fhub%2F
- **Hub decommisioned after event?**: No

### Task List

**Before the event**

- [x] Dates confirmed with the community representative and added to Hub Events Calendar
- [x] **One week before event** Hub is running.
- [x] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    </details>  

- [x] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [x] Confirm event is finished.
- [x] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [x] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by choldgraf** [comment]
cc @khider and @commonclimate - it would be helpful if you could run a representative notebook from top to bottom a day or two before the event, just to confirm that the environment is correct and such!

**Comment by khider** [comment]
Thanks! Yes, I'm hoping to release the latest version of the code today or tomorrow so I can rebuild the environment and see if everything works. 

They will be busy with another platform on Wednesday March 9th (some may make it to the hub during the night between 9th and 10th).

**Comment by choldgraf** [comment]
Sounds good @khider !

Also just in case it'll take a bit of time to figure out stress-testing stuff, I opened an issue so that we can track it: https://github.com/2i2c-org/infrastructure/issues/1041

**Comment by khider** [comment]
@choldgraf We updated all the notebooks and environment. The container built automatically and I grabbed the image from quay for the Configurator but this is the error I get when restarting:


![Screen Shot 2022-03-03 at 3 44 41 PM](https://user-images.githubusercontent.com/11758571/156672044-5e20e76b-b2f5-4107-8162-b7fa05758ae5.png)

**Comment by choldgraf** [comment]
Hmmm - that _might_ be because you're just using the tag and not the fully-resolved name. I just tried setting it to:

`2i2c/paleohack-2021:cb5757e7c9f8`

try logging in and see if that works?

**Comment by choldgraf** [comment]
ah it needed to be the fully-resolved name:

```
quay.io/2i2c/paleohack-2021:cb5757e7c9f8
```

it should be working now

**Comment by choldgraf** [comment]
I opened up a PR to clarify the image tag prompt here: https://github.com/yuvipanda/jupyterhub-configurator/pull/11

**Comment by khider** [comment]
Thanks! I got it to run but now I can't get it to sync with GitHub. It tells me that it did but actually didn't for mine. When opening a new user server, I don't get the notebooks at all.

**Comment by sgibson91** [comment]
What's your nbgitpuller link @khider ?

**Comment by khider** [comment]
https://paleohack2021.hackathon.2i2c.cloud/hub/login?next=%2Fhub%2Fuser-redirect%2Fgit-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252FLinkedEarth%252FpaleoHackathon%26urlpath%3Dtree%252FpaleoHackathon%252F%26branch%3Dmain

**Comment by choldgraf** [comment]
@khider I just tried clicking that link and it worked for me ). Can you share a specific notebook that you expect to be there, but that is not there?

Here are the notebooks in my folder:

![image](https://user-images.githubusercontent.com/1839645/156812193-5f4b5ab5-5b61-4e39-92dc-cf55996dae04.png)

**Comment by sgibson91** [comment]
> I just tried clicking that link and it worked for me

same here

**Comment by khider** [comment]
For me, it seems to merge old/new versions of the notebooks.

This is the hub version:

![image](https://user-images.githubusercontent.com/11758571/156819753-16aca487-ce77-4a01-9ace-00617b55c5fd.png)

But this is the version on GitHub

![image](https://user-images.githubusercontent.com/11758571/156819834-751f7263-4594-4149-b19d-e2ffbf0d6a9e.png)


If this is just me (because I have been using the same account for 3 hackathons), then not a problem.

**Comment by khider** [comment]
And the merge decision is somewhat random. I changed the preamble from the version we had and it got updated but the working with datasets didn't.

**Comment by choldgraf** [comment]
Hmmm - the language around the merging behavior is defined here: https://jupyterhub.github.io/nbgitpuller/topic/automatic-merging.html

Does that help disambiguate at all? If we can clarify that language let me know and we can update it.

**Comment by khider** [comment]
Yes, that makes more sense now. I'll delete my files and retry.

**Comment by khider** [comment]
Perfect!

**Comment by choldgraf** [comment]
wohoo! I am curious - where could advertise this link in the [2i2c docs](docs.2i2c.org) so it is discoverable?

**Comment by khider** [comment]
I have been building my own Google Doc with all the links.

**Comment by choldgraf** [comment]
Ah cool - well, maybe once this round is over you'd be willing to tell us all of the things that were confusing, and that we could improve in the docs? :-)

**Comment by khider** [comment]
We are ready on the notebook side. Should I try to launch all the servers at the same time?

**Comment by choldgraf** [comment]
I believe that @yuvipanda has provisioned a dedicated set of nodes for the event (see https://github.com/2i2c-org/infrastructure/pull/1058) so there's no problem in giving it a shot if you like

**Comment by khider** [comment]
Thank you! And we're all ready to go.

**Comment by yuvipanda** [comment]
@khider sorry, it's not done yet, I'm doing that by the next hour - sorry.

**Comment by yuvipanda** [comment]
@khider ok I've scaled up a lot of nodes (20), and enabled an additional performance optimization (pre-pulling the existing image).

**Comment by khider** [comment]
BTW, everything is working great!

**Comment by choldgraf** [comment]
![YayYesGIF](https://user-images.githubusercontent.com/1839645/157949155-628db8d7-123c-49ea-bd7b-f1c09270704d.gif)

**Comment by choldgraf** [comment]
Hey @khider - just want to confirm that this event is over, and that you no longer need the extra nodes for the event!

**Comment by yuvipanda** [comment]
I just set the minimum node size to 0.

**Comment by khider** [comment]
Yes, we're done! Thank you; everything worked great!

**Comment by choldgraf** [comment]
Wohoo, thanks @khider ! If you like, it'd be helpful for any thoughts that you might have about how the event went:

If you like, could you answer any of the following questions?

- Did the infrastructure behave as expected?
- Anything that was confusing or could be improved?
- Any extra functionality you wish you would have had?
- Could you share a story about how you used the hub?
- Any other feedback that you'd like to share?

I'll close this one since I don't think there are any more actions to take!

**Comment by yuvipanda** [comment]
@choldgraf I need to put the hub back into the general pool (rather than to its own), will close when done.

**Comment by yuvipanda** [comment]
Done in https://github.com/2i2c-org/infrastructure/pull/1123
