### ISSUE TITLE
[EVENT] Openscapes NASA Cloud Data Services Telecon (1 hour)

### ISSUE THREAD

**Issue by jules32** [2i2c-org/infrastructure#1075]
### Summary

Hi All, apologies for the late notice. 

This is a one-time event: a 1-hour hands-on demo for the NASA Cloud Data Services Bi-Weekly Telecon, led by Amy Steiker (NSIDC) as part of NASA-Openscapes.

### Event Info

- **Community Representative:** @jules32, @erinmr
- **Event begin:** March 10, 2022
- **Event end:** March 10, 2022
- **Active times:** 9:30-10:30am Pacific
- **Number of attendees:** 40-50
- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Hub info

- **Hub URL**: https://openscapes.2i2c.cloud/hub/
- **Hub decommisioned after event?**: no

### Task List

**Before the event**

- [ ] Dates confirmed with the community representative and added to Hub Events Calendar
- [ ] **One week before event** Hub is running.
- [ ] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  

- [ ] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [ ] Confirm event is finished.
- [ ] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [ ] Hub decommissioned (if needed).
- [ ] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by yuvipanda** [comment]
I'll scale up the hub and keep an eye out during the event as well.

**Comment by jules32** [comment]
Thank you so much @yuvipanda 🚀

**Comment by damianavila** [comment]
@jules32, I just tested the scale-up event and things worked as expected.
I will give @yuvipanda some free time 😉 and I will be scaling up the cluster tomorrow morning (I am 5 hours ahead of PT) to minimize the cost associated with a too early scale-up process but making sure the cluster is ready for the time you need it.
I will post updates here as I trigger those scale events.

Btw, I assume I should scale down the cluster by afternoon? evening? (not sure if people will stay a little bit longer playing around).

**Comment by jules32** [comment]
Thanks so much @damianavila ! That sounds like a great plan. 

Yes scaling down by the evening would be great in case folks play around a little bit more during the day/afternoon. Thank you!

**Comment by damianavila** [comment]
FYI, I have scaled up the cluster to 50 nodes (supporting the small instances you used in [previous events](https://github.com/2i2c-org/infrastructure/issues/870#issuecomment-991378157)).
I have also successfully launched one small instance without any issues (starting the container took less than one minute).

**Comment by damianavila** [comment]
FYI, I have scaled down the cluster since the usage was in levels close to the size before the event started.
I did not see any irregularities but feel free to post here any feedback you may have about your experience.

**Comment by jules32** [comment]
That's great @damianavila, thank you. It was a great experience, I didn't see the peak number of folks using the hub together but 42 people had requested access in advance so hopefully close to that number were all following along with the tutorial.

**Comment by damianavila** [comment]
This is the usage profile in case you are interested (14:30 ARG time is the start of the event):

<img width="619" alt="Screen Shot 2022-03-10 at 19 55 59" src="https://user-images.githubusercontent.com/1640669/157773681-4a6e58db-48df-4b73-9676-f46d5cab00e2.png">

Glad to hear everything run smoothly, @jules32!!

**Comment by choldgraf** [comment]
I'll close this issue as I believe the event is now over!

**Comment by choldgraf** [comment]
@damianavila just a quick question: do you plan to leave the dedicated node pool for the next event? Or did you delete it as well?

**Comment by yuvipanda** [comment]
@choldgraf I think this is its own cluster, so a dedicated nodepool is not necessary.

**Comment by choldgraf** [comment]
@yuvipanda good point :-)
