### ISSUE TITLE
[EVENT] Openscapes SWOT Ocean Workshop

### ISSUE THREAD

**Issue by jules32** [2i2c-org/infrastructure#1076]
### Summary

Hi All, This is a 2-day hands-on demo for the SWOT Oceanography Cloud Workshop for a small group of researcher principal investigators coordinated by Catalina Oaida (PODAAC) as part of NASA-Openscapes.

### Event Info

- **Community Representative:** @jules32, @erinmr
- **Event begin:** March 16, 2022
- **Event end:** March 17, 2022
- **Active times:** 9:00am 1:00pm Pacific
- **Number of attendees:** 20-30
- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Hub info

- **Hub URL**: https://openscapes.2i2c.cloud/hub/
- **Hub decommisioned after event?**: no
### Task List

**Before the event**

- [x] Dates confirmed with the community representative and added to Hub Events Calendar
- [ ] **One week before event** Hub is running.
- [ ] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  

- [x] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [x] Confirm event is finished.
- [x] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [ ] Hub decommissioned (if needed).
- [x] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by yuvipanda** [comment]
@damianavila can you do this too?

**Comment by damianavila** [comment]
Yep, I can take care of this one too, @yuvipanda.

**Comment by damianavila** [comment]
FYI, I have successfully already scaled up the cluster to 30 nodes.

Btw, according to @yuvipanda, the support ticket about the Dask Gateway issue (https://2i2c.freshdesk.com/a/tickets/105) was already worked out (and solved) and things should be running as expected.

**Comment by jules32** [comment]
Great, thanks so much @damianavila !

**Comment by damianavila** [comment]
FYI, I have successfully scaled down the cluster since I saw user numbers around the levels before the start of the event.

<img width="575" alt="Screen Shot 2022-03-16 at 18 58 49" src="https://user-images.githubusercontent.com/1640669/158698255-2e397a7a-9001-48dc-9414-9325b49008b3.png">

Since we did not hear anything more about the Dask Gateway issue, I presume everything was working smoothly. Let us know if that is not the case.

Btw, I will be scaling up the cluster again tomorrow at about the same time I did it today.

**Comment by betolink** [comment]
Dask Gateway seems to be working again @damianavila, we're still trying to figure out what would be a good strategy for data persistence in the worker nodes but that's a different story. Thanks a lot!

**Comment by damianavila** [comment]
> Dask Gateway seems to be working again

Glad to know that is the case!

FYI, I have successfully already scaled up the cluster to 30 small nodes again.

**Comment by damianavila** [comment]
> we're still trying to figure out what would be a good strategy for data persistence in the worker nodes but that's a different story

I think @consideRatio might have some thoughts about this one since he has been in contact with Dask Gateway lately.

**Comment by consideRatio** [comment]
> we're still trying to figure out what would be a good strategy for data persistence in the worker nodes but that's a different story

Hmm... I think the workers, which will be ephemeral when they shut down, can persist some data in memory and maybe on storage while they live. I recall a concept of managed and unmanaged data by the dask workers, and where managed data is supposed to be collected at some point in time from someplace else etc, while unmanaged is not collectable data.

I know it can be tricky to understand and know what kind of data should be considered managed, and not cleared, by dask workers. I recall the difference can be with regards to what kinds of variables your functions that run on your dask workers etc or what is being returned hmm.

I'm not a dask user, I've just been a person helping out trying to debug issues really. Well this captures my vague understanding about the situation. I think questions about this could be relevant to ask in https://dask.discourse.group/ where they will be more visible and re-findable if answered.

**Comment by betolink** [comment]
I don't think the Dask worker persistence is an urgent issue. Some tasks (embarrassingly parallel) require reprocessing a lot of files and dumping the results into an attached storage (available on each worker node) is more practical than sending them back to the scheduler. For cloud workflows a common pattern is to pass the workers S3 credentials so each task can persist data to an S3 bucket, so I'm guessing that's probably the path will have to take if we want to do some big data processing (costs aside).

**Comment by damianavila** [comment]
FYI, I have successfully scaled the cluster down.

Btw, I noticed there were more than 40 users at some time during the day as it is shown below:

<img width="690" alt="Screen Shot 2022-03-17 at 19 34 07" src="https://user-images.githubusercontent.com/1640669/158905284-ec9d834f-6512-4dab-8afe-8b42d2688003.png">

Given the fact we are a few users above the "planned" attendance (and arriving slowly), I guess most of your attendees did not notice the additional delay at the time to spin up a new node. Btw, if you are expecting more people at the last minute, let's know and we will try to accommodate the cluster warming as well.

As usual, feel free to write back any feedback you may have. Otherwise, I will close this issue in the next few hours/days.

**Comment by jules32** [comment]
Thank you @damianavila et al! This worked great this week, thank you so much. Yes we had some more than the "planned" attend and they didn't notice any delay. Thank you - in the future we'll let you know as there are more folks joining last minute. 

We really appreciate your help! Really awesome to help folks get oriented in the Cloud :)
