### ISSUE TITLE
[EVENT] IceSat Hackweek

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1115]
### Summary

The ICESAT 2 Hackweek is coming up, this is an issue to track prepping their cluster for a bump in users!

### Event Info

- **Community Representative:** @scottyhq 
- **Event begin:** March 21st
- **Event end:** March 25th
- **Active times:** US/Pacific
- **Number of attendees:** 95
- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Hub info

- **Hub URL**: https://uwhackweeks.2i2c.cloud/
- **Hub decommisioned after event?**: No!
- [Schedule for the Hackweek](https://icesat-2.hackweek.io/#schedule)

### Task List

**Before the event**

- [ ] Dates confirmed with the community representative and added to Hub Events Calendar
- [ ] **One week before event** Hub is running.
- [ ] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  

- [ ] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [ ] Confirm event is finished.
- [ ] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [ ] Hub decommissioned (if needed).
- [ ] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by scottyhq** [comment]
thanks @choldgraf ! Number of attendees = 95

**Comment by consideRatio** [comment]
### Notes from tech team sprint meeting

An email has been sent with requirements:
- Storage space question (we are good, it is unrestricted)
- AWS credits applied to the relevant AWS account (we need to look into this)

@damianavila suggests we warm up user nodes, @yuvipanda suggests that we ask if they want warmup of node pools.

**Comment by sgibson91** [comment]
Ah sorry @choldgraf - you are assigned in reference to working with @yuvipanda to figure out the credits and billing situation for this cluster :) Not the node pool part!

**Comment by choldgraf** [comment]
ah yes! 100% I am happy to help with that, I have a vested interest in not paying for things with my credit card haha

**Comment by scottyhq** [comment]
Hi folks, having trouble with scaling as we ramp up active use. I sent an email to support@2i2c.freshdesk.com (is that an alias for support@2i2c.org?), but including the screenshot here too:

 
<img width="1131" alt="Screen Shot 2022-03-17 at 12 01 52 PM" src="https://user-images.githubusercontent.com/3924836/158879226-6d18212d-fe9e-459a-9737-1a2930166987.png">

**Comment by choldgraf** [comment]
Quick updates here:

- We've resolved the issue that @scottyhq mentioned above (via #1128)
- I've added our Expensify card to the AWS billing, and we have #1142 to track the credits
- So I'm removing myself from this issue, and we can close it when the hackweek is done!

**Comment by yuvipanda** [comment]
The hackweek is done! Everything went great, I think! Please let me know if anything else needs to come out of this, @scottyhq!
