### ISSUE TITLE
[Incident] uwhackweeks hub not spawning due to AWS quota limits

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1128]
### Summary

https://2i2c.freshdesk.com/a/tickets/109 reports that users can't spin up new nodes, even the smallest. This is due to the AWS account running out of quota.

### Impact on users

The hub is unusable for new users.

### Important information

- Hub URL: https://uwhackweeks.2i2c.cloud/
- Support ticket ref: https://2i2c.freshdesk.com/a/tickets/109
- 
### Tasks and updates

- [x] Discuss and address incident, leaving comments below with updates
- [x] Incident has been dealt with or is over
- [ ] Copy/paste the after-action report below and fill in relevant sections
- [ ] Incident title is discoverable and accurate
- [ ] All actionable items in report have linked GitHub Issues

<details>
<summary>After-action report template</summary>

```
# After-action report

These sections should be filled out once we've resolved the incident and know what happened.
They should focus on the knowledge we've gained and any improvements we should take.

## Timeline

_A short list of dates / times and major updates, with links to relevant comments in the issue for more context._

All times in {{ most convenient timezone}}.

- {{ yyyy-mm-dd }} - [Summary of first update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of another update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of final update](link to comment)


## What went wrong

_Things that could have gone better. Ideally these should result in concrete
action items that have GitHub issues created for them and linked to under
Action items._

- Thing one
- Thing two

## Where we got lucky

_These are good things that happened to us but not because we had planned for them._

- Thing one
- Thing two

## Follow-up actions

_Every action item should have a GitHub issue (even a small skeleton of one) attached to it, so these do not get forgotten. These issues don't have to be in `infrastructure/`, they can be in other repositories._

### Process improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Documentation improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Technical improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]
```

</details>

**Comment by yuvipanda** [comment]
https://us-east-1.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=9786816411&language=en is the case where I've asked for a bump in the quota.

**Comment by choldgraf** [comment]
It sounds like the next step here is just to wait for AWS to respond. But for a long-term question, is this something we'll need to do for every new AWS account? It [seems like quotas are account- and region-specific](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) so I guess we should be prepared to run into this issue the first time a new account gets a bump in usage?

**Comment by scottyhq** [comment]
> https://us-east-1.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=9786816411&language=en is the case where I've asked for a bump in the quota. 

Not sure if the region in that URL matters, but just wanted to flag that we're running in us-west-2.  

> is this something we'll need to do for every new AWS account? 

I definitely had to do this for the Pangeo AWS account a number of years back, but it appears AWS has since moved from per-instance-type limits to vCPU total limits:
https://aws.amazon.com/ec2/faqs/#EC2_On-Demand_Instance_limits

| On-Demand Instance Limit Name | Default vCPU Limit
| -- | -- |
| Running On-Demand Standard (A, C, D, H, I, M, R, T, Z) instances | 1152 vCPUs |

Which clearly fine for events where everyone requests a machine with 2vCPU? I'm just surprised we got to this limit so quickly... unless there is some other service quota at play

**Comment by yuvipanda** [comment]
> Not sure if the region in that URL matters, but just wanted to flag that we're running in us-west-2.

Good catch! It looks like the support is hosted in us-east-1 regardless. I explicitly specified we want us-west-2 in the body of the ticket:

![image](https://user-images.githubusercontent.com/30430/158905829-a2973756-3c0e-4bc8-8181-d20acf1a1f99.png)


Apparently the limit we had was... 32!? 1152 would have been plenty fine.

**Comment by yuvipanda** [comment]
They bumped up the limit to 1024 and we're all good now!

**Comment by choldgraf** [comment]
I think that this one is now resolved - I am not sure if there's anything we can do as a follow-up improvement on this. Maybe we could document that a quota bump will be commonly-needed for AWS quickly? But I suspect that we would have ran into this problem either way. @yuvipanda is there anything you had in mind?

**Comment by yuvipanda** [comment]
@choldgraf I think we should document 'check quotas' as a step before any event, and also after creating a new AWS account. We can close this after that. Not sure where that documentation should go though.

**Comment by choldgraf** [comment]
@yuvipanda how about this:

- https://github.com/2i2c-org/infrastructure/pull/1149

**Comment by consideRatio** [comment]
Closing as it seems resolved with related docs updated, and uwhackweeks is removed!

**Comment by consideRatio** [comment]
@choldgraf you removed "type: hub incident" and it made me think it didn't merit being documented in https://github.com/2i2c-org/incident-reports/tree/main/reports, but I figure it should be.

### Action point

- [ ] Add an entry about this in https://github.com/2i2c-org/incident-reports/tree/main/reports.
