### ISSUE TITLE
[EVENT] Openscapes NASA ECOSTRESS Workshop

### ISSUE THREAD

**Issue by jules32** [2i2c-org/infrastructure#1173]
### Summary

Hi 2i2c team! We've got a 2- half-day event next week and would appreciate you prewarming the JupyterHub for us. Please let us know if you have any questions. Thank you!

### Event Info

NASA Openscapes workshop with ECOSTRESS group

- **Community Representative:** @jules32, @erinmr
- **Event begin:** April 12
- **Event end:** April 13
- **Active times:** 2pm- 5pm US/Pacific each day
- **Number of attendees:** 40-50 people
- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Hub info

- **Hub URL**: https://openscapes.2i2c.cloud/hub/
- **Hub decommisioned after event?**: no

### Task List

**Before the event**

- [x] Dates confirmed with the community representative and added to Hub Events Calendar
- [ ] **One week before event** Hub is running.
- [ ] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  

- [ ] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [ ] Confirm event is finished.
- [ ] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [ ] Hub decommissioned (if needed).
- [ ] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by choldgraf** [comment]
Hey @jules32 - thanks for giving us a heads up. In the future could you please let us know about events via `support@2i2c.org`? We are trying to use that as a single place to track requests coming in from communities, so that we don't lose track of them.

**Comment by jules32** [comment]
Hi @choldgraf , yes, absolutely.

Shall I include the Summary, Event Info, and Hub Info like I did above or is there anything more (or less) that you need when we email?

Thank you!

**Comment by damianavila** [comment]
> Shall I include the Summary, Event Info, and Hub Info like I did above or is there anything more (or less) that you need when we email?

The email would be a simple one-line request, @jules32.
The support agent will acknowledge the request and reply to you providing you with a GH issue/form link (like this one) where you will be able to complete all the necessary details.

**Comment by jules32** [comment]
Ah, excellent. Thanks @damianavila !

**Comment by damianavila** [comment]
FYI, the cluster has been scaled up to min 50 nodes.
Have a great event!

**Comment by yuvipanda** [comment]
I've turned down the cluster back to its smaller state now.
