### ISSUE TITLE
[Decommission Hub] uwhackweeks.2i2c.cloud

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1336]
### Summary
Based on https://github.com/2i2c-org/infrastructure/issues/1309#issuecomment-1136277855, we should turn down the ICESat Hackweek hub at uwhackweeks.2i2c.cloud on June 1.

### Info

- **Community Representative:** 
- **Link to New Hub issue:** 
- **Proposed end date:** June 1

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [x] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
  - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration

#### Phase II - Hub Removal

- [ ] (Optional) Migrate data from the hub
- [x] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` file
- [x] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml file.
- [x] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [x] Delete the hub's authentication application on auth0 or GitHub

**Comment by yuvipanda** [comment]
@scottyhq just to confirm that on June 1, I'll turn off the hub at uwhackweeks.2i2c.cloud *and* delete all the user home directories.

**Comment by scottyhq** [comment]
>  confirm that on June 1, I'll turn off the hub at uwhackweeks.2i2c.cloud and delete all the user home directories. 

That is correct!

**Comment by scottyhq** [comment]
One other request @yuvipanda it would be great to have a plot / summary of the total cloud costs for this event (basically this figure extended through June 1 https://github.com/2i2c-org/infrastructure/issues/1142#issuecomment-1078544468). Cheers!

**Comment by GeorgianaElena** [comment]
The hub was deleted and the user home dirs deleted 🚀 Closing this.
