### ISSUE TITLE
[Decommission Hub] anu.pilot.2i2c.cloud -> Monday 20th June 2022

### ISSUE THREAD

**Issue by mmcky** [2i2c-org/infrastructure#1364]
### Summary

The final exam for the test class EMET2007 is on Friday 17 June (final exam day)

It would be great to have the pilot closed on Monday 20th June 2022 so students can save any work over the weekend. 

### Info

- @mmcky
- **Link to New Hub issue:** https://github.com/2i2c-org/infrastructure/issues/991
- **Proposed end date:** 20th June 2022

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [x] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
  - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration

#### Phase II - Hub Removal

- [ ] (Optional) Migrate data from the hub
- [ ] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` file
- [ ] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml file.
- [ ] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [ ] Delete the hub's authentication application on auth0 or GitHub

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [ ] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [ ] Remove the following files from the repository:
  - The associated `config/clusters/<cluster_name>` directory
  - The associated CI deployer key in `secrets/`
  - Remove the name of the cluster from [CI](https://github.com/2i2c-org/infrastructure/tree/HEAD/.github/workflows/deploy-hubs.yaml)

**Comment by GeorgianaElena** [comment]
Hi @mmcky! There are some upcoming changes related to authentication that require some migration of the ANU auth config (https://github.com/2i2c-org/infrastructure/pull/1403).

But I noticed this issue and that the proposed decommissioning day was yesterday. So I have a couple of quick questions that would help us in the decommission process:

- [ ] Can you please confirm it is safe to delete the hub and it's no longer in use?
- [ ] Can we delete the user home directories, or do you want to migrate the user's data to somewhere else before deleting the hub?

**Comment by mmcky** [comment]
@GeorgianaElena thanks for checking in on this. I can't seem to edit your check boxes.

- [x] confirmed to delete and no longer in use
- [x] you may remove and delete user home directories.
