### ISSUE TITLE
[EVENT] Jack Eddy Symposium [DECOMMISSION SCHEDULED]

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1384]
### Summary

The [3rd Jack Eddy Symposium](https://cpaess.ucar.edu/meetings/eddy-symposium-2022) will take place June 6 - 11 in Vail CO. The conference honors the late [Jack Eddy](https://en.wikipedia.org/wiki/John_A._Eddy), an astronomer who pioneered the field of heliophysics and demonstrated that the variability of the Sun can be seen in signals (e.g. tree rings with carbon dating) on Earth. Jack Eddy approached his research using interdisciplinary tools and appears to have inspired a next generation of Sun-Earth-Climate researchers.

Website: https://cpaess.ucar.edu/meetings/eddy-symposium-2022

 The new hub was deployed here: https://github.com/2i2c-org/infrastructure/issues/1329

### Event Info

- **Community Representative:** @dan800
- **Event begin:** June 6th
- **Event end:** June 10th
- **Active times:** 8 AM MT - 6 PM MT
- **Number of attendees:** ~45
- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Hub info

- **Hub URL**: https://jackeddy.2i2c.cloud/
- **Hub decommisioned after event?**: TBD (@dan800, can you confirm?)

### Task List

**Before the event**

- [x] Dates confirmed with the community representative and added to Hub Events Calendar.
- [x] Quotas from the cloud provider are high-enough to handle expected usage.
- [x] **One week before event** Hub is running.
- [x] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  
- [x] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [x] Confirm event is finished.
- [ ] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [ ] Hub decommissioned: June 22nd
- [ ] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by damianavila** [comment]
@dan800, can you revisit the event info section and reply to the questions I raised above? Thanks!

cc @colliand and @fperez because they will participate in the event and they might have more event specfic information.

**Comment by damianavila** [comment]
Accordingly to this comment from @fperez: https://github.com/2i2c-org/infrastructure/issues/1329#issuecomment-1145064806, it seems warming the cluster might be needed (total number of participant to confirm yet).

> Quotas from the cloud provider are high-enough to handle expected usage.
> 1 day before event, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

@yuvipanda, do you think we have enough quotas for this event? Are you willing to warm the cluster on your Monday morning (should be a couple of hours before the start of the event) so it is hot for the attendes arrival? Not sure yet how much we want to warm it and I guess it will depend on the confirmed expected attendes number.

**Comment by damianavila** [comment]
>  Confirm with Community Representative that their workflows function as expected.

This is being handled in the hub issue itself: https://github.com/2i2c-org/infrastructure/issues/1329#issuecomment-1145917517

**Comment by dan800** [comment]
> 

Apologies for the slow response - the number of attendees is around 45.

**Comment by dan800** [comment]
@damianavila and @yuvipanda Thanks so much for all your work on this hub. It really made a huge difference in the event and made it a huge success. I spoke with @colliand at the end and we agreed that the hub can be closed down next weekend. @colliand can you please confirm the exact date? I think the main need is to give attendees the oppotunity to copy any notebooks to the event github repo.
Again, many thanks!

**Comment by damianavila** [comment]
This is great to hear, @dan800!!
After @colliand confirmation, we can plan and schedule the decommissioning process.

In the meantime, we are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!

- Did the infrastructure behave as expected?
- Anything that was confusing or could be improved?
- Any extra functionality you wish you would have had?
- Could you share a story about how you used the hub?
- Any other feedback that you'd like to share?

@colliand already shared some feedback but it would be helpful to have some specific from you as well, @dan800.
 
Thanks!

**Comment by colliand** [comment]
Thanks Dan. In the spirit of the conference, let's plan to have the hub shut down on summer solstice. The hub will likely be unavailable on June 22.

**Comment by dan800** [comment]
Sounds good! I can let folks know on slack.

**Comment by yuvipanda** [comment]
There were 27 users and 6G of home directory storage. am deleting it all now.

**Comment by yuvipanda** [comment]
hub is gone!

**Comment by damianavila** [comment]
#1466 LGTM, so I think we can close this one when that one is finally merged.
