### ISSUE TITLE
[Decommission Hub] farallon.2i2c.cloud

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1454]
### Summary

@cgentemann reached out to me and said this hub can now be decomissioned, as the users have moved to an ESIP run hub.

### Info

- **Community Representative:** @cgentemann
- **Link to New Hub issue:** https://github.com/2i2c-org/infrastructure/issues/135 maybe
- **Proposed end date:** 

#### Phase I

- [ ] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [ ] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
    - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration
  - [ ] If no, confirm it is ok to delete all the data stored in the user home directories

#### Phase II - Hub Removal

- [ ] Manage existing data (migrate data from the hub or delete it)
- [ ] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` file
- [ ] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [ ] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [ ] Delete the hub's authentication application on auth0 or GitHub

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [ ] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [ ] Remove the following files from the repository:
  - The associated `config/clusters/<cluster_name>` directory
  - The associated CI deployer key in `secrets/`
  - Remove the name of the cluster from [CI](https://github.com/2i2c-org/infrastructure/tree/HEAD/.github/workflows/deploy-hubs.yaml)

**Comment by yuvipanda** [comment]
I got confirmation from @cgentemann that it's ok to delete everything

**Comment by damianavila** [comment]
@yuvipanda, since you closed it I assume you remove the hub and clean up everything in the Farallon AWS land, can you confirm? Thanks!!
