### ISSUE TITLE
[New Hub] NeuroHackademy 2022

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1505]
### Hub Description

A general description of the hub requested lives here: https://github.com/2i2c-org/infrastructure/issues/1300#issue-1232600616

### Community Representative(s)

@arokem

### Important dates

- **Target start date**: July 15th
- **Required start date**: July 22th
- **Any important dates for usage**: 
  - Event begin: July 25th
  - Event end: August 5th

### Hub Authentication Type

GitHub Authentication (e.g., @mygithubhandle)

### Hub logo information

- **URL to Hub Image**: https://user-images.githubusercontent.com/118582/177910655-a2403aeb-9c08-44fd-94a8-543b5070f6a9.png
- **URL for Image Link**: https://neurohackademy.org/ (todo: confirm this is it)

### Hub user image

- Repository for user image: https://github.com/neurohackademy/hub-image-2022
- User image registry: quay.io
- User image tag and name: quay.io/arokem/nh-jhub-2022

### Extra features you'd like to enable

- [x] Specific cloud provider or datacenter: GCP or AWS is preferable.
- [ ] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### Other relevant information

More detailed information about the requirements:
* General needs + some tiny specifics: https://github.com/2i2c-org/infrastructure/issues/1300#issue-1232600616
* More specifics: https://github.com/2i2c-org/infrastructure/issues/1300#issuecomment-1128126597
* Template customization:  https://github.com/2i2c-org/infrastructure/issues/1300#issuecomment-1145530640
* Zoom links under auth: https://github.com/2i2c-org/infrastructure/issues/1500

### Hub URL

neurohackademy.2i2c.cloud

### Hub Type

basehub

### Tasks to deploy the hub

- [x] Engineer who will deploy the hub is assigned
- [x] Deploy information filled in above
- [x] Initial Hub deployment PR: https://github.com/2i2c-org/infrastructure/pull/1507
- [x] Administrators able to log on
- [x] Community Representative satisfied with hub environment
- [x] Hub now in steady-state

**Comment by damianavila** [comment]
Event issue ref: https://github.com/2i2c-org/infrastructure/issues/1300

**Comment by damianavila** [comment]
@arokem, do you have any preference for the name of the hub? Any logo image link that you want to share with us?

**Comment by damianavila** [comment]
@GeorgianaElena is going to lead on this deployment with @yuvipanda as a helper resource (in fact he is already helping/building new functionality for this one with https://github.com/2i2c-org/infrastructure/pull/1502)!

**Comment by arokem** [comment]
Hey @damianavila - thanks for kicking this off. And hello @GeorgianaElena : excited to work with you on this! And always glad to have @yuvipanda on board!

If neurohackademy.2i2c.cloud works as a name for the hub (is that what you meant?) that would be great. 

Here is the logo we use for our Slack/etc: 

![image](https://user-images.githubusercontent.com/118582/177910655-a2403aeb-9c08-44fd-94a8-543b5070f6a9.png)

**Comment by GeorgianaElena** [comment]
Hey @arokem! I just did an initial deployment of the hub at https://neurohackademy.2i2c.cloud (PR here https://github.com/2i2c-org/infrastructure/pull/1507) 🚀 

## Initial setup of the hub
Right now the neurohackademy:
- uses CILogon for authentication and only allows and shows GitHub identity provider as an option
- hub admins are 2i2c folks + @arokem 
- user image is currently the default 2i2c one (defined at https://github.com/2i2c-org/2i2c-hubs-image)

## Missing pieces
Below are the required features of the hub that are still missing and require more info from either @2i2c-org/tech-team or @arokem 
### 1. Waiting for 2i2c
- [ ] Zoom links under auth: https://github.com/2i2c-org/infrastructure/issues/1500
### 2. Waiting for @arokem 
- [ ] Confirm https://neurohackademy.org is the official URL we should use on the landing login page
- [ ] Confirm which funding info we should link from the login page
   <img width="1346" alt="Screenshot 2022-07-08 at 15 41 32" src="https://user-images.githubusercontent.com/7579677/177994310-f58a28b9-f0d2-4a71-a913-a8fdd14ea3d3.png">

- [ ] Decide which user image to use
  
   @arokem, I noticed you mentioning that this is the image you'd like to use https://github.com/neurohackademy/nh2021-jupyterhub/blob/main/deployments/hub-neurohackademy-org/image/Dockerfile, is that right?

   In order to [configure the hub to use a specific image](https://infrastructure.2i2c.org/en/latest/howto/configure/update-env.html#configuring-your-hub-to-use-the-custom-image), we need the image name and tag. Are you building and pushing that docker image to any image registry already?
   
    If not, as @choldgraf mentioned, we usually recommend communities to build off [the repo2docker user image template](https://github.com/2i2c-org/hub-user-image-template/blob/main/README.md) that's using [jupyterhub/repo2docker-action]([jupyterhub/repo2docker-action](https://github.com/jupyterhub/repo2docker-action)) to build and push the image defined in a repo.
    I suggest using the info in the README of that template repo and the docs at https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide.html to create a new repo for this hub's user-image and move over the Dockerfile there. What do you think?

- [ ] Template customization
 
   There is now a branch called `2i2c-neurohackademy` at https://github.com/2i2c-org/default-hub-homepage/tree/2i2c-neurohackademy. Any change pushed to that branch should show up in your hub in max 5min. Feel free to check it out 🚀 and modify the templates there as you wish. 
 Someone at 2i2c must probably merge the changes though as I don't think you have the right permissions to push to that repo, so probably a PR would be the way to go?
 Btw, how often do you intend to change the info in the login page?
 
### Anything else missing?
@arokem, if I missed anything else here, please ping me ✨

**Comment by arokem** [comment]
Hello! 

> Right now the neurohackademy:
>
> - uses CILogon for authentication and only allows and shows GitHub identity provider as an option 
> - hub admins are 2i2c folks + @arokem

Looks great! How do we add multiple new users to the hub? Can we manage a user-list somewhere on github? This could even be a public page -- something like [this](https://github.com/neurohackademy/nh2021-jupyterhub/blob/main/deployments/hub-neurohackademy-org/config/common.yaml#L11-L22)

> Confirm https://neurohackademy.org/ is the official URL we should use on the landing login page

Confirmed! 

Sorry about this, but could we change the logo image to this instead? 

<img width="545" alt="Screen Shot 2022-07-09 at 2 01 23 PM" src="https://user-images.githubusercontent.com/118582/178122521-aa5b83e7-f898-415a-89ff-dc288f599b4f.png">

> Confirm which funding info we should link from the login page

[The National Institutes of Health grant 2R25MH112480-06](https://reporter.nih.gov/search/ydTvTwXxk0yd6eGdRznbLQ/project-details/10409452)

> I suggest using the info in the README of that template repo and the docs at https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide.html to create a new repo for this hub's user-image and move over the Dockerfile there. What do you think?

That sounds good to me! I think that we could inherit from jupyter-datascience, adding some neuroimaging-specific software on top of that. I don't remember exactly why we didn't use repo2docker in the last few years, and it looks like we're inheriting from a pangeo image. Maybe @consideRatio (who worked with us on our hub last couple of years) remembers why we didn't use repo2docker directly? 

> Someone at 2i2c must probably merge the changes though as I don't think you have the right permissions to push to that repo, so probably a PR would be the way to go?
Btw, how often do you intend to change the info in the login page?

I don't think we'll change it much. Probably set it once before the beginning of the event and then leave it as-is.

**Comment by yuvipanda** [comment]
@GeorgianaElena may I suggest using GitHub authentication + a GitHub org for authentication rather than using GitHub via CILogon? That should make maintaining a list of allowed users easier. I think we should default to this for workshop and research hubs, reserving CILogon for educational hubs.

**Comment by consideRatio** [comment]
> Maybe @consideRatio (who worked with us on our hub last couple of years) remembers why we didn't use repo2docker directly?

I don't remember, but I'll confabulate that it could have been because we wishes for it to be mostly like pange/pangeo-notebook was, and then just add a few things to that.

**Comment by GeorgianaElena** [comment]
> @GeorgianaElena may I suggest using GitHub authentication + a GitHub org for authentication rather than using GitHub via CILogon?

@yuvipanda, actually @arokem's answer from a previous issue was why this is not using GitHub org based authentication -> [*"We'd actually rather not do that and use individual GitHub user-names instead, if that's OK.*"](https://github.com/2i2c-org/infrastructure/issues/1300#issuecomment-1128126597)

> Looks great! How do we add multiple new users to the hub? Can we manage a user-list somewhere on github? This could even be a public page -- something like [this](https://github.com/neurohackademy/nh2021-jupyterhub/blob/main/deployments/hub-neurohackademy-org/config/common.yaml#L11-L22)

@arokem, you can manually add users from the admin panel (multiple users at once too). There are docs about this here https://docs.2i2c.org/en/latest/admin/howto/manage-users.html#manage-users-from-the-administrator-panel

But given @yuvipanda's [suggestion above](https://github.com/2i2c-org/infrastructure/issues/1505#issuecomment-1179608234), would you consider using the GitHub organization or GitHub teams membership, instead of manually adding the users through the hub admin panel? Does that seem more suitable? Just want to make sure if I should change or not the current implementation.

**Comment by GeorgianaElena** [comment]
I've updated the hub at https://neurohackademy.2i2c.cloud with latest logo image and funding info.

So I believe that the next steps need your input @arokem:

- [ ] 1. Decide whether or not to use GitHub organization or GitHub teams membership to authorize users
- [ ] 2. Create a new repository for this hub's user-image using the [template repo](https://github.com/2i2c-org/hub-user-image-template/blob/main/README.md) and the guide at https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide.html to 
- [ ] 3. Open a PR against the [2i2c-neurohackademy branch](https://github.com/2i2c-org/default-hub-homepage/tree/2i2c-neurohackademy) with the desired hub template changes
- [ ] 4. Create the private repository with static web content that should be served from within the hub (behind auth) (ref https://docs.2i2c.org/en/latest/admin/howto/content.html#create-your-static-html-files)

Once the steps above are completed, then they will all be hooked to the hub and deployed 🚀

**Comment by damianavila** [comment]
> 4. Create the private repository with static web content that should be served from within the hub (behind auth) (ref https://docs.2i2c.org/en/latest/admin/howto/content.html#create-your-static-html-files)

Using #1502 instead of what is currently described in the docs. I am sure you already know that @GeorgianaElena, just clarifying for other readers 😉.

**Comment by arokem** [comment]
> 1. Decide whether or not to use GitHub organization or GitHub teams membership to authorize users

Let's not. I can add them through the hub admin panel. 

> 2. Create a new repository for this hub's user-image using the [template repo](https://github.com/2i2c-org/hub-user-image-template/blob/main/README.md) and the guide at https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide.html to

Done! https://github.com/neurohackademy/hub-image-2022

> 3. Open a PR against the [2i2c-neurohackademy branch](https://github.com/2i2c-org/default-hub-homepage/tree/2i2c-neurohackademy) with the desired hub template changes

OK. I will if I spot anything, but it looks good for now. 

> 4. Create the private repository with static web content that should be served from within the hub (behind auth) (ref https://docs.2i2c.org/en/latest/admin/howto/content.html#create-your-static-html-files)

I have created a repo at https://github.com/neurohackademy/zoom2022. The file to render is https://github.com/neurohackademy/zoom2022/blob/index/index.html

**Comment by GeorgianaElena** [comment]
Yay! Thanks for all this work @arokem ✨ 

There is one more small step to be taken for in order to host the zoom links repo, which is to [grant access to the 2i2c github app that will read the content in the private repo that you just setup](https://infrastructure.2i2c.org/en/latest/howto/features/static-sites.html?highlight=static#grant-access-to-the-private-repo) by installing the https://github.com/apps/2i2c-neurohackademyhub-static-pull app in the `neurohackademy` org.

Also, two small things to double-check:
- the branch of  https://github.com/neurohackademy/zoom2022 to use is `main`, right?
- the zoom repo will be hosted at  https://neurohackademy.2i2c.cloud/zoom/. Is this ok, or do you want to use a different path than `/zoom`?

**Comment by arokem** [comment]
> There is one more small step to be taken for in order to host the zoom links repo, which is to [grant access to the 2i2c github app that will read the content in the private repo that you just setup](https://infrastructure.2i2c.org/en/latest/howto/features/static-sites.html?highlight=static#grant-access-to-the-private-repo) by installing the https://github.com/apps/2i2c-neurohackademyhub-static-pull app in the neurohackademy org.

I believe I just did that! 

> - the branch of https://github.com/neurohackademy/zoom2022 to use is main, right?

It's on `master`

> - the zoom repo will be hosted at https://neurohackademy.2i2c.cloud/zoom/. Is this ok, or do you want to use a different path than /zoom?

Sounds good!

**Comment by GeorgianaElena** [comment]
Thanks @arokem! ✨ I just deployed the latest changes and the hub is running at https://neurohackademy.2i2c.cloud/hub/login 🚀  Also, the zoom links from the private repo are available at https://neurohackademy.2i2c.cloud/zoom/

Please check it out and let me know if you can login ok and have access to the admin panel and if everything works as expected

**Comment by arokem** [comment]
Thank you! Yes: I can login, though it's still going through CILLogin and I have access to the admin panel.

Questions: 

- How often does the static webpage at https://neurohackademy.2i2c.cloud/zoom/ update, or how soon after a push to the `master` branch on the designated repo? I pushed a change about 10 minutes ago and not seeing it propagate yet. 
- Could you please set this to the "lab" view per default? I am currently getting the "tree" view.
- Is it ready for me to add users? I added one more admin for now.
- Could we please add another repo with notebooks/curriculum material to be pulled with nbgitpuller into user's home directories? This will be an open repo.  
- In past events, we designated a folder in each user's home directory for shared data storage. This was a directory into only a few users ("instructors") were able to write (to upload shared datasets) and all users ("students") could read from. IIUC, @consideRatio had set this up so that the storage was centralized for this location, so we didn't have to store multiple copies of the same data. Would it be possible to set that up here as well? 


Thanks again!

**Comment by consideRatio** [comment]
> In past events, we designated a folder in each user's home directory for shared data storage. This was a directory into only a few users ("instructors") were able to write (to upload shared datasets) and all users ("students") could read from. IIUC, @consideRatio had set this up so that the storage was centralized for this location, so we didn't have to store multiple copies of the same data. Would it be possible to set that up here as well?

@arokem I think you can get this very conveniently out of the box in a 2i2c provided hub. There will be a `shared` folder available to everyone mounted in a readonly state, and then a `shared-readwrite` folder - the same folder as `shared` - that only jupyterhub admins will be able to see that they can use to also write data to.

I did some work to optimize performance of that data, making it copied to each node etc to ensure many people reading it at the same time wouldn't slow each other down. I think probably such optimization isn't going to be needed - and the out of the box NSF storage will work fine.

**Comment by GeorgianaElena** [comment]
> [Seems like 5 minutes](https://github.com/2i2c-org/infrastructure/blob/eb691a87a718cd75b08650bc8384c8f2fbeffb03/helm-charts/basehub/templates/static/deployment.yaml#L64-L67). So if you are sure you have made a relevant change, maybe there is a bug to fix.

I think there was a small bug with the sync. Should be fixed now. @arokem, can you confirm that you can now see the changes?

**Comment by arokem** [comment]
And thanks @consideRatio for pointing out the `shared` and `shared-readwrite` folders. That should do the job.

**Comment by arokem** [comment]
The configurator doesn't seem to be working for us. I did as instructed above, and I even see this when I return to the configurator page: 

<img width="1312" alt="Screen Shot 2022-07-13 at 1 52 11 PM" src="https://user-images.githubusercontent.com/118582/178832284-a88e74d4-1d1e-4af4-85c2-f2f58da557c4.png">

But I still see the "tree" view when returning to my server, even after logging in and out and restarting the server.

**Comment by consideRatio** [comment]
@arokem / @yuvipanda could this be a configurator-bug? Does it need the image set as well?

**Comment by arokem** [comment]
How long should it take between an update to the `main` branch of the hub image repo (https://github.com/neurohackademy/hub-image-2022) and until I can start using the new image specifications? I pushed a change more than 30 minutes ago, and I can see that the change was also pushed to quay, but still not seeing the software dependencies added in the hub (i.e., getting import errors for things like `import numpy as np`). This despite stopping and restarting the server just now.

**Comment by consideRatio** [comment]
@arokem there is no longer automation regarding updating the hub to use the new image - it was coupled to a redeployment of the helm chart that isn't done as part of building the image any more. So, after the image is built you need to visit /services/configurator/ again and write in your new image name:tag.

If you declare that the "latest" tag should be used, you can avoid this - the downside is that you will possibly run into version mismatches between user server image version and dask workers image version when using a latest tag.

**Comment by arokem** [comment]
Looks like I broke it :-/ 

I tried to enter `arokem/nh-jhub-2022:latest` in there, which I think made it look for `docker.io/arokem/nh-jhub-2022:latest`, which doesn't exist and now the thing is stuck in `Error: ImagePullBackOff`. 

I did try to change that to `quay.io/arokem/nh-jhub-2022:latest` (is that the correct format for this? And yes, quay.io does have a `latest` tag:  https://quay.io/repository/arokem/nh-jhub-2022?tab=tags), but it still seems to be stuck unable to recover from the previous error.

**Comment by arokem** [comment]
Sorry! Looks like I spoke too soon. After finally timing out, I was given the option to relaunch the server and that seems to have done the trick. It found the right image/tag and launched successfully. So, I am back on track setting things up in terms of software/environment.

**Comment by GeorgianaElena** [comment]
> @arokem / @yuvipanda could this be a configurator-bug? Does it need the image set as well?

I don't think it's configurator's fault. I can see in the logs that the correct interface is being set on the spawner (plus, I've made `/lab` the default anyway).

After investigating this morning and not finding anything obviously wrong, I remembered that we recently bumped `z2jh` and that required us to bump the `jupyterhub` version in the user images too otherwise, [@yuvipanda noticed that the default URL doesn't take effect](https://github.com/2i2c-org/infrastructure/pull/1468#issue-1284222372).

I believe we should try to update jupyterhub from 1.5.0 in the user image to 2.3.1, like we did for the 2i2c default user image. Hopefully that should fix the default url issue.

**Comment by arokem** [comment]
I am now getting a 403 error for the zoom webpage: 

<img width="1392" alt="Screen Shot 2022-07-14 at 9 25 22 PM" src="https://user-images.githubusercontent.com/118582/179150229-be4092e1-baf8-410b-a82a-8b344883992e.png">
 
Did something change?

**Comment by GeorgianaElena** [comment]
@arokem, the 403 should be fixed now. I also noticed that the redirect to `/lab` also works now, yay 🚀 

Is there anything else I could help with on the hub env side of things? Please let me know if I missed anything ✨

**Comment by arokem** [comment]
No - looks like smooth sailing from here on out! Thank you! I'll plan to start adding participants early next week, so they can start taking a look around.
