### ISSUE TITLE
[New Hub] COESSING Pangeo-Style Hub

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#1516]
### Hub Description

This is a request for a new hub to support the  upcoming [Coastal Environment Summer School in Ghana](https://coessing.org/). The school runs August 1-5, 2022 so this is a hot request. 2i2c supported last year's version of this event. The 2022 edition will take place in Nigeria. This summer school is scoped under the Columbia Moore grant led by @rabernat.

### Community Representative(s)

- @paigem

### Important dates

- **Target start date**: July 25, 2022
- **Required start date**:  July 30, 2022
- **Any important dates for usage**: August 1-5, 2022 is when the school takes place.

### Hub Authentication Type

GitHub Authentication (e.g., @mygithubhandle)

### Hub logo information

- **URL to Hub Image**: {{ URL HERE }}
- **URL for Image Link**: {{ URL HERE }}

### Hub user image

- Repository for user image: { REPO LINK IF IT EXISTS }
- User image registry: { REGISTRY IF ONE ALREADY EXISTS }
- User image tag and name: { NAME AND TAG IF IT EXISTS }

### Extra features you'd like to enable

- [ ] Specific cloud provider or datacenter: 
- [ ] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### Other relevant information

Email with information shared by Paige: 

Hi 2i2c!

I am hoping that we can set up another Hub for an oceanography summer school in West Africa ([COESSING](https://coessing.org/)) in a couple weeks. The school will be held in hybrid format with an in-person portion in Lagos, Nigeria, and a virtual component with primarily West African participants. We used a 2i2c Hub last year for our entirely virtual school and it worked great!

Logistics:

    Workshop dates: Monday, August 1 - Friday, August 5
    Desired start date of Hub: Monday, July 25 (I realize this is very soon - please let me know if this is not possible)
    Desired end date of Hub: August 31
    Estimated maximum usage at any given point in time (likely only for ~1 hour each day): 120 people
    Desired authentication: Google accounts that are added manually (i.e. I will add them manually as the admin)

Other details:
A few desired functions, partly based on a recent discussion with Chris Holdgraf:

    Ideally this Hub is a “sub” version of the Pangeo Hub. The idea is that we will invite any participants who are computationally inclined to join the Pangeo Hub after the workshop. However, because we may have up to 200 participants engage with content on the JupyterHub, we would like to have our own dedicated Hub for the workshop.
    We would like the Pangeo Cloud computing environment, with the option to add more packages on top.
    Last year we used the Pangeo Google Cloud distribution on us-central1. This year we have one instructor who wishes to use aws-us-west-2 to access NASA’s PODAAC, but we would still like access to datasets that (I believe) are stored on Google Cloud (eg ECCOv4r3). Is there a way to have both Google Cloud and AWS as an option? If that is too complicated/expensive, then let’s stick with Google Cloud.
    This Hub will be Python-based. However, is it possible to include a Julia kernel as an option on this Hub?
    We will use very little (if any) Dask capability. Is this something we can add closer to the time? I am still communicating with instructors to determine if Dask will be needed.
    I have discussed possible funding options with Chris Holdgraf - please let me know if 2i2c does not have funding for this Hub, and Ryan Abernathey has offered some funding to cover this.

Please let me know if you have any more questions! I look forward to working with 2i2c again!
Paige

### Hub URL

<hub ID>.<hub cluster>.2i2c.cloud

### Hub Type

daskhub

### Tasks to deploy the hub

- [x] Engineer who will deploy the hub is assigned
- [x] Deploy information filled in above
- [x] Initial Hub deployment PR: <link to PR>
- [x] Administrators able to log on
- [ ] Community Representative satisfied with hub environment
- [ ] Hub now in steady-state

**Comment by paigem** [comment]
**Repository for user image:** https://github.com/coessing/coessing2022-hub (empty for now, but will be populated over the next couple weeks)
**URL to Hub image:** https://coessing.org/2022-school-in-nigeria/#jp-carousel-510

**Comment by sgibson91** [comment]
@paigem We still have your image from last year if it would be useful to reuse/build off of that? https://github.com/2i2c-org/coessing-image

**Comment by damianavila** [comment]
@yuvipanda is colocated with @paigem at SciPy so he is going to work with her on this one!
I added @GeorgianaElena as a secondary helper in case additional help is needed.

**Comment by paigem** [comment]
The Hub has been set up thanks to the amazing @yuvipanda! 🙏 

@yuvipanda I confirmed that we *do* need a Julia kernel. Let me know if you need any more info to set one up.

**Comment by paigem** [comment]
I am getting an error when adding any new users:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/26591824/179630682-12f9d396-fa53-4e1f-922b-ccb5dd9584ad.png">

Looks like I am set up as an admin already - have I missed a step in the setup? @yuvipanda @GeorgianaElena

**Comment by yuvipanda** [comment]
@paigem ah, interesting. let me look.

I'll add Julia to the image over the next few days.

**Comment by yuvipanda** [comment]
Hmm, so looking at the hub logs when trying to add users, i see:

```
[W 2022-07-18 22:56:04.735 JupyterHub web:1787] 400 POST /hub/api/users (10.128.0.4): Must specify at least one user to create
```

**Comment by paigem** [comment]
I am copying and pasting Google email addresses into the "Add Users" box when I click the "Add Users" button from the admin control panel. Is there something I'm missing?

I've tried numerous different email addresses, and all of them seem to fail...

**Comment by yuvipanda** [comment]
@paigem unfortunately this looks like a JupyterHub bug - https://github.com/jupyterhub/jupyterhub/issues/3983. I'm working on resolving it, will keep you posted.

**Comment by yuvipanda** [comment]
I've fixed up the issue! PR coming up soon. Me and @paigem added the users who needed to be admin, and they were accepted.

**Comment by paigem** [comment]
Just checking in on the status of adding Julia to our Hub @yuvipanda @GeorgianaElena 

Also, is it easy to replace the Pangeo logo with the [COESSING logo](https://coessing.org/2022-school-in-nigeria/#jp-carousel-510) on the main landing page? Is this something I can do myself?

**Comment by sgibson91** [comment]
Julia was added yesterday by Simone! I wil change the logo today.

**Comment by choldgraf** [comment]
Also just to clarify there @paigem - any hub administrator can add any other user, including other hub administrators! See these docs for reference:

- https://docs.2i2c.org/en/latest/admin/howto/manage-users.html?highlight=add%20user#to-add-users

**Comment by paigem** [comment]
Thanks @sgibson91!! Didn't realize Simone added Julia already - amazing! (For some reason I thought we needed some backend help to make that happen.)

And thanks @choldgraf! I clearly should have specified that the I want the _language_ Julia added to our Hub. 😉

**Comment by choldgraf** [comment]
LOL omg I feel like I just had an "out of touch old person" moment, how embarrassing 🤦

**Comment by yuvipanda** [comment]
@choldgraf this is extremely funny because when me and @paigem were chatting about this in person at SciPy Julia Signell was nearby and kept getting confused in the same way...

**Comment by sgibson91** [comment]
> For some reason I thought we needed some backend help to make that happen.

@paigem In general, we try to give communities control over their own images, both because this underpins our Right to Replicate and so that image updates don't bottle neck on the strained capacity of the engineering team. That being said, if a particular image customisation is too difficult, we will of course help out!
