### ISSUE TITLE
[New Hub] Project Victor

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#1546]
### Hub Description

This issue gathers information to create a **DaskHub** for Project Victor. This Project will assemble a community of researchers focused on volcanology. 

### Community Representative(s)

@einatlev-ldeo
Others?

### Important dates

- **Target start date**:  ~2022-08-23~ TBD
- **Required start date**:  ~2022-09-15~ TBD
- **Any important dates for usage**: 

The project timeline as currently envisioned is:

+  9/1/22 — Annual report due for NSF. This is the most pressing deadline. We would like to have a solid plan and early design to share with NSF. 
+  Fall 2022 — development
+   mid-December 2022  — AGU meeting. We will likely have an abstract (in an ML/AI session?) and would like to mention the VICTOR system 
+  Late January 2023 — IAVCEI meeting. We would like to demonstrate the hub to a select group of testers at the meeting. Bug reports and incidents will start coming in then. 
+  Spring 2023 — development
+  June 2023 – Workshop and Hackathon event based on VICTOR. Usage will likely pick up after that. 
+   August 15, 2023 — NSF Geoinformatics program deadline. We plan to submit a proposal to support VICTOR for a few more years. 

### Hub Authentication Type

Other (may not be possible, please specify in comments)

### Hub logo information

- **URL to Hub Image**: {{ URL HERE }}
- **URL for Image Link**:  https://drive.google.com/file/d/1b7TMc1tkg98PtfOokCQ5Bvbik1m8fcAT/view?usp=sharing

Pending input from Project Victor team (so @einatlev-ldeo)? See [this example](https://openscapes.2i2c.cloud/hub/login?next=%2Fhub%2F) and notice the OpenScapes image at the top? We request an image to be used for your landing page. 

### Hub user image

- Repository for user image: { REPO LINK IF IT EXISTS }
- User image registry: { REGISTRY IF ONE ALREADY EXISTS }
- User image tag and name: { NAME AND TAG IF IT EXISTS }

Pending input from Project Victor team (so @einatlev-ldeo?). As a default plan, we could launch a Pangeo-style hub and the Victor team could customize the Docker image during Fall 22.

### Extra features you'd like to enable

- [ ] Specific cloud provider or datacenter: 
- [ ] Dedicated Kubernetes cluster
- [x] Scalable Dask Cluster

Question for Project Victor (so @einatlev-ldeo): Are there large data sets you wish to frequently access hosted on a particular data center? If yes, we should deploy the hub adjacent to that data.

### Hub URL

<hub ID>.<hub cluster>.2i2c.cloud

@einatlev-ldeo: Should the hub be located at projectvictor.2i2c.cloud?
@SamKrasnoff

### Tasks to deploy the hub

- [ ] Engineer who will deploy the hub is assigned
- [ ] Deploy information filled in above
- [ ] Initial Hub deployment PR: <link to PR>
- [ ] Administrators able to log on
- [ ] Community Representative satisfied with hub environment
- [ ] Hub now in steady-state

**Comment by colliand** [comment]
What input from 2i2c is needed for the NSF report due on September 1? @einatlev-ldeo? 

I invite you to provide answers or ask questions related to the inputs requested about the Project Victor hub below.

**Comment by einatlev-ldeo** [comment]
VICTOR logo link: [https://docs.google.com/document/d/1XBlprGT64qSNP6lr-P9RoN786fb_JoIhUUIINgebSg0/edit?pli=1#heading=h.qo34o8p9in1e](url)

**Comment by einatlev-ldeo** [comment]
Additional personnel: 
Sam Krasnoff
Laura Connor
(github handles will be added soon)

**Comment by einatlev-ldeo** [comment]
We do not have user images yet.

**Comment by damianavila** [comment]
I have already talked with @GeorgianaElena about this one and she is going to lead the deployment and I will provide her support.

Two things we need to first figure it out first to start working on this deployment are:

* Cloud provider (from previous conversations in the lead issue it seems it will be AWS, but we need certainty).
* Auth

Can we please get these details first?
Access to the could provider might be the most time-consuming piece, IMHO.
And even more, if this actually involves a deployment in Columbia cloud land.

**Comment by damianavila** [comment]
A little update here: there is currently an ongoing conversation between @jmunroe and people from the project Victor to fully understand the use case and, based on that, choose the proper cloud provider.

**Comment by jmunroe** [comment]
I closing this issue and continuing the conversation under

- https://github.com/2i2c-org/infrastructure/issues/1831 

using the recently improved "[Request Deployment] New Hub" template.
