### ISSUE TITLE
[Decommission Hub] Azure Hub for Carbon Plan

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#1618]
### Summary

Carbon Plan wishes to decommission their hub on Microsoft Azure. They will continue to use their AWS-based hub.

### Info

- **Community Representative:** @andersy005 @norlandrhagen 
- **Link to New Hub issue:** https://github.com/2i2c-org/infrastructure/issues/800
- **Proposed end date:** 2022-09-15

#### Phase I

~~- [ ] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission~~
~~- [ ] Confirm if there is any data to migrate from the hub before decommissioning~~
  ~~- [ ] If yes, confirm where the data should be migrated to~~
    ~~- [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration~~
  ~~- [ ] If no, confirm it is ok to delete all the data stored in the user home directories~~

#### Phase II - Hub Removal
(These steps are decribed in more detail in the docs at https://infrastructure.2i2c.org/en/latest/howto/hubs/delete-hub.html.)

~~- [ ] Manage existing data (migrate data from the hub or delete it)~~
~~- [ ] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.~~
~~- [ ] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.~~
~~- [ ] Remove the hub deployment~~
  ~~- `helm --namespace HUB_NAME delete HUB_NAME`~~
  ~~- `kubectl delete namespace HUB_NAME`~~
- [x] Delete the hub's authentication application on auth0, GitHub or CILogon

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

~~- [ ] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster~~
- [x] Delete the terraform workspace
- [x] Remove the associated `config/clusters/<cluster_name>` directory and all its contents
- Remove the cluster from CI:
  - [x] [`deploy-hubs.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-hubs.yaml)
  - [x] [`validate-clusters.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/validate-clusters.yaml)
- [x] Remove the cluster from the list of grafana datasources at https://grafana.pilot.2i2c.cloud/datasources

**Comment by sgibson91** [comment]
Joe noted on Slack that the sponsorship account has been closed out for this hub and that the cluster/hub are down for good: https://2i2c.slack.com/archives/C01DB2JRP8W/p1661288927380899 I asked a clarifying question on whether this means we need to run `terraform destroy` or if it's just a case of cleaning up the files in our repo.

If it's a case of cleaning up files, I'm more than happy to do that.

**Comment by yuvipanda** [comment]
@sgibson91 we should probably also delete the terraform workspace we used.

**Comment by sgibson91** [comment]
@yuvipanda Yup, I had made a mental note but not written it down before a meeting :smile:

**Comment by sgibson91** [comment]
PR to update the template here: https://github.com/2i2c-org/infrastructure/pull/1653

**Comment by sgibson91** [comment]
PR to remove the cluster here: https://github.com/2i2c-org/infrastructure/pull/1654

**Comment by jhamman** [comment]
Thanks @sgibson91!
