### ISSUE TITLE
[New Hub] gridSST Hack-A-Thon

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#1650]
### Hub Description

Alison Gray, an oceanographer at the University of Washington, requests a hub to support an upcoming OceanHackWeek. Alison has recently been notified that her proposal to support this event and ongoing work thereafter with the hub was funded by NASA. 🎉 

### Community Representative(s)

Alison Gray, @alisonrgray, @dgumustel
Who else?

### Important dates

- **Target start date**: 2022-10-14
- **Required start date**: 2022-10-31
- **Any important dates for usage**: hackathon event 10-31 -> 11-04 

### Hub Authentication Type

GitHub Authentication (e.g., @mygithubhandle)

### Hub logo information

- **URL to Hub Image**: https://drive.google.com/file/d/1i9R3JkdNRddWpMYWrLKSn2mQNu0YxRjE/view
- **URL for Image Link**:  ?

In this field, 2i2c is requesting a URL with the splash image that will appear at the top of the landing page. For example, see the openscapes logo at the [top of this page](https://openscapes.2i2c.cloud/hub/login?next=%2Fhub%2F). 

### Hub user image

- Repository for user image: { REPO LINK IF IT EXISTS }
- User image registry: { REGISTRY IF ONE ALREADY EXISTS }
- User image tag and name: { NAME AND TAG IF IT EXISTS }

### Extra features you'd like to enable

- [x] Specific cloud provider or datacenter:  AWS
- [x] Dedicated Kubernetes cluster
- [x] Scalable Dask Cluster

### Hub URL

<hub ID>.<hub cluster>.2i2c.cloud

### Tasks to deploy the hub

- [x] Engineer who will deploy the hub is assigned
- [x] Deploy information filled in above
- [x] Initial Hub deployment PR: https://github.com/2i2c-org/infrastructure/pull/1818
- [x] Administrators able to log on
- [ ] Community Representative satisfied with hub environment
- [ ] Hub now in steady-state

**Comment by colliand** [comment]
Hi @alisongray! Please share comments on this issue below. Specific questions that are implicitly asked in the issue anchor above include:

1. Will the users of this hub be frequently using large data sets hosted from specific cloud vendor data centers? If yes, 2i2c should stand up the hub service in the data center.
2. Are there others who should added as community representatives for this hub service?

**Comment by alisonrgray** [comment]
Thanks for getting this started.  This is me (@alisonrgray) 
A few notes:
- This event is actually called "SST Hack-A-Thon".
- It will be similar to the OceanHackWeek hub that 2i2c did, but there will be some key differences.  After talking to @abkfenris it seems that it probably doesn't make sense to simply copy the OceanHackWeek hub.

> Will the users of this hub be frequently using large data sets hosted from specific cloud vendor data centers? If yes, 2i2c should stand up the hub service in the data center.

Yes, users will be working closely  with the NASA  cloud-based datasets which are hosted by AWS.

> Are there others who should added as community representatives for this hub service?

Working on identifying these folks, will let you know asap.

**Comment by alisonrgray** [comment]
URL for splash image:

https://drive.google.com/file/d/1i9R3JkdNRddWpMYWrLKSn2mQNu0YxRjE/view?usp=sharing

**Comment by damianavila** [comment]
> There is some ongoing discussion about possibly delaying the start.

Can we get a better sense of this one? Because it might impact the dates referenced above.

> It will be similar to the OceanHackWeek hub that 2i2c did, but there will be some key differences. After talking to @abkfenris it seems that it probably doesn't make sense to simply copy the OceanHackWeek hub.

We need more details about those key differences, can you please provide more information about those. Thanks!

**Comment by alisonrgray** [comment]
We settled on a date, which is the same as what is listed in the original issue
Target start date: 2022-09-12
Required start date: 2022-09-19

**Comment by alisonrgray** [comment]
Here are some key differences with OHW, right off the bat:
- We only need python, no R or Rstudio
- We won't need the ability for users to create their own environments (which was an option in OHW)
- We will be heavily using NASA's cloud-enable datasets and accessing them using the Harmony API - https://harmony.earthdata.nasa.gov/
- We will want to use Dask

**Comment by alisonrgray** [comment]
Another update - we are going to be moving this event back after all.  My apologies for the whiplash! The new event date will be either the week of Oct 31 or the week of Nov 7 - still TBD.  I'll update you on here as soon as it's decided.

**Comment by colliand** [comment]
Thanks @alisonrgray! Please do let us know when the new event schedule is confirmed. At this point, should we pencil in a plan:

- [ ] deploy hub 2022-10-01
- [ ] support hackathon event week
- [ ] wind down the gridSST hub (WHEN? 2022-12-31? longer? I recall from our conversation that you were interested possibly in a persistent hub)

**Comment by damianavila** [comment]
> Another update - we are going to be moving this event back after all. My apologies for the whiplash! The new event date will be either the week of Oct 31 or the week of Nov 7 - still TBD. I'll update you on here as soon as it's decided.

@alisonrgray, do you have any updates about the definitive dates for the event?
We are trying to figure it out the best allocation of resources and the proper timeline to deploy this hub.
Thanks!

**Comment by alisonrgray** [comment]
Hi @damianavila Sorry for the delay!  

The event will be held Oct 31 - Nov 4.

**Comment by damianavila** [comment]
Thanks for the quick response!
OK, given those dates, we are targeting mid-October for the deployment.

In the meantime, we will try to collect all the information we need to be able to deploy the hub.
Looking at the description on this issue, it seems this is a daskhub living on AWS land (as opposed to the OHW hub which lives in our GCP cluster). For deployments on AWS, we either need access to an existing AWS account that the community owns or we fully control the account as part of the 2i2c org on behalf of the community: https://infrastructure.2i2c.org/en/latest/topic/cloud-auth.html#aws-access. 

What would be the case for this community? cc @alisonrgray @colliand @jmunroe 
Thanks!

**Comment by alisonrgray** [comment]
HI @damianavila - For this event, let's do the latter - 2i2c fully controls the account on behalf of the community.
Thanks!

**Comment by alisonrgray** [comment]
Regarding the plan outlined above:
> 
>     * [ ]  deploy hub 2022-10-14 (updated)

Perfect.

> 
>     * [ ]  support hackathon event week
> 
Yes!

>     * [ ]  wind down the gridSST hub (WHEN? 2022-12-31? longer? I recall from our conversation that you were interested possibly in a persistent hub)

This will depend a lot on funding.  I think 12-31-2022 would be the earliest, but hopefully we will be able to keep it going.  TBD.

**Comment by alisonrgray** [comment]
Also, can we add @dgumustel as an additional community representative?  Thanks :)

**Comment by GeorgianaElena** [comment]
Hey @alisonrgray! I will be deploying the hub for the event soon (probably starting tomorrow morning), but I need some more info before, if could help me:

1.
> Yes, users will be working closely with the NASA cloud-based datasets which are hosted by AWS.

Do you know which is the aws region where this data is hosted? Is it `us-west-2`? (deploying the cluster in the same region as the data, will help minimize the costs)

2.
> We only need python, no R or Rstudio

Do you have a link to the registry where this user image is stored? (checkout the docs at https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide.html#create-a-custom-user-image-for-your-hub for 2i2c's recommendation on how to create one).

3.
> Hub Authentication Type: GitHub Authentication (e.g., @MyGitHubHandle)

It is possible to manage hub access based on GitHub team or organization membership or manage the list of users manually, [from the admin panel](https://docs.2i2c.org/en/latest/admin/howto/manage-users.html#manage-users-from-the-administrator-panel). Which one would you like to use for the hackathon?

Thanks!

**Comment by damianavila** [comment]
Gently reminder for @alisonrgray to provide the requested information. Thanks!!

**Comment by alisonrgray** [comment]
Hello @damianavila and @GeorgianaElena 

> 
> 1.
> > Yes, users will be working closely with the NASA cloud-based datasets which are hosted by AWS.
> 
> Do you know which is the aws region where this data is hosted? Is it `us-west-2`? (deploying the cluster in the same region as the data, will help minimize the costs)

Yes - AWS-west-2 .  

> 
> 2.
> 
> Do you have a link to the registry where this user image is stored? (checkout the docs at https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide.html#create-a-custom-user-image-for-your-hub for 2i2c's recommendation on how to create one).
> 

I am working on this as we speak and will update asap.


> 3.
> > Hub Authentication Type: GitHub Authentication (e.g., @MyGitHubHandle)
> 
> It is possible to manage hub access based on GitHub team or organization membership or manage the list of users manually, [from the admin panel](https://docs.2i2c.org/en/latest/admin/howto/manage-users.html#manage-users-from-the-administrator-panel). Which one would you like to use for the hackathon?

Do you have a general recommendation about this?  We have a pretty small community right now, so I think manually adding people would be fine, but happy to do whatever you think is less problematic...

**Comment by alisonrgray** [comment]
Hi again

Regarding the hub image, do you recommend creating a new image from scratch using the template, or would it be okay to start from the image that this similar event (snowex Hackweek hosted by my colleagues here at UW) and make a few tweaks to that?  https://github.com/2i2c-org/infrastructure/issues/1309

What do you advise?

**Comment by GeorgianaElena** [comment]
Thanks a lot for the info provided @alisonrgray 

> Do you have a general recommendation about this? We have a pretty small community right now, so I think manually adding people would be fine, but happy to do whatever you think is less problematic...

There's no issue using either of the approaches from an infrastructure perspective.
We can also switch it later, if you change your mind. As long as we're not changing the authentication provider entirely (from GitHub to Google for example), the setup is pretty straightforward.

What do you think about starting with manually adding the allowed users and see if it works out?

> Regarding the hub image, do you recommend creating a new image from scratch using the template, or would it be okay to start from the image used during this similar event (snowex Hackweek hosted by my colleagues here at UW) and make a few tweaks to that? https://github.com/2i2c-org/infrastructure/issues/1309

We usually recommend using the template repository described in [the docs](https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide.html#create-a-custom-user-image-for-your-hub), because it's easier to use than starting from scratch and has everything you need to quickly create an image and push it to a registry.
But since you won't be starting from scratch and instead tweak an existing image, that should also work.
You are in complete control of the image, so it's best to use whichever option is feels more appropriate.

**Comment by GeorgianaElena** [comment]
Hey @alisonrgray. There is now a hub running at https://gridsst.2i2c.cloud that you can start testing it 🚀

A few things about it:

1. The user docker image it is currently using is the one below per your request.

     But you have full access to change it whenever you want using the `configurator`. There are docs about this at https://docs.2i2c.org/en/latest/admin/howto/configurator.html
      ```
      image:
              name: quay.io/uwhackweek/snowex
              tag: "2022.07.07"
      ```

2. Unfortunately the logo image is too big to render. Do you have a smaller one that we could use?

3. There is also some missing info in on the front page:
    - funding information (name and link)
    - a link to the event that we will redirect to when clicking the logo
    
     
<img width="983" alt="Screenshot 2022-10-28 at 15 15 39" src="https://user-images.githubusercontent.com/7579677/198585183-6374e3b4-cb83-4ab8-9782-38862006f6cf.png">


P.S. There is also a staging one at https://staging.gridsst.2i2c.cloud where we usually test thing before deploying them in production.

Thank you!

**Comment by alisonrgray** [comment]
Hi @GeorgianaElena - Fantastic!  Thank you so much 😄 

We will start testing right away.  

Funding is NASA Physical Oceanography Program.  You can link to https://science.nasa.gov/earth-science/focus-areas/climate-variability-and-change/ocean-physics

I will get you a smaller logo.  You can link to https://gridsst-hackathon.github.io/

Would someone (you?) from 2i2c want to join our Slack during the event (starting next week!)?

**Comment by alisonrgray** [comment]
![image](https://user-images.githubusercontent.com/12631887/198593014-83d1a09e-f66a-4f00-9dcb-da930f0e1912.png)

I'm not able to log on - I know I need to set up users through the admin panel, but I can't seem to access that myself.  Thanks for your help!

**Comment by GeorgianaElena** [comment]
@alisonrgray, can you try logging in again now? I believe there was a typo in your username that should be fixed now.

The logo is also rendering after using this link https://gridsst-hackathon.github.io/_static/logo.png

**Comment by alisonrgray** [comment]
That worked!  Thanks :)

**Comment by damianavila** [comment]
> Would someone (you?) from 2i2c want to join our Slack during the event (starting next week!)?

If you have any issues, you can email us at the support email: https://docs.2i2c.org/en/latest/support.html.
Btw, I have created an accompanying event issue to figure it out and follow some specifics about the event itself: https://github.com/2i2c-org/infrastructure/issues/1832.

**Comment by alisonrgray** [comment]
Sounds great, thank you!  I'll answer your questions on the other issue as well.

**Comment by GeorgianaElena** [comment]
I'll close this issue and move the conversation over in that issue to reduce confusion. I've also just merged the PR that officially deployed the hub. Thanks everyone!
