### ISSUE TITLE
[Incident] UToronto hub unavailable

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1662]
### Summary

Visiting https://jupyter.utoronto.ca does not resolve

### Impact on users

No one can access the hub

### Important information

- Hub URL: https://jupyter.utoronto.ca
- Support ticket ref: https://2i2c.freshdesk.com/a/tickets/181

### Tasks and updates

- [x] Discuss and address incident, leaving comments below with updates
- [x] Incident has been dealt with or is over
- [x] Copy/paste the after-action report below and fill in relevant sections
- [x] Incident title is discoverable and accurate
- [ ] All actionable items in report have linked GitHub Issues

<details>
<summary>After-action report template</summary>

```
# After-action report

These sections should be filled out once we've resolved the incident and know what happened.
They should focus on the knowledge we've gained and any improvements we should take.

## Timeline

_A short list of dates / times and major updates, with links to relevant comments in the issue for more context._

All times in {{ most convenient timezone}}.

- {{ yyyy-mm-dd }} - [Summary of first update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of another update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of final update](link to comment)


## What went wrong

_Things that could have gone better. Ideally these should result in concrete
action items that have GitHub issues created for them and linked to under
Action items._

- Thing one
- Thing two

## Where we got lucky

_These are good things that happened to us but not because we had planned for them._

- Thing one
- Thing two

## Follow-up actions

_Every action item should have a GitHub issue (even a small skeleton of one) attached to it, so these do not get forgotten. These issues don't have to be in `infrastructure/`, they can be in other repositories._

### Process improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Documentation improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Technical improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]
```

</details>

**Comment by sgibson91** [comment]
I can't take this incident on myself as I've done a lot of support already today and it's late in the UK right now, but I did a quick check and all the pods seem to be running

```
❯ python deployer use-cluster-credentials utoronto

❯ kubens support
Context "hub-cluster" modified.
Active namespace is "support".

❯ kgp
NAME                                                READY   STATUS    RESTARTS   AGE
support-cryptnono-5xxk7                             1/1     Running   0          76d
support-cryptnono-6nntt                             1/1     Running   0          76d
support-cryptnono-kjhrx                             1/1     Running   1          76d
support-cryptnono-mvtsw                             1/1     Running   0          76d
support-cryptnono-vftjl                             1/1     Running   0          76d
support-grafana-6b68db7b4c-nkkdn                    1/1     Running   0          267d
support-ingress-nginx-controller-69b767f7c8-dkr9k   1/1     Running   0          61d
support-kube-state-metrics-59dc5bf757-9stfl         1/1     Running   0          38d
support-prometheus-node-exporter-2jlw8              1/1     Running   1          62d
support-prometheus-node-exporter-k2r5d              1/1     Running   0          62d
support-prometheus-node-exporter-stdxv              1/1     Running   0          62d
support-prometheus-node-exporter-thhf4              1/1     Running   0          62d
support-prometheus-node-exporter-ttgqq              1/1     Running   0          62d
support-prometheus-server-f58ffd445-w972t           2/2     Running   0          62d

❯ kubens staging
Context "hub-cluster" modified.
Active namespace is "staging".

❯ kgp
NAME                              READY   STATUS    RESTARTS   AGE
continuous-image-puller-8295j     1/1     Running   1          54d
continuous-image-puller-9jx5x     1/1     Running   0          54d
hub-bb49f96b7-x94kh               2/2     Running   0          21h
proxy-cc8bc457d-p2z9h             1/1     Running   0          54d
user-scheduler-6c55488875-4nzfg   1/1     Running   9          54d
user-scheduler-6c55488875-9fv2q   1/1     Running   11         54d

❯ kubens prod
Context "hub-cluster" modified.
Active namespace is "prod".

❯ kgp
NAME                                                   READY   STATUS    RESTARTS   AGE
continuous-image-puller-57vbj                          1/1     Running   1          54d
continuous-image-puller-hdrzx                          1/1     Running   0          54d
hub-59dfc79b5c-qn7ht                                   2/2     Running   0          21h
jupyter-5b1a0c68-2daa31-2d4912-2da026-2d90e6ea918797   1/1     Running   0          148d
jupyter-71156be0-2da782-2d4a48-2dbc89-2d38d74bcc3d9f   1/1     Running   4          188d
jupyter-de168949-2d05ee-2d4f22-2da459-2d721b3ac437be   1/1     Running   0          28h
proxy-75d9b55895-q2qbr                                 1/1     Running   0          54d
user-scheduler-7747c4cb8-9c7w6                         1/1     Running   11         54d
user-scheduler-7747c4cb8-jbtfp                         1/1     Running   8          54d
```

**Comment by choldgraf** [comment]
### 20:25 - Potential ubuntu bug

Jeremy shared this with us via email:

> Azure customers running Canonical Ubuntu 18.04 experiencing DNS errors - Investigating
Starting at approximately 06:00 UTC on 30 Aug 2022, a number of customers running Ubuntu 18.04 (bionic) VMs recently upgraded to systemd version 237-3ubuntu10.54 reported experiencing DNS errors when trying to access their resources. Reports of this issue are confined to this single Ubuntu version. This bug and a potential fix have been highlighted on the Canonical / Ubuntu site, which we encourage impacted customers to read: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1988119 An additional potential workaround customers can consider is to reboot impacted VM instances so that they receive a fresh DHCP lease and new DNS resolver(s). If you are running a VM with Ubuntu 18.04 image, and you are experiencing connectivity issues, we recommend you evaluate the above mitigation options. If you are not experiencing impact on your Ubuntu 18.04 images, but you have unattended security updates enabled, we recommend you review this setting until the Ubuntu issue is mitigated. The next update will be provided in 6 hours, or as events warrant.”

### 20:41 - nodes aren't ready

We discovered that the nodes weren't in a healthy state:

```
aks-core-34239724-vmss000000        NotReady   agent   273d   v1.20.7
aks-core-34239724-vmss000001        NotReady   agent   196d   v1.20.7
aks-core-34239724-vmss000002        NotReady   agent   196d   v1.20.7
aks-nbdefault-34239724-vmss000010   NotReady   agent   193d   v1.20.7
aks-nbdefault-34239724-vmss00002b   NotReady   agent   148d   v1.20.7
```

### 20:43 Restarting nodes

We decided to restart the nodes to see if this would resolve the issue.
We first tried with the Azure UI but discovered it has no UI-based restart feature.

So, we decided to **upgrading the cluster + nodepool** which would also force a reboot.

**Comment by choldgraf** [comment]
### Hub is back up

We just tried the hub and it is responding. https://jupyter.utoronto.ca/hub/login?next=%2Fhub%2F

**Comment by choldgraf** [comment]
# After-action report

## Summary

- There was a bug that got introduced in Azure infrastructure running our version of ubuntu
- That bug bit our hub causing all of the nodes to become unresponsive
- This brought down the toronto hub and was reported via FreshDesk
- We needed to restart the nodes, and the easiest way to do this was to upgrade the nodes
- When they restarted this issue was resolved (because we pulled an updated image w/ a patched bug or something?)

## Timeline

See above for the timeline.

## What went wrong

- Thing one
- Thing two

## Where we got lucky

_These are good things that happened to us but not because we had planned for them._

- Thing one
- Thing two

## Follow-up actions

_Every action item should have a GitHub issue (even a small skeleton of one) attached to it, so these do not get forgotten. These issues don't have to be in `infrastructure/`, they can be in other repositories._

### Process improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Documentation improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Technical improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

**Comment by yuvipanda** [comment]
More detailed postmortem in https://2i2c-org.pagerduty.com/postmortems/1714f617-7062-735f-94b4-74a2ef9f32ae

**Comment by damianavila** [comment]
The postmortem was shared with UToronto folks in Freshdesk.
I guess the missing piece is to create GH issues for the improvements proposed, is there anything else I am missing from this one?  cc @yuvipanda @choldgraf @sgibson91

**Comment by damianavila** [comment]
Well, it seems https://github.com/2i2c-org/infrastructure/issues/1709 was opened after this one.

**Comment by damianavila** [comment]
And another one is related: https://github.com/2i2c-org/infrastructure/issues/1716.

**Comment by yuvipanda** [comment]
I think GH issues are open for all the improvements proposed, and linked to from the PDF. Going to close this one.
