### ISSUE TITLE
[Incident] University of Toronto 500 errors

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#1687]
### Summary

The University of Toronto Hub is giving 500 errors before arriving at the log-in screen.

### Impact on users

Nobody can log in to the hub

### Important information

- Hub URL: https://jupyter.utoronto.ca/
- Support ticket ref: https://2i2c.freshdesk.com/a/tickets/188

### Tasks and updates

- [x] Discuss and address incident, leaving comments below with updates
- [x] Incident has been dealt with or is over
- [x] Copy/paste the after-action report below and fill in relevant sections
- [x] Incident title is discoverable and accurate
- [x] All actionable items in report have linked GitHub Issues

<details>
<summary>After-action report template</summary>

```
# After-action report

These sections should be filled out once we've resolved the incident and know what happened.
They should focus on the knowledge we've gained and any improvements we should take.

## Timeline

_A short list of dates / times and major updates, with links to relevant comments in the issue for more context._

All times in {{ most convenient timezone}}.

- {{ yyyy-mm-dd }} - [Summary of first update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of another update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of final update](link to comment)


## What went wrong

_Things that could have gone better. Ideally these should result in concrete
action items that have GitHub issues created for them and linked to under
Action items._

- Thing one
- Thing two

## Where we got lucky

_These are good things that happened to us but not because we had planned for them._

- Thing one
- Thing two

## Follow-up actions

_Every action item should have a GitHub issue (even a small skeleton of one) attached to it, so these do not get forgotten. These issues don't have to be in `infrastructure/`, they can be in other repositories._

### Process improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Documentation improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Technical improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]
```

</details>

**Comment by sgibson91** [comment]
> The University of Toronto Hub is giving 500 errors before arriving at the log-in screen.

I just tested on jupyter.utoronto.ca and the error is coming up _after_ logging in. So I'm now pretty sure this is a credentials of the AzureAD app thing

**Comment by choldgraf** [comment]
### Might be related to a previous incident

About a week ago, the UToronto hub reported similar issues with 500 errors. The problem was that a secret had expired within UToronto IT. The resolution was that @yuvipanda spoke to UT IT, got a new secret, and we deployed it to the hub.

We found reports of auth-related issues in the hub logs. Note the `Invalid client secret provided` error.

```
[E 2022-09-07 14:27:52.120 JupyterHub oauth2:386] Error fetching 401 POST https://login.microsoftonline.com/78aac226-2f03-4b4d-9037-b46d56c55210/oauth2/token: {
     "correlation_id": "0c40c72d-7f10-4f9e-a5ad-686aef7eda05",
     "error": "invalid_client",
     "error_codes": [
      7000215
     ],
     "error_description": "AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'de1b459c-5a90-432f-80fa-d0fe3b68a79b'.\r\nTrace ID: 04c99770-5c5f-4bf4-a516-ce02e4e9fa00\r\nCorrelation ID: 0c40c72d-7f10-4f9e-a5ad-686aef7eda05\r\nTimestamp: 2022-09-07 14:27:52Z",
     "error_uri": "https://login.microsoftonline.com/error?code=7000215",
     "timestamp": "2022-09-07 14:27:52Z",
     "trace_id": "04c99770-5c5f-4bf4-a516-ce02e4e9fa00"
    }
[E 2022-09-07 14:27:52.121 JupyterHub web:1789] Uncaught exception GET /hub/oauth_callback?code=0.ARwAJsKqeAMvTUuQN7RtVsVSEJxFG96QWi9DgPrQ_jtop5tvAAA.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P-wVtDBuxMpL1JLwgNSr6LJvX_2jjuQ-w-Y9doiepWIsfxyxbrOdLVsM9Cw98KluoXpkogs9jF-wm4XtUEtwT_l4ihOzfDpA9ititISECZv8EfZZxOVAbVKARumdjRL4hrciUozzSJagwh1PPo5tNCZ4u5zym-DcVLy-_xawPQq8YD8fVTcEhc1xVuf4jWHFAfuW976YtqrdqXgc--DyoTm5SV1iUUcJ1pde2OK2sVGRk82wdy1Jk2FqnFA1iLYXsaFLq_uTrp_45gaM0mh1eN5VWLHsRsNPJeRgQC587lfWs1lVB6sg8-NmZLae43UD2RJmrkDFqBxYsThGuT5108vTBD1lCUMsPi6IdcliaqpctYLV_eejUjcnLCp8p_oLgh15Xxt4R8wvWxe-IJN5SOoBYMLMFRMVFm_RZBYNEUlDLR_mxnGBMvem-u1GR8oN9xwEP8w0kkY8zO4yvwaBOuqyCHVPThj2vuO5_LtYk2lc8TII3Fp382JyKRlFwXx9S29ABgNr7VRpjSf-HN1QQa8fcdO_ZzKmJ0Bc0qaSEt1AcEVd8M8RbDbXXm-2RvMb5p0TKsyvzNMIH3YPw5iKflso1F-iYlTy2qGVc3PgVEL2I4rahqINjqnkrNZgtCz4ip6GUTvAqcwUfoMfgixq0v8kCVVnls9b4zgMZ1Kf4zruk6796QjF84xNdgF4W-4xdbJPV9S4V_4_MRXYp1PJo8&state=eyJzdGF0ZV9pZCI6ICI0YzRiM2U1NTkwOWM0MGU0OGM0ODMwZDFlMjU2ZDVmZiIsICJuZXh0X3VybCI6ICIvaHViLyJ9&session_state=7f776f13-5e6b-4044-8e10-d84f011a379d (10.1.0.4)
    HTTPServerRequest(protocol='https', host='jupyter.utoronto.ca', method='GET', uri='/hub/oauth_callback?code=0.ARwAJsKqeAMvTUuQN7RtVsVSEJxFG96QWi9DgPrQ_jtop5tvAAA.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P-wVtDBuxMpL1JLwgNSr6LJvX_2jjuQ-w-Y9doiepWIsfxyxbrOdLVsM9Cw98KluoXpkogs9jF-wm4XtUEtwT_l4ihOzfDpA9ititISECZv8EfZZxOVAbVKARumdjRL4hrciUozzSJagwh1PPo5tNCZ4u5zym-DcVLy-_xawPQq8YD8fVTcEhc1xVuf4jWHFAfuW976YtqrdqXgc--DyoTm5SV1iUUcJ1pde2OK2sVGRk82wdy1Jk2FqnFA1iLYXsaFLq_uTrp_45gaM0mh1eN5VWLHsRsNPJeRgQC587lfWs1lVB6sg8-NmZLae43UD2RJmrkDFqBxYsThGuT5108vTBD1lCUMsPi6IdcliaqpctYLV_eejUjcnLCp8p_oLgh15Xxt4R8wvWxe-IJN5SOoBYMLMFRMVFm_RZBYNEUlDLR_mxnGBMvem-u1GR8oN9xwEP8w0kkY8zO4yvwaBOuqyCHVPThj2vuO5_LtYk2lc8TII3Fp382JyKRlFwXx9S29ABgNr7VRpjSf-HN1QQa8fcdO_ZzKmJ0Bc0qaSEt1AcEVd8M8RbDbXXm-2RvMb5p0TKsyvzNMIH3YPw5iKflso1F-iYlTy2qGVc3PgVEL2I4rahqINjqnkrNZgtCz4ip6GUTvAqcwUfoMfgixq0v8kCVVnls9b4zgMZ1Kf4zruk6796QjF84xNdgF4W-4xdbJPV9S4V_4_MRXYp1PJo8&state=eyJzdGF0ZV9pZCI6ICI0YzRiM2U1NTkwOWM0MGU0OGM0ODMwZDFlMjU2ZDVmZiIsICJuZXh0X3VybCI6ICIvaHViLyJ9&session_state=7f776f13-5e6b-4044-8e10-d84f011a379d', version='HTTP/1.1', remote_ip='10.1.0.4')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.9/site-packages/oauthenticator/oauth2.py", line 222, in get
        user = await self.login_user()
      File "/usr/local/lib/python3.9/site-packages/jupyterhub/handlers/base.py", line 807, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.9/site-packages/jupyterhub/auth.py", line 473, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.9/site-packages/oauthenticator/azuread.py", line 69, in authenticate
        resp_json = await self.fetch(req)
      File "/usr/local/lib/python3.9/site-packages/oauthenticator/oauth2.py", line 387, in fetch
        raise e
      File "/usr/local/lib/python3.9/site-packages/oauthenticator/oauth2.py", line 366, in fetch
        resp = await self.http_client.fetch(req, **kwargs)
    tornado.httpclient.HTTPClientError: HTTP 401: Unauthorized

[E 2022-09-07 14:27:52.122 JupyterHub log:181] {
      "Cookie": "oauthenticator-state=[secret]",
      "Sec-Gpc": "1",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Accept-Encoding": "gzip, deflate, br",
      "Referer": "https://login.microsoftonline.com/",
      "Sec-Ch-Ua-Platform": "\"macOS\"",
      "Sec-Ch-Ua-Mobile": "?0",
      "Sec-Ch-Ua": "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"",
      "Sec-Fetch-Dest": "document",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-Site": "cross-site",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
      "Dnt": "1",
      "Upgrade-Insecure-Requests": "1",
      "Cache-Control": "max-age=0",
      "X-Scheme": "https",
      "X-Forwarded-Scheme": "https",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "jupyter.utoronto.ca",
      "X-Forwarded-For": "10.1.0.4,::ffff:10.244.8.12",
      "X-Real-Ip": "10.1.0.4",
      "X-Request-Id": "72585e1d998e0839e820c58d0eca06a3",
      "Host": "jupyter.utoronto.ca",
      "Connection": "close"
    }
```

**Comment by choldgraf** [comment]
### Potentially an over-written secret

Our theory right now is that:

- the original secret was deployed **manually**
  - This is because right now there are no recent commits to the UT hub config: https://github.com/2i2c-org/infrastructure/tree/master/config/clusters/utoronto
- A recent change to our `main` branch means that all hubs were re-deployed:
	- https://github.com/2i2c-org/infrastructure/actions/runs/2999517788
	- https://github.com/2i2c-org/infrastructure/runs/8206692754?check_suite_focus=true
- This deploy may have over-written the secret

### Next steps

If this is the correct diagnosis, then we need to:

- Get the updated secret from @yuvipanda
- Deploy the secret via our `infrastructure/` repository so that it is encoded in our config

**Comment by yuvipanda** [comment]
There are a bunch of very important takeaways from this! https://github.com/2i2c-org/infrastructure/issues/1118 being bumped up in priority is one.

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/team-compass/pull/508 replaces GitHub with PagerDuty for managing incidents - this makes sure it becomes much more difficult to accidentally miss an important step in the incident response process

**Comment by yuvipanda** [comment]
There's a WIP incident report at https://2i2c-org.pagerduty.com/postmortems/171317d6-5f19-7511-7d3a-117b13f62584/edit

**Comment by yuvipanda** [comment]
Incident report added at https://github.com/2i2c-org/incident-reports/pull/1

**Comment by damianavila** [comment]
The incident report was shared with Toronto folks.
I think we can close this one now.
Feel free to re-open if you disagree.
