### ISSUE TITLE
[Decommission Hub] allen-swdb

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1722]
### Summary

Confirmed the request for decommission on this comment: https://github.com/2i2c-org/infrastructure/issues/1440#issuecomment-1252551218

### Info

- **Community Representative:** @mabuice
- **Link to New Hub issue:** https://github.com/2i2c-org/infrastructure/pull/1585
- **Proposed end date:** Oct 3rd 2022

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [ ] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
    - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration
  - [ ] If no, confirm it is ok to delete all the data stored in the user home directories

#### Phase II - Hub Removal
(These steps are decribed in more detail in the docs at https://infrastructure.2i2c.org/en/latest/howto/hubs/delete-hub.html.)

- [ ] Manage existing data (migrate data from the hub or delete it)
- [ ] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.
- [ ] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [ ] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [ ] Delete the hub's authentication application on auth0, GitHub or CILogon

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [ ] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [ ] Delete the terraform workspace: `terraform workspace delete <NAME>`
- [ ] Remove the associated `config/clusters/<cluster_name>` directory and all its contents
- Remove the cluster from CI:
  - [ ] [`deploy-hubs.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-hubs.yaml)
  - [ ] [`validate-clusters.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/validate-clusters.yaml)
- [ ] Remove the cluster from the list of grafana datasources at https://grafana.pilot.2i2c.cloud/datasources
- [ ] Remove A record from Namecheap account

**Comment by damianavila** [comment]
@mabuice, can you please confirm the following two items:

* Confirm with Community Representative that the hub is no longer in use and it's safe to decommission (double checking because of protocol :wink:).
* Confirm if there is any data to migrate from the hub before decommissioning

**Comment by damianavila** [comment]
@mabuice, just a gentle reminder about confirming the items I asked about above. Thanks!

**Comment by damianavila** [comment]
I also assigned this decommission to @yuvipanda since he is going to finish and merge #1585 before the decommission actually happens 😉.

**Comment by mabuice** [comment]
@damianavila I think everything is good.  It's ok to decommission.  Sorry for the late response.

Thanks for everything; this was great.

**Comment by yuvipanda** [comment]
Thanks for confirming, @mabuice! This will destroy all user data in their home directories irretrievably, hope that's ok :)

Decomission will happen whenever https://github.com/2i2c-org/infrastructure/pull/1736 is reviewed and merged.

**Comment by yuvipanda** [comment]
It is gone now!

**Comment by sgibson91** [comment]
Just FYI, I noticed the GitHub OAuth apps and Namecheap entries for this hub are hanging around, so I will clean those up

**Comment by damianavila** [comment]
> so I will clean those up

Thanks @sgibson91!
