### ISSUE TITLE
[EVENT] GES DISC User Working Group Workshop

### ISSUE THREAD

**Issue by alexishunzinger** [2i2c-org/infrastructure#1731]
### Summary

 This is a 1.5 hour hands-on demo for the GES DISC User Working group's annual in-person meeting, focusing on cloud access of NASA data.

### Event Info

- **Community Representative:**  @alexishunzinger, @battistowx
- **Event begin:**   September 29, 2022
- **Event end:**  September 29, 2022
- **Active times:**  10:00am - 1:00pm Eastern
- **Number of attendees:**  25-35
- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Hub info

- **Hub URL**:  https://openscapes.2i2c.cloud/hub/
- **Hub decommisioned after event?**:  no

### Task List

**Before the event**

- [x] Dates confirmed with the community representative and added to Hub Events Calendar.
- ~Quotas from the cloud provider are high-enough to handle expected usage.~

**One week before event** Hub is running.
- [ ] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  
~**1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.~

**During and after event**

- [x] Confirm event is finished.
~Nodegroup created for the hub is decommissioned / cluster is scaled down.~
~Hub decommissioned (if needed).~
- [ ] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by yuvipanda** [comment]
/me waves at @briannapagan from GES DISC (I think?) with whom I'm working on other projects :)

I think for this number of users, a separate nodepool is not necessary. Should be ok I think.

Good luck with the event!

**Comment by damianavila** [comment]
Hey @alexishunzinger, the date of your event is getting close!

Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
- [ ] Confirm that the "Event Info" above is correct
- [ ] On your hub: log-in and authentication works as-expected
- [ ] `nbgitpuller` links you intend to use resolve properly (in case you are using nbgitpuller)
- [ ] Your notebooks and content run as-expected

Thanks!

**Comment by damianavila** [comment]
Hey @alexishunzinger, your event appears to be over 🎉

We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!

- Did the infrastructure behave as expected?
- Anything that was confusing or could be improved?
- Any extra functionality you wish you would have had?
- Could you share a story about how you used the hub?
- Any other feedback that you'd like to share?

Thanks!!

**Comment by jules32** [comment]
Thank you all, we've heard good things about this successful event!

**Comment by alexishunzinger** [comment]
Thanks @yuvipanda, thanks @damianavila! A short, but successful event. We has no issues.

- _Did the infrastructure behave as expected?_
Yes!
- _Anything that was confusing or could be improved?_
No.
- _Any extra functionality you wish you would have had?_
No.
- _Could you share a story about how you used the hub?_
We hosted a mini-workshop (< 1.5 hours) for our User Working Groups members to show them one data access method. It was hybrid and we had issues with some virtual participants being able to see the meeting platform chat. This made it very challenging to share links and help them troubleshoot!
- _Any other feedback that you'd like to share?_
Only gratitude for this JupyterHub and the support you all provide! :-)
