### ISSUE TITLE
[Decommission Hub] University of Texas

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1739]
### Summary

The request for decommissioning comes from the lead issue: https://github.com/2i2c-org/leads/issues/52#issuecomment-1155728242. Also, the decommission will solve: https://github.com/2i2c-org/infrastructure/issues/1738

### Info

- **Community Representative:** @jameshowison
- **Link to New Hub issue:** https://github.com/2i2c-org/infrastructure/issues/968
- **Proposed end date:** First week of October

#### Phase I

- [ ] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [ ] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
    - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration
  - [ ] If no, confirm it is ok to delete all the data stored in the user home directories

#### Phase II - Hub Removal
(These steps are decribed in more detail in the docs at https://infrastructure.2i2c.org/en/latest/howto/hubs/delete-hub.html.)

- [ ] Manage existing data (migrate data from the hub or delete it)
- [ ] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.
- [ ] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [ ] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [ ] Delete the hub's authentication application on auth0, GitHub or CILogon
- [ ] Delete additional utexas-demo associated resources (https://github.com/2i2c-org/infrastructure/issues/1738)

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [ ] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [ ] Delete the terraform workspace: `terraform workspace delete <NAME>`
- [ ] Remove the associated `config/clusters/<cluster_name>` directory and all its contents
- Remove the cluster from CI:
  - [ ] [`deploy-hubs.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-hubs.yaml)
  - [ ] [`validate-clusters.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/validate-clusters.yaml)
- [ ] Remove the cluster from the list of grafana datasources at https://grafana.pilot.2i2c.cloud/datasources
- [ ] Remove A record from Namecheap account

**Comment by jameshowison** [comment]
Thanks.  As the community rep for this hub I confirm that it can be
removed.  I continue to evangelize for the 2i2c infrastructure, but this
particular hub isn't being used at present.

--J
