### ISSUE TITLE
[Request deployment] New Hub: VICTOR

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#1831]
### Important dates

- **Target start date**: Nov 4, 2022
- **Required start date**: Nov 11, 2022
- **Any important dates for usage**: N/A

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

Einat Lev, einatlev@ldeo.columbia.edu, @einatlev-ldeo
Sam Krasnoff, krasnoff@ldeo.columbia.edu, @SamKrasnoff

### Hub logo image URL

https://drive.google.com/file/d/1b7TMc1tkg98PtfOokCQ5Bvbik1m8fcAT/view

### Hub logo website URL

https://people.climate.columbia.edu/projects/view/2387

### Hub user image tag and name

pangeo/pangeo-notebook:2022.09.21

### Extra features you'd like to enable

- [X] Specific cloud provider or datacenter (otherwise GCP)
- [ ] Dedicated Kubernetes cluster
- [X] Scalable Dask Cluster

### (Optional) Preferred cloud provider

AWS

### Other relevant information to the features above

- AWS region `us-west-2` per https://github.com/2i2c-org/leads/issues/51#issuecomment-1282673893

- Please deploy initial with a `pangeo/pangeo-notebook` image. The expectation is that the VICTOR team will replace this with a self-managed image in the near future.

- Suggested Hub URL: `https://victor.2i2c.cloud`

- If possible, please configure multiple machine profiles. As a suggestion, something like the following I think is a good starting point. I'll ask for guidance from @2i2c-org/tech-team on what to use for the `instance-type` for this deployment on AWS.

```
      profileList:
        # The mem-guarantees are here so k8s doesn't schedule other pods
        # on these nodes. They need to be just under total allocatable
        # RAM on a node, not total node capacity. Values calculated using
        # https://learnk8s.io/kubernetes-instance-calculator
        - display_name: "Small"
          description: 5GB RAM, 2 CPUs
          default: true
          kubespawner_override:
            mem_limit: 7G
            mem_guarantee: 4.5G
            node_selector:
              node.kubernetes.io/instance-type: <unknown>
        - display_name: Medium
          description: 11GB RAM, 4 CPUs
          kubespawner_override:
            mem_limit: 15G
            mem_guarantee: 11G
            node_selector:
              node.kubernetes.io/instance-type: <unknown>
        - display_name: Large
          description: 24GB RAM, 8 CPUs
          kubespawner_override:
            mem_limit: 30G
            mem_guarantee: 24G
            node_selector:
              node.kubernetes.io/instance-type: <unknown>
        - display_name: Huge
          description: 52GB RAM, 16 CPUs
          kubespawner_override:
            mem_limit: 60G
            mem_guarantee: 52G
            node_selector:
              node.kubernetes.io/instance-type: <unknown>
```

### Tasks to deploy the hub

- [x] 1. Deploy information filled in above
- [x] 2. Engineer who will deploy the hub is assigned
- [x] 3. Initial Hub deployment PR https://github.com/2i2c-org/infrastructure/pull/1877
- [x] 4. Administrators able to log on -> Hub now in steady-state

**Comment by GeorgianaElena** [comment]
There is now a cluster running at https://victor.2i2c.cloud 🚀

**Comment by jmunroe** [comment]
Thanks @GeorgianaElena! I'll let @einatlev-ldeo and @SamKrasnoff know and, assumming they are also able to access this new hub, I think we should be able to close this particular issue.

**Comment by damianavila** [comment]
Lovely piece of work, @GeorgianaElena!

**Comment by jmunroe** [comment]
The administrators have been able to access this new hub. Assuming no further action is required, this issue can be closed.

**Comment by damianavila** [comment]
> Assuming no further action is required, this issue can be closed.

Once the associated PR lands (get's merged), let's close it 😉.
