### ISSUE TITLE
[Incident] UToronto Hub Login failing with 500 errors

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/infrastructure#1845]
### Summary

Looks like for UToronto we still store hub logs on the db disk and it's full.
The incident is over now thanks to @yuvipanda.

### Impact on users

Everyone, AFAIK.

### Important information

- Hub URL: jupyter.utoronto.ca
- Support ticket ref: https://2i2c.freshdesk.com/a/tickets/250 (and 249 which was merged here.
- PagerDuty incident: https://2i2c-org.pagerduty.com/incidents/Q166EM816R6LY7
- Dedicated Slack: https://2i2c.slack.com/archives/C048GNWMF3R

### Tasks and updates

- [x] Discuss and address incident, leaving comments below with updates
- [x] Incident has been dealt with or is over
- [x] Copy/paste the after-action report below and fill in relevant sections
- [x] Incident title is discoverable and accurate
- [x] All actionable items in report have linked GitHub Issues

<details>
<summary>After-action report template</summary>

```
# After-action report

These sections should be filled out once we've resolved the incident and know what happened.
They should focus on the knowledge we've gained and any improvements we should take.

## Timeline

_A short list of dates / times and major updates, with links to relevant comments in the issue for more context._

All times in {{ most convenient timezone}}.

- {{ yyyy-mm-dd }} - [Summary of first update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of another update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of final update](link to comment)


## What went wrong

_Things that could have gone better. Ideally these should result in concrete
action items that have GitHub issues created for them and linked to under
Action items._

- Thing one
- Thing two

## Where we got lucky

_These are good things that happened to us but not because we had planned for them._

- Thing one
- Thing two

## Follow-up actions

_Every action item should have a GitHub issue (even a small skeleton of one) attached to it, so these do not get forgotten. These issues don't have to be in `infrastructure/`, they can be in other repositories._

### Process improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Documentation improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Technical improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]
```

</details>

**Comment by damianavila** [comment]
Logs (edited) from @yuvipanda's investigation:

* I looked at hub logs, and found `sqlite3.OperationalError: database or disk is full`.
* I gzipped the log file, I copied the gzipped file locally
* Changed the pvc to 60G
* I restarted the hub pod, after, which resizes the disk too
* I copied the jupyterhub.log.gz file back now

**Comment by damianavila** [comment]
PR in grafana-dashboards to check disk usage: https://github.com/jupyterhub/grafana-dashboards/pull/49.

**Comment by damianavila** [comment]
* [ ] We still need to write and post-mortem and send it back to UToronto.

**Comment by damianavila** [comment]
The incident report was merged and shared through the support channel, I think we can close this one now.
