### ISSUE TITLE
[EVENT] UToronto Exam on JupyterHub

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1905]
### Summary

https://2i2c.freshdesk.com/a/tickets/220 has more information.

UToronto wants to try running a pilot, where they use the JupyterHub to run an exam for students. This needs a highly available JupyterHub, with a support engineer available during the specific time of the exams (I think they're about 3h).

### Event Info

- **Community Representative:** 
- **Event time:** Wednesday December 14, 9-12pm noon ET
- **Number of attendees:** 90
- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Hub info

- **Hub URL**:  jupyter.utoronto.ca
- **Hub decommisioned after event?**:  no

### Task List

**Before the event**

- [x] Dates confirmed with the community representative and added to Hub Events Calendar.
- [x] Quotas from the cloud provider are high-enough to handle expected usage.
- [x] NFS disk has enough free space for this event to go fine
- [x] Exam setters have tried out the exam on the JupyterHub, and confirm that all the code for solutions executes as required with the environment in the hub. The environment will be frozen temporarily after this.
- [x] Exam setters have figure out how much RAM (and CPU) the solution will take, and we set these as *guarantees* for the student user pods during the course of the exam. The config changes will be deployed 1 working day before the exam.
- [x] Pre-warm the cluster to make sure there is enough nodes for all the students coming in, so no student will have to wait for a node scale up. This should be done a few hours before the exam starts.
- [x] Make sure an engineer is assigned to watch support tickets during this time period.

**During and after event**

- [x] Confirm event is finished.
- [x] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [x] Debrief with community representative. ->  https://2i2c.freshdesk.com/a/tickets/220

**Comment by yuvipanda** [comment]
Progress being tracked in https://2i2c.freshdesk.com/a/tickets/220

**Comment by yuvipanda** [comment]
Copying relevant message from freshdesk ticket:

We currently guarantee users 1G of RAM, and limit then to 2G of RAM. We do not set any CPU limits or guarantees, but to ensure that during an exam everyone has access to equal resources, I suggest we set these for the duration of the exam.

So for this one, I propose we set a memory guarantee of 2G of RAM, and a CPU guarantee of 1 CPU per user. This makes sure that all students get the same amount of resources, even if it perhaps a little overkill. We can collect info on how much was actually used, and perhaps use that for future endeavors. 

Given that we don't have a hub specific for exams, we'll have to apply these resource changes across all users for the duration of the exam. This might increase the cloud cost a *little*, but I don't think it'll be particularly noticeable - most likely it'll be lost in the noise. This too, we can validate after to see how it went.

I've opened https://github.com/2i2c-org/infrastructure/pull/1962 to make these resource requests happen, but we will not merge these before Dec 14.

David, if you can confirm that 2G of RAM and 1 CPU will be enough for students to complete the exam, that would be very valuble :) I can also temporarily set a 1 CPU restriction for users on the hub if you want to use that to test.

**Comment by yuvipanda** [comment]
We currently are using E8s, which have... 8 CPUs :) If we offer users 1 CPU each, and expect 90, that would place about 7 users per node (unless we want to try adding other nodes, which I don't wanna). So that means we should pre-warm to at least about 14 nodes, but might have to be a little higher due to the fact that other regular users might also be on the hub at the same time. So I'd say we want to scale it up about 1h before the event to at least *14 nodes over what it currently has*.

So we should check Azure quota right now.

**Comment by damianavila** [comment]
> So we should check Azure quota right now.

I do not see any internal documentation about checking quotas in Azure. Does anyone besides @yuvipanda have experience looking at Azure quotas, maybe @sgibson91?

> NFS disk has enough free space for this event to go fine

Is there actually a limit for the Azure NFS layer?

> Pre-warm the cluster to make sure there is enough nodes for all the students coming in, so no student will have to wait for a node scale up. This should be done a few hours before the exam starts.

Maybe it could be warmed the day before in Pacific Time?

> Make sure an engineer is assigned to watch support tickets during this time period.

@GeorgianaElena or @sgibson91, can any of you be the dedicated eng for this event?
Btw, we should actually have the whole (available at that time) team ready to jump if something arises, you should not be alone during these dedicated hours of special support.

**Comment by sgibson91** [comment]
> have experience looking at Azure quotas, maybe @sgibson91?

No idea, sorry. The only experience I had was being limited to 3 CPUs if you had a free/starter Azure subscription. This limit was removed as soon as you upgraded to a full subscription (which I'm sure UofT is). Other than that, I never ran into quota limits on Azure so never needed to look them up.

**Comment by damianavila** [comment]
We have a plan after some conversations in our sprint/cycle meeting.
This is now a multiple assignees issue 😉.

* @damianavila will take care of closely monitoring Freshdesk during the event.
* @GeorgianaElena will take care of the prewarming and be available if something arises during the event.
* @sgibson91 will take care of the shutting down process.

@yuvipanda will be available as a backup if we need to escalate.

**Comment by sgibson91** [comment]
I can be available during the event too, so then there's three of us to work on any problem.

**Comment by damianavila** [comment]
> I can be available during the event too, so then there's three of us to work on any problem.

Plan updated 😉!

**Comment by GeorgianaElena** [comment]
> David's last message in this ticket thread https://2i2c.freshdesk.com/a/tickets/220 suggests that he would like to test if the 1 CPU limit is ok.

Actually, for this one, I believe we could deploy  https://github.com/2i2c-org/infrastructure/pull/1962 to staging and get David test it there?

**Comment by yuvipanda** [comment]
@GeorgianaElena re: Quotas, I think you can see them in https://learn.microsoft.com/en-us/azure/quotas/view-quotas. I'd suggest the 'test' be just to scale up to like maybe 40 instances and see how that goes?

**Comment by damianavila** [comment]
It seems we are OK from the quotas perspective...

<img width="1168" alt="Screen Shot 2022-12-12 at 18 23 30" src="https://user-images.githubusercontent.com/1640669/207157833-89ba81f1-1766-49de-b353-baad9db195ba.png">

**Comment by damianavila** [comment]
Also @GeorgianaElena bumped the storage size from 3 to 4.5 TB.

<img width="387" alt="Screenshot 2022-12-12 at 21 56 15" src="https://user-images.githubusercontent.com/1640669/207190985-de1d3413-f1fc-49bd-89c5-1065a79b57fd.png">

**Comment by yuvipanda** [comment]
Here's how we evaluated how much quota to check for:

1. Each node has about 8 CPUs, and given we 'guarantee' 1 cpu per user (https://github.com/2i2c-org/infrastructure/pull/1962), that is about 7 users per node
2. For 90 users, that's about 13 nodes
3. We looked at peak usage over the last 30 days, and that was about 410 users:

![image](https://user-images.githubusercontent.com/30430/207237627-c36d383a-d14c-4d03-bf17-72d7cc10be6d.png)

4. So if we hit similar peak user numbers now (very unlikely!), *each of them will get 1 CPU!*. Not just the 90 users. So we have to plan for that!
5. So assuming about 410 + 90 as worst case, that's about 500 users. At 7 per node, that's about 71 nodes. This is super unlikely, and we will *not* be scaling up to this - but quotas can take time to increase, so it's important to plan for the worst case scenario here.
8. 71 nodes at 8 cpus is about 568 CPUs. So we added some more padding here and asked for a quota of 700

So I think CPU quota is good :)

The pre-warming should add let's say *15 nodes* to whatever is the existing number of nodes an hour or so before the exam. We should also do a quick check about 15 minutes before the exam to make sure that at least 15 empty nodes are still available.

**Comment by sgibson91** [comment]
@GeorgianaElena @damianavila We should merge #1962 within the next hour if my ET -> GMT conversion is correct

**Comment by GeorgianaElena** [comment]
Yes. I was saying the same thing but in a different channel https://2i2c.slack.com/archives/C028WU9PFBN/p1671022674981399 😅 I just merged that one

**Comment by GeorgianaElena** [comment]
Warm up completed 🎉

**Comment by GeorgianaElena** [comment]
Yes, I believe so.  There were 2 nodes when I started and the autoscaler was set with 1-100 limits

**Comment by sgibson91** [comment]
- Autoscaler reset to be within 1-100, and
- PR #1962 reverted in #2003

BUT

- I was under the impression that our policy was to scale user pools down to zero to save costs. We should document somewhere easy to find in these scenarios where a decision was made to diverge from that policy. E.g., UToronto has a min of 1 according to the terraform config which I took to be the source of truth.
- The maximum for autoscaling was 100, but we get a quota warning in the console about it, so I don't think we actually have enough quota to ever reach that maximum

<img width="560" alt="Screenshot 2022-12-14 at 18 04 11" src="https://user-images.githubusercontent.com/44771837/207678164-57b2e387-73fb-4c51-acc3-bd4be586e06b.png">

**Comment by yuvipanda** [comment]
We also need to send them an invoice - i would say 3h setup + teardown + 3h actual time. Sound ok?

thank you everyone for making this a success!

**Comment by GeorgianaElena** [comment]
>  i would say 3h setup + teardown + 3h actual time. Sound ok?

I believe that sounds pretty accurate.

**Comment by damianavila** [comment]
> Thanks everyone 🎉

Indeed, this one was a great example of the team quality we have.
Congrats to everyone!!
