### ISSUE TITLE
Get rid of eksctl from our infrastructure

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1924]
Almost 3y after filing, https://github.com/aws/containers-roadmap/issues/724 is finally fixed on the EKS side! This means we can switch away from using eksctl, and towards using terraform for our AWS setup - same as we do for GCP, Azure, etc.

I'd suggest we pick a single cluster and move it, and see how that goes.

# TODO

- [ ] Write Terraform Code that uses [managed nodegroups](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group) for nodegroups (EKS equivalent of nodepools)
- [ ] Upgrade to k8s 1.24 on EKS, as that is necessary for managed nodegroups to work properly
- [ ] Make sure our nvidia driver install is moved back into the support chart - this was moved to be handled by eksctl in https://github.com/2i2c-org/infrastructure/pull/1787

Once this is done, we can evaluate moving all the other ones gradually.
