### ISSUE TITLE
Remove all config generation in the deployer

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1925]
From a right to replicate perspective, our end users should be able to take the config out of this repo, and be able to use a `helm` command to continue to deploy the hubs, passing in just the config. The current impediment to this is the bits of config we autogenerate from the deployer: https://github.com/2i2c-org/infrastructure/blob/e351ddd68894a45f778caae7278fb1720056156d/deployer/hub.py#L27. That entire function should just go away. We'll just have to manually put in the config there as needed in all our hubs instead. 

# TODO:

- [ ] Move the hub homepage config out of deployer generated config
- [ ] Move ingress config out of deployer generated config
- [ ] Move binderhub registry config out of deployer generated config
- [ ] Move off auth0 completely, as CILogon already doesn't require we use deployer generate config

**Comment by yuvipanda** [comment]
Just absolutely amazing work, @GeorgianaElena!!!!!!!
