### ISSUE TITLE
[Request deployment] New Hub: UC Merced Education Hub on a 2i2c Shared Cluster

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#1929]
### Important dates

- **Target start date**: 2022-12-15
- **Required start date**: 2023-01-02

### Hub Authentication Type

Institutional Provider via CILogon (e.g., username@institution.org)

### First Hub Administrators

2i2c's @colliand has been working with [Sarvani Chadalapaka](https://www.linkedin.com/in/sarvanichadalapaka) (Github: handle @schadalapaka) to set this hub up. Sarvani serves as the Director of Research Computing. She may identify others at UC Merced who will assist with hub administration. 

I invite @schadalapaka to communicate with the 2i2c team about the deployment of this hub service using the comments under this issue. 

### Hub logo image URL

https://brand.ucmerced.edu/sites/brand.ucmerced.edu/files/images/ucm-logo-text.png

### Hub logo website URL

https://www.ucmerced.edu/

### Hub user image GitHub repository

Education Hub image (similar to that used for UC Berkeley's Data8 program)

### Hub user image tag and name

@colliand seeks help here from 2i2c engineering; this should be an education hub set up to support students taking a course like UC Berkeley's Data8. 

### Extra features you'd like to enable

- [ ] Specific cloud provider or datacenter (otherwise GCP)
- [ ] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

This will launch on a 2i2c managed shared cluster.

### (Optional) Billing and Cloud account

2i2c managed shared cluster.

### Other relevant information to the features above

This is a request for a new education hub for UC Merced on a shared 2i2c cluster.

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [x] 2. Engineer who will deploy the hub is assigned
- [x] 3. Initial Hub deployment PR https://github.com/2i2c-org/infrastructure/pull/1969
- [ ] 4. Administrators able to log on -> Hub now in steady-state

**Comment by schadalapaka** [comment]
Hi James- 
Thank you for the note.
Our preferred cloud provider can be 2i2c.
We do not need a dedicated kubernetes cluster or Dask cluster at this time.
Hope this helps.
Please let me know if you need any additional information from me.

Regards,
Sarvani

**Comment by colliand** [comment]
Thanks @schadalapaka! Can you share names or GitHub usernames for people at UC Merced who might be able to help us with setting up the single sign on? This should be straightforward.

**Comment by GeorgianaElena** [comment]
Hey @schadalapaka! There is now a hub running at https://ucmerced.2i2c.cloud 🚀 Please try it out and let me know what you think.

A few things about the hub's current configuration:

1. **you can login using your university provider through [CILogon](https://www.cilogon.org/home)**
2. **the following email address has been added as a hub admin: `schadalapaka@ucmerced.edu`**
     Let me know if this is not correct and I can change it
3. **you can add additional administrator users [from the admin panel](https://docs.2i2c.org/en/latest/admin/howto/manage-users.html#manage-users-from-the-administrator-panel)**
4. **the current user image is the [2i2c default one](https://github.com/2i2c-org/2i2c-hubs-image)**
   - This image is used by a few 2i2c educational hubs already, so I figured it might be a good starting point.
   - But you can always change the image yourself using the configurator. There is a small guide about this [here]
(https://github.com/2i2c-org/2i2c-hubs-image).
   - You can also create your custom user image, if the default one is missing things. There is a guide about this [here](https://docs.2i2c.org/en/latest/admin/howto/environment/index.html) and also more general info about the [user environment here](https://docs.2i2c.org/en/latest/admin/howto/environment/index.html)

**Comment by colliand** [comment]
Thanks Georgiana! I have written separately to our colleagues at UC Merced and am waiting for confirmation that all is well with this deployment. I will let you know if there are any issues.

**Comment by schadalapaka** [comment]
Hi All -
Thank you for setting up the pilot hub.
Question:how do instructors share notebooks with students/other users?
My understanding is that at Berkeley, notebooks are integrated with canvas.
Please let me know if you need additional information.
Regards,
Sarvani

**Comment by damianavila** [comment]
Hi @schadalapaka,

About how to share notebooks with students and other users, we recommend nbgitpuller: https://docs.2i2c.org/en/latest/community/content.html.

> My understanding is that at Berkeley, notebooks are integrated with canvas.

AFAIK, UC Berkeley has no notebook integration with canvas, they use nbgitpuller.

Btw, I suggest you send any further questions to our support email. Thanks!!

**Comment by shaneknapp** [comment]
> AFAIK, UC Berkeley has no notebook integration with canvas, they use nbgitpuller.

this is indeed true.  :)
