### ISSUE TITLE
[Request deployment] New Hub: researchdelight

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#1949]
### Important dates

- **Target start date**: 2022-12-05
- **Required start date**: 2022-12-12
- **Any important dates for usage**: N/A

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

@jmunroe

### Hub logo image URL

2i2c logo (@jmunroe will provide)

### Hub logo website URL

https://2i2c.org

### Hub user image GitHub repository

https://github.com/2i2c-org/researchdelight-image

### Hub user image tag and name

quay.io/2i2c/researchdelight-image

### Extra features you'd like to enable

- [X] Specific cloud provider or datacenter (otherwise GCP)
- [ ] Dedicated Kubernetes cluster
- [X] Scalable Dask Cluster

### (Optional) Preferred cloud provider

AWS

### Other relevant information to the features above

This hub is for demo use, initially, by @jmunroe at AGU in December.  I'd like this to be on an AWS shared cluster (us-west-2) and so proximate to NASA and NOAA datasets.  My vision here is this would be a "showcase" hub that can be used to demonstrate what is possible for science/research communities. 

This new hub is part of the Q4 goal:
- https://github.com/2i2c-org/infrastructure/issues/1813

The hub image itself is part of the demonstration and should follow our "best practices" we are recommended our community partners follow.  

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [x] 2. Engineer who will deploy the hub is assigned
- [ ] 3. Initial Hub deployment PR <link to PR>
- [ ] 4. Administrators able to log on -> Hub now in steady-state

**Comment by damianavila** [comment]
Thanks for opening this new hub request @jmunroe!

I think it is important to define which image you might use.
Do you have in mind using some pre-existing image? Building one on top of our user image repo? Something else?

**Comment by jmunroe** [comment]
I've created a placeholder image and linked up through quay.io

`quay.io/2i2c/researchdelight-image`

**Comment by jmunroe** [comment]
Given that this hub is meant to showcase what is possible on a 2i2c research hub, it made sense to rename it something that evoked 2i2c's mission _to make **research** and **education** more **impactful**, **accessible**, and **delightful** by developing, operating, and supporting infrastructure for interactive computing_.

For me, `researchdelight` has the right distinctiveness but naming things is hard. I am totally open to suggestions if we need to get a '2i2c-' in there somehow.

**Comment by sgibson91** [comment]
@jmunroe Regarding GitHub auth - how do you expect to use this hub in demos? Should we be able to add anyone with a valid GitHub account to the hub to try it out, e.g. manually via the admin panel, or by adding them to a GitHub team? Should I restrict it to only 2i2c-org members for now?

**Comment by jmunroe** [comment]
GitHub authentication so I can manage a list of specific handles in the JupyterHub admin panel.  Thanks.

**Comment by sgibson91** [comment]
Hub is now available for testing at https://researchdelight.2i2c.cloud/

**Comment by jmunroe** [comment]
Awesome. Thanks!

**Comment by sgibson91** [comment]
This issue can be closed once #1967 has a positive review from @2i2c-org/tech-team and is merged.
