### ISSUE TITLE
[Request deployment] New Hub: UBC-EOAS Hub

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#2001]
### Important dates

- **Target start date**: 2022-01-09
- **Required start date**: 2022-01-16
- **Any important dates for usage**: end of January labs and projects require the hub

### Hub Authentication Type

Institutional Provider via CILogon (e.g., username@institution.org)

### Community Technical Repesentatives
- _primary_: [Charles Kryzsik](https://www.eoas.ubc.ca/people/charleskrzysik), @charleskrzysik
- _secondary_: @lheagy 

### Hub logo image URL

https://brand.ubc.ca/files/2018/09/Logos_1_2CrestDownload_768px.jpg

### Hub logo website URL

https://www.eoas.ubc.ca/

### Hub user image tag and name

uncertain at this moment

### Extra features you'd like to enable

- [X] Specific cloud provider or datacenter (otherwise GCP)
- [X] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

AWS

### (Optional) Billing and Cloud account

I need help figuring out the billing and cloud accounts

### Other relevant information to the features above

UBC rules will likely require that this hub be hosted on a cluster in a data center located in Canada. Based on other information, UBC is likely to want 2i2c to deploy on AWS. 

Related leads issue: https://github.com/2i2c-org/leads/issues/100.

### Tasks to deploy the hub

- [x] 1. Deploy information filled in above
- [x] 2. Engineer who will deploy the hub is assigned
- [x] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [x] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by colliand** [comment]
This is a first hub for UBC designed to support educational scenarios in the [Department of Earth, Ocean and Atmospheric Sciences (EOAS)](https://www.eoas.ubc.ca/). I suggest we place the hub at ubc-eoas.2i2c.cloud URL. We can configure DNS rerouting to another URL target if requested.

**Comment by consideRatio** [comment]
As discussed in the sprint meeting, this is something I plan to start working on Monday 9th!

**Comment by consideRatio** [comment]
Hi @CharlesKrzysik!

I'm now actively working on setting up a JupyterHub for you and need some input from you.

### Blocking 1: choice of cloud provider and datacenter/region

> UBC rules will likely require that this hub be hosted on a cluster in a data center located in Canada. Based on other information, UBC is likely to want 2i2c to deploy on AWS.

In Canada there are three existing datacenters from AWS/GCP to deploy to with different ping time and opt-in GPU capability from Vancouver.

- AWS `ca-central-1` in Montreal. Ping time ~66 ms.
- GCP `northamerica-northeast1` in Montreal. Ping time ~66 ms.
- GCP `northamerica-northeast2` in Toronto. Ping time ~52 ms. (opt-in use of GPU not possible)
- (scheduled for end of 2023 / early 2024) AWS Calgary. Ping time ~13 ms.

@CharlesKrzysik - do you have a wish on where to deploy?

- It could be a benefit to stick with a cloud provider and datacenter/region if you have large datasets with that cloud provider datacenter/region
- The ping is mostly showing when writing things in terminals and using a "desktop view" as compared to for example JupyterLab

If you are not opined about the choice, I'll ask my 2i2c collegeas to weigh in and go with what they think is best. We have historically leaned towards GCP due to their maturity in providing Kubernetes based services. I guess we may suggest `northamerica-northeast1` then.

### Blocking 2: decision about a billing account

@CharlesKrzysik do you have a billing account with AWS/GCP (depending on the choice above) that should be used, for example where you may have been given AWS or GCP credits, or should we create one for you?

For us to create one is probably the easiest option.

### Allowed users

> Institutional Provider via CILogon (e.g., [username@institution.org](mailto:username@institution.org))

@CharlesKrzysik, does it make sense to you to limit access to users with a `<user>@eoas.ubc.ca` domain suffixes in their associated email? Are there other groups of users you wish to provide access?

### Hub user image GitHub repository

A user image should be initialized as described [in this user image template project](https://github.com/2i2c-org/hub-user-image-template#readme).

@CharlesKrzysik is there a GitHub organization associated with UCB-EOAS, or should you perhaps create one to contain a project building the user image?

Until there is a custom image configured, the hub will rely on a 2i2c managed image with some common functionality defined in https://github.com/2i2c-org/2i2c-hubs-image.

**Comment by damianavila** [comment]
> I'll ask my 2i2c collegeas to weigh in and go with what they think is best.

@consideRatio, I just added @sgibson91 as a secondary helper on this deployment so you have quick feedback with any internal questions you may have 😉.

**Comment by CharlesKrzysik** [comment]
> Hi @CharlesKrzysik!
> 
> I'm now actively working on setting up a JupyterHub for you and need some input from you.
> 
> ### Blocking 1: choice of cloud provider and datacenter/region
> > UBC rules will likely require that this hub be hosted on a cluster in a data center located in Canada. Based on other information, UBC is likely to want 2i2c to deploy on AWS.
> 
> In Canada there are three existing datacenters from AWS/GCP to deploy to with different ping time and opt-in GPU capability from Vancouver.
> 
> * AWS `ca-central-1` in Montreal. Ping time ~66 ms.
> * GCP `northamerica-northeast1` in Montreal. Ping time ~66 ms.
> * GCP `northamerica-northeast2` in Toronto. Ping time ~52 ms. (opt-in use of GPU not possible)
> * (scheduled for end of 2023 / early 2024) AWS Calgary. Ping time ~13 ms.
> 
> @CharlesKrzysik - do you have a wish on where to deploy?

I would prefer to deploy in northamerica-northeast1. 
> 
> * It could be a benefit to stick with a cloud provider and datacenter/region if you have large datasets with that cloud provider datacenter/region
> * The ping is mostly showing when writing things in terminals and using a "desktop view" as compared to for example JupyterLab
> 
> If you are not opined about the choice, I'll ask my 2i2c collegeas to weigh in and go with what they think is best. We have historically leaned towards GCP due to their maturity in providing Kubernetes based services. I guess we may suggest `northamerica-northeast1` then.

That sounds good.

> ### Blocking 2: decision about a billing account
> @CharlesKrzysik do you have a billing account with AWS/GCP (depending on the choice above) that should be used, for example where you may have been given AWS or GCP credits, or should we create one for you?

We do not have account with AWS credits.
> For us to create one is probably the easiest option.
> 
> ### Allowed users
> > Institutional Provider via CILogon (e.g., [username@institution.org](mailto:username@institution.org))
> 
> @CharlesKrzysik, does it make sense to you to limit access to users with a `<user>@eoas.ubc.ca` domain suffixes in their associated email? Are there other groups of users you wish to provide access?

No I do not believe that it makes sense to limit users. Only staff, or grad students possess @eoas.ubc.ca domain suffix.

> 
> ### Hub user image GitHub repository
> A user image should be initialized as described [in this user image template project](https://github.com/2i2c-org/hub-user-image-template#readme).
> 
> @CharlesKrzysik is there a GitHub organization associated with UCB-EOAS, or should you perhaps create one to contain a project building the user image?

I will create one shortly.

> Until there is a custom image configured, the hub will rely on a 2i2c managed image with some common functionality defined in https://github.com/2i2c-org/2i2c-hubs-image.

**Comment by consideRatio** [comment]
@CharlesKrzysik thanks for filling in the blanks!

I'm now already on my way with a setup in AWS `ca-central-1`, also in Montreal. Do you wish to switch to GCP `northamerica-northeast1` or should we stay with AWS?

**Comment by consideRatio** [comment]
@CharlesKrzysik, @lheagy, @colliand, @sgibson91 - we are now up and running at https://ubc-eoas.2i2c.cloud!

- A PR adding the configuration for this deployment to the automation going onwards: #2044

**Comment by consideRatio** [comment]
## Some open questions

- Does the login with your institutional email work?
- Server options
  - Should users be provided dedicated machines only, or also have the ability to request a share resources of a server as well?
  - How powerful machines should be possible to start?

**Comment by consideRatio** [comment]
It turns out that we are now granted 512 in quota for our project, but I don't understand why. This will support very many dedicated user servers if needed.

**Comment by sgibson91** [comment]
> It turns out that we are now granted 512 in quota for our project, but I don't understand why.

We have automatic quota increase request for every new project that gets added to the 2i2c AWS org. This still needs documenting as part of this issue:

- https://github.com/2i2c-org/infrastructure/issues/1793

**Comment by sgibson91** [comment]
This hub is up and running now, the associated PR was merged. So I believe we can close this issue and any further questions regarding the hub can be sent to `support@2i2c.org`. Please reopen if you disagree.
