### ISSUE TITLE
[Request deployment] New Hub: NASA VEDA Hub

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#2017]
### Important dates

- **Target start date**: 2023-01-24
- **Required start date**: 2023-02-01

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

@abarciauskas-bgse
@freitagb
@j08lue
@rezuma

### [GitHub Auth only] How would you like to manage your users?

Allowing members of specific GitHub team(s): `@veda-analytics-access/all-users`

### [GitHub Teams Auth only] Profile restriction based on team membership

> No restriction for now, thanks - @veda-analytics-access/all-users should get the one machine size we have. We might want to add more in the future, though, if that is okay.

### Hub logo image URL

pending

### Hub logo website URL

https://www.earthdata.nasa.gov/esds/veda

### Hub user image GitHub repository

> 2i2c default / pangeo-notebook https://github.com/pangeo-data/pangeo-docker-images/tree/master/pangeo-notebook

### Hub user image tag and name

> 2i2c default / latest tagged release - at the time of writing pangeo/pangeo-notebook:2023.01.04

### Extra features you'd like to enable

- [x] Specific cloud provider or datacenter (otherwise GCP)
- [ ] Dedicated Kubernetes cluster
- [x] Scalable Dask Cluster

### (Optional) Preferred cloud provider

> [Science Managed Cloud Environment (SMCE)](https://www.nccs.nasa.gov/systems/SMCE) - a managed Amazon Web Service (AWS) based infrastructure for NASA funded projects

> We had a coordinating discussion between 2i2c and NASA earlier this week and found a working arrangement. SMCE creates the AWS organization and 2i2c gets accounts with full access, as I recall.

### (Optional) Billing and Cloud account

To be provided by SMCE @rezuma

### Tasks to deploy the hub

- [x] 1. Deploy information filled in above
- [x] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR: https://github.com/2i2c-org/infrastructure/pull/2083
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by damianavila** [comment]
@colliand, I see a lot of unknowns (pending) on this request 😉.
Can we make sure we consolidate the minimum information needed (during the next few days) so we can deploy this hub soon? Thanks!!

**Comment by j08lue** [comment]
### [GitHub Auth only] How would you like to manage your users?
Allowing members of specific GitHub team(s): @veda-analytics-access/veda-hub-users

### [GitHub Teams Auth only] Profile restriction based on team membership
What is this?

### Hub logo image URL
[pending](https://www.earthdata.nasa.gov/s3fs-public/2022-08/veda_logo_lp.png)

### Hub logo website URL
https://www.earthdata.nasa.gov/esds/veda

### Hub user image GitHub repository
2i2c default / `pangeo-notebook` https://github.com/pangeo-data/pangeo-docker-images/tree/master/pangeo-notebook

### Hub user image tag and name
2i2c default / latest tagged release - at the time of writing `pangeo/pangeo-notebook:2023.01.04`

### Extra features you'd like to enable
- [x] Specific cloud provider or datacenter (otherwise GCP)
- [ ] Dedicated Kubernetes cluster
- [x] Scalable Dask Cluster

### (Optional) Preferred cloud provider
[Science Managed Cloud Environment (SMCE)](https://www.nccs.nasa.gov/systems/SMCE) - a managed Amazon Web Service (AWS) based infrastructure for NASA funded projects

(Optional) Billing and Cloud account
To be provided by SMCE @rezuma

**Comment by sgibson91** [comment]
> ### [GitHub Teams Auth only] Profile restriction based on team membership
> What is this?

We can offer different profile on the hub, such as: different sizes of machine, different environments, even GPUs. You may wish only _some_ folk who can access the hub to be able to select certain profiles, such as GPUs since they cost more money. If you setup different GitHub teams, we can use those teams to make sure only the right groups can see the appropriate profiles as options. See the "Tip" box in the documentation here: https://docs.2i2c.org/en/latest/admin/howto/manage-users.html

**Comment by sgibson91** [comment]
> ### (Optional) Preferred cloud provider
> [Science Managed Cloud Environment (SMCE)](https://www.nccs.nasa.gov/systems/SMCE) - a managed Amazon Web Service (AWS) based infrastructure for NASA funded projects

Unfortunately, I don't think we are setup to deploy onto anyone else's managed service right now. We would either need to deploy directly to AWS or spend some development time figuring out how to extend our deployment infrastructure to be compatible with the NASA service.

**Comment by j08lue** [comment]
Thanks for following up, @sgibson91!

> We would either need to deploy directly to AWS

You will get direct access. We had a coordinating discussion between 2i2c and NASA earlier this week and found a working arrangement. SMCE creates the AWS organization and 2i2c gets accounts with full access, as I recall.

> We can offer different profiles on the hub

Thank you for explaining that. For now, we only need one team and one machine size for all - details to be specified. I created team called named `all-users`, the example in the docs, then we can scale from there later, if need be. I'll adjust my comment above.

**Comment by sgibson91** [comment]
> You will get direct access. We had a coordinating discussion between 2i2c and NASA earlier this week and found a working arrangement. SMCE creates the AWS organization and 2i2c gets accounts with full access, as I recall.

Amazing!

**Comment by j08lue** [comment]
Quick follow-up, @sgibson91: I am assuming that user _roles_ in JupyterHub (`user`/`admin`) are not controlled via GH teams. Pls correct me if I am wrong about that, then I'll create a GH team for admins.

**Comment by ranchodeluxe** [comment]
Good to meet you @sgibson91. I'm new to the VEDA project and wanted to ask some questions about  environment customization. 

1. What's the process for requesting customization(s) to the default image? Is this something we do now? For example, if I want `conda.store` (https://github.com/Quansight/conda-store) to be available by default.

2. In the "Extra features" section what's the difference between having a "Dedicated Kubernetes cluster" versus not? I assume not choosing a dedicated cluster means we get our own k8 worker node that all deploys are assigned to (through affinity) but the rest of the cluster ("control plane" nodes) are shared among different customers?

3. Where can I read about how the JupyterHub roles are mapped to Kubernetes RBAC permissions? Or is it an entirely separate layer of the system?

**Comment by sgibson91** [comment]
> 1. What's the process for requesting customization(s) to the default image? Is this something we do now? For example, if I want `conda.store` ([Quansight/conda-store](https://github.com/Quansight/conda-store)) to be available by default.

If you need something specific in your environment, we would encourage you to setup your own image to use with the hub following our docs here: https://docs.2i2c.org/en/latest/admin/howto/environment/index.html

> 2. In the "Extra features" section what's the difference between having a "Dedicated Kubernetes cluster" versus not? I assume not choosing a dedicated cluster means we get our own k8 worker node that all pods are assigned to (through affinity) but the rest of the cluster ("control plane" nodes) are shared among different customers?

For a non-dedicated cluster, your hub would be on a Kubernetes cluster with other hubs, but we assign pods to nodes based on machine size requested, not which hub the request comes from. "Dedicated" means that your community's hub (a staging and prod pairing, to be explicit) would be the only hub on that cluster.

> 3. Where can I read about how the JupyterHub roles are mapped to Kubernetes RBAC permissions? Or is it an entirely separate layer of the system?

I believe these two things are separate. For example, the hub itself makes requests to Kubernetes on behalf of the user, so I don't think the JupyterHub role a user is assigned would pass down to the Kubernetes layer. Would love confirmation from @2i2c-org/engineering on that though.

**Comment by ranchodeluxe** [comment]
Thanks for the replies @sgibson91. One more clarifying question if you don't mind:

> For a non-dedicated cluster, your hub would be on a Kubernetes cluster with other hubs, but we assign pods to nodes based on machine size requested, not which hub the request comes from. "Dedicated" means that your community's hub (a staging and prod pairing, to be explicit) would be the only hub on that cluster.

When I asked the initial question I kinda glossed over the fact that that `2i2c` will be deploying into a new AWS account (supplied by SMCE). Does this change aspects of the answer? For example, does this mean we'd actually need to have a dedicated EKS cluster? Or does this mean that what gets deployed into that new AWS account is just a worker node (where other potential customer hub pods are also deployed based on machine size)? The latter option seems unlikely to me based on IAM roles/permissions etc. But I don't know anything. The reason I'm asking these questions is because I really want to understand what the k8 setup looks like so I have the power to noodle (technical term 😉 ) without stepping on other hub user toes.

**Comment by sgibson91** [comment]
We would deploy an EKS cluster into the AWS account setup by SMCE once we have access to it.

**Comment by sgibson91** [comment]
Given that SMCE is creating a specific AWS account and granting us access, this will have to be a dedicated cluster. There will be no other hubs deployed to it.

**Comment by consideRatio** [comment]
> > 5\. Where can I read about how the JupyterHub roles are mapped to Kubernetes RBAC permissions? Or is it an entirely separate layer of the system?
> 
> I believe these two things are separate. For example, the hub itself makes requests to Kubernetes on behalf of the user, so I don't think the JupyterHub role a user is assigned would pass down to the Kubernetes layer. Would love confirmation from @2i2c-org/engineering on that though.

When JupyterHub the software, configured for a k8s cloud environment using jupyterhub/kubespawner, starts a server represented as a k8s Pod, it is only JupyterHub that has the k8s RBAC permissions to manage Pods etc. When the user pod/container is started, the software running inside it will not be provided k8s RBAC permissions by default. JupyterHub (kubespawner) is by default declaring `automountServiceAccountToken: false` on the Pod.

If there is a need you have to grant k8s api-server permissions to the users of the pods, it is technically possible for us to configure that - in practice allowing them to use tools like `kubectl` from their pods.

**Comment by consideRatio** [comment]
Ah, the RBAC permissions granted jupyterhub itself is part of the jupyterhub/zero-to-jupyterhub-k8s project on github, which defines the jupyterhub helm chart we rely on.

**Comment by ranchodeluxe** [comment]
> Ah, the RBAC permissions granted jupyterhub itself is part of the jupyterhub/zero-to-jupyterhub-k8s project on github, which defines the jupyterhub helm chart we rely on.

Great! Thank you. I didn't see this repo and this is exactly the exercise I need to understand more 🏃‍♂️

**Comment by yuvipanda** [comment]
@ranchodeluxe if you'd like, there's also the specific terraform we use at https://github.com/2i2c-org/infrastructure/tree/master/terraform/aws, and eksctl at https://github.com/2i2c-org/infrastructure/tree/master/eksctl

**Comment by ranchodeluxe** [comment]
> @ranchodeluxe if you'd like, there's also the specific terraform we use at https://github.com/2i2c-org/infrastructure/tree/master/terraform/aws, and eksctl at https://github.com/2i2c-org/infrastructure/tree/master/eksctl

This thread keeps getting better 🥳 Thanks @yuvipanda

**Comment by yuvipanda** [comment]
@ranchodeluxe we also have a lot of documentation at infrastructure.2i2c.org :)

**Comment by ranchodeluxe** [comment]
Howdy @sgibson91 ✨ 

I know you folks are kicking things off on `2023-01-24` so I have two more quick questions:

0. I know in the above thread Jonas specified "pangeo" for the hub user image. But what are the default instance types that you choose for the `hub` node and `user` node where the containers will be running (e.g. options such as "t3a.medium" and "m5.xlarge" etc) ? Is this something we can also specify?

0. Myself (and possibly one other person) will have full IAM `AdministratorAccess` to install k8 goodies. That means there's a good chance that I'll want to log into the EKS nodes themselves to debug service networking etc. How can we specify a keypair to use for the EC2 nodes?

Thanks

**Comment by sgibson91** [comment]
@ranchodeluxe Just a note that we usually answer questions like this through our `support@2i2c.org` email https://docs.2i2c.org/en/latest/support.html

As for starting on the 24th, I think we will be delayed by negotiating with SMCE the right permissions we need for our automatic deployment infrastructure to work.

1. The instance types we use are defined below and yes they are customisable.

https://github.com/2i2c-org/infrastructure/blob/c0ef1a0ce18f3997f27e0144779b1bb11a620029/eksctl/template.jsonnet#L19-L42

2. I don't know. You are the first community representative who has asked for such a thing so we will have to develop a process for that together :)

**Comment by yuvipanda** [comment]
@ranchodeluxe I have responded to you on the support ticket :)

@georgianaelena I've opened https://github.com/2i2c-org/infrastructure/pull/2083 with the cluster (which i've setup!). I've made sure you have access to the EKS cluster. There's also an ongoing thread about removing 2FA restriction for our CI/CD setup, so we can continue. I'm off from tomorrow night, would you be able to pick up adding the actual hubs?

**Comment by GeorgianaElena** [comment]
> @GeorgianaElena I've opened https://github.com/2i2c-org/infrastructure/pull/2083 with the cluster (which i've setup!). I've made sure you have access to the EKS cluster. There's also an ongoing email thread (you're cc'd) about removing 2FA restriction for our CI/CD setup, so we can continue. I'm off from tomorrow night, would you be able to pick up adding the actual hubs?

Thank you so much @yuvipanda!  yes, I can try and take it from there

**Comment by GeorgianaElena** [comment]
Two hubs are now available at the following URLs:

- staging.nasa-veda.2i2c.cloud
- nasa-veda.2i2c.cloud

Please check everything is as expected and working.
 
Specifically, please make sure you grant access to the 2i2c OAuth app when first logging in, by following the instructions at https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/configure-auth/github-orgs.html?highlight=oauth#granting-access-to-the-oauth-app. If the OAuth app is not granted the right permissions, it will block everyone from the `veda-analytics-access:all-users` GitHub team.

There also one small piece of info that's missing, and that is the project's funding information (name and url) to link from here:
<img width="1223" alt="Screenshot 2023-01-26 at 17 21 13" src="https://user-images.githubusercontent.com/7579677/214878120-d5cb1919-027b-4b2b-a3eb-be49318dc3aa.png">

**Comment by abarciauskas-bgse** [comment]
@GeorgianaElena could you check if permission is configured for github user `abarciauskas-bgse`? I'm getting a 403 Forbidden message after authorizing the 2i2c-org

Also this is minor but can we update the name of the prod application? It shows `nasa-cryo-prod`

![Screen Shot 2023-01-26 at 12 37 17 PM](https://user-images.githubusercontent.com/15016780/214945229-25303ac6-a6bd-4741-90d2-86116a9726fe.png)

**Comment by GeorgianaElena** [comment]
> Also this is minor but can we update the name of the prod application? It shows nasa-cryo-prod

Oh, yes, sorry about the confusion. I just changed its name.

> @GeorgianaElena could you check if permission is configured for github user abarciauskas-bgse? I'm getting a 403 Forbidden message after authorizing the 2i2c-org organization.

Hmm, then I believe something is going on with either the naming of the GitHub org and team or OAuth app not getting the required access to the `veda-analytics-access`, because thhe username is listed as an admin:

<img width="1223" alt="Screenshot 2023-01-27 at 09 48 07" src="https://user-images.githubusercontent.com/7579677/215035919-a48fa8a2-cdec-42a1-a2b9-d4509f8342e8.png">

@abarciauskas-bgse, do you think you could give me `Owner` rights  to the `veda-analytics-access` org so I can investigate what's going on? Thank you so much.

**Comment by sgibson91** [comment]
I the "grant" button next to the name of the organisation wasn't clicked _before_ clicking "authorise", then that will cause 403 errors.

**Comment by abarciauskas-bgse** [comment]
Apologies, it looks like that's probably what happened in my case. @GeorgianaElena are you able to reset the Github OAuth app? I'm assuming the github organization is `2i2c-org` and the applications are `nasa-veda-staging` and `nasa-veda-prod`?

**Comment by GeorgianaElena** [comment]
Yes. Already reset @abarciauskas-bgse!

**Comment by abarciauskas-bgse** [comment]
Thanks @GeorgianaElena  - I don't see the `2i2c-org` in the list of organizations to grant application access to - should I be concerned? Don't want to cause the same issue again 😅 
<img width="529" alt="Screen Shot 2023-01-27 at 7 31 46 AM" src="https://user-images.githubusercontent.com/15016780/215124855-b97f0fed-c1a6-45b9-9bb4-1414b6b62e63.png">

**Comment by sgibson91** [comment]
@abarciauskas-bgse No, grant access to the  the parent org of your team: `veda-access-analytics`

**Comment by sgibson91** [comment]
You do not need to grant access to the 2i2c-org, because your team is not associated with it. You need to grant access to the org that your team belongs to.

**Comment by abarciauskas-bgse** [comment]
Ok, sorry if I'm asking questions I could answer myself but I am not sure what org the `veda-access-analytics` is a part of. I would have guessed NASA-IMPACT but I don't see it in the list of NASA-IMPACT teams, so I'm unsure which org to grant/request access.

**Comment by GeorgianaElena** [comment]
Hmm, I believe https://github.com/veda-analytics-access its an org itself and there should be a team called `all-users`. That team has been granted access to the hub.

I believe this was the message in which the org and team were specified: [_No restriction for now, thanks - @veda-analytics-access/all-users should get the one machine size we have. We might want to add more in the future, though, if that is okay._ ](https://github.com/2i2c-org/infrastructure/issues/2017#issuecomment-1373419021)

@abarciauskas-bgse, should and other org/team be allowed access instead?

**Comment by j08lue** [comment]
It is a dedicated org just for this access management: https://github.com/veda-analytics-access

**Comment by GeorgianaElena** [comment]
Hey @abarciauskas-bgse! Were you or anyone from the  `veda-analytics-access/all-users` GitHub team able to login in any of the new hubs? Is there anything I can do to help out with that?

**Comment by j08lue** [comment]
@GeorgianaElena, I am getting 403 when attempting to sign in on either of the deployments, although I am on that GitHub team. 
![image](https://user-images.githubusercontent.com/3404817/215774779-f207729a-7703-44c2-b73e-c01e58fe1502.png)

**Comment by GeorgianaElena** [comment]
@j08lue, are you an admin of that GitHub team? Someone with admin rights must authorise the 2i2c GitHub OAuth app (by following the steps in https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/configure-auth/github-orgs.html#granting-access-to-the-oauth-app) and then everyone will be able to login. I am also resetting the OAuth app again to make sure sure that is not the culprit.

**Comment by j08lue** [comment]
Reading the docs helped, @GeorgianaElena, thanks... We are set up now.

**Comment by GeorgianaElena** [comment]
Great to hear @j08lue 🎉 🚀 Then my next step will be to merge the PR that formally adds the nasa veda hubs and cluster  to the 2i2c infra.

Note that the PR merge will close this issue, but you should feel free to ask for 2i2c support related to the hubs by opening support tickets, following the guide in https://docs.2i2c.org/en/latest/support.html

Thank you ✨
