### ISSUE TITLE
[Decommission Hub] snowex.uwhackweek

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2031]
### Summary

It was a hack event that is now over.

### Info

- **Community Representative:** @scottyhq
- **Link to New Hub issue:** https://github.com/2i2c-org/infrastructure/issues/1309
- **Proposed end date:** Now on request from @scottyhq via [freshdesk support ticket](https://2i2c.freshdesk.com/a/tickets/352) 

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [x] Confirm if there is any data to migrate from the hub before decommissioning
  UPDATE: Erik asked Scott via freshdesk ticket about this
  - [ ] If yes, confirm where the data should be migrated to
    - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration
  - [x] If no, confirm it is ok to delete all the data stored in the user home directories

#### Phase II - Hub Removal

(These steps are described in more detail in the docs at https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/hubs/other-hub-ops/delete-hub.html)

- [x] Manage existing data (migrate data from the hub or delete it)
- [x] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.
- [x] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [x] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [x] Delete the hub's authentication application on auth0, GitHub or CILogon

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [ ] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [ ] Delete the terraform workspace: `terraform workspace delete <NAME>`
- [ ] Remove the associated `config/clusters/<cluster_name>` directory and all its contents
- Remove the cluster from CI:
  - [ ] [`deploy-hubs.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-hubs.yaml)
  - [ ] [`validate-clusters.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/validate-clusters.yaml)
- [ ] Remove the cluster from the list of grafana datasources at https://grafana.pilot.2i2c.cloud/datasources
- [ ] Remove A record from Namecheap account

**Comment by scottyhq** [comment]
Thanks @consideRatio !

> Confirm if there is any data to migrate from the hub before decommissioning 

No. You can go ahead and wipe everything.

Out of curiosity though, what is the general procedure for this? Are there docs with recommended options (e.g. an S3 bucket, lab server with a big usb-mounted hard drive, etc.) It could be something we want to do in the future.

**Comment by consideRatio** [comment]
@scottyhq for now it seems we don't have such policies for migrating data well defined, see this documentation: https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/hubs/other-hub-ops/delete-hub.html#migrate-data

I recall Yuvi has done some work to package things into s3 buckets and provide links for users though.

**Comment by consideRatio** [comment]
@scottyhq I see a S3 snowex-scratch bucket, is this fine to remove as well?

**Comment by consideRatio** [comment]
@scottyhq there is still https://staging.uwhackweeks.2i2c.cloud up and running as I haven't worked to tear everything down, but only the snowex hub part of the uwhacksweek cluster.

If everything uwhackweeks related should be cleaned up, there are further actions to take for us. Let us know if that is the case!

**Comment by scottyhq** [comment]
> @scottyhq I see a S3 snowex-scratch bucket, is this fine to remove as well? 

Yes! 

> If everything uwhackweeks related should be cleaned up

Yes, we're not anticipating any events in the near future so everything can be removed.

Thanks @consideRatio !
