### ISSUE TITLE
[Incident] Upgrading ingress-nginx caused brief outage in carbonplan

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2080]
### Summary

The CI/CD pipeline when merging a PR (#2067) upgrading the support chart's dependencies on `ingress-nginx`, `prometheus`, and `grafana` [failed like this](https://github.com/2i2c-org/infrastructure/actions/runs/3989923635). Among the failures I observed most of them related to a mundane failure to auth with GKE that by chance showed up now, but at least one was related to AWS - the carbonplan cluster.

In the carbonplan cluster, the staging and prod wasn't accessible so I reverted the version bump in #2079 which restored carbonplan but overall failed to deploy fully to other hubs as there was need for a patch commit still that was reverted.

#### GKE Auth issue

```
Unable to connect to the server: getting credentials: exec: executable gke-gcloud-auth-plugin not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

Install gke-gcloud-auth-plugin for use with kubectl by following https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
```

#### Carbonplan issue

I'm very confident it relates to carbonplan being the one eksctl based AWS cluster that has k8s 1.19, while others have k8s 1.21 or higher. I assume the ingress-nginx chart has dropped support for so ancient versions, just like z2jh has already.

### Impact on users

I think only users of carbonplan was disrupted, and it seems nobody used it.

### Important information

- Hub URL: carbonplan.2i2c.cloud
- Support ticket ref: I saw this myself

### Tasks and updates

- [x] Discuss and address incident, leaving comments below with updates
- [x] Incident has been dealt with or is over
- [x] Copy/paste the after-action report below and fill in relevant sections
- [x] Incident title is discoverable and accurate
- [ ] All actionable items in report have linked GitHub Issues

<details>
<summary>After-action report template</summary>

```
# After-action report

These sections should be filled out once we've resolved the incident and know what happened.
They should focus on the knowledge we've gained and any improvements we should take.

## Timeline

_A short list of dates / times and major updates, with links to relevant comments in the issue for more context._

All times in UTC+1.

- 2023-01-23 - 20:38, #2067 was merged
- 2023-01-23 - 20:57, [I report in slack](https://2i2c.slack.com/archives/C01GLCC1VCN/p1674503843249809) that I've observed failures in the CI/CD pipeline to deploy #2067 and I'm afraid of a massive outage, but quickly realize its not as bad as I fear
- 2023-01-23 - 20:59, #2079 was merged, making carbonplan functional again
- 2023-01-23, and onwards for ~6 hours, I'm overviewing all k8s clusters versions, and then set out to update carbonplan from k8s 1.19 to 1.24.
  - #2057 
  - #2085

## What went wrong

_Things that could have gone better. Ideally these should result in concrete
action items that have GitHub issues created for them and linked to under
Action items._

- Thing one
- Thing two

## Where we got lucky

_These are good things that happened to us but not because we had planned for them._

- Thing one
- Thing two

## Follow-up actions

_Every action item should have a GitHub issue (even a small skeleton of one) attached to it, so these do not get forgotten. These issues don't have to be in `infrastructure/`, they can be in other repositories._

### Process improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Documentation improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Technical improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]
```

</details>

**Comment by jmunroe** [comment]
I created a document in https://github.com/2i2c-org/incident-reports to record this incident for posterity.

Closing.

**Comment by consideRatio** [comment]
Thank you @jmunroe!!! :heart: :tada: :sunflower:
