### ISSUE TITLE
Integrate JMTE hub into our current infrastructure

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2201]
The Jupyter Meets the Earth grant is what is currently funding my time, and I'm going to work with @fperez to bring https://github.com/2i2c-org/infrastructure/pull/436 into the 2i2c infrastructure. The current hub + that PR was the amazing work of @consideRatio, blazing several trails that have led our current infrastructure to be where it is at. This issue tracks the various bits needed to integrate that hub into our infrastructure as a regular hub so it can be supported via our regular means.

## TODO

- [x] Make sure all 2i2c engineers have access to the JMTE AWS Account
  - [x] yuvipanda
  - [x] Erik
  - [x] Pris
  - [x] Georgiana
  - [x] Sarah
  - [x] Damian
  - [x] James
- [x] Create a generic daskhub terraform infrastructure on AWS on the JMTE AWS Account
- [x] Use [terraform import](https://developer.hashicorp.com/terraform/cli/import) to import the EFS filesystem and the S3 buckets in use.
- [x] Setup a new eksctl based cluster
- [x] Deploy JupyterHubs on this cluster *identical* to the config from https://github.com/2i2c-org/infrastructure/pull/436
- [x] Consider copying the prometheus data from existing cluster to new cluster
- [x] Co-ordinate with current users to move them over to new cluster
- [ ] 2i2c-org/features#20
- [ ] 2i2c-org/infrastructure#2512
- [x] Decomission existing cluster
- [ ] Quick audit of existing resources to make sure they're clean and there isn't anything unwanted
   - [x] EC2 instances
   - [x] EBS Volumes
   - [x] EFS file systems
   - [ ] S3 buckets

**Comment by damianavila** [comment]
@yuvipanda, do we have a deadline for this one to happen? Just trying to figure it out a timeline...

**Comment by consideRatio** [comment]
> Add SFTP service to basehub, as that service is used to bring data in and out of home directories. JupyterHub SSH itself doesn't seem to be used much, so we can probably ignore that one.

If there is agreement that we should support this, then this is what I suggest as a solution to this ticket for the LIS basehub in the shared 2i2c cluster.

Does that seem reasonable? If so, I suggest we extract that out as a dedicated issue as that work item is large enough on its own and should be easy to self-contain I think.

**Comment by consideRatio** [comment]
I've opened https://github.com/2i2c-org/infrastructure/issues/2208 with this

**Comment by yuvipanda** [comment]
I think for the first quarter, what we'd like to accomplish is:

- [ ] Setup a new hub based on our traditional usual AWS tune-up, nothing specific. Let's ignore terraform import, just do a full new setup
- [ ] Copy user files and any storage buckets needed to be here.
- [ ] Move the image building to new repo with repo2docker-action

Things that will be stretch goals:
- [ ] SFTP setup

Things we are not going to do is to try to import current resources. Maybe EFS is still worth it, otherwise let's not try too much.

**Comment by yuvipanda** [comment]
I could import the existing EFS with `terraform import  -var-file=projects/jmte.tfvars aws_efs_file_system.homedirs fs-01707b06`

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/infrastructure/pull/2474 moves most things over, and users are already back on this!

**Comment by yuvipanda** [comment]
Checked with @consideRatio and cleaned up remnants of an old magic castle installation

**Comment by damianavila** [comment]
> and so does @damianavila. Let me know if that is not the case.

I do not think I have access (no internal references), can you resend the credentials for my existing user? Thanks!

**Comment by yuvipanda** [comment]
I think for this quarter, what's left to do is to move the image building process to using repo2docker-action. Then this can be considered done for this quarter

**Comment by damianavila** [comment]
> I think for this quarter, what's left to do is to move the image building process to using repo2docker-action.

Created #2512 for that one!

**Comment by yuvipanda** [comment]
I have now asked the JMTE folks to direct support through our 2i2c support process, rather than by pinging me or Erik individually on their slack!

**Comment by consideRatio** [comment]
@yuvipanda do you have thoughts on what level of support are 2i2c to provide jmte as part of this?

Specifically I'm considering if we are to help with user image updates ([here](https://github.com/pangeo-data/jupyter-earth/blob/master/hub.jupytearth.org-image/Dockerfile)). I think that may be an expectation currently from jmte when transitioning to 2i2c support.

**Comment by consideRatio** [comment]
I think this is sufficiently completed and no longer useful issue to retain open - closing
