### ISSUE TITLE
[QCL] Tracking: New Hub Deployment 

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2287]
This is a tracking issue to track the technical steps of the new hub deployment in #2118

**Comment by pnasrat** [comment]
## TODO 

- [ ] New GCP project https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/cloud-accounts/new-gcp-project.html
- [ ] New Kubernetes cluster https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/new-cluster/new-cluster.html
- [ ] Deploy support https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/deploy-support/index.html
- [ ] Hub deployment docs https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/hubs/new-hub.html
- [ ] Authentication https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/configure-auth/index.html#

**Comment by pnasrat** [comment]
I followed the intial steps to create `qcl-hub` GCP project (note GCP project naming requires 6-30 letters so not just `qcl`). Next step would be terraform.

**Comment by pnasrat** [comment]
Terraform run and follow up plan gives

```
No changes. Your infrastructure matches the configuration.
```

**Comment by pnasrat** [comment]
Notes to self

<details><summary>terraform IAM error</summary>
<p>

```
╷
│ Error: Error applying IAM policy for service account 'projects/qcl-hub/serviceAccounts/qcl-prod@qcl-hub.iam.gserviceaccount.com': Error setting IAM policy for service account 'projects/qcl-hub/serviceAccounts/qcl-prod@qcl-hub.iam.gserviceaccount.com': googleapi: Error 400: Identity Pool does not exist (qcl-hub.svc.id.goog). Please check that you specified a valid resource name as returned in the `name` attribute in the configuration API., badRequest
│ 
│   with google_service_account_iam_binding.workload_identity_binding["prod"],
│   on workload-identity.tf line 26, in resource "google_service_account_iam_binding" "workload_identity_binding":
│   26: resource "google_service_account_iam_binding" "workload_identity_binding" {
│ 
╵
╷
│ Error: Error applying IAM policy for service account 'projects/qcl-hub/serviceAccounts/qcl-staging@qcl-hub.iam.gserviceaccount.com': Error setting IAM policy for service account 'projects/qcl-hub/serviceAccounts/qcl-staging@qcl-hub.iam.gserviceaccount.com': googleapi: Error 400: Identity Pool does not exist (qcl-hub.svc.id.goog). Please check that you specified a valid resource name as returned in the `name` attribute in the configuration API., badRequest
│ 
│   with google_service_account_iam_binding.workload_identity_binding["staging"],
│   on workload-identity.tf line 26, in resource "google_service_account_iam_binding" "workload_identity_binding":
│   26: resource "google_service_account_iam_binding" "workload_identity_binding" {
│ 
╵

```
</p>
</details>

**Comment by pnasrat** [comment]
Reading the docs I think terraform should be creating this via a WorkloadIdentity

But I don't see that happening https://console.cloud.google.com/iam-admin/iam?project=qcl-hub

I destryed the service accounts via a targeted destroy and tried again but still not seeing in IAM

```
google_service_account.workload_sa["prod"]: Creating...
google_service_account.workload_sa["staging"]: Creating...
google_service_account.workload_sa["prod"]: Creation complete after 1s [id=projects/qcl-hub/serviceAccounts/qcl-prod@qcl-hub.iam.gserviceaccount.com]
google_service_account.workload_sa["staging"]: Creation complete after 1s [id=projects/qcl-hub/serviceAccounts/qcl-staging@qcl-hub.iam.gserviceaccount.com]
google_service_account_iam_binding.workload_identity_binding["prod"]: Creating...
google_service_account_iam_binding.workload_identity_binding["staging"]: Creating...
google_storage_bucket_iam_member.member["prod.scratch"]: Creating...
google_storage_bucket_iam_member.member["staging.scratch-staging"]: Creating...
google_service_account_iam_binding.workload_identity_binding["staging"]: Creation complete after 4s [id=projects/qcl-hub/serviceAccounts/qcl-staging@qcl-hub.iam.gserviceaccount.com/roles/iam.workloadIdentityUser]
google_service_account_iam_binding.workload_identity_binding["prod"]: Creation complete after 4s [id=projects/qcl-hub/serviceAccounts/qcl-prod@qcl-hub.iam.gserviceaccount.com/roles/iam.workloadIdentityUser]
google_storage_bucket_iam_member.member["staging.scratch-staging"]: Creation complete after 6s [id=b/qcl-scratch-staging/roles/storage.admin/serviceAccount:qcl-staging@qcl-hub.iam.gserviceaccount.com]
google_storage_bucket_iam_member.member["prod.scratch"]: Creation complete after 6s [id=b/qcl-scratch/roles/storage.admin/serviceAccount:qcl-prod@qcl-hub.iam.gserviceaccount.com]
```

**Comment by pnasrat** [comment]
ok I see them under https://console.cloud.google.com/iam-admin/serviceaccounts?project=qcl-hub I was comparing to another cluster so not sure what went wrong.

**Comment by pnasrat** [comment]
`deployer deploy-support qcl`

**Comment by pnasrat** [comment]
```
kubectl get pods -n support
NAME                                                READY   STATUS    RESTARTS   AGE
cm-acme-http-solver-tggnt                           1/1     Running   0          119s
cm-acme-http-solver-wvcrl                           1/1     Running   0          119s
support-cryptnono-2z6br                             1/1     Running   0          2m6s
support-grafana-58ccb47c7c-ddfpc                    1/1     Running   0          2m5s
support-ingress-nginx-controller-74845bdd8c-2pffx   1/1     Running   0          2m5s
support-kube-state-metrics-84fd45d9b8-9ds7c         1/1     Running   0          2m6s
support-prometheus-node-exporter-4l2b4              1/1     Running   0          2m6s
support-prometheus-server-75bfcdbfd4-frmzx          2/2     Running   0          2m6s
```

**Comment by pnasrat** [comment]
```
kubectl get certificates -n support
NAME             READY   SECRET           AGE
grafana-tls      True    grafana-tls      16m
prometheus-tls   True    prometheus-tls   16m
```

**Comment by pnasrat** [comment]
helm fails when manually deploy the staging hub 

```
client.go:770: [debug] nfs-share-creator: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
upgrade.go:436: [debug] warning: Upgrade "staging" failed: pre-upgrade hooks failed: timed out waiting for the condition
Error: UPGRADE FAILED: pre-upgrade hooks failed: timed out waiting for the condition
helm.go:84: [debug] pre-upgrade hooks failed: timed out waiting for the condition
UPGRADE FAILED
main.newUpgradeCmd.func2
	helm.sh/helm/v3/cmd/helm/upgrade.go:203
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.6.1/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1571
```

**Comment by pnasrat** [comment]
Terraform creates the homedirs as a Google Filestore but the deployer generate config didn't include in `common.values.yaml` added after consulting console for IP. These docs need updating

**Comment by pnasrat** [comment]
```
NAME        	NAMESPACE   	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
cert-manager	cert-manager	4       	2023-03-03 10:24:19.139949261 -0500 EST	deployed	cert-manager-v1.8.2	v1.8.2     
staging     	staging     	3       	2023-03-03 10:55:27.002949812 -0500 EST	deployed	basehub-0.1.0      	1.0        
support     	support     	4       	2023-03-03 10:24:38.611641991 -0500 EST	deployed	support-0.1.0      	     
```

**Comment by pnasrat** [comment]
ok something weird is happening and I wonder if the redirects block isn't generalized enough so I'm going to switch to 2i2c.cloud for debugging

**Comment by pnasrat** [comment]
Somethign weird was config errors on my part staging hub up and spawning. 

![image](https://user-images.githubusercontent.com/13798/222775859-73735353-1993-4140-aafa-f83a5bb63bf0.png)

**Comment by pnasrat** [comment]
via https://github.com/2i2c-org/infrastructure/pull/2295#pullrequestreview-1325204197

- [ ] Prod hub
- [ ] Redirects for prod / grafana
- [ ] admin_users to include listed accounts from QCL
- [ ] singleuser.profileList configuration for staging and prod

**Comment by pnasrat** [comment]
highcpu profiles failing spawn

```json
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"jupyter-pnasrat\" is invalid: spec.containers[0].resources.requests: Invalid value: \"31017180069\": must be less than or equal to memory limit","reason":"Invalid","details":{"name":"jupyter-pnasrat","kind":"Pod","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"31017180069\": must be less than or equal to memory limit","field":"spec.containers[0].resources.requests"}]},"code":422}
```

**Comment by pnasrat** [comment]
Going to null out limit cf small/medium.

**Comment by pnasrat** [comment]
That looks better

```
2023-03-14T15:23:05Z [Normal] pod triggered scale-up: [{https://www.googleapis.com/compute/v1/projects/qcl-hub/zones/europe-west1-d/instanceGroups/gke-qcl-cluster-nb-huge-highcpu-56ceaf12-grp 0->1 (max: 100)}]

Event log
```
