### ISSUE TITLE
[Billing] Goal Q2 2023: Cloud cost billing pass through process

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2431]
## Context

Based on Q4 2022 Goal https://github.com/2i2c-org/infrastructure/issues/1853 and Quarterly Planning

Rationale: For a lot of clients, we ‘pass through’ cloud billing. We pay the cloud vendors, and then invoice them. This process is currently not well defined, and tgis is a very important part of our long term sustainability.

### Definition of done:

- We have a single source of truth of all contracts that we are passing cloud costs through for. This should also link to the specific hub that is being run for those contracts.
- We have code that generates how much each of those contracts should be charged. This involved:
  - Automatically getting this number for GCP in cases with dedicated clusters
  - Automatically getting this number for GCP in cases with shared clusters
  - Instructions on manually getting this number for AWS projects
  - We do not have any Azure clusters we have to pass through for now, so we can skip that.
  - Manual extra service charge as a % of our fixed shared costs (such as pagerduty, uptime alerts, etc)
  - Stretch goal: Automatically getting centralized or shared overhead/infrastructure costs eg uptime alerts, pagerduty or other and splitting (maybe ratioed) between clusters  
- There is a monthly process that involves at least two people (redundancy?) for generating invoices for the previous month, and sending it to CS&S
- There is a monthly process for checking-in to see if any previous invoices have not been paid yet.
- There is a ‘catch-up’ process that lets us clear all current invoicing backlogs
- There is documentation on what exactly ‘generating an invoice’ means

#### Cost Reconcilliation / Backlog up to Q1 2023

* [x] 2i2c-org/meta#350
  * [ ] Define and document catch-up process to clear any invoice backlog for cloud costs til Q1 2023
* [ ] Document historic billing model
  * [x] 2i2c-org/team-compass#498 

#### Define manual billing process for Q2 2023 and beyond 

* [ ] 2i2c-org/team-compass#519
* [ ] 2i2c-org/team-compass#499
* [x] 2i2c-org/team-compass#355
* [ ] 2i2c-org/team-compass#546
* [x] 2i2c-org/meta#529 
  * [ ] #2456
  * [x]  #2465
* [ ] Define manual monthly process for checking on outstanding invoices to create accounts receivable
* [ ] Documentation on what generating an invoice means 

#### Tooling for Cost Generation for manual process for Q2  2023 and beyond

* [ ] Code that generates cost for clusters
  * [x] #1921
  * [ ] #1922
  * [x] #1923
  * [ ] #2263 

## Issue Backlog / Related Issues

- #2442 
- #2467 
- #1669
- 2i2c-org/team-compass#555
- #730 
- 2i2c-org/team-compass#694
- 2i2c-org/team-compass#663

### Updates and actions

2023-04-07: @pnasrat Adding issue backlog to capture historical state
2023-04-06: @pnasrat rework proposal into 3 strands of work

**Comment by pnasrat** [comment]
Current plan is to use central grafana to

- Add GCP Billing BigQuery datasource to Grafana
 - Configure service account permitting Big Query viewing and annotate pod
 - Create ad-hoc queries via explore using multi data source to test out
 - See if through transformations can create monthly invoice data 
- Create permanent GCP shared cluster billing dashboard (inspired by opencost UI)

**Comment by pnasrat** [comment]
Manually created service account [billing-bigquery-reader@two-eye-two-see.iam.gserviceaccount.com](https://console.cloud.google.com/iam-admin/serviceaccounts/details/107344378974361490804;edit=true?previousPage=%2Fapis%2Fcredentials%3Fproject%3Dtwo-eye-two-see&project=two-eye-two-see)

TODO: Figure if we need to generate support serviceaccounts, currently this is for a single cluster so setting up manually first before automating.

**Comment by pnasrat** [comment]
Note I misread the permissions for datasources are only in Grafana Enterprise and Cloud not in the open source version. Given non-admin users are currently Viewer we can limit billing dashboard (and Explore which is currently) to Admin only via dashboard permissions https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/#dashboard-permissions

**Comment by colliand** [comment]
Follow up memorializing an exchange in the 2023-04-04 Product and Engineering meeting.

Over recent months, @jmunroe has been gathering cloud billing reports and sharing those with CS&S for invoicing. As our billing systems advance, we should move cloud billing under @colliand and partnerships giving James more bandwidth to focus on product and community. James and Jim will work with Engineering and 2i2c to strengthen our cloud billing back office.

**Comment by choldgraf** [comment]
### More AirTable automation for our account transactions

I've been iterating a bit more with Joe, and now have an AirTable that is still manually updated but with much fewer steps and complexity than before. Here's a brief summary:

- Joe can automate the generation of a "raw dump" of transactions from their Xero financial accounting, and put it in a Google Sheet.
- This can be "direct imported" into AirTable via their Google Sheet integration.
- I've updated our `Accounting Transactions` sheet with the proper field names [at this AirTable URL](https://airtable.com/appbjBTRIbgRiElkr/tblDKGQFU0iEIa5Qb/viwAdsIgMwbqKDdZ0).
- If we want to update the data, we follow these steps:
	- Delete all records on the page.
	- Go to `Accounting Transactions` -> `Import Data` -> `Google Sheets` -> `Google sheets account`
	   ![image](https://user-images.githubusercontent.com/1839645/230121196-0d398812-ba22-4cea-a42f-e3ad644a3e19.png)
    - This is already integrated with the right folder, we choose the latest sheet that Joe has given us. It starts with `Automated 2i2c Cloud Costs`.
    - For now we choose the `2i2c only and deduplicated` tab, but we will be able to remove this step after the next data dump.
    - Import the data and skip the first row so that we don't import headers.

This should automatically update our data with the latest Xero data from CS&S. I've also started working on some dashboards to visualize this data [at this Interface link](https://airtable.com/invite/l?inviteId=invF192DfoKa5xqqY&inviteToken=ef8865617dd3b6ebbb01b753fa2de0d231f1a7f526b6fe07d3cf88c12a418f5f&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts).

Will provide more updates as I get them from Joe, but this is a good step towards a (mostly) automated source of truth for our accounting data, that is updated in real-time.

**Comment by pnasrat** [comment]
Note metadata API need personal access token https://airtable.com/developers/web/guides/personal-access-tokens not the legacy api key

**Comment by choldgraf** [comment]
OK I got an updated table from Joe after he incorporated some of my feedback, so I've updated [the description here for how to access](https://github.com/2i2c-org/infrastructure/issues/2431#issuecomment-1497641051) and we can add it to the team compass once we know that the process is settled for now.
