### ISSUE TITLE
Q2 2023 Goal: Move CloudBank hubs to their own data8 style image

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2435]
# Rationale
The default image we use for 2i2c hubs has grown well beyond i[ts initial purpose](https://github.com/2i2c-org/infrastructure/issues/2336#issuecomment-1480842625), and needs a lot of catchup maintenance. The process around it also needs fixing. Many universities using us have a break in this time period, making it possible to change images.

# Definition of done
1. We have an image built for all the cloudbank hubs that teach data8 style classes
2. Stretch goal: We have clear guidance on when this particular image would be updated, and how that can be communicated to users

# TODO

- [x] Specify a `common.yaml` file for cloudbank, specifying the image + tag https://github.com/2i2c-org/infrastructure/pull/2437
- [x] Build a data8-style image that is small and specific
- [ ] Figure out which hubs were just teaching data8, and which are not
- [ ] Decide on a date to do the swap for data8 teaching classes

**Comment by yuvipanda** [comment]
We'd probably also want to make it easy to extend, so there can be a temporary extension for different versions of otter.

**Comment by sean-morris** [comment]
Re: Who is using R on the cloudbank hubs

Who: Edward Pineda-Castro at Los Angeles City College
Hub: https://lacc.cloudbank.2i2c.cloud/

He is using R Studio on the hub with a couple of different classes.

**Comment by ericvd-ucb** [comment]
@sean-morris  what about CSU hub with CSU Sacramento ?
Aren't they also R users?

https://csu.cloudbank.2i2c.cloud/
Clark Fitzgerald at CSU Sacramento

**Comment by sean-morris** [comment]
> @sean-morris what about CSU hub with CSU Sacramento ? Aren't they also R users?
> 
> https://csu.cloudbank.2i2c.cloud/ Clark Fitzgerald at CSU Sacramento

CSUS moved to a different solution; we don't have any R needs on the csu hub

**Comment by yuvipanda** [comment]
Well, no more cloudbank hubs are using the old image so I think we can call this one done!
