### ISSUE TITLE
[billing] Single source of truth for contracts and method to link hubs to contracts

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2456]
Part of billing story. Placeholder - define single source of truth for contracts and integration with hub metadata

## Context

2i2c need a stable and central source of truth for contracts that can be queried for current and historical state.

Questions - what is the life of a contract?

## TODO 

- [ ] Write up requirements for single source of truth
- [ ] Document current options (including airtable, grafana, google sheets)
- [ ] Define schema for single source of truth
- [ ] Populate existing data for current (and historical? contracts)
- [ ] Design and document manual process for updating source of truth
- [ ] integrate manual process for invoicing with this source of truth

**Comment by choldgraf** [comment]
Just a note that I think we'll also need to define a source of truth for **invoices**, so that we can link invoices to contracts, as well as to outstanding cloud costs. That way we can answer "which invoice is the one that paid for cloud charge X for contract Y"

**Comment by choldgraf** [comment]
I've got a PR to document our Contracts and Invoices airtable tables here:

- https://github.com/2i2c-org/team-compass/pull/698

If we somehow got our "currently active hubs" data into AirTable form[^1], we could link hubs to contracts (and thus to invoices) via [Linked Records](https://www.airtable.com/guides/build/connect-data-with-linked-records).

[^1]: How would we do that? We could either programmatically update this somehow, or we could potentially manually maintain a record of all running hubs in AirTable that we cross-reference with our deployment information. For example, we might have a daily job that checks our `infrastructure/` repository for all currently deployed hubs, checks a `Hubs` AirTable to make sure that all hubs in our deployment are represented in the AirTable, and if not then adds new records to reflect any new hubs that have been added. We could then add extra metadata to the AirTable and link them to other contracts / invoice records in AirTable.

**Comment by choldgraf** [comment]
Also just for team visibility - I'm also iterating a bit with Joe at CS&S in a notion page he set up for us to provide feedback. I've requested that @colliand and @jmunroe have access to this page as well so they can see the conversation there too.

**Comment by colliand** [comment]
I have access to the Notion page. Thank you.

**Comment by choldgraf** [comment]
### Quick idea: keep an auto-updated "hubs" airtable?

The goal of this comment is to satisfy the "method to link hubs to contracts" part of this issue[^1].

[^1]: apologies for the weekend update, but the thought just popped into my head and I wanted to write it down while it was fresh.

Now that we have [a `Contracts` airtable](https://airtable.com/appbjBTRIbgRiElkr/tbliwB70vYg3hlkb1/viwOWxGxMBVmJFwiC), what if we created a **Hubs** airtable (call it `Hubs` for now), that was **automatically updated** by a Python/CRON job. This job would scan our `cluster.yaml` configuration files, and for each hub it would ensure that there was a record in `Hubs` that had the same `url` and the other metadata we use to customize the info about the hub (e.g. hub name etc). It'd use the hub URL as a unique ID, and would update fields if they already existed.

We could then attach our own metadata to this table. For example, in `Hubs/`:

- We could link each hub to a record in `Contracts/` so that we have a clear link between hubs and contracts.
- We could define a `Community Representative` field (in Contracts, or in `Hubs/`) that'd be the source of truth for individuals who may contact us on behalf of a hub.
- We could define a `Status` field to encode whether a hub was currently running, or now shut down (this could be automatically changed in the CRON job if a hub in the AirTable no longer existed in the `.yaml` file).

Then we could create a little interface dashboard that would display, for example, "for each hub, list all of the community representatives and their e-mails". This could be a quick reference for resolving uncertainties in who is contacting us.

### Alternatives / the reason I'm thinking AirTable

We could also try and put this metadata in the `cluster.yaml` files themselves, so that all hub metadata is in one place. What I worry is that this data is relatively inaccessible to non-engineers, and more complex to update, and so we'd need to build out some kind of interface ourselves to view / change that data. It feels like AirTable could serve as that interface instead, and then we could gain the benefit of cross-linking it to our `Contracts/` table.

**Comment by choldgraf** [comment]
Just a quite note on the above and given @pnasrat's comments earlier, I think my suggestion here:

https://github.com/2i2c-org/infrastructure/issues/2456#issuecomment-1510161236

might be better as a follow-up issue so that we can tie-off this one more cleanly. We don't need a full-blown automation with AirTable if we can achieve a reasonable "source of truth" status without it.

**Comment by choldgraf** [comment]
I've opened a new issue to track and prototype creating an AirTable that syncs our hubs metadata, so we can move that discussion over there:

- https://github.com/2i2c-org/team-compass/issues/724
