### ISSUE TITLE
[Request deployment] New Ephemeral Hub: ESA HackAnExoplanet

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#2461]
### Important dates

- **Target start date**: as soon as possible and certainly before April 11, 2023
- **Required start date**: April 11, 2023
- **Any important dates for usage**: Usage peak is forecast for April 18, 2023

### Hub Authentication Type

Other (may not be possible, please specify in comments)

### First Hub Administrators

-  Maximilian N. Günther @MNGuenther

### [GitHub Auth only] How would you like to manage your users?

None

### Hub logo image URL

pending...

### Hub logo website URL

https://hackanexoplanet.esa.int/

### Hub user image GitHub repository

pending....

### Hub user image tag and name

pending...

### Extra features you'd like to enable

- [ ] Specific cloud provider or datacenter (otherwise GCP)
- [ ] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

None

### (Optional) Billing and Cloud account

None

### Other relevant information to the features above

This is a request for an _ephemeral hub_ following up on discussions with @yuvipanda in 2i2c's Slack.

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [ ] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by colliand** [comment]
Hello @MNGuenther! With this issue, we are gathering the required information from you so that 2i2c's engineering team can launch the ephemeral hub for HackAnExoplanet. You will likely exchange messages with @yuvipanda. Yuvi and I are excited to support you and your colleagues at ESA and help you to inspire students with this project.

We request some information from you.

Please share a **URL pointing at the "splash image"** that users will see when they land on the login page. For example, notice the image at the top of the Openscapes login page here: https://openscapes.2i2c.cloud/

Do you have a Docker image that specifies the software environment you'd like for the hub? [Documentation is available here](https://docs.2i2c.org/en/latest/admin/howto/environment/hub-user-image-template-guide.html). 2i2c can provide a standard image or you can work with us to customize the environment for your usage scenario.

**Comment by yuvipanda** [comment]
Ah unfortunately no splash screen is possible here, you'll just get directly sent to your notebook.

I've repurposed #2458 to be at https://hackanexoplanet.2i2c.cloud now, so you can check it out :)

**Comment by MNGuenther** [comment]
Hi @yuvipanda, thanks a lot! 

I followed all the steps in the instructions above to the best of my (severely limited) knowledge. The (empty) quay repository is now under https://quay.io/repository/mnguenther/hackanexoplanet-env.

Note that https://github.com/MNGuenther/hackanexoplanet-env only holds the environment, while https://github.com/MNGuenther/hackanexoplanet holds the actual code (and Jupyter notebook) that needs to be executed.

Please can you let me know if everything worked?

**Comment by MNGuenther** [comment]
(As I might not be able to respond in time: If there are any issues with my setup of these GitHub repositories, please feel free to simply clone/fork them and set things up via the clones/forks.)

**Comment by MNGuenther** [comment]
Hi @yuvipanda, I'm afraid I had to delete the .gitconfig file from https://github.com/MNGuenther/hackanexoplanet-env again. It lead to the Binder implementation crashing. As several schools are already relying on the Binder one, this is not feasible. So I assume it is really best to work with forks then.

**Comment by yuvipanda** [comment]
@MNGuenther it is now available at https://hackanexoplanet.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FMNGuenther%2Fhackanexoplanet&urlpath=tree%2Fhackanexoplanet%2FGUI.ipynb. Check it out.

**Comment by MNGuenther** [comment]
@yuvipanda @colliand 

This is absolutely amazing! Fantastic work on such a short timescale, and a perfect in-time delivery for our big launch event today. It loads lightning fast. Thank you very much for handling everything so thoroughly. 

One difference I noticed to the Binder version is that the browser cache seems to affect things differently. In the Binder implementation, one can launch various instances in the same browser (simultaneously or sequentially) without it affecting the GUI. In the 2i2c implementation, only the first launch lets you execute the GUI fully. Additional (simultaneous or sequentially) launched instances lead to the GUI not executing anymore after the first selection. I assume this is a consequence of the new ephemeral hub system that you set up especially for this project. This is not an issue, however, as we will simply ask users to clean their browser cache or use private windows when launching via the 2i2c implementation.

Once again, thank you so much!

**Comment by yuvipanda** [comment]
@MNGuenther I'll take a quick look and see if there is something we can do. We don't generally push this much but we all <3 the ESA :)

**Comment by yuvipanda** [comment]
@MNGuenther I'm also going to provision some dedicated compute resources for this hub at least for today - this should ensure fast startups for all 1000 people if they are there. Otherwise, every 30 users or so someone might have to wait for 5-6 minutes. This will increase the cloud costs as the dedicated resources are being charged even when not used - but I should be able to bring it up and then turn it down tomorrow. I think that should be ok as we are recovering cloud costs too.

**Comment by yuvipanda** [comment]
@MNGuenther as another temporary fix, users can go to https://hackanexoplanet.2i2c.cloud/hub/home, click 'stop server' to stop their server. After that, they can click the nbgitpuller link again - that should work.

At 2i2c we fundamentally believe in the idea of the 'long fix' - providing a short term solution (like above) but also working on longer term upstream fixes. I've opened a PR in the upstream JupyterHub org (https://github.com/jupyterhub/tmpauthenticator/pull/25) that would help with this in the future :) Not for today though.

**Comment by MNGuenther** [comment]
@yuvipanda Perfect, thanks a lot! 

Great news about the increased capacity and loading speed for today, thanks for working towards this! 

I assume we will not hit the critical mass of 1000 simultaneous users. My best guess is ~100, but I could be wildly off. But with such a pilot project and live event it is best to have a safety margin, spare capacity, and room to grow, rather than suddenly hit a hard limit.

We anticipate that many schools will still try the Binder implementation first (as that link is in the documentation they received in the past months already). But during the live event, we will be recommending people to switch over to the 2i2c implementation for all its benefits. In sum, I would expect a steady increase of users today and that they are spread out quite evenly.

The temporary fix works well for me, too!

**Comment by damianavila** [comment]
> Quick question: Is it feasible to remove the username and password requirement? Then we could directly replace the Binder link for the time we have the 2i2c support. Otherwise we will keep both links running in parallel.

@MNGuenther, I do not think removing the username and password is an option because those are preventing crypto abuse: https://infrastructure.2i2c.org/howto/features/ephemeral.html

I will call this issue complete and ask people to submit support tickets in case they need further assistance.
