### ISSUE TITLE
[Request deployment] New Hub: Climatematch Academy

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#2505]
### Important dates

- **Target start date**: 2023-05-20
- **Required start date**: 2023-05-30
- **Any important dates for usage**: The Academy will run during July 17-28 2023. Instructors will be developing and uploading content prior to the academy. The hub is scheduled to be wound down in late August unless directed differently by Climatematch. 

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

- Abigail Bodner: @abodner

Who else? Abigail, are there others in your team that should be included among the first group of hub administrators? People that can advise on how the infrastructure should be configured for the academy event will be especially helpful at this stage. 

### [GitHub Auth only] How would you like to manage your users?

None

### Hub logo image URL

https://lh6.googleusercontent.com/HqycnXkgAL7kB1O_Ouv7t0K7n4XUxwUCXBF6ZrejBii6E84jK40bNtAYWH4GtTVpJPoOnzhoNpiUXyfktm38Z7ICqJ314bfGKm_hfGWD_Cfwg554mnCN3Hyb4Fk2zUE7pA=w1280

### Hub logo website URL

https://academy.climatematch.io/

### Hub user image GitHub repository

pending...

### Hub user image tag and name

pending...

### Extra features you'd like to enable

- [ ] Specific cloud provider or datacenter (otherwise GCP)
- [ ] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

None

### (Optional) Billing and Cloud account

None

### Other relevant information to the features above

Climatematch Academy is a virtual training program designed to introduce a large cohort of students to computational methods in climate science. The program will likely have strong overlaps with the tech used by Pangeo. 2i2c's Community and Partnerships team (@colliand and @jmunroe) will work with Climatematch director @abodner to gather more information about the requirements for this hub deployment in our [shared running notes Google document](https://docs.google.com/document/d/1SjaOrUh0DmZ2zkcyVMjW6iMko_zsQnjmsxCVK5rJre4/edit#). 

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [ ] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by damianavila** [comment]
> 2i2c's Community and Partnerships team (@colliand and @jmunroe) will work with Climatematch director @abodner to gather more information about the requirements for this hub deployment in our [shared running notes Google document](https://docs.google.com/document/d/1SjaOrUh0DmZ2zkcyVMjW6iMko_zsQnjmsxCVK5rJre4/edit#).

@colliand and @jmunroe, could you please update the top message of this issue with all the information requested/needed so we can make this one actionable? Thanks!!

**Comment by colliand** [comment]
Yes. I will do this today.

**Comment by colliand** [comment]
I need to gather more info from @abodner to make this hub deployment request actionable. More soon...

**Comment by jmunroe** [comment]
Closing since it appears that #2524 is the same request with more updated information.
