### ISSUE TITLE
[EVENT] AWI-ciroh

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#2520]
### Summary

[CIROH Training and Developers Conference](https://ciroh.ua.edu/devconference/)

### Event Info
Placeholder issue for https://2i2c.freshdesk.com/a/tickets/675.
To add more details once available.

- **Community Representative:**  Arpita Patel and James Halgren
- **Event begin:**  16 May 2023 (Tuesday)
  - **In your timezone:**   9:30 a.m. MDT
- **Event end:**  18 May 2023 (Thursday)
  - **In your timezone:**  3:30 p.m. MDT
- **Active times:** 
  - **In your timezone:**  10:00 a.m. MDT - 3:00 p.m. MDT each day of the conference
- **Number of attendees:**  May have up to 100 simultaneous connections at any given time, though the number is more likely to be around 40.
   Expected type and number of user servers to be available:
    - 20x small
    - 15x medium
    - 5x large
    - 5x huge

- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Test resources before the event
From the community:
_We would like to do the stress-test as soon as feasible. The goal with the stress test would be to have at least 20 simultaneous sessions within a 1.5 hour period, to simulate a significant workshop load -- if you are able to make necessary changes, we could have people ready to launch their individual hubsites with some dummy loads on Friday, May 5th (feliz cinco de mayo!) at 12:30 p.m. CDT._

### Hub info

- **Hub URL**:  https://ciroh.awi.2i2c.cloud
- **Hub decommisioned after event?**:  No

### Task List

**Before the event**

- [x] Dates confirmed with the community representative and added to Hub Events Calendar.
- [x] Quotas from the cloud provider are high-enough to handle expected usage.\
- [ ] **ASAP** Get the hub ready for a stress-test as soon as feasible. The goal with the stress test would be to have at least 20 simultaneous sessions within a 1.5 hour period, to simulate a significant workshop load
- [ ] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  
- [x] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [x] Confirm event is finished.
- [x] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [ ] Hub decommissioned (if needed).
- [ ] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by GeorgianaElena** [comment]
More details are needed about the kind of user servers expected to be used at the workshop before asking for quotas increases I believe, but this is the CPU Quota Usage history:

It looks like the peak ~60% of the CPU quota (128) in last 30 days was achieved while 9 users were using the hub.

<img width="567" alt="Screenshot 2023-05-04 at 11 48 39" src="https://user-images.githubusercontent.com/7579677/236155823-4652b929-63d8-4783-813a-ed111624cacd.png">
otas from the cloud provider:

<img width="695" alt="Screenshot 2023-05-04 at 11 46 40" src="https://user-images.githubusercontent.com/7579677/236155756-96e17ef3-7729-491a-b135-406d7909bb87.png">

**Comment by GeorgianaElena** [comment]
The proposed expected servers by the community rep is the following:

Ensure the following type and number of servers are available for the duration of the workshop at any given time:
- 20x small
- 15x medium
- 5x large
- 5x huge

I will also update the top comment with this info

**Comment by GeorgianaElena** [comment]
I've updated the CPU quota from 128 to 256 that _I believe_ should be sufficient for the expected communicated usage.

**Comment by damianavila** [comment]
Updates:

1. @GeorgianaElena checked on quotas and requested upgrades to 512 CPU (granted) and we are going to let the test ride on their own.
2. We checked for availability/capacity and @consideRatio / @pnasrat confirmed they will be covering (as support stewards) the event if there is a need for our engs intervention (btw, there might need a need for preparation work on Mon 16th as a follow-up of the stress test).

More details on this Slack thread: https://2i2c.slack.com/archives/C028WU9PFBN/p1683556880515699.

**Comment by consideRatio** [comment]
I pre-warmed 220 CPU based on a comment above in https://github.com/2i2c-org/infrastructure/pull/2539: 
- 20x small
- 15x medium
- 5x large
- 5x huge

> I've updated the CPU quota from 128 to 256 that I believe should be sufficient for the expected communicated usage.

> GeorgianaElena checked on quotas and requested upgrades to 512 CPU (granted) and we are going to let the test ride on their own.

Note that if they end up starting 10x huge nodes, its 5x more 16 CPU nodes than pre-warmed already so we would be ending up at 220+16*5 which is more than 256. So having 512 is very relevant now that we pre-warm of many different types.

**Comment by consideRatio** [comment]
The remaining point in this issue is the post-event debriefing.

**Comment by damianavila** [comment]
Hey, @arpita0911patel and @jameshalgren, your event appears to be over 🎉

We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!

- Did the infrastructure behave as expected?
- Anything that was confusing or could be improved?
- Any extra functionality you wish you would have had?
- Could you share a story about how you used the hub?
- Any other feedback that you'd like to share?

**Comment by damianavila** [comment]
Time to close this one.
