### ISSUE TITLE
[Decommission Hub] paleohackweek2021

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#2552]
### Summary

This hub was created for an event in 2022 and needs to be shut down. @colliand followed up today to collect outstanding cloud costs and confirmed with Julien Emile-Geay that the hub should be decomissioned. 

https://paleohack2021.hackathon.2i2c.cloud

The hub was used for an event that took place long ago and the data can be wiped. 

Not certain but @colliand believes this hub runs in the same cluster as the hub located at [linkedearth.2i2c.cloud](https://linkedearth.2i2c.cloud/). The linked-earth hub and cluster should continue to be operated while the paleohack2021 hub should be shut down. 

### Info

- **Community Representative:** @khider @CommonClimate 
- **Link to New Hub issue:** https://github.com/2i2c-org/infrastructure/issues/1032
- **Proposed end date:** ASAP

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [x] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
    - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration
  - [ ] If no, confirm it is ok to delete all the data stored in the user home directories

#### Phase II - Hub Removal

(These steps are described in more detail in the docs at https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/hubs/other-hub-ops/delete-hub.html)

- [ ] Manage existing data (migrate data from the hub or delete it)
- [x] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.
- [x] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [x] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [ ] Delete the hub's authentication application on auth0, GitHub or CILogon

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [ ] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [ ] Delete the terraform workspace: `terraform workspace delete <NAME>`
- [ ] Remove the associated `config/clusters/<cluster_name>` directory and all its contents
- Remove the cluster from CI:
  - [ ] [`deploy-hubs.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-hubs.yaml)
  - [ ] [`validate-clusters.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/validate-clusters.yaml)
- [ ] Remove the cluster from the list of grafana datasources at https://grafana.pilot.2i2c.cloud/datasources
- [ ] Remove A record from Namecheap account

**Comment by colliand** [comment]
Hi @commonclimate! Can you confirm here that 2i2c can decommission the paleohack2021 hub? Data that may be located on that hub will be lost after the hub is shut down.

**Comment by damianavila** [comment]
Decommissioned after @colliand confirmation in https://github.com/2i2c-org/infrastructure/pull/2576.
