### ISSUE TITLE
[Decommission Hub] 2023 DRAKKAR Ocean Modelling Workshop hub

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#2570]
### Summary

The hub located at [https://drakkar-demo.meom-ige.2i2c.cloud](https://drakkar-demo.meom-ige.2i2c.cloud/) was deployed for an event earlier this year. The event is over and the hub should be decommissioned.  

### Info

- **Community Representative:** @roxyboy @auraoupa
- **Link to New Hub issue:** https://github.com/2i2c-org/infrastructure/issues/2049
- **Proposed end date:** 

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [ ] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
    - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration
  - [ ] If no, confirm it is ok to delete all the data stored in the user home directories

#### Phase II - Hub Removal

(These steps are described in more detail in the docs at https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/hubs/other-hub-ops/delete-hub.html)

- [ ] Manage existing data (migrate data from the hub or delete it)
- [ ] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.
- [ ] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [ ] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [ ] Delete the hub's authentication application on auth0, GitHub or CILogon

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [ ] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [ ] Delete the terraform workspace: `terraform workspace delete <NAME>`
- [ ] Remove the associated `config/clusters/<cluster_name>` directory and all its contents
- Remove the cluster from CI:
  - [ ] [`deploy-hubs.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-hubs.yaml)
  - [ ] [`validate-clusters.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/validate-clusters.yaml)
- [ ] Remove the cluster from the list of grafana datasources at https://grafana.pilot.2i2c.cloud/datasources
- [ ] Remove A record from Namecheap account

**Comment by colliand** [comment]
Thanks @roxyboy for confirming in #2049 that this hub is ready to be decommissioned. Is there any data on that hub that needs to be downloaded and saved elsewhere? The decommission action will permanently delete any data presently on the hub.

**Comment by auraoupa** [comment]
Hi ! No data have been kept there, thanks for asking !

**Comment by yuvipanda** [comment]
This has been completed now via #2571
