### ISSUE TITLE
[Decommission Hub] Catalyst Cooperative

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#2607]
### Summary

Catalyst Cooperative (CC) carries out their data analysis group using local Jupyter installed on laptops. The data sizes and compute requirements for their work have not benefited from cloud-based JupyterHub. As a result, and after a virtual meeting with @zaneselvans, this hub should be commissioned.

There may be future opportunities for 2i2c to engage with Catalyst Cooperative.  CC generates and shares open data on the energy system. This data, and associated analyses, are used by various stakeholders to understand and improve the energy system. For example, stakeholders use CC data and shared computational narratives to advocate for transitions from fossil fuels over to renewable energy sources. **CC needs improved methods for sharing interactive computational narratives.** Mybinder is too slow and does not offer enough compute for their needs. Some other ideas were discussed and will be shared with the 2i2c team internally. 

### Info

- **Community Representative:** @zaneselvans 
- **Link to New Hub issue:** 
- **Proposed end date:** 2023-06-30

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [x] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
    - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration
  - [ ] If no, confirm it is ok to delete all the data stored in the user home directories

#### Phase II - Hub Removal

(These steps are described in more detail in the docs at https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/hubs/other-hub-ops/delete-hub.html)

- [ ] Manage existing data (migrate data from the hub or delete it)
- [x] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.
- [x] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [ ] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [x] Delete the hub's authentication application on auth0, GitHub or CILogon

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [ ] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [ ] Delete the terraform workspace: `terraform workspace delete <NAME>`
- [ ] Remove the associated `config/clusters/<cluster_name>` directory and all its contents
- Remove the cluster from CI:
  - [ ] [`deploy-hubs.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-hubs.yaml)
  - [ ] [`validate-clusters.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/validate-clusters.yaml)
- [ ] Remove the cluster from the list of grafana datasources at https://grafana.pilot.2i2c.cloud/datasources
- [ ] Remove A record from Namecheap account

**Comment by yuvipanda** [comment]
@colliand can you confirm wether the data is to be deleted too?

**Comment by colliand** [comment]
Yes. Let's keep the hub up through June so that @zaneselvans can pull down any data or code. We can then decommission and delete everything.

**Comment by damianavila** [comment]
@sgibson91 will be leading the decommissioning once we get the green light.

I now realized @colliand suggested keeping the hub up through June, although it might be the case we can decommission it earlier if @zaneselvans already got all the information he needed.

@zaneselvans, can you update us on your status to see if we can proceed with the decommission on the current sprint cycle? Thanks!!

**Comment by sgibson91** [comment]
@zaneselvans are we good to decommission this hub now?

**Comment by sgibson91** [comment]
Hub has been decommissioned!
