### ISSUE TITLE
[Decommission Hub] Peddie

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#2609]
### Summary

The hub for Peddie Academy was deployed as an experiment when 2i2c was very young. @colliand has recently exchanged emails with Mark Sawula. Peddie has moved over to using Colab. Mark indicates interest in using 2i2c for his education scenarios, especially with integrations to support automated grading, but can't justify the current costs associated to our education hub service offering. @colliand indicated that 2i2c is exploring ways to support education usage at a lower cost and that 2i2c will reach out to Mark/Peddie in the future if/when we develop such a lower cost offering. 

Hmm, while looking for the new hub issue, I found #354 and see that a previous deletion request for this hub was overruled. Based on Mark's feedback, I suggest we decommission this hub.  

### Info

- **Community Representative:** Mark Sawula
- **Link to New Hub issue:** 
- **Proposed end date:** 

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [x] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
    - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration
  - [x] If no, confirm it is ok to delete all the data stored in the user home directories

#### Phase II - Hub Removal

(These steps are described in more detail in the docs at https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/hubs/other-hub-ops/delete-hub.html)

- [ ] Manage existing data (migrate data from the hub or delete it)
- [ ] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.
- [ ] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [ ] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [ ] Delete the hub's authentication application on auth0, GitHub or CILogon

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [ ] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [ ] Delete the terraform workspace: `terraform workspace delete <NAME>`
- [ ] Remove the associated `config/clusters/<cluster_name>` directory and all its contents
- Remove the cluster from CI:
  - [ ] [`deploy-hubs.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-hubs.yaml)
  - [ ] [`validate-clusters.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/validate-clusters.yaml)
- [ ] Remove the cluster from the list of grafana datasources at https://grafana.pilot.2i2c.cloud/datasources
- [ ] Remove A record from Namecheap account

**Comment by yuvipanda** [comment]
Done!
