### ISSUE TITLE
[Request deployment] New Hub: Catalyst Project - LatAm

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#2703]
### The GitHub handle of the community representative

@jmunroe

### Hub important dates

- **Target Start Date**: July 5, 2023 (flexible)

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

@jmunroe will serve as administrator

### [GitHub Auth only] How would you like to manage your users?

Allowing members of specific GitHub team(s)

### [GitHub Teams Auth only] Profile restriction based on team membership

not required

### Hub logo image URL

pending

### Hub logo website URL

pending

### Hub user image GitHub repository

N/A

### Hub user image tag and name

 jupyter/scipy-notebook

### Extra features you would like to enable

- [x] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

GCP (default and preferred)

### (Optional) Billing and Cloud account

None

### Other relevant information to the features above

This will be the first Hub on a new shared cluster in southamerica-east1-c (GCP in São Paulo, Brazil) for the Catalyst Project (CZI - ECB grant)

There will also be another cluster on AWS in Africa (af-south-1) See https://github.com/2i2c-org/infrastructure/issues/2704

It's intended use is to be a first tenant of eventually ~10 hubs on the same cluster.  

Namespace considerations: The overall project has now officially been designated the "Catalyst Project" so I think **catalystproject** makes sense as a slug for both this hub and part of the name of the cluster.  It is also possible that future 'Catalyst Project' communities should share the same subdomain (similar to what we do for cloudbank). I defer to @2i2c-org/engineering on the right naming scheme for this hub, the cluster, and future communities on this hub.  

### Tasks to deploy the hub

- [x] 1. Deploy information filled in above
- [x] 2. Engineer who will deploy the hub is assigned
- [x] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [x] 4. Initial Hub deployment PR <link to PR>
- [x] 5. Administrators able to log on -> Hub now in steady-state

**Comment by jmunroe** [comment]
There isn't anything an official logo or website yet.  How about 

![CatalystProject](https://github.com/2i2c-org/infrastructure/assets/6181563/0667c576-7dce-4443-afd2-922288530814)

as a place holder image with not website URL.

**Comment by consideRatio** [comment]
- New GCP Cluster in the zone `southamerica-east1-c`
- Authenticator: GitHubOAuthenticator
- Logo: https://github.com/2i2c-org/infrastructure/assets/6181563/0667c576-7dce-4443-afd2-922288530814
- Name: Catalyst Project, cluster slug: catalystproject, domain: catalystproject.2i2c.cloud
- Image: jupyter/scipy-notebook

## A staging hub, and one more?

If there are to be multiple communities on this hub, and no community is a "primary" community using the domain `catalystproject.2i2c.cloud`, then I suggest that a staging hub and future community specific hubs are created like:

- `staging.catalystproject.2i2c.cloud`
- `<future community name 1>.catalystproject.2i2c.cloud`
- `<future community name 2>.catalystproject.2i2c.cloud`

That is what cloudbank has, where `cloudbank.2i2c.cloud` doesn't go anywhere currently.

@jmunroe the concrete question becomes: should a jupyterhub beyond a staging hub be deployed, and if so, should that hub be accessed via the `catalystproject.2i2c.cloud` domain directly or via `<community name 0>.catalystproject.2i2c.cloud`? And if relevant, what then should <community name 0> be?

If the purpose of a non-staging hub is to act as a demo with no permanent users, I suggest the staging hub acts as a demo instead.

## Authentication

I'll preliminary allow us at 2i2c to work on the staging hub, but the communities to use this cluster should probably manage a github organization that can have various teams in them etc.

## Machine types

I'll setup the cloud to have 4, 16, and 64 CPU highmem nodes, but only expose the small (4) and medium (16) nodes initially with configurable requests of how much capacity of the individual nodes is wanted, defaulting to something low.
