### ISSUE TITLE
[Request deployment] New Hub: NASA Greenhouse Gas Center (GHG)

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#2799]
### The GitHub handle of the community representative

@freitagb

### Hub important dates

-- **Target Start Date:** 2023-08-01
-- **Required Start Date:** 2023-08-08

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

- @freitagb 
- WHO ELSE?

### [GitHub Auth only] How would you like to manage your users?

None

### Hub logo image URL

https://github.com/US-GHG-Center/ghgc-docs/blob/87204d4a4e5f29c335a8f905c73de551aabd4845/Logo/ghg-logo.svg

### Hub logo website URL

https://www.nasa.gov/emd/ghg

### Hub user image GitHub repository

pending

### Hub user image tag and name

pending

### Extra features you would like to enable

- [X] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

None

### (Optional) Billing and Cloud account

None

### Other relevant information to the features above

This new hub request is part of the NASA VEDA Phase 2 engagement. This hub should be a replica of the current NASA VEDA hub (same image for now) launched in a new billing account to be shared soon by @freitagb or others at NASA. The hub will be used for the Greenhouse Gas Center. 2i2c's engineering team is already authorized to access NASA's AWS cloud infrastructure and those authorizations will likely allow for similar access to the infrastructure for this new  hub. 

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [ ] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by damianavila** [comment]
I have assigned @yuvipanda for the deployment of this new hub.
I have also co-assigned @colliand as the liaison who will be providing any details needed to start and complete this deployment. Information provided by the community representative is also welcome.

@yuvipanda, please ping @colliand over here in case you have any doubts/questions or need to move forward with the deployment.

**Comment by yuvipanda** [comment]
@freitagb great, i'll probably do so on wednesday

**Comment by yuvipanda** [comment]
I have access now! I'll grant others access and work on it later this week.

**Comment by yuvipanda** [comment]
@freitagb ok, almost here! Two things:

1. Can you give me a list of github orgs that should have access to this hub?
2. We'll need to get a waiver for the CD AWS account as well. It's called `hub-continuous-deployer`, and we have the exact same setup on VEDA. Can we get this exception here too?

**Comment by yuvipanda** [comment]
@freitagb can you also provide a link to a logo image to use?

**Comment by colliand** [comment]
I am not certain if this is the final choice but suggest we can move with content extracted from here: https://www.nasa.gov/emd/ghg

I'll add corresponding content to the anchor issue above.

**Comment by brianmfreitag** [comment]
@yuvipanda we can use US-GHG-Center:ghg-hub-access for Github Org/Team. I'm working with the team to get a public url for a *temporary* GHG center logo. I'll take a look at the VEDA account and see how we handled the `hub-continuous-deployer` and see if I can replicate for GHG account.

**Comment by brianmfreitag** [comment]
@yuvipanda - here's the [logo url](https://github.com/US-GHG-Center/ghgc-docs/blob/87204d4a4e5f29c335a8f905c73de551aabd4845/Logo/ghg-logo.svg). Let me know if the white text is a problem. If possible and if it's easily configurable, we could also change the background color of the landing page to make the text legible.

**Comment by colliand** [comment]
I edited the anchor comment to point to the logo suggested by @brianmfreitag instead of the one I pointed at yesterday.

**Comment by brianmfreitag** [comment]
@yuvipanda would it be possible to support desktop QGIS in the cloud for the GHG hub as described [here](https://blog.jupyter.org/desktop-gis-software-in-the-cloud-with-jupyterhub-ddced297019a) for cryocloud? Partner agencies for the GHG Center rely on GIS software for their workflows.

**Comment by yuvipanda** [comment]
@brianmfreitag yep we can do something like that! We could have an 'image choice' dropdown that lets end users pick what image they wanna use when starting the server. We can have the default pangeo image as well as a qgis one! I'm actually excited to get more qgis onto JupyterHubs in more production style workloads.

**Comment by yuvipanda** [comment]
@brianmfreitag there is a grafana setup at grafana.nasa-ghg.2i2c.cloud, can you tell us which github org should have access to that?

**Comment by freitagb** [comment]
@yuvipanda - can we do veda-analytics-access:veda-ghg-admins for access to the grafana dashboard?

**Comment by freitagb** [comment]
@yuvipanda can you coordinate with @slesaad on the target url for the hub?

**Comment by yuvipanda** [comment]
@slesaad @freitagb just to make reasoning about auth cookies easier and simpler in the long term, can we use `hub.ghg.center` instead? If so, can you make a CNAME from `hub.ghg.center` pointing to `nasa-ghg.2i2c.cloud` and let me know once that is done?

**Comment by slesaad** [comment]
@yuvipanda we want to keep the uniformity as much as possible since all our other services follow the `/<service>` pattern. what are the issues that it might cause?

**Comment by yuvipanda** [comment]
@slesaad the primary concern is around cookie stealing, because Jupyter Notebooks can execute arbitrary code - including arbitrary JS. 

So if you have a service under `/service1` and the hub under `/hub`, a very easy attack is for `/service1` to not set Path in any of its auth cookies correctly. Path should be set to `/service1` but is often set to `/`, so *any* web page under `/` can read these cookies. This is an extremely common problem, as many web frameworks assume that the application owns entire root. For example, here's this reported and unfixed in ASP.net core https://github.com/dotnet/aspnetcore/issues/48165. This is a fairly common cookie vulnerability (often called the 'loosely scoped cookie vulnerability' or something like that) - see https://www.acunetix.com/blog/articles/why-scoping-cookies-to-parent-domains-is-a-bad-idea/ for example.

In general exploiting this requires at least an XSS vulnerability. However, because Jupyter Notebooks execute arbitrary code *by design*, including arbitrary JS, the vector here is much much larger. Isolating this vector on its own domain is a useful secure default, protecting other services on the domain. Hence the recommendation that the hub live in a domain of its own.

The secondary issue is that if you want it to live under a suffix, then you would need to manage and proxy all requests to `ghg.center/hub` via your own mechanisms (some kinda proxy) to a backend here. This adds an additional layer of network complexity that is instead better handled via DNS. This also complicates any debugging we might have to do, as we would not have access to this network proxy and it would be the first point of access for end users.

So, due to both these factors, at this point we want to only support having the hub on the domain by itself. I have dealt with the consistency requirement in the past by having a redirect - so `ghg.center/hub` may redirect to `hub.ghg.center`. Would that work for you?

**Comment by slesaad** [comment]
@yuvipanda thanks for the explanation! the redirecting should work for us, I'll get `hub.ghg.center` ready for you!

**Comment by yuvipanda** [comment]
@slesaad @freitagb it's set up now at hub.ghg.center!

**Comment by slesaad** [comment]
@yuvipanda yay thanks! although, i can't access the hub even tho I'm a member of the https://github.com/orgs/US-GHG-Center/teams/ghgc-hub-access team. is the team setup still pending?

**Comment by yuvipanda** [comment]
@slesaad I think it needs someone with admin rights on that org to approve it first time. @brianmfreitag do you have admin rights on that org? If so, can you try logging into the hub and see what it says?

**Comment by slesaad** [comment]
I do have admin rights to the org, but it still says access denied
![image](https://github.com/2i2c-org/infrastructure/assets/7830949/95e89ba7-9516-49d3-ad64-ead1516e4c16)

also, can we change all the instances of "NASA Green House Gases Center" to "U.S. Greenhouse Gas Center"?

**Comment by freitagb** [comment]
i'm getting the same error for both github accounts @freitagb and @brianmfreitag. @slesaad we need to be added as admins on that org

**Comment by yuvipanda** [comment]
@freitagb @slesaad looks like I made a typo in the team name! Should be fixed now, can you try?

You can also remove me from admin access now.

**Comment by slesaad** [comment]
@yuvipanda it works! thanks!
