### ISSUE TITLE
Document policy for deploying unreleased versions of packages in the hub image: when, how and why.

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#2800]
We use a custom image for the jupyterhub pod (documented in https://github.com/2i2c-org/infrastructure/blob/master/docs/topic/infrastructure/hub-image.md), mostly to install jupyterhub-configurator on top. Sometimes we have deployed unreleased or even unmerged PRs there, to roll out features to users faster.

While we have some documentation, we don't have a defined policy for *when* this is ok. We should document this
```[tasklist]
### Tasks
- [x] Move current docs from topic/ to howto/ https://github.com/2i2c-org/infrastructure/pull/2801
- [ ] Write a policy for *when* unreleased packages may be installed on the hub image
- [ ] Document *how* to install unreleased packages on the hub image
- [ ] Write a policy for when *unmerged* packages may be installed on the hub image, if at all
```

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/infrastructure/pull/2851 sets up an `hub-experimental` image that can move a little bit faster. I think our policy should say that something must *graduate* from `hub-experimental` to `hub` within about 4 weeks, and if not, it should be removed. The goal is to avoid a situation where we permenantly carry a patch in `hub-experimental`. If we identify issues in whatever we have deployed in `hub-experimental`, we should fix it until it's good enough to deploy.

Here's a workflow I'm thinking of:

1. Deploy something to `hub-experimental`, and watch for *one week* to see how it goes. If there are issues here, we fix them until it runs for *one week* without needing any fixes.
2. If everything seems ok there, move it to `hub` and deploy it everywhere with some more testing for hubs that are configured differently. Test things here and deploy. 
3. We can keep the `hub-experimental` image around, but leave it *exactly the same* as `hub` so it is ready for the next experiment.

Thoughts on this, @GeorgianaElena?

**Comment by GeorgianaElena** [comment]
So the hard deadline for a change to graduate into `hub` is 4 weeks, but in reality, if it runs for one week without issues being reported, we can graduate it earlier, right?

I like this plan @yuvipanda and I believe we should go for it. We can always change the policy if we notice errors reported later than the one week window in the lifecycle of hub image change.

I also believe we should have some sort an automation to remind us of graduating for the hard deadline at least (https://github.com/marketplace/actions/issue-reminder might be the simplest approach)
