### ISSUE TITLE
[Request deployment] New Hub: COESSING

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#2844]
### The GitHub handle of the community representative

@paigem

### Hub important dates

- **Target Start Date**: July 24, 2023 (or when possible)

Hub will run until at least August 21 or a few weeks longer depending on funding.

### Hub Authentication Type

Google (e.g., myemailaddress@gmail.org, or a Google-backed domain)

### First Hub Administrators

- paigemar@umich.edu

### [GitHub Auth only] How would you like to manage your users?

None

### Hub logo image URL

https://coessing.files.wordpress.com/2016/08/ghana-logo-21.png?w=262&h=376&zoom=2

### Hub logo website URL

https://coessing.org/

### Hub user image GitHub repository

2i2c-org/coessing-image

### Hub user image tag and name

pangeo-notebook (please use this as the default -- admin will use the configurator to point to an updated coessing-image once that has been updated)

### Extra features you would like to enable

- [ ] Dedicated Kubernetes cluster
- [X] Scalable Dask Cluster

### (Optional) Preferred cloud provider

GCP (default and preferred)

### (Optional) Billing and Cloud account

None

### Other relevant information to the features above

This hub was added last year in 
- #1537 

and decommissioned in
- #1802

We are waiting on @paigem to confirm if this hub should again be set up on the same cluster as pangeo-hubs (meaning that we are effectively rolling back #1802) and will use the columbia billing account OR if this is paid from a new funding source in which case it should be deployed on the shared 2i2c shared cluster.  Confirmation should be provided by Friday July 21. It is understood that deployment of this hub can not proceed until this determination has been made.

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [ ] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by jmunroe** [comment]
I've received confirmation that the COESSING hub should once again be in the same cluster as Pangeo's GCP hub. The billing account is still the Columbia billing account.

So this 'new' hub deployment is more of a recommission a previously deployed hub with all the same settings/options it had when taken down in October 2022.

**Comment by sgibson91** [comment]
- New hub PR: https://github.com/2i2c-org/infrastructure/pull/2858
- Hub available at: https://coessing.2i2c.cloud

**Comment by sgibson91** [comment]
Hoping everything is going well with the hub! I'm going to close this now, please follow our [support process](https://docs.2i2c.org/support/) for any additional requests.
