### ISSUE TITLE
Spanish translation of homepage for Latin American Catalyst Project communities

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#2870]
### Context

We need to create a Spanish language equivalent of our [homepage template](https://github.com/2i2c-org/default-hub-homepage) for the UNITEFA-CONICET hub and for other upcoming LatAm hubs.

Tracking Catalyst project issue: https://github.com/czi-catalystproject/Project-Board/issues/39

### Updates and actions

- [x] Make a new branch in https://github.com/2i2c-org/default-hub-homepage
- [x] Translate to Spanish
- [x] Verify that translation is accurate
- [x] Update homepage template for the UNITEFA-CONICET hub
```[tasklist]
### Tasks
- [x] Download recent translations from Crowdin
- [x] Update landing pages to spanish translations
```

**Comment by jmunroe** [comment]
While I'm sure @damianavila would be able to verify that the translation is good, MetaDocencia is also available to provide language support.  MD has a translator that they contract with when needed.

**Comment by jmunroe** [comment]
I notice that Jinja2 does support multiple languages through its i18n extension which can be used in combination with [gettext](https://docs.python.org/3/library/gettext.html) or [Babel](https://babel.pocoo.org/). I don't think that level of complexity is needed at this point.

**Comment by jmunroe** [comment]
I created a new [catalystproject-ES](https://github.com/2i2c-org/default-hub-homepage/tree/catalystproject-ES) branch on the `default-hub-homepage` repo.  

I also gave a first pass at a Google Translate assisted Spanish version of the `login.html` page.   

@damianavila could you please give that a sanity check?

**Comment by damianavila** [comment]
> @damianavila could you please give that a sanity check?

I briefly took a look and changes are needed (google translate is not good enough, IMHO).
When this is expected to be delivered? What is the priority, @jmunroe?

**Comment by colliand** [comment]
A related observation. The [OceanHackWeek Hub](https://oceanhackweek.2i2c.cloud/hub/login?next=%2Fhub%2F) has a splash page rendered _en español_. This was set up for an AECID-funded (Government of Spain) event in March. The hub has remained up for use during another OceanHackweek funded by the Bigelow Lab in the USA state of Main.

I like the idea hinted at above by @jmunroe that the International Interactive Computing Collaboration should (eventually) support hub landing pages in multiple languages!

**Comment by jmunroe** [comment]
This is part of the Catalyst Project on the community support side. Part of on-boarding the community -- important but not immediate

If the translation from Google is imperfect, it might be better to pass on to MetaDocencia for their translator contractor to handle.  I don't want you to pick up that labour -- but thanks for the sanity check.

**Comment by jmunroe** [comment]
I've come back to this issue and used professional translators through Crowdin to verify/correct the translation.

**Comment by jmunroe** [comment]
The verified translation of the landing page has been committed to the catalystproject-ES branch of the `default-hub-homepage` repo.

**Comment by jmunroe** [comment]
Thanks @damianavila . The conversation on changes that need to made is being tracked at 
- https://github.com/czi-catalystproject/Project-Board/issues/39

**Comment by colliand** [comment]
James. needed but not absolutely urgent

**Comment by jnywong** [comment]
At the Catalyst Community Success meeting yesterday, lack of progress was raised by Sabrina (MetaDocencia). I think we should kick this one into the next iteration and I am happy to pick up and coordinate this work then.

**Comment by jmunroe** [comment]
Completed!
