### ISSUE TITLE
[Request deployment] New Hub: GO-BGC Hub

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#2877]
### The GitHub handle of the community representative

@alisongray @dnicholson

### Hub important dates

- **Target Start Date:** 2023-08-01
- **Required Start Date:** 2023-08-08
- **Heavy Usage Dates:** The [Float Data Workshop](https://www.go-bgc.org/news/2023-float-data-workshop) takes place August 21-23, 2023. 
- Hub will be wound down 2023-09-15. 

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

@alisongray
@dnicholson

### [GitHub Auth only] How would you like to manage your users?

Allowing members of a specific GitHub organization

### [GitHub Teams Auth only] Profile restriction based on team membership

https://github.com/go-bgc

Workshop will function well with MEDIUM sized machines assigned to all users. 

### Hub logo image URL

https://www.go-bgc.org/wp-content/uploads/2023/04/GO-BGCBGC-Argo-Float-Data-Workshop-Flyer-2023-2-980x656.jpeg

### Hub logo website URL

https://www.go-bgc.org/news/2023-float-data-workshop

### Hub user image GitHub repository

pending, likely best to use latest pangeo image

### Hub user image tag and name

pending

### Extra features you would like to enable

Research hub deployed on shared cluster.
No DASK Gateway required.
No GPU required. 

### (Optional) Preferred cloud provider

AWS

### (Optional) Preferred cloud region

us-west-2

### (Optional) Billing and Cloud account

None

### Other relevant information to the features above

This is a request for a research hub (WITHOUT DASK and WITHOUT GPU) deployed on a shared cluster in AWS us-west-2 adjacent to NASA data. The hub will be used for the upcoming Float Data Workshop.

### Tasks to deploy the hub

- [x] 1. Deploy information filled in above
- [x] 2. Engineer who will deploy the hub is assigned
- [x] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [x] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by colliand** [comment]
Hi @alisongray and @dnicholson. Do you have a software image you'd like to use for this workshop? If not, shall we set this hub up with the current Pangeo image?

**Comment by consideRatio** [comment]
Hi @AlisonGray @dnicholson, I'm an engineer at 2i2c and have now setup a JupyterHub available at https://go-bgc.2i2c.cloud. There are a few points I'd like your help with and feedback on.

1. Could you as part of attempting to login at https://go-bgc.2i2c.cloud press the `Grant` or `Request` button for the [`go-bgc` github organization](https://github.com/go-bgc), similar to the grant button next to `jupyterhub` seen in this image?
   ![image](https://github.com/2i2c-org/infrastructure/assets/3837114/b320afbe-f0a1-4991-8fe6-52989907435f)
   Granting this only needs to be done once by one of you. What we request here is permissions to inspect the members of various teams in the github organization `go-bgc` (`read:org`). Specifically, JupyterHub will check if the user is a member of the GitHub org `go-bgc` to decide if the github user should be authorized access. Note that if you can't or don't want to press Grant, the login isn't expected to succeed unless your github user's membership of the github team has explicitly been made public ahead of time.
2. Could you confirm that the domain name `go-bgc.2i2c.cloud` is acceptable among the choices of `<anything>.2i2c.cloud`? Note that we can also make use of a domain not managed by 2i2c as an alternative to this.
3. Could you check if this view on the login page looks correct?
   
   ![image](https://github.com/2i2c-org/infrastructure/assets/3837114/d6b3b8f8-c844-4435-a87c-afdb71996b26)

   Please also inspect the part below the logo, maybe the funding for example is incorrectly attributed?

   > Operated by: [2i2c](https://2i2c.org/) | Funded by: [GO-BGC](https://2i2c.org/) | Designed by: [2i2c](https://2i2c.org/)

Also note that:

- The user environment docker image is setup to be `pangeo/pangeo-notebook:2023.07.05` (currently the latest version), if you want something else you can configure that via https://go-bgc.2i2c.cloud/services/configurator/
- The user environment is configured to be JupyterLab by default, you can change that via https://go-bgc.2i2c.cloud/services/configurator/ as well.
- Users are defaulting to get a **_guaranteed capacity_** of 4 GB of memory and 0.5 CPU on 128 GB and 16 CPU based machines, but are not limited. If this hub is setup for a workshop, I suggest that you inspect how much memory you expect users to use and request that by default - memory is almost always the limiting factor. To learn about your memory use, you can look at the footer status bar in jupyterlab.

**Comment by colliand** [comment]
Thanks @consideRatio for your work deploying this hub. Hi @AlisonGray @dnicholson! Can you please confirm you have access to the hub? It may be necessary to carry out the GitHub org authorization step [mentioned by Erik Sundell above](https://github.com/2i2c-org/infrastructure/issues/2877#issuecomment-1659006655).

**Comment by damianavila** [comment]
I will call it done and close this one since it is already deployed (and we waited a few days for confirmation).
If there is a need for a follow-up, it should be directed via support.
Thanks!
