### ISSUE TITLE
[Support] cryocloud: Allow bucket access based on hub admin status

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#2886]
### Context

In https://2i2c.freshdesk.com/a/tickets/847 a persistent bucket is requested. This bucket should be accessible only by hub admins.

It is my understanding that this is not possible given the current setup because we map all the hub user pods to a cloud user account (`user-sa`) and there's no further granular acccess.

Another way to manage more granular access is [through Google Groups](https://infrastructure.2i2c.org/howto/features/buckets/#allowing-access-to-buckets-from-outside-the-jupyterhub) but that's only setup for GCP.

### Question
What does @2i2c-org/engineering think about a new hub-admin <-> specific cloud user account for more granular access setup on the hubs? Is this feasible? Or is there an easier way that I'm missing?
```[tasklist]
### Tasks
- [ ] https://github.com/2i2c-org/infrastructure/issues/2893
- [x] Decide if granular access based on admin/non-admin status of users is achievable
- [ ] Follow-up to https://2i2c.freshdesk.com/a/tickets/847 with an answer
```

**Comment by damianavila** [comment]
Bumping ping to @2i2c-org/engineering for feedback on @GeorgianaElena's question.

**Comment by yuvipanda** [comment]
I think we're currently not planning on doing this for cryocloud. If that changes, we can reopen this.
