### ISSUE TITLE
[Support] 2i2c-aws-us/itcoocean: help to setup s3 bucket (admin/non-admin with readwrite/readonly access)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3038]
In https://2i2c.freshdesk.com/a/tickets/906 Eli asks for help to setup a s3 bucket for the itcoocean.2i2c.cloud hub part of the 2i2c-aws-us cluster.

The goals are:

- Admin users should have read/write permissions
- non-admin users should just have read access
- Allowing anyone access the data, but to not need to pay for users accessing the data.

> Goal is to not have egress charges from our S3 bucket (in us-west-2). The data are not "private". We'd make the S3 bucket public but the egress charges would rack up.

## Related

- Looking at [s3 pricing](https://aws.amazon.com/s3/pricing/), I see they mention you don't have to pay for:
  > Data transferred from an Amazon S3 bucket to any AWS service(s) within the same AWS Region as the S3 bucket (including to a different account in the same AWS Region).
- 2i2c infrastructure docs about buckets: https://infrastructure.2i2c.org/howto/features/cloud-access/
- Notes from Eli about setting up a bucket and declaring permissions: https://2i2c.freshdesk.com/a/tickets/906

## Todo

- Distinguishing admin users from non-admin users access to buckets
  - [x] Enable us to configure admin users to have different k8s ServiceAccounts (that should be associated with AWS credentials in s3 buckets) than normal users
    #3039
  - Enable creation of another set of cloud credentials to access buckets with
    - [x] For AWS
    - [ ] For GCP
  - [x] Enable creation of another k8s ServiceAccount that we can annotate as well
- [ ] Allowing anyone access the data, but to not need to pay for users accessing the data

**Comment by jmunroe** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Freshdesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Freshdesk:&nbsp;</strong><a href="https://2i2c.freshdesk.com/a/tickets/906" target="_blank">906</a>&nbsp; linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Freshdesk:&nbsp;<a href="https://2i2c.freshdesk.com/a/tickets/906" target="_blank">#906</a>
                  <div class="pull-right" style="float:right">By: <em>James Munroe &lt;jmunroe@2i2c.org&gt;</em></div>
                </div>
              </div>

**Comment by consideRatio** [comment]
We received an update that this wasn't required to have setup by september 11, so I've updated the title to reflect that now.

**Comment by consideRatio** [comment]
The freshdesk ticket was closed following no response, but on AWS this is now very doable.
