### ISSUE TITLE
Process of onboarding a new customer

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#306]
# Background

Once somebody decides that they'd like to pay 2i2c to manage a hub for them, there are several repeatable things that we'll need to do. This process isn't documented clearly right now, and it will be helpful both for us and for customers to know what to expect and follow.

It is somewhat documented [in the team compass](https://2i2c.org/team-compass/sales/#converting-sales-into-hubs) but we need to put more work into streamlining and fleshing it out.

The thing that triggers this process is:  The customer signs a contract.

# User stories

- As a 2i2c engineer, I want to know when new hubs will soon be needed, and who on the team is responsible for setting it up
- As a new customer for 2i2c, I want my hub infrastructure to begin as quickly as possible after signing a contract

# Important links

- [**Draft of onboarding process**](https://docs.google.com/document/d/1DOsmJ3Xrnp5IDpJfXQR_aq33EBnsr72EXErqL0lgVuw/edit?usp=sharing)

# Tasks

- [ ] Run through the process of deploying one or two hubs, write down the steps we needed to take
- [ ] Write down a prototype of this process for the `pilot-hubs` or `pilot` docs
   - [ ] For GCP
   - [ ] For Azure
   - [ ] For AWS
- [ ] Run through this process and refine
- [ ] After several iterations, re-assess the process to make sure all is going OK and no major changes are needed

**Comment by yuvipanda** [comment]
I'm adding GCP instructions in this PR: https://github.com/2i2c-org/pilot-hubs/issues/306

We should also add Azure & AWS instructions.

**Comment by yuvipanda** [comment]
In https://github.com/2i2c-org/pilot/pull/67, we asked new customers to give GCP billing account invites to `yuvipanda@2i2c.org` and `choldgraf@2i2c.org`. Once received, these two folks must grant access to all other 2i2c infrastructure engineers. We should document this as part of 'new hub setup' documentation.

Ideally, users can invite `sre@2i2c.org`, and that be a general account that gives access to all the 2i2c engineers. Unfortunately, I think only Google Accounts (not aliases) can be invited, so I think that's not quite possible yet.

**Comment by yuvipanda** [comment]
Since a lot of this is hub admin facing documentation, we should add screenshots (per @GeorgianaElena at https://github.com/2i2c-org/pilot/pull/67#discussion_r602116212).

**Comment by yuvipanda** [comment]
So after we get access to a new billing account, 2i2c staff should:

1. Invite other 2i2c staff members to it
2. Create a new GCP project for the hub
3. Setup [billing export](https://cloud.google.com/billing/docs/how-to/export-data-bigquery), ideally to a single BigQuery instance we control (in the two-eye-two-see project). However, if we can only put data in bigquery instances in a project under the same billing account, we should do that.

**Comment by choldgraf** [comment]
@2i2c-org/tech-team I think that we are getting close to being able to have contracts w/ ICSI (see https://github.com/2i2c-org/meta/issues/90). What do you say we use #291 to onboard @jhamman, and write down the process as we do it, then document it as a first pass for this issue.

**Comment by yuvipanda** [comment]
@damianavila and I want to figure out a better way to get information about deadlines from clients. There's a deadline for first time admins need to start using it, first time for early users to start using it, and when they expect the flood of users. Having these be separate will help us plan.

**Comment by damianavila** [comment]
I agree with that proposal. I guess we can modified the issue template to include that information. But I think the most difficult thing is actually getting the whole info. How we make sure we have all the info we need before starting the process. Should we follow some sort of “waterfall” model where one action starts **only** when the previous one (ones) have finished?

**Comment by choldgraf** [comment]
I believe that we have a process for onboarding communities in place now:

- We have a sales and invoicing process here: https://team-compass.2i2c.org/en/latest/projects/managed-hubs/sales.html
- We have new hub creation here: https://infrastructure.2i2c.org/en/latest/howto/hubs/new-hub/index.html
- We have support process defined here: https://team-compass.2i2c.org/en/latest/projects/managed-hubs/support.html
