### ISSUE TITLE
[EVENT] itcoocean

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3071]
### Summary

Requested in https://2i2c.freshdesk.com/a/tickets/937

### Event Info

- **Community Representative:** 
- **Event begin:**  **Sept 11**!!!
  - **In your timezone:** 
- **Event end:**  Sept 22
  - **In your timezone:** 
- **Active times:**   9am to 5pm IST (India)
  - **In your timezone:** 
- **Number of attendees:**  70
- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

#### Q: Do you need to need hub infrastructure to be [pre-initialized before the event](https://docs.2i2c.org/community/events/#events-pre-initialized)?
A: No, I think I am all set up.

#### Q: Any other information that will help us prepare for the extra usage during the event.

I don't expect that participants will have heavy RAM needs for the course. This is the first hack event that I am running as the hub point person. I have participated in a number of hackweeks with 2i2c hubs however.   We are at the Indian National Centre for Ocean Information Services (INCOIS) and internet is fast but outages will probably happen.

Note, the spin-up of the itcoocean.2i2c hub seems slower than when I was in Seattle. Spin-up is also slow for oceanhackweek and openscapes 2i2c hubs but itcoocean is noticeably slower. It seems to take 4-5x longer than my hub on Azure, which is on us-west-2 region like the other 2i2c hubs and uses the same image as I am using on itcoocean.2i2c. It takes about 4 minutes to fully spin up (server started, JupyterLab open, and notebooks able to load). The same spin-up on my Azure hub (dedicated Kubernetes instance) takes under 1 minute.

### Hub info

- **Hub URL**:  https://itcoocean.2i2c.cloud/
- **Hub decommisioned after event?**:  No

### Task List

**Before the event**

- [x] Dates confirmed with the community representative and added to Hub Events Calendar.
- [x] Quotas from the cloud provider are high-enough to handle expected usage.
- [ ] **One week before event** Hub is running.
- [ ] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  
- [ ] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [ ] Confirm event is finished.
- [ ] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [ ] Hub decommissioned (if needed).
- [ ] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by consideRatio** [comment]
Whenever an event takes place, users may end up doing the same thing as everyone else. This can lead to systematic behaviors among users in how much RAM they consume etc. Due to this, I think its relevant to limit the available RAM.

By limiting the available RAM, the instructor etc testing out something to work ahead of time will experience the same result no matter if the node is full of users doing the same thing - at least with regards to not running out of memory.

**Comment by damianavila** [comment]
I have assigned @sgibson91 to lightly monitor this event given that she will be rotating through support during the start date (Sep 11th).

**Comment by sgibson91** [comment]
Hey @eeholmes, your event appears to be over 🎉

We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!

- Did the infrastructure behave as expected?
- Anything that was confusing or could be improved?
- Any extra functionality you wish you would have had?
- Could you share a story about how you used the hub?

- Any other feedback that you'd like to share?

**Comment by damianavila** [comment]
Closing now but @eeholmes you are more than welcome to provide any feedback on the close issue, thanks!
