### ISSUE TITLE
[Incident] Spawn failed on nasa-veda

### ISSUE THREAD

**Issue by j08lue** [2i2c-org/infrastructure#3074]
### Summary

Trying to start a session on https://nasa-veda.2i2c.cloud/ repeatedly fails with "Spawn failed: Could not create pod prod/jupyter-j08lue". Other users report the same.

<img width="1326" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/3404817/1ae498a6-f48a-4a4d-ae94-e9ef7c1c1173">

### Impact on users

Users cannot create a session.

Pls note - this is not time critical today (4th of September) due to the U.S. holiday.

### Important information

- Hub URL: https://nasa-veda.2i2c.cloud/

### Tasks and updates

- [x] Discuss and address incident, leaving comments below with updates
- [x] Incident has been dealt with or is over
- [ ] Copy/paste the after-action report below and fill in relevant sections
- [ ] Incident title is discoverable and accurate
- [ ] All actionable items in report have linked GitHub Issues

<details>
<summary>After-action report template</summary>

```
# After-action report

These sections should be filled out once we've resolved the incident and know what happened.
They should focus on the knowledge we've gained and any improvements we should take.

## Timeline

_A short list of dates / times and major updates, with links to relevant comments in the issue for more context._

All times in {{ most convenient timezone}}.

- {{ yyyy-mm-dd }} - [Summary of first update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of another update](link to comment)
- {{ yyyy-mm-dd }} - [Summary of final update](link to comment)


## What went wrong

_Things that could have gone better. Ideally these should result in concrete
action items that have GitHub issues created for them and linked to under
Action items._

- Thing one
- Thing two

## Where we got lucky

_These are good things that happened to us but not because we had planned for them._

- Thing one
- Thing two

## Follow-up actions

_Every action item should have a GitHub issue (even a small skeleton of one) attached to it, so these do not get forgotten. These issues don't have to be in `infrastructure/`, they can be in other repositories._

### Process improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Documentation improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]

### Technical improvements

1. {{ summary }} [link to github issue]
2. {{ summary }} [link to github issue]
```

</details>

**Comment by jmunroe** [comment]
Thanks for letting us know!  I'll create a corresponding support ticket and we'll take a look at it tomorrow.

**Comment by consideRatio** [comment]
Thank you for reporting this @j08lue, the incident should now be resolved! I've replied from the 2i2c support as well.

**Comment by j08lue** [comment]
Confirmed, thanks!
