### ISSUE TITLE
[Request deployment] New Hub: HHMI

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#3080]
### The GitHub handle of the community representative

@colliand and pending

### Hub important dates

- **Target Start Date:** 2023-09-11
- **Required Start Data:** 2023-09-19

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

- Jim Colliander, @colliand

### [GitHub Auth only] How would you like to manage your users?

pending

### [GitHub Teams Auth only] Profile restriction based on team membership

pending

### Hub logo image URL

https://www.hhmi.org/sites/default/files/Logos/JPG/HHMI-vertical-signature-color.jpg

### Hub logo website URL

https://www.hhmi.org/

### Hub user image GitHub repository

pending

### Hub user image tag and name

pending

### Extra features you would like to enable

- [X] Dedicated Kubernetes cluster
- [x] Scalable Dask Cluster

### (Optional) Preferred cloud provider

None

### (Optional) Billing and Cloud account

None

### Other relevant information to the features above

This hub will be used for an emerging pilot with the Howard Hughes Medical Institute (HHMI). This engagement is different from 2i2c's prior partnerships. The project is led by central administration instead of by a Principal Investigator. As a result, we don't have input from a scientist requesting specific tools in the image, etc. 

The first big user of this hub is likely to be a neuroscientist. Therefore, the software image used on the Neurohackademy or the Allen Institute hubs are likely the best first choices. As the pilot evolves, I expect that the hub will be used by a variety of medical researchers. The hub should be configured to eventually support multiple hubs with different hardware configurations. 

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [ ] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by colliand** [comment]
Next week, @colliand will travel to SF to meet with the [Loren Frank Group](https://franklab.ucsf.edu/) on Tuesday 2023-09-12 at UCSF. Ideally, the hub will be set up for demonstration on that afternoon.

**Comment by colliand** [comment]
After speaking with @damianavila, it is likely unreasonable to get this hub up before 2023-09-11. There is a workshop taking place at HHMI/Janelia on September 19. If possible, please make this hub available in time for experimental usage at that event.

**Comment by damianavila** [comment]
Assigned @GeorgianaElena to perform this new hub deployment. To be deployed during this sprint and before Sep 19th.

> There is a workshop taking place at HHMI/Janelia on September 19. If possible, please make this hub available in time for experimental usage at that event.

**Comment by GeorgianaElena** [comment]
@colliand after reading the comments above, it is my understanding that the hub I need to deploy has the following characteristics. Can you please help me verify that the following assumption is correct:

- new GCP cluster in the us-west2 zone (default choices as no preference was specified)
- billing will be managed by 2i2c (this means I will be creating the new cluster and project under the 2i2c GCP org)
- no dask
- GitHub auth through CILogon. The list of users allowed will be managed manually through the admin panel.
- the initial user image that I will setup will be the one that the neurohackademy hub is using, which is 
https://github.com/2i2c-org/infrastructure/blob/c536a75957465d94b55c9210c3ae8c67a4cfd7ea/config/clusters/2i2c/neurohackademy.values.yaml#L36-L39

**Comment by colliand** [comment]
Yes. In near term, I imagine a 2i2c team on GitHub can manage users. The team will likely be transitioned to be managed by HHMI personnel later in the year. Let's include Dask to save time later.

**Comment by yuvipanda** [comment]
@colliand does @arokem know his image may be used for this? My suggestion is to not use the specific neurohackedemy image, as the only person who can control what goes into that is @arokem and it is probably specific to that use case. I would recommend starting with a pangeo image. Is managing images written into the contract? I think that's important to specify, as *someone* needs to manage images, and that can't actually be @arokem :) Is it 2i2c?

**Comment by colliand** [comment]
Good insight here. Let's proceed with Pangeo and use new image management methods to evolve the image in response to requests from the HHMI personnel we support.

**Comment by yuvipanda** [comment]
Thanks @colliand. Does the contract include paying us for image management?

**Comment by colliand** [comment]
Not explicitly but functionally, yes. The contract outlines targets of success (open science, easier collaboration, improved knowledge sharing) across HHMI that will require 2i2c to assist with image management. There is adequate budget to cover this work.

**Comment by yuvipanda** [comment]
@colliand great, makes sense! I think in the future, it would be useful to explicilty include language about image management so that is clear.

**Comment by arokem** [comment]
Just to chime in that you can certainly use our image for this, but I suspect that it will not be a great fit, because I am guessing the users of this hub will have needs that are distinct from the needs we have at neurohackademy (e.g., experimental data shows up in formats that are different, and require different libraries to be read).

Given what I know about these use-cases, I would suggest to build an image that at least also includes these libraries (all pip installable): 

- [pynwb](https://pypi.org/project/pynwb/)
- [nwbwidgets](https://pypi.org/project/nwbwidgets/)

That will give you some immediate domain-relevant demo material: 

https://github.com/NeurodataWithoutBorders/nwbwidgets/blob/master/examples/NWBWidgets-modality-demos.ipynb

**Comment by GeorgianaElena** [comment]
@colliand, https://hhmi.2i2c.cloud and https://staging.hhmi.2i2c.cloud are now deployed. They have dask enabled and the `pangeo/pangeo-notebook:2023.09.11` image.

The only missing info is about funding (name and URL) and it shows as TODO on the hub's main login page.
 
<img width="512" alt="Screenshot 2023-09-18 at 15 02 29" src="https://github.com/2i2c-org/infrastructure/assets/7579677/0b6d196a-0cfc-4877-805e-3a5b9e5d651d">

**Comment by GeorgianaElena** [comment]
I will close this issue as the hub is now ready to try. @colliand, when you have additional info about the funding, please let me know so I can update the todo message with the relevant info.
