### ISSUE TITLE
[EVENT] Cryocloud (Geosmart Hackweek 2023), with GPU to be setup ahead of time

### ISSUE THREAD

**Issue by scottyhq** [2i2c-org/infrastructure#3135]
EDIT: Associated freshdesk ticket at https://2i2c.freshdesk.com/a/tickets/982

### Summary

Geosmart Hackweek 2023 is focused on the application of machine learning in Hydrology and Cyrosphere science (https://geosmart.hackweek.io)

### Event Info

- **Community Representative:** @scottyhq @tsnow03
- **Event begin:** 2023-10-23
  - **In your timezone:** https://arewemeetingyet.com/Los%20Angeles/2023-10-23/08:00
- **Event end:** 2023-10-27
  - **In your timezone:**  https://arewemeetingyet.com/Los%20Angeles/2023-10-27/08:00
- **Active times:** 8am - 5pm US/Pacific) 
- **Number of attendees:** 60
- [**Hub Events Calendar**](https://geosmart.hackweek.io/#schedule)

### Hub info

- **Hub URL**: https://hub.cryointhecloud.com
- **Hub decommissioned after event?**: NO

### Task List

**Before the event**

- [x] Dates confirmed with the community representative and added to Hub Events Calendar.
- [x] Quotas from the cloud provider are high-enough to handle expected usage.
- [x] **One week before event** Hub is running.
- [x] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  
- [ ] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [x] Confirm event is finished.
- [ ] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [ ] Hub decommissioned (if needed).
- [ ] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by scottyhq** [comment]
Additional notes: we would love to expose a temporary GPU nodepool for this event (https://infrastructure.2i2c.org/howto/features/gpu/#aws), and also should have cloud credits to apply to the relevant AWS account.

**Comment by scottyhq** [comment]
Just wanted to add a couple updates, hope we're good to go for this event?

> we would love to expose a temporary GPU nodepool

From support email thread on 9/20: plan is for `g4dn.xlarge with 4 CPU / 16GB memory` 

> should have cloud credits to apply to the relevant AWS account.

$5000 in cloud credits have been applied to the cryocloud account! courtesy of this program: https://www.earthdata.nasa.gov/engage/esds-public-private-partnerships/aws-storage-compute

**Comment by damianavila** [comment]
I have assigned @sgibson91 to take care of preparing for this one.
Getting enough GPU quota from the cloud provider may take some time, so @sgibson91 can you please make sure we are ready on that aspect? There is a lot of info in the support ticket and @consideRatio may have some additional context. Also, feel free to request any further information from @scottyhq if that is needed. Thanks!

**Comment by consideRatio** [comment]
@sgibson91 it can be good to use machines with multiple GPU attached for these events to avoid issues with for example running out of disk quota or public ip quota, and faster startup times.

Maybe 4x or 8x GPU machines could make sense to use instead of those with 1 per machine to avoid such issues.

**Comment by sgibson91** [comment]
These are the docs I'm following https://infrastructure.2i2c.org/howto/features/gpu/#id1

I don't have a lot of time to do any fine-tuning of the quota calculations as I am doing a 3-day week this week and I'm trying to get through as much on my plate as I can.

**Comment by yuvipanda** [comment]
@scottyhq how many people do you think will be using GPUs? I mostly wanted to check in case the GPU quota is denied or partially granted.

**Comment by tsnow03** [comment]
@yuvipanda I think we can make do with whatever you end up getting in your quota.

**Comment by consideRatio** [comment]
AWS seems to provide at minimum 4 CPU per GPU, so using the 1 GPU x 4 CPU nodes is the cheapest option and also the most AWS quota efficient option, as the quota is measuerd in CPU rather than GPU's or instances. The machines with 4 / 8 GPU attached have a ratio of 1 GPU x 12 CPU, so they are a bad choice.

![image](https://github.com/2i2c-org/infrastructure/assets/3837114/27ee926a-9dc4-4e23-96f0-c0c4452cbcc1)

**Comment by sgibson91** [comment]
The quota increase was approved.

On re-reading the docs, I realised that I maybe should've asked for 4 * 60

> the recommendation is to give users a single g4dn.xlarge each, so the number of vCPUs requested should be 4 * max number of GPU nodes

However, that may have been so much that they wouldn't have approved it

**Comment by scottyhq** [comment]
Thanks for working on this @sgibson91 ! Great to hear about the approved quota. 

I pointed to a specific docker image to use earlier in this issue, but also noticed these docs on freeform image selection https://infrastructure.2i2c.org/howto/features/allow-unlisted-profile-choice/#allow-users-to-setup-custom-free-form-user-profile-choices . I think this would be a fantastic option for this event if possible since ML environments are often bloated and it's hard to cram everything into a single image for the various projects and teams using the hub.

**Comment by tsnow03** [comment]
Thank you for knocking this out @sgibson91! I wanted to confirm that the GPU will be attached to the ml-in-glaciology Github team that we have in our org so that we can restrict access to only users in this hackweek and to specific individuals moving forward as we learn about costs for the server.

**Comment by sgibson91** [comment]
I have opened https://github.com/2i2c-org/infrastructure/pull/3269 to setup for this and deployed it to the staging hub, so please feel free to test it out.

I provided the originally requested pytorch image alongside the unlisted choice option. If you select "Other" from the image dropdown, you will see the input field appear.

**Comment by scottyhq** [comment]
Thanks @sgibson91 ! It seems to be working well I quickly tested the default image and (quay.io/pangeo/ml-notebook:2023.10.03) 

Could you confirm that there are up to 15 GPU nodes available simultaneously with the current quota (60/4vCPU=15 assuming g4dn-xlarge and the discussion above)?

**Comment by sgibson91** [comment]
@scottyhq yes I believe that is right. I could probably ask for another quota bump since we still have time. I'll do that today.

**Comment by tsnow03** [comment]
Staging looks good to me, though I can't test the GPU. I think it will be good to add to CryoCloud.

**Comment by sgibson91** [comment]
Ok, merged! I've also submitted a request to see if we can double the GPU vCPUs from 60 to 120.

**Comment by sgibson91** [comment]
> I've also submitted a request to see if we can double the GPU vCPUs from 60 to 120.

This was also approved. I might try another couple of small increments in the week and see if we can get up to having one for every attendee.

**Comment by tsnow03** [comment]
Awesome. Thank you so much @sgibson91! You're crushing this :)

**Comment by sgibson91** [comment]
Now at 180

**Comment by scottyhq** [comment]
Submitted a support email, but also posting here. GPU nodes have been working over the last couple days, but this morning people have been unable to launch them. Perhaps we're exceeding some availability limit... 

<img width="1308" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/3924836/e92b978f-c563-41e5-b2be-7ec149e58480">

**Comment by sgibson91** [comment]
@scottyhq I've been responding via support email - but I can't reproduce this issue, I've accessed GPUs on both prod and staging successfully. Is this still an issue for you? I'm starting to see a few spikes of usage now

<img width="839" alt="Screenshot 2023-10-25 at 18 31 19" src="https://github.com/2i2c-org/infrastructure/assets/44771837/91438234-b580-4118-b8e3-fb71f400d67e">

**Comment by sgibson91** [comment]
(apologies, multiple pings, I've seen your response in freshdesk)

**Comment by damianavila** [comment]
Hey @scottyhq and @tsnow03, your event appears to be over 🎉

We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!

- Did the infrastructure behave as expected?
- Anything that was confusing or could be improved?
- Any extra functionality you wish you would have had?
- Could you share a story about how you used the hub?
- Any other feedback that you'd like to share?

**Comment by scottyhq** [comment]
> Did the infrastructure behave as expected?

Yes! Worked a treat. One day we had trouble launching GPU nodes, but that was fixed here (https://github.com/2i2c-org/infrastructure/issues/3334). One other non-urgent issue opened here related to core-dump files showing up for people https://github.com/2i2c-org/infrastructure/issues/3321.

> Any extra functionality you wish you would have had?

**Comment by sgibson91** [comment]
Thanks @scottyhq! How are we handling the infrastructure now? Are we leaving as-is, removing the GPU nodepool, something else?

**Comment by scottyhq** [comment]
Let's leave it untouched for now. As for removing the GPU nodepool, is it possible to do a summary of weekly total cost for the last month? That would be helpful to know how long we can keep the more expensive machines as options.

**Comment by sgibson91** [comment]
@scottyhq do you have access to the AWS project for this cluster? I think those graphs will be generated by clicking around in the console

**Comment by sgibson91** [comment]
<img width="538" alt="Screenshot 2023-11-09 at 11 04 58" src="https://github.com/2i2c-org/infrastructure/assets/44771837/6ce671de-4f41-4f7c-95b7-45ba3aeaf674">

Is this a helpful graph? (I've also downloaded the CSV if you'd like me to send you that)

**Comment by damianavila** [comment]
I am gonna close this one since we received feedback from @scottyhq and additional data was provided by @sgibson91.
If further requests are needed, let's tunnel those through support. Thanks, everyone!

**Comment by tsnow03** [comment]
Thanks @damianavila and @sgibson91! This was perfect. Thank you for your support on this one and we will contact y'all when we need any of this infrastructure to be changed in the future.
