### ISSUE TITLE
[Request deployment] New Hub: NM-AIST (Catalyst Project)

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#3140]
### The GitHub handle of the community representative

@beatusmodest

### Hub important dates

Please deploy within the next sprint cycle (Oct 11-Oct 24)

### Hub Authentication Type

Google (e.g., myemailaddress@gmail.org, or a Google-backed domain)

All of the users will be using @[nm-aist.ac.tz](http://nm-aist.ac.tz/) email (this is a Google suite domain)

### First Hub Administrators

Beatus Lyimo, beatus.lyimo@nm-aist.ac.tz, beatus.lyimo@nm-aist.ac.tz

### [GitHub Auth only] How would you like to manage your users?

None

### Hub logo image URL

https://nm-aist.ac.tz/images/logo.png

### Hub logo website URL

https://nm-aist.ac.tz/

### Hub user image GitHub repository

      name: rocker/binder
      tag: "4.3"

### Extra features you would like to enable

- [ ] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

Deploy to the existing catalystproject-africa cluster.

### Other relevant information to the features above

This is a new community on the African Catalyst Project cluster.  

### Tasks to deploy the hub

- [x] 1. Deploy information filled in above
- [x] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [x] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by jmunroe** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Freshdesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Freshdesk:&nbsp;</strong><a href="https://2i2c.freshdesk.com/a/tickets/976" target="_blank">976</a>&nbsp; linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Freshdesk:&nbsp;<a href="https://2i2c.freshdesk.com/a/tickets/976" target="_blank">#976</a>
                  <div class="pull-right" style="float:right">By: <em>James Munroe &lt;jmunroe@2i2c.org&gt;</em></div>
                </div>
              </div>

**Comment by jmunroe** [comment]
Please use a profile list like:

```
jupyterhub:
  singleuser:
    image:
      # rocker/binder is maintained at: https://github.com/rocker-org/rocker-versioned2
      # tags can be viewed at: https://hub.docker.com/r/rocker/binder/tags
      name: rocker/binder
      tag: "4.3"
    profileList:
        - display_name: "Small: up to 4 CPU / 32 GB RAM"
        description: &profile_list_description "Start a container with at least a chosen share of capacity on a node of this type"
        slug: small
        default: true
        profile_options:
          requests:
            # NOTE: Node share choices are in active development, see comment
            #       next to profileList: above.
            display_name: Node share
            choices:
              mem_1:
                default: true
                display_name: ~1 GB, ~0.125 CPU
                kubespawner_override:
                  mem_guarantee: 0.904G
                  cpu_guarantee: 0.013
              mem_2:
                display_name: ~2 GB, ~0.25 CPU
                kubespawner_override:
                  mem_guarantee: 1.809G
                  cpu_guarantee: 0.025
              mem_4:
                display_name: ~4 GB, ~0.5 CPU
                kubespawner_override:
                  mem_guarantee: 3.617G
                  cpu_guarantee: 0.05
              mem_8:
                display_name: ~8 GB, ~1.0 CPU
                kubespawner_override:
                  mem_guarantee: 7.234G
                  cpu_guarantee: 0.1
              mem_16:
                display_name: ~16 GB, ~2.0 CPU
                kubespawner_override:
                  mem_guarantee: 14.469G
                  cpu_guarantee: 0.2
              mem_32:
                display_name: ~32 GB, ~4.0 CPU
                kubespawner_override:
                  mem_guarantee: 28.937G
                  cpu_guarantee: 0.4
        kubespawner_override:
          cpu_limit: null
          mem_limit: null
          working_dir: /home/rstudio
          default_url: /rstudio
          volume_mounts:
            - name: home
              mountPath: /home/rstudio
              subPath: "{username}"
            - name: home
              mountPath: /home/rstudio/shared
              subPath: _shared
              readOnly: true
          node_selector:
            node.kubernetes.io/instance-type: r5.xlarge
```

**Comment by jmunroe** [comment]
I was able to meet with the community representative today. @2i2c-org/engineering please proceed with the deployment of this hub as you are able and let me know if any additional information is required. Thanks.

**Comment by damianavila** [comment]
Assigned to @GeorgianaElena to push forward during the current cycle.

**Comment by damianavila** [comment]
Assigned to @sgibson91 to deploy it next week.

**Comment by damianavila** [comment]
@jmunroe, can you confirm the community representative tested so we can close this one? Thanks!

**Comment by jmunroe** [comment]
I just was thinking about that -- I've emailed the community rep and I'm waiting on confirmation that it is working for them.

**Comment by jmunroe** [comment]
Community champion has been able to successfully log in. Let's close this issue as successfully deployed!
