### ISSUE TITLE
[Request deployment] New Hub: Jack Eddy Symposium

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#3166]
### The GitHub handle of the community representative

@colliand

### Hub important dates

- **Target Start Date:** 2023-10-05
- **Required Start Date:** 2023-10-12

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

- @colliand, Jim Colliander 
- @dan800, Dan Marsh
- @rmcgranaghan, Ryan McGranaghan 

### [GitHub Auth only] How would you like to manage your users?

Manually, by adding specific GitHub handles in the JupyterHub Admin panel

### Hub logo image URL

https://cpaess.ucar.edu/sites/default/files/styles/extra_large/public/2023-08/EddySymposium-900x400.jpg?itok=8qG7Dqi3

### Hub logo website URL

https://cpaess.ucar.edu/meetings/4th-eddy-cross-disciplinary-symposium

### Hub user image GitHub repository

Pangeo (possibly also Heliocloud as another option)

### Hub user image tag and name

pending; likely latest pangeo image

### Extra features you would like to enable

- [ ] Dedicated Kubernetes cluster
- [X] Scalable Dask Cluster

### (Optional) Preferred cloud provider

AWS

### (Optional) Preferred cloud region

us-west2

### (Optional) Billing and Cloud account

None

### Other relevant information to the features above

This hub will be used for the 4th Jack Eddy Symposium. The event will take place October 29 -- November 3, 2023 in Golden, Colorado. This event will focus on open science, sun-climate interactions, space weather, and exoplanets. Talks will take place in the morning with hackathon-style activities during the afternoons. @colliand will be in attendance at the event. Funding for this hub and the Symposium flows from NASA's Living with a Star Program and UCAR/CPAESS. 

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [x] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by damianavila** [comment]
I assigned @consideRatio to deploy this hub. I would recommend deploying it close to the end of the iteration (first days of October).

Previous Jack Eddy hub:
* https://github.com/2i2c-org/infrastructure/issues/1329
* https://github.com/2i2c-org/infrastructure/pull/1337

@colliand, please provide any further information we might need to deploy this in the next few days. For example:
1. shared or dedicated cluster?
2. is there any reason to be now in AWS given the fact the previous deployment lives under GCP (see links referenced above)?


@consideRatio, feel free to ask any additional questions to @colliand (and the other community representatives) you might need to effectively perform this deployment.

**Comment by colliand** [comment]
I think GCP is fine. The Symposium is an opportunity for 2i2c to experiment with new stuff. There will be communities working on space weather, climate, and exoplanets. Allowing these groups to customize environments may be helpful but is not necessary. I'm available for questions @consideRatio!

**Comment by colliand** [comment]
Is there progress or are there any blockers on this deployment request?

**Comment by damianavila** [comment]
Not particular blockers, although other high-priority operational issues took precedence.
@consideRatio, can you please make a priority to deploy this early next week? Thanks!

**Comment by damianavila** [comment]
Reassigned to @GeorgianaElena to deploy during this cycle (as planned above).

**Comment by GeorgianaElena** [comment]
Thank you very much @consideRatio for this plan! It's really useful <3

I am confused about the cloud provider to go with though.

Is it AWS or is it GCP? The previous deployment (https://github.com/2i2c-org/infrastructure/issues/1329) seemed to have been deployed in GCP because this is where the data was. @colliand do we have information about where the data lives? Otherwise I was thinking to default to GCP, like the previous one.

**Comment by colliand** [comment]
GCP is fine. Thanks @GeorgianaElena. Proximate access to data like Pangeo will be useful.

**Comment by colliand** [comment]
Thanks @GeorgianaElena and everyone else who contributed to this on-time deployment!

**Comment by GeorgianaElena** [comment]
Then I will close this issue as the hub is now ready and let's continue the discussion on freshdesk for possible improvements requests to it.

Please feel free to reopen if you disagree.
