### ISSUE TITLE
[EVENT] OpenScapes

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#3217]
### Summary

> We have an event coming up on October 17, 2023 and are expecting ~100 people using large python instances. I'm reaching out in advance to make sure the necessary computational resources are available on the front end so that things go smoothly.  

### Event Info

- **Community Representative:** 
- **Event begin:** October 17th, 2023
  - **In your timezone:** 
- **Event end:** October 17th, 2023
  - **In your timezone:** 
- **Active times:** 
  - **In your timezone:** 
- **Number of attendees:** ~100
- [**Hub Events Calendar**](https://calendar.google.com/calendar/u/2?cid=Y19rdDg0c2g3YW5tMHNsb2NqczJzdTNqdnNvY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

### Hub info

- **Hub URL**: 
- **Hub decommisioned after event?**:  No

### Task List

**Before the event**

- [ ] Dates confirmed with the community representative and added to Hub Events Calendar.
- [ ] Quotas from the cloud provider are high-enough to handle expected usage.
- [ ] **One week before event** Hub is running.
- [ ] Confirm with Community Representative that their workflows function as expected.
  - <details>
    <summary>👉Template message to send to community representative</summary>
    
    ```
    Hey {{ COMMUNITY REPRESENTATIVE }}, the date of your event is getting close!
    
    Could you please confirm that your hub environment is ready-to-go, and matches your hub's infrastructure setup, by ensuring the following things:
    - [ ] Confirm that the "Event Info" above is correct
    - [ ] On your hub: log-in and authentication works as-expected
    - [ ] `nbgitpuller` links you intend to use resolve properly
    - [ ] Your notebooks and content run as-expected
    ```
    
    </details>  
- [ ] **1 day before event**, either a separate nodegroup is provisioned for the event or the cluster is scaled up.

**During and after event**

- [ ] Confirm event is finished.
- [ ] Nodegroup created for the hub is decommissioned / cluster is scaled down.
- [ ] Hub decommissioned (if needed).
- [ ] Debrief with community representative.
  - <details>
    <summary>👉Template debrief to send to community representative</summary>
      
     ```
     Hey {{ COMMUNITY REPRESENTATIVE }}, your event appears to be over 🎉
     
     We hope that your hub worked out well for you! We are trying to understand where we can improve our hub infrastructure and setup around events, and would love any feedback that you're willing to give. Would you mind answering the following questions? If not, just let us know and that is no problem!
  
     - Did the infrastructure behave as expected?
     - Anything that was confusing or could be improved?
     - Any extra functionality you wish you would have had?
     - Could you share a story about how you used the hub?

     - Any other feedback that you'd like to share?
     
     ```

    </details>

**Comment by damianavila** [comment]
I have assigned this one to @GeorgianaElena so we get it ready before the event and to lightly monitor it when it happens.

**Comment by GeorgianaElena** [comment]
I've checked and

- [x] the quota for number of nodes per groups is ok 450 and we will need at least 100 nodes for each large Python instance that will be used (~100 r5.4xlarge machines is expected to be started)
- [ ] requested an increase in `Running On-Demand Standard (A, C, D, H, I, M, R, T, Z) instances` quota from `1360` to `1760` to account for 16vCPus per user, where total number of users is 110.

The latter has not yet been approved, will update the issue once that's done.

**Comment by GeorgianaElena** [comment]
### Update

1. Yesterday I asked for more info from the community about their expected usage, and what did large Python instances specifically meant. This is to make sure the assumption that they are planning to use the largest resource allocation from the Python profile was correct. Also, this happened following @consideRatio's feedback about possible further allocation improvements and node packing we can make based on being confident about their intended usage.

2. Still no update from AWS about the quota increse request. Is it expected for this to take a significant amount of time?

**Comment by GeorgianaElena** [comment]
### Update 2

1.  Expected usage is 14.8 GB per person (~100 people expected)
2. The quota increase for max number of vCPUs assigned to the Running On-Demand Standard (A, C, D, H, I, M, R, T, Z) instances from 1,360 to 1,760 has not been approved yet. But, given the latest info about the intended usage to be for the 14.8 GB profile, which has a limit of 3.75 CPU, the previous quota value is more than enough.

**Comment by GeorgianaElena** [comment]
@consideRatio, given this new info, using the same rationale from https://github.com/2i2c-org/infrastructure/issues/3166#issuecomment-1755630637, I was thinking to have the `14.8GB & 3.75CPU` share be from a `r5.4xlarge

**Comment by BriannaLind** [comment]
I was expecting to be able to monitor the openscapes jupyter hub in detail, but some of what I was expecting to see in grafana looks blank...... I opened an issue [here](https://github.com/2i2c-org/infrastructure/issues/3280)

**Comment by BriannaLind** [comment]
The workshop went off without a hitch!  @GeorgianaElena Thanks very much for your help!  It was challenging to monitor individual usage without being able to see the usual variables in grafana, but other than that it was awesome.

**Comment by GeorgianaElena** [comment]
Yay! I am happy everything went smoothly @BriannaLind, congratulations 🎉 Also, thanks @consideRatio and @yuvipanda for figuring out and providing a fix for the grafana issue.

Closing this tracking issue, as the infrastructure changes were reverted thanks to @yuvipanda in https://github.com/2i2c-org/infrastructure/pull/3281 🚀
