### ISSUE TITLE
rename researchdelight.2i2c.cloud to showcase.2i2c.cloud

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#3279]
```[tasklist]
### Tasks
- [ ] Review existing documentation on renaming a hub (engineering docs? community docs?)
- [x] Update `config/**/*.yaml` files as needed, including changing name on landing page
- [x] UpdateA CNAME so that showcase.2i2c.cloud points to this hub
- [x] Set researchdelight.2i2c.cloud as a redirect to showcase.2i2c.cloud
```

**Comment by jmunroe** [comment]
@sgibson91 you are welcome to start into this task next week whenever you have time.  The overall goal is to rename researchdelight -> showcase. I don't expect this to be a 'community self-serve' and would necessarily require the participation of 2i2c engineering. So as long as the process is covered in the engineering documentation, I think that's sufficient.

If "renaming a hub" turns out to be more difficult than tearing down the existing hub and deploying a completely new one, that's another path forward as well.  In this task I want to learn what the engineering cost associated with 'renaming a hub' to determine if this is something we should be (or should not be) offering communities as a regular service.

If any step that I've listed above turns out to be 'non-trivial' please let's discuss it first before sending you down any rabbit holes.

**Comment by sgibson91** [comment]
How to set a redirect is documented here: https://infrastructure.2i2c.org/howto/manage-domains/redirects/

**Comment by sgibson91** [comment]
[Copying some questions from Slack to here for posterity]

1. Is the canonical way to log into researchdelight/showcase using GitHub? I see an old CILogon client laying around and wondering if I should clean up
2. Will the @2i2c-org/research-delight-team and @2i2c-org/research-delight-gpu-team team names be updated also?

**Comment by sgibson91** [comment]
> If "renaming a hub" turns out to be more difficult than tearing down the existing hub and deploying a completely new one, that's another path forward as well. In this task I want to learn what the engineering cost associated with 'renaming a hub' to determine if this is something we should be (or should not be) offering communities as a regular service.

So, changing the `name:` field of a hub entry in a cluster.yaml file will result in the creation of a new hub. This is because this field is linked to the helm namespace in which the hub is deployed, and I don't _believe_ that helm has the concept of renaming a namespace. The old namespace will continue to exist and will need to be manually deleted.

I think it's important to change this field because engineers run `deployer deploy $CLUSTER_NAME $HUB_NAME` from the command line a lot and having two different names may create unnecessary cognitive load. Especially since a change from `researchdelight` to `showcase` is quite drastic (in terms of characters typed, if not conceptually), though maybe not all change requests from our communities will be this drastic.

But this does mean that renaming a hub would be a destructive operation. So @jmunroe in reference to our conversation yesterday, we may want to lean towards the "put some effort into your community name from the start" end of the spectrum.

**Comment by sgibson91** [comment]
🎉  https://showcase.2i2c.cloud 🎉

**Comment by sgibson91** [comment]
While the technical aspects of this issue are completed, I'm leaving it open as I took some notes I'd like to get into the infrastructure guide
