### ISSUE TITLE
[Request deployment] New Hub: Uganda Virus Research Institute/Makerere University

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#3306]
### The GitHub handle of the community representative

pending

### Hub important dates

Waiting on additional information from the community.

### Hub Authentication Type

pending

### First Hub Administrators

- Edward Lukyamuzi, elukyamuzi2010@gmail.com
- Alfred Ssekagiri, assekagiri@gmail.com

### [GitHub Auth only] How would you like to manage your users?

None

### Hub logo image URL

pending

### Hub logo website URL

pending

### Hub user image GitHub repository

pending

### Hub user image tag and name

pending

### Extra features you would like to enable

- [ ] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

None

### (Optional) Billing and Cloud account

None

### Other relevant information to the features above

This hub will be deployed on the af.catalystproject.2i2c.cloud cluster.  I am currently waiting to get additional information from the community champions before this deployment can be scheduled.

### Tasks to deploy the hub

- [x] 1. Deploy information filled in above
- [x] 2. Engineer who will deploy the hub is assigned
- [x] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [x] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by damianavila** [comment]
@jmunroe, do you think it is possible to have some preliminary information for next week?
I would like @AIDEA775 (Alejandro) to try deploying a new hub in a pre-existing cluster and this one would be a good target if the complexity is not major.

**Comment by jmunroe** [comment]
What about #3305 since that's ready to go?

**Comment by jmunroe** [comment]
I am not sure why this community has not been responding to us over email.  In the meantime, I propose we can move it forward by taking the same approach I outlined in https://github.com/2i2c-org/infrastructure/issues/3515:

- Have both a R and Python image available
- Only have a single hardware profile (4GB / 1CPU on shared small 32GB/4CPU machine)
- Use GitHub teams for authentication with the the hub champions invited to join a GitHub org called CatalystProject-hubs
  - Edward Lukyamuzi, [elukyamuzi2010@gmail.com](mailto:elukyamuzi2010@gmail.com)
  - Alfred Ssekagiri, [assekagiri@gmail.com](mailto:assekagiri@gmail.com)
- Use the 2i2c logo, the phrase "Catalyst Project" and the name of the community as a placeholder

**Comment by damianavila** [comment]
Roger that! I have assigned @AIDEA775 to work on this in the next few days.

**Comment by AIDEA775** [comment]
@jmunroe the invitations are sent and hub was deployed without admins.

**Comment by damianavila** [comment]
Did we have any feedback from the community or do we know if the successfully login? cc @jmunroe @AIDEA775

**Comment by AIDEA775** [comment]
Hi @eddUG, this is a friendly reminder: can you log in and test the hub? It was deployed at https://uvri.af.catalystproject.2i2c.cloud/ 

Also I resend the invitation to assekagiri@gmail.com to the GitHub Team: https://github.com/orgs/CatalystProject-Hubs/teams/uvri

**Comment by AIDEA775** [comment]
I can see that edu was able to log in to the hub. I will close this issue.
