### ISSUE TITLE
Alert when Azure Fileshare is about to run out of disk space

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3320]
https://github.com/2i2c-org/infrastructure/pull/3085 adds alerts for disk storage being full to GCP clusters. We should add this for Azure as well - https://2i2c.freshdesk.com/a/tickets/1070 was just caused by this.

## Tasks

- [x] Make sure whoever is working on this has pagerduty rights to create appropriate webhooks
- [x]  Create a PagerDuty integration (https://www.pagerduty.com/docs/guides/azure-integration-guide/). This will give us a webhook URL
- [x] Use terraform to create an alert (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_metric_alert). The example there has a place for the webhook URL to slot into
- [x] Figure out what metric to actually use in the alert. https://learn.microsoft.com/en-us/azure/storage/common/storage-insights-overview (or related documentation pages) may help find the metric to use
- [x] Test that it fires (by changing the alert % to low). Look in `#pagerduty-notifications` channel - make sure it comes there
- [ ] Communicate back when done via https://2i2c.freshdesk.com/a/tickets/1410 to Amar

## Relavant info

https://github.com/2i2c-org/infrastructure/blob/main/terraform/gcp/pagerduty.tf is related code we have for GCP. The `pagerduty` related parts (via `sops`) will be the **same**, but the notification part will be different.

**Comment by yuvipanda** [comment]
We need to:

1. Create a PagerDuty integration (https://www.pagerduty.com/docs/guides/azure-integration-guide/). This will give us a webhook URL
2. Use terraform to create an alert (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_metric_alert). The example there has a place for the webhook URL to slot into
3. tada!

**Comment by yuvipanda** [comment]
This just happened again :(

**Comment by yuvipanda** [comment]
We should prioritize this soon - we have this alerting on other cloud providers, and it has meant we haven't had this issue crop up in any hubs there for a while. https://2i2c.freshdesk.com/a/tickets/1410 was the last time this happened in UToronto (earlier this week)

**Comment by sgibson91** [comment]
I will be picking this up when I have completed #3908

**Comment by sgibson91** [comment]
I believe that I have enough rights to add the itegration in PagerDuty and have done the "correct thing", but would like a double check please.

I added "Microsoft Azure" integration to our "Disk Space" service here: https://2i2c-org.pagerduty.com/service-directory/P5GF7G3/integrations

**Comment by sgibson91** [comment]
I think from [this documentation](https://learn.microsoft.com/en-gb/azure/storage/blobs/monitor-blob-storage-reference#supported-metrics-for-microsoftstoragestorageaccounts), the metric we want is `UsedCapacity` and unfortunately the units are Bytes, which means we won't be able to define a percentage threshold like we do for GCP.

**Comment by yuvipanda** [comment]
Thanks @sgibson91 for making progress on this.

> have done the "correct thing", but would like a double check please.

I don't think there's any real way for us to know if something is 'correct' or not, but I do think as you make progress you'll find out if it 'works' or not. Given team size and capacity, I suggest that's the approach we take for this task - 'does this work? ok, let us document what we did and move on. If not, debug and then if necessary, ask for help'.

**Comment by sgibson91** [comment]
> I think from [this documentation](https://learn.microsoft.com/en-gb/azure/storage/blobs/monitor-blob-storage-reference#supported-metrics-for-microsoftstoragestorageaccounts), the metric we want is `UsedCapacity` and unfortunately the units are Bytes, which means we won't be able to define a percentage threshold like we do for GCP.

I learned how to multiply numbers in terraform from [this stack overflow thread](https://stackoverflow.com/questions/51855824/multiply-variable-by-another-variable-and-then-format-it-as-a-string) which means we can use a fraction between 0 and 1 for a threshold.

**Comment by sgibson91** [comment]
I ended up needing to bump the version of the Azure terraform provider in order to not get errors from terraform plan. Specifically, the following error was a blocker:

```
│ Error: retrieving Cluster: (Managed Cluster Name "hub-cluster" / Resource Group "2i2c-utoronto-cluster"): containerservice.ManagedClustersClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'canadacentral' and API version '2022-01-02-preview' for type 'managedClusters'. The supported api-versions are '2017-08-31, 2018-03-31, 2019-02-01, 2019-04-01, 2019-06-01, 2019-08-01, 2019-10-01, 2019-11-01, 2020-01-01, 2020-02-01, 2020-03-01, 2020-04-01, 2020-06-01, 2020-07-01, 2020-09-01, 2020-11-01, 2020-12-01, 2021-02-01, 2021-03-01, 2021-05-01, 2021-07-01, 2021-08-01, 2021-09-01, 2021-10-01, 2022-01-01, 2022-02-01, 2022-03-01, 2022-04-01, 2022-06-01, 2022-07-01, 2022-07-02-preview, 2022-08-01, 2022-08-02-preview, 2022-08-03-preview, 2022-09-01, 2022-09-02-preview, 2022-10-02-preview, 2022-11-01, 2022-11-02-preview, 2023-01-01, 2023-01-02-preview, 2023-02-01, 2023-02-02-preview, 2023-03-01, 2023-03-02-preview, 2023-04-01, 2023-04-02-preview, 2023-05-01, 2023-05-02-preview, 2023-06-01, 2023-06-02-preview, 2023-07-01, 2023-07-02-preview, 2023-08-01, 2023-08-02-preview, 2023-09-01, 2023-09-02-preview, 2023-10-01, 2023-10-02-preview, 2023-11-01, 2023-11-02-preview, 2024-01-01, 2024-01-02-preview, 2024-02-01, 2024-02-02-preview, 2024-03-02-preview, 2024-04-02-preview'. The supported locations are 'australiacentral, australiacentral2, australiaeast, australiasoutheast, brazilsouth, brazilsoutheast, canadacentral, canadaeast, centralindia, centralus, eastasia, eastus, eastus2, francecentral, francesouth, germanynorth, germanywestcentral, israelcentral, italynorth, japaneast, japanwest, jioindiacentral, jioindiawest, koreacentral, koreasouth, mexicocentral, northcentralus, northeurope, norwayeast, norwaywest, polandcentral, qatarcentral, southafricanorth, southafricawest, southcentralus, southindia, southeastasia, spaincentral, swedencentral, switzerlandnorth, switzerlandwest, uaecentral, uaenorth, uksouth, ukwest, westcentralus, westeurope, westus, westus2, westus3'."
│ 
│   with azurerm_kubernetes_cluster.jupyterhub,
│   on main.tf line 82, in resource "azurerm_kubernetes_cluster" "jupyterhub":
│   82: resource "azurerm_kubernetes_cluster" "jupyterhub" {
```

However, bumping the version caused some yak-shaving. Specifically we will now have a deprecation warning for a variable.

```
│ Warning: Argument is deprecated
│ 
│   with azurerm_kubernetes_cluster.jupyterhub,
│   on main.tf line 146, in resource "azurerm_kubernetes_cluster" "jupyterhub":
│  146:     node_taints = concat([], var.node_pools["core"][0].taints)
│ 
│ This field will be removed in v4.0 of the Azure Provider since the AKS API doesn't allow arbitrary node taints on the default node pool
```

**Comment by sgibson91** [comment]
Plan output with a targeted command to avoid issue with NFS share

```
$ tf plan -var-file=projects/$CLUSTER_NAME.tfvars -out=$CLUSTER_NAME -target=azurerm_monitor_action_group.alerts -target=azurerm_monitor_metric_alert.disk_space_full_alert

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_monitor_action_group.alerts will be created
  + resource "azurerm_monitor_action_group" "alerts" {
      + enabled             = true
      + id                  = (known after apply)
      + location            = "global"
      + name                = "AlertsActionGroup"
      + resource_group_name = "2i2c-utoronto-cluster"
      + short_name          = "alertaction"

      + webhook_receiver {
          + name        = "callpagerdutyapi"
          + service_uri = "https://events.pagerduty.com/integration/5ebdc22d2399400cd0560e450b579333/enqueue"
        }
    }

  # azurerm_monitor_metric_alert.disk_space_full_alert will be created
  + resource "azurerm_monitor_metric_alert" "disk_space_full_alert" {
      + auto_mitigate            = true
      + description              = "Action will be triggered when used disk space is > 7372.8 GB."
      + enabled                  = true
      + frequency                = "PT1M"
      + id                       = (known after apply)
      + name                     = "Used disk space > 7372.8 GB on ead3521a-d994-4a44-a68d-b16e35642d5b"
      + resource_group_name      = "2i2c-utoronto-cluster"
      + scopes                   = [
          + "/subscriptions/ead3521a-d994-4a44-a68d-b16e35642d5b/resourceGroups/2i2c-utoronto-cluster/providers/Microsoft.Storage/storageAccounts/2i2cutorontohubstorage",
        ]
      + severity                 = 3
      + target_resource_location = (known after apply)
      + target_resource_type     = (known after apply)
      + window_size              = "PT5M"

      + action {
          + action_group_id = (known after apply)
        }

      + criteria {
          + aggregation            = "Average"
          + metric_name            = "UsedCapacity"
          + metric_namespace       = "Microsoft.Storage/storageAccounts"
          + operator               = "GreaterThan"
          + skip_metric_validation = false
          + threshold              = 7372800000000
        }
    }

  # azurerm_storage_account.homes will be updated in-place
  ~ resource "azurerm_storage_account" "homes" {
      ~ allow_nested_items_to_be_public   = false -> true
        id                                = "/subscriptions/ead3521a-d994-4a44-a68d-b16e35642d5b/resourceGroups/2i2c-utoronto-cluster/providers/Microsoft.Storage/storageAccounts/2i2cutorontohubstorage"
      ~ min_tls_version                   = "TLS1_0" -> "TLS1_2"
        name                              = "2i2cutorontohubstorage"
        tags                              = {}
        # (28 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 2 to add, 1 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to
│ use it as part of an error message.
╵
╷
│ Warning: Failed to decode resource from state
│ 
│ Error decoding "azurerm_container_registry.container_registry" from prior state: unsupported attribute "georeplication_locations"
╵
╷
│ Warning: Failed to decode resource from state
│ 
│ Error decoding "azurerm_kubernetes_cluster.jupyterhub" from prior state: unsupported attribute "addon_profile"
╵
╷
│ Warning: Failed to decode resource from state
│ 
│ Error decoding "azurerm_kubernetes_cluster_node_pool.user_pool[\"usere8sv5\"]" from prior state: unsupported attribute "availability_zones"
╵
```
