### ISSUE TITLE
[Request deployment] New Hub: EarthScope

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#3394]
### The GitHub handle of the community representative

@timdittmann

### Hub important dates

- **Target Start Date:** 2023-12-07
- **Required Start Date:** 2023-12-15

### Hub Authentication Type

Other (may not be possible, please specify in comments)

### First Hub Administrators

- @timdittmann
- @chad-earthscope 

### [GitHub Auth only] How would you like to manage your users?

None

### Hub logo image URL

pending

### Hub logo website URL

https://www.earthscope.org/

### Hub user image GitHub repository

pending

### Hub user image tag and name

pending

### Extra features you would like to enable

- [X] Dedicated Kubernetes cluster
- [X] Scalable Dask Cluster

### (Optional) Preferred cloud provider

AWS

### (Optional) Preferred cloud region

pending

### (Optional) Billing and Cloud account

I need help figuring out the billing and cloud accounts

### Other relevant information to the features above

This hub will be deployed with special access methods based on Auth0. In January 2024, this hub will be enriched with token passing from Auth0 to allow users to access restricted EarthScope resources. These aspects have been discussed with @yuvipanda and members of the EarthScope team. 

EarthScope will provide 2i2c's engineering team with access to the cloud infrastructure and Auth0 accounts required to set up this customized research hub. 

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [ ] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by damianavila** [comment]
This is assigned to be worked on by @AIDEA775 with support from @yuvipanda (who already have more context from previous discussions).

AFAIK, the scope of this new hub request is to deploy a daskhub in a new dedicated AWS cluster.
Ale will be doing this deployment for the first time and Yuvi is going to help him in any blockage he may have.

> EarthScope will provide 2i2c's engineering team with access to the cloud infrastructure and Auth0 accounts required to set up this customized research hub.

@colliand, can you please make sure the community representatives provide the needed AWS account details and credentials so we can start with this deployment ASAP? Thanks!

**Comment by damianavila** [comment]
@AIDEA775, any updates on this one? I think the AWS credentials were provided, am I right?

**Comment by chad-earthscope** [comment]
Not part of the requested information, but we want our hub parked at `geolab.earthscope.cloud`.  I'm not sure when that becomes important but putting it here early just in case.  We own that TLD and can configure DNS when needed.

**Comment by yuvipanda** [comment]
Thanks @chad-earthscope. Once we have it setup, we'll provide you with some targets (CNAMEs) you can point that domain to.

**Comment by timdittmann** [comment]
Regarding [this comment:](https://github.com/2i2c-org/infrastructure/issues/3394#issuecomment-1804217434)

The information pieces still missing, are:
- hub logo image url
[High res](https://drive.google.com/file/d/1RyQLUCPeQvZvDI_Ct0UDrsn7n1zYdZP-/view?usp=drive_link), [low res](https://drive.google.com/file/d/1UUStqv7PBcxiIkzECUFKIdQKKIU8mXeb/view?usp=sharing) options.  (Does this file get stored in the repo or do we need to host this somewhere more permanent?)
- hub user image github repository
Can we use standard 2i2c base image for initial deployment, while we experiment with [custom images](https://docs.2i2c.org/admin/howto/environment/hub-user-image-template-guide/) on our end?

**Comment by AIDEA775** [comment]
@timdittmann We are deploying the cluster in the _us-east-2_ zone on AWS. Is that ok?

**Comment by timdittmann** [comment]
> @timdittmann We are deploying the cluster in the _us-east-2_ zone on AWS. Is that ok?

Yes, thank you @AIDEA775

**Comment by AIDEA775** [comment]
@timdittmann, the hub was deployed, and you can access it at https://staging.earthscope.2i2c.cloud/ (staging) and https://earthscope.2i2c.cloud/ (production). Can you try it?

**Comment by timdittmann** [comment]
> @timdittmann, the hub was deployed, and you can access it at https://staging.earthscope.2i2c.cloud/ (staging) and https://earthscope.2i2c.cloud/ (production). Can you try it?

@AIDEA775 Yes, I am able to access prod with CILogin.
I see that @yuvipanda has initiated the [auth0 integration](https://github.com/2i2c-org/infrastructure/issues/3533).  This is great news.

**Comment by colliand** [comment]
Auth0 integration request was completed as of 2024-01-29.
