### ISSUE TITLE
Q4 Reduced workload goal - Nov 29 Sprint 4 tracking issue

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#3469]
Follow-up to https://github.com/2i2c-org/infrastructure/issues/3467
## I. Wrap-ups:
```[tasklist]
- [x] [Wrap up PR about event issue template update](https://github.com/2i2c-org/infrastructure/pull/3436)  with follow-ups tasks listed in the PR description
- [x] [Wrap up PR about central grafana doubled 2i2c datasource](https://github.com/2i2c-org/infrastructure/pull/3450). Now, there's a phantom "default" datasource that appears in the dashboads, but NOT in the data source list, which is confusing. Investigate what that's about.
- [ ] https://github.com/2i2c-org/infrastructure/issues/3248
```

### II. Grafana & monitoring:

1. We have two strategies documented and we still need to decide what is "the right one" and document it for the community on docs.2i2c.org website:
- https://infrastructure.2i2c.org/howto/grafana-github-auth/
- https://infrastructure.2i2c.org/sre-guide/support/grafana-account/

```[tasklist]
- [ ] https://github.com/2i2c-org/infrastructure/issues/1850
- [ ] https://github.com/2i2c-org/infrastructure/issues/3505
- [ ] https://github.com/2i2c-org/docs/issues/198
```

2. Very important maintenance work related to Grafana & prometheus atm IMO is:

```[tasklist]
- [ ] https://github.com/jupyterhub/grafana-dashboards/issues/89 (Helping Yuvi push forward on: https://github.com/jupyterhub/grafana-dashboards/pull/90)
- [ ] https://github.com/2i2c-org/infrastructure/issues/3237
- [ ] Document the steps needed to perform [Migrate all GCP hubs prometheus disks to pd-balanced from pd-standard #3119 ](https://github.com/2i2c-org/infrastructure/issues/3119) with the help of Yuvi and start doing it as this will also solve [Correctly size prometheus disks on all clusters](https://github.com/2i2c-org/infrastructure/issues/3270) and [Make sure prometheus PVs of all our clusters have deletionPolicy set to retain #2717 ](https://github.com/2i2c-org/infrastructure/issues/2717)
```
 
## III. Support process
```[tasklist]
- [x] Open an issue about creating a very simple issue template for issues that get created as part of a ticket not being solved during the first 30m time frame: https://github.com/2i2c-org/infrastructure/issues/3477
- [ ] https://github.com/2i2c-org/infrastructure/issues/3477
- [ ] Open an issue about creating an automation to add this tickets to the relevant project boards with the right properties for proper planning in a timely manner (they should now happen manually and I don't think we're very consistent about doing it) -> https://github.com/2i2c-org/infrastructure/pull/3586
