### ISSUE TITLE
Create a hub operation and support  workflow

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#355]
# Summary

In https://github.com/2i2c-org/team-compass/pull/73 we are adding some new team workflow structure so that we can better keep track of our priorities and daily tasks.

However, this workflow is focused more around "development" of new things, rather than operation and maintenance of pre-existing things. There are at least two kinds of "ongoing" things that we'll also need to do:

- Operating / fixing issues in our managed JupyterHubs
- Supporting users that have questions (potentially leading to issues to fix)

We should document how to do this in a way that:

1. Makes it clear how we should prioritize certain kinds of tasks
2. Makes it likely that important tasks will be tackled first
3. Makes it clear who is responsible for what
4. Distributes the "maintenance" things in an equitable fashion across the team

# User Stories

- As a team member I want to
	- Know when there are unexpected issues that have come up, and whether I should prioritize them over development work
	- Know when I should work on one of these issues, vs. when another team member is tackling them
	- Know I should be balancing my "maintenance / operations" and my "new development" time
- As a hub administrator I want to
	- Know that an issue I have brought up is being worked on, and where I can check its status

# Acceptance criteria

- A documented process that
	- Begins with a user contacting us about an issue
	- Results in us documenting that issue somewhere
	- This issue is integrated in our team workflow
	- It is clear who should work on it, and whether/how to prioritize it

# Important information

- [**Here's a draft proposal for this process**](https://docs.google.com/document/d/17Kj_FbtVMl32TEcfvCp18fF1SEiBjVOhCswdidUytgM/edit?usp=sharing)

# Tasks

- [x] Discuss ideas here: https://github.com/2i2c-org/pilot-hubs/discussions/356
- [x] #494
- [x] #495
- [x] https://github.com/2i2c-org/team-compass/issues/227
- [x] https://github.com/2i2c-org/team-compass/issues/167
- [x] https://github.com/2i2c-org/team-compass/issues/187
- Iterate on this process with a few hubs and collect our experiences
  - [x] https://github.com/2i2c-org/pilot-hubs/issues/595 
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/306
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/302

**Comment by choldgraf** [comment]
In a recent conversation with @yuvipanda we discussed this. Here were a few highlights from that conversation, I'll try to write this up into a google doc proposal so we can review.

- Create a new role that is responsible for supporting hub users. This includes creating new hubs, triaging questions, etc. Something like **Hub Support Steward**.
- Define a process by which support issues are collected in a single space so that we know all "active support requests" at any moment.
- Define a **rotation process** so that the "Support Steward" role rotates through team members over time, so that this work doesn't just fall on a single person.
