### ISSUE TITLE
[Request deployment] New Hub: sciencecore.opensci.2i2c.cloud

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#3667]
This hub is part of
- https://github.com/2i2c-org/meta/issues/788

Functionality requested:

- Dynamic image building -- YES via binderhub-service + fancy profile stuff as seen in imagebuilding-demo
- Authenticated users -- YES
- Persistent user storage -- YES
- dask-gateway -- NO
- magic-links -- No requirement to do something here.

### The GitHub handle of the community representative

@jmunroe

### Technical support contacts listed

- [ ] Technical contact present

### Hub important dates

- **Target Date** Feb 14, 2024 
- To be demo'd at a NASA TOPS-T meeting Feb 27-29

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

@jmunroe 

### [GitHub Auth only] How would you like to manage your users?

team membership under https://github.com/ScienceCore

### Hub logo image URL

2i2c logo

### Hub logo website URL

2i2c.org

### Hub user image tag and name

I assume we'll need a "default" image even if we support dynamic image building.

Let's deploy a jupyter-scipy image and a rocker-binder image

### Extra features you would like to enable

- [x] Dedicated Kubernetes cluster -- depends on our ability to do cloud billing (see below)
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

AWS

### (Optional) Preferred cloud region

us-west-2 

### (Optional) Billing and Cloud account

We could use the existing cluster: 2i2c-aws-us IF there is way to bill internally charges on this hub back to the HPOSS grant.

If this is not possible, this hub may need to go on its own cluster.

DECISION: dedicated cluster. 

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [ ] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by GeorgianaElena** [comment]
@jmunroe, just double-checking that this will be a `daskhub`, right?
Also, there are is a [redeem code that will to be applied](https://infrastructure.2i2c.org/sre-guide/support/credits/) on this new aws account, right?

**Comment by GeorgianaElena** [comment]
Ah, I just noticed that @consideRatio has updated the top comment with the info based on the yesterday's discussion. All clear now 🙏🏼 Thank you!
