### ISSUE TITLE
Support reading data from cloud data storage

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#372]
# Summary

Across a few issues now we have run into questions about the right ways that users should try to access remote data from their hubs. A few that come to mind:

- https://github.com/2i2c-org/pilot-hubs/issues/280
- https://github.com/2i2c-org/pilot/issues/63

We should document some basic best practices in where to store / how to access data on the major cloud providers, so that people know where to start. To scope this a bit, let's assume the storage is Object Storage.

# User Stories

- As a hub user, I want to access data that is in one of the major cloud providers (Azure/AWS/Google) that may be authenticated

# Acceptance criteria

- Given a user that wishes to access data in a cloud provider, there's a documented practice for how to set up their data and authenticate themselves to access it.

# Tasks to complete

- [ ] See what tutorials and guides other communities have written, consider linking to them
- [ ] Define the recommended best practices for accessing this data from a 2i2c hub
- [ ] Write out a draft PR for one or more cloud providers
- [ ] ...

**Comment by yuvipanda** [comment]
I think there's other more specific issues dealing with this now, and we do allow reading from various cloud datasets most of the time.
