### ISSUE TITLE
[EPIC] Billing Automation - Shared Knowledge

### ISSUE THREAD

**Issue by haroldcampbell** [2i2c-org/infrastructure#3759]
This epic reflects [Billing Automation](https://2i2c.productboard.com/feature-board/7803674-product-ideas/features/25995236/detail) ticket on Product Board.

The initial list of tasks (below) were source from conversations with @yuvipanda and @Gman0909 .

### Description

The goal of this epic is to make sure that everyone in the team has a common, *shared* understanding of our billing practices. It would also give us a shared terminology when doing more billing related work.

### Why is this important?

- This will allow us to remove a SPoF.
- This will allow us to be more effective at the time to provide billing artifacts

### Measures and definition of done

- We expect to see several documents outlining could billing-related concepts
- We exepct to see clear guidelines to create billing-related artifact (data to be shared with CS&S)

## Tasks

- [ ] **Building a shared mental model** https://github.com/2i2c-org/infrastructure/issues/3658

  - [x] #3760

  - [ ] #3761

  - [ ] https://github.com/2i2c-org/infrastructure/issues/3711

- [x] #3763

  - [x] #3725 ~~Document and review the manual process currently handled by Yuvi and Partnerships (Jim & James) to account for cloud costs every quarter.~~

  - [x] #3726 ~~Have another engineer replicate this process for at least one month, to identify gaps in this documentation~~
  - [ ] https://github.com/2i2c-org/infrastructure/issues/3767
  - [ ] https://github.com/2i2c-org/infrastructure/issues/3768

**Comment by damianavila** [comment]
FYI, I have formatted the top comment with the new Initiative format in mind.

**Comment by yuvipanda** [comment]
Closing based on https://github.com/2i2c-org/meta/issues/1028#issuecomment-2087793473 and https://github.com/2i2c-org/meta/issues/1028#issuecomment-2089063971
