### ISSUE TITLE
Build a shared mental model of how cloud costs work for JupyterHubs (not 2i2c specific) that can be shared by engineers, partnerships and our communities

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3760]
# Context

Cloud billing is a vast area with many nuances. However, because of our usage patterns, we only need to understand a small-ish subset of it. This needs to be a shared understanding, so we all have a common base to reason from.

# Tasks

- [x] Create a document outline with topics to be covered, and get feedback on this structure https://2i2c.slack.com/archives/C0206KLF76E/p1707790364795369
- [x] Fill out the document to completion
- [ ] Merge this into this repository, incorporating feedback during the PR process as needed
