### ISSUE TITLE
Build a shared mental model of the different kinds of billing we currently support for various communities, and how this ties into our infrastructure choices.

### ISSUE THREAD

**Issue by haroldcampbell** [2i2c-org/infrastructure#3761]
# Context

This is a follow-up from https://github.com/2i2c-org/infrastructure/issues/3760, focusing more specifically on the billing related choices we have made so far. This knowledge is both technical and contractual, and not available in a single place. The goal here is to produce a single document that's our best understanding of current reality.

# Tasks

- [ ] Create a document outline, providing information about the various billing models we currently offer to our communities
- [ ] Fill out the document to completion
- [ ] Merge this document into this repository, incorporating review and feedback from others

**Comment by haroldcampbell** [comment]
This is currently blocking https://github.com/2i2c-org/infrastructure/issues/3958 from being closed.

**Comment by yuvipanda** [comment]
Enough people have now done the billing work that I think it's ok to close this.
