### ISSUE TITLE
Document & Replicate the manual cloud billing process

### ISSUE THREAD

**Issue by haroldcampbell** [2i2c-org/infrastructure#3763]
# Context

We currently manually bill cloud costs at intermittent time periods. The process of doing so is not documented in a repeatable way. This is a tracking issue to do that.

# Tasks

## Dedicated Clusters

- [x] https://github.com/2i2c-org/infrastructure/issues/3725
- [x] https://github.com/2i2c-org/infrastructure/issues/3726

## Shared Clsuters

- [x] https://github.com/2i2c-org/infrastructure/issues/3768
- [x] https://github.com/2i2c-org/infrastructure/issues/3767

**Comment by yuvipanda** [comment]
Specific documentation tasks now tracked in the tasklist of https://github.com/2i2c-org/infrastructure/issues/3958
