### ISSUE TITLE
[Spike] Understand CS&S regarding their non-functional requirements

### ISSUE THREAD

**Issue by haroldcampbell** [2i2c-org/infrastructure#3764]
A spike to determine the capabilities of the CS&S API as far as fulfilling the Definition of Done.

### TASKS
- [x] Meet with CS&S to understand their security and financial requirements for billing
- [ ] Reporting back with the information to help inform the [Billing Automation - Sending the Bill](https://github.com/2i2c-org/infrastructure/issues/3765) epic

**Comment by yuvipanda** [comment]
We should meet with CS&S to answer the following questions:

- [ ] Would they be open to us sending *automated invoices* to our communities for *cloud costs*?
- [ ] Would they be open to us sending automated invoices to our communities for the *management fee*?
- [ ] What kind of financial / auditing requirements would such an automated invoice system need?
- [ ] Could we have access to the [Xero API](https://developer.xero.com/documentation/api/accounting/overview) to automatically send these?

We don't need to  commit to timelines here from them, only understand the *possibilities* so we know what our ceilings are.

**Comment by choldgraf** [comment]
I spoke today with Jess @ CS&S about this (she is [our FSP advisor](https://compass.2i2c.org/administration/css/#our-fsp-advisor)). Some quick updates:

- I told her about this issue and the fact that our team is focusing on billing automation right now.
- She said the CS&S team is keen to make improvements here as well, as invoicing generates a lot of work for them too.
- Her suggestion was to coordinate on having a meeting between relevant folks in 2i2c and in CS&S.
- She also suggested that we set up regular "retrospective" style meetings around the more complex touchpoints between 2i2c and CS&S to make sure that we continue to identify challenges and ideas for improvement.
- @haroldcampbell would you be willing to meet with Jess to start working out the next steps? I think it's a good idea to build a relationship with her either way, since she's our FSP rep. We can use that meeting to plan out "who needs to be in the room" for making progress on this issue (and then we can plan it into a sprint).

What do y'all think?

**Comment by haroldcampbell** [comment]
I'm happy to meet with Jess. Will coordinate calendar with myself and @yuvipanda.

**Comment by yuvipanda** [comment]
This meeting is going to be scheduled for later this week

**Comment by yuvipanda** [comment]
This is scheduled for tomorrow!

**Comment by yuvipanda** [comment]
Me and @haroldcampbell attended this meeting, along with Elliot from CS&S.

Report from this meeting is posted at https://github.com/2i2c-org/infrastructure/issues/3765#issuecomment-2038594554
