### ISSUE TITLE
[EPIC] Billing Automation - Sending the bill

### ISSUE THREAD

**Issue by haroldcampbell** [2i2c-org/infrastructure#3765]
This epic reflects [Billing Automation](https://2i2c.productboard.com/feature-board/7803674-product-ideas/features/25995236/detail) ticket on Product Board.

- [ ] Do a spike to determine the capabilities of the CS&S API as far as fulfilling the Definition of Done.
- [ ] Fully automate our manual invoicing process. This would be a fully automated technical system we build and run, separate from our JupyterHub infrastructure. It would need to at least:
  - [ ] Have a source of truth for what communities we serve. Covered by issue [3711](https://github.com/2i2c-org/infrastructure/issues/3711)
  - [ ] Accurately determine the cloud costs for each community
  - [ ] Automatically send them invoices in a way that CS&S finds acceptable
  - [ ] Be robustly built in a way that's maintainable, open source and compatible with right to replicate.
  - [ ] Be extensively documented, so it can be worked on by anyone in the team.
  - [ ] Be part of a product lifecycle, with continuous monitoring and improvement as needed.

**Comment by yuvipanda** [comment]
Me and @haroldcampbell met with Elliot from CS&S. There was conversation about renewal cycles and what not, but I'm going to keep this focused instead on 'sending invoices'.

# Sending invoices for our operational fees

1. This is manually sent by Elliot, but is not hard
2. CS&S takes a % of this as our FSP
3. This is going to continue to be manually done. There are process improvements to be made here, around contract renewals and stuff. But doesn't involve engineering.

Outcome: **no change**

# Sending cloud bills

1. This is manually sent by Elliot, and she doesn't mind.
2. Currently uses https://docs.google.com/spreadsheets/d/1AWVCg0D_-ATub_cVsIy5XZCwqnC6uIcgwDGYK9Q7yno/edit#gid=1349808947. In the past it's been more ad hoc
3. Here *our* (2i2c) process breaks down, and we haven't been able to consistently provide her this information so we can send this billing out.
4. We had explored using [Stripe Invoices](https://docs.stripe.com/invoicing/overview) to send out these. However, since the issue hasn't been about *sending out the invoices* but about calculating the cloud costs, we have agreed to *defer this for now*
5. Instead, we will try to recover all cloud costs in a *quarterly cadence*, and aim to get this information to elliot within *a week of the quarter ending*. The quarterly cadence is what CS&S desires, because it keeps collecting money from invoices simple
6. For a first approximation, this is going to have us update the billing automation we *do* have to fully work. And generate a new sheet every quarter that Elliot can use. It can have the same structure we currently have.
7. CS&S doesn't collect a % of this money, it's directly pass through

Outcome: **Yuvi will spec out what minimal work would need to happen here, and we should plan on finishing it up ASAP**.

# Future work with Stripe

We'd still like to work with Stripe in the future! They have a CS&S wide stripe account, but we'll probably need to make another stripe account just for 2i2c. Xero (the accounting software they use) doesn't do multitenancy, and our expectation is that stripe does not either. CS&S is very open to this. So if we want to start experimenting with stripe, we should spec that out, reach out to them (CS&S), and work together to set up a test account.

Outcome: I'll ping @Gman0909 to figure out what timeline we need for this, and who can take on this work.

**Comment by yuvipanda** [comment]
Report from this was posted at https://github.com/2i2c-org/infrastructure/issues/3765#issuecomment-2038594554

**Comment by yuvipanda** [comment]
Closing based on https://github.com/2i2c-org/meta/issues/1028#issuecomment-2087793473 and https://github.com/2i2c-org/meta/issues/1028#issuecomment-2089063971
