### ISSUE TITLE
[Request deployment] New Hub: molerhealth.af.catalystproject.2i2c.cloud

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#3771]
### The GitHub handle of the community representative

Onabajo Monsurat <onabajofunmilayo@gmail.com>  @Monsurat-Onabajo

### Technical support contacts listed

- [ ] Technical contact present

### Hub important dates

Next iteration

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

Onabajo Monsurat <onabajofunmilayo@gmail.com>  @Monsurat-Onabajo

### [GitHub Auth only] How would you like to manage your users?

Allowing members of specific GitHub team(s)

### [GitHub Teams Auth only] Profile restriction based on team membership

https://github.com/orgs/CatalystProject-Hubs/teams/molerhealth

### Hub logo image URL

https://catalystproject.cloud/_images/catalyst-icon-dark.png

### Hub logo website URL

https://catalystproject.cloud/

### Hub user image GitHub repository

Standard Catalyst Profile

### Hub user image tag and name

Standard Catalyst Profile

### Extra features you would like to enable

- [ ] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

None

### (Optional) Billing and Cloud account

None

### Other relevant information to the features above

This is for the MolerHealth as a part of the Catalyst Project on the catastproject-af cluster. Please use standard catalyst profile being developed in 
- https://github.com/2i2c-org/infrastructure/issues/3631

### Tasks to deploy the hub

- [x] 1. Deploy information filled in above
- [x] 2. Engineer who will deploy the hub is assigned
- [x] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [x] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by Monsurat-Onabajo** [comment]
Hi, I'm a bit confuse on how to go about this , my question are as follows:
1. Am I to provide the following information here or there's a specific file I need supply this information in.
2. I don't quite understand what the Hub and related questions are in this context, could you please elaborate if this is MolerHealth or 2i2c.

I would really appreciate if I get feedback as relating to how I go about these. I will also be tagging our developer @mqnifestkelvin so he can provide answers to some of the infrastructure requirements we need

**Comment by jmunroe** [comment]
Hi @Monsurat-Onabajo .  Sorry for the confusion. 

No action is required by you or MolerHealth. The GitHub issue above is a standardized way that 2i2c uses to set up a new JupyterHub.

You are listed so that when the hub is deployed, you'll be able to log in and set up as an administrator. This will allow you to add others to the hub.

This is part of the Catalyst Project. There will be more formalized training on what it means to be a 'Hub Champion' (to be scheduled).

**Comment by Monsurat-Onabajo** [comment]
> Hi @Monsurat-Onabajo . Sorry for the confusion.
> 
> No action is required by you or MolerHealth. The GitHub issue above is a standardized way that 2i2c uses to set up a new JupyterHub.
> 
> You are listed so that when the hub is deployed, you'll be able to log in and set up as an administrator. This will allow you to add others to the hub.
> 
> This is part of the Catalyst Project. There will be more formalized training on what it means to be a 'Hub Champion' (to be scheduled).

Ok, I totally understand that. Thank you for your response

**Comment by AIDEA775** [comment]
@Monsurat-Onabajo Can you confirm that you can log in to the hub? It was deployed at https://molerhealth.af.catalystproject.2i2c.cloud

Also, you can now add more users to the Github Team: https://github.com/orgs/CatalystProject-Hubs/teams/molerhealth

**Comment by Monsurat-Onabajo** [comment]
> @Monsurat-Onabajo Can you confirm that you can log in to the hub? It was deployed at https://molerhealth.af.catalystproject.2i2c.cloud
> 
> Also, you can now add more users to the Github Team: https://github.com/orgs/CatalystProject-Hubs/teams/molerhealth

Hello, I can now access the hub. Thank you very much for setting it up
