### ISSUE TITLE
[Request deployment] New Hub: Jupyter Health Hub

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#3796]
### The GitHub handle of the community representative

@fperez @colliand @yuvipanda

### Technical support contacts listed

- [ ] Technical contact present

### Hub important dates

- **Target Start Date:** 2024-03-31 (...or as soon as reasonably possible within 2i2c Engineering's sprint process)

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

- @colliand 
- @fperez 
- @maryamv
- @ryanlovett

### [GitHub Auth only] How would you like to manage your users?

Allowing members of a specific GitHub organization

### [GitHub Teams Auth only] Profile restriction based on team membership

https://github.com/jupyterhealth

### Hub logo image URL

pending

### Hub logo website URL

pending

### Hub user image GitHub repository

pending

### Hub user image tag and name

pending

### Extra features you would like to enable

- [x] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

AWS

### (Optional) Preferred cloud region

us-east-2 <---This was updated by @colliand on 2024-03-14.

### (Optional) Billing and Cloud account

None

### Other relevant information to the features above

Let's set this hub on its own billing account so that the project can track and assign cloud costs effectively. 

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [ ] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by colliand** [comment]
I suggest this be deployed as a dedicated cluster. Thanks @consideRatio.

**Comment by minrk** [comment]
Trying to answer some of these questions, to help me get up to speed on 2i2c process

> technical support contacts listed

Should this be @minrk and/or @ryanlovett ?

> hub logo image url

Don't have one yet, so start with default Jupyter logo?

>  hub logo website url

For now, https://github.com/jupyterhealth

> hub user image github repository

@colliand should we create a public repo on @jupyterhealth just for the user image? I assume we're at least going to install the TCP client package in there once we can get access to it.

> hub user image tag and name

let's start with `quay.io/jupyter/scipy-notebook:2024-03-14` while we wait for the user image repo.

> extra features you would like to enable

I don't think we need any for now. Eventually, we're going to need some customization to issue credentials as part of the pre_spawn_hook. This will likely require one package to be added to the hub image.

**Comment by surfdoc** [comment]
@colliand we are running our elastic container service for this project in us-east-2.

**Comment by colliand** [comment]
Thanks @minrk. I like all your suggestions. Getting the cluster and hub up and running seems to me to be the first target. After that, changes to the image can be brought in to support the integration with the TCP side of the project.

**Comment by yuvipanda** [comment]
I've asked folks some questions in the slack to figure out the fastest way to move this forward. I'll take actions based on responses i get there tomorrow.

**Comment by yuvipanda** [comment]
As we refine this, I've created an AWS account and granted @ryanlovett and @minrk access to the AWS account.

Next step is for me to set this issue up to get a proper hub going.

**Comment by yuvipanda** [comment]
@minrk @ryanlovett you can now test this hub out at jupyter-health.2i2c.cloud. We can switch out domains once we know where they should be. 

I don't have access to the jupyterhealth org, can someone make me an admin there so we can grant access to anyone who is a member of that org? Right now I think only the people marked as admins can login.

**Comment by ryanlovett** [comment]
Thanks @yuvipanda ! I was able to authenticate, but ryanlovett is not authorized to access that hub. (though per your comment ryanlovett is in `admin_users`)

**Comment by yuvipanda** [comment]
@ryanlovett cool, I'll have to wait for someone to make me admin on the jupyter health org.

**Comment by maryamv** [comment]
@yuvipanda your invitation to JupyterHealth org has expired. I resent the invitation and for now, added you with the Admin role as an outside organizer.

**Comment by maryamv** [comment]
Thanks @yuvipanda! I was able to authenticate and access the Jupyter-Health.2i2.cloud!

**Comment by ryanlovett** [comment]
@yuvipanda I tried again this morning and was authorized!

**Comment by yuvipanda** [comment]
@surfdoc can you tell me what AZ you're running in? I can put the nodes in the same AZ so we can avoid cross AZ traffic.

I've also set up the github oauth app permissions accordingly, so I think otherwise this is good.

**Comment by surfdoc** [comment]
@yuvipanda we are in us-east-2

**Comment by yuvipanda** [comment]
@surfdoc ah, great. our nodes are only set up in `us-east-2a` (master is in all 3 azs). So we're all good here.

I'm going to close this issue as 'done' now! Yay!

**Comment by yuvipanda** [comment]
Actually I missed a couple steps on updating airtables. I'll do that shortly.

**Comment by colliand** [comment]
With this deployment completed, can we close this issue in the JupyterHealth GitHub space? https://github.com/jupyterhealth/jupyter-health-software/issues/1

**Comment by yuvipanda** [comment]
@colliand yes i believe so. Can that repo also be made public? I think it's easier to do that earlier than latter.

**Comment by yuvipanda** [comment]
I opened https://github.com/2i2c-org/infrastructure/issues/3888 to track the last remaining part, and this issue can be closed now.
