### ISSUE TITLE
Add "Authorized to Open PRs" information to AirTable

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#3819]
We need a list of the users/hub administrators who are authorized to open PRs against the 2i2c infrastructure repo. This is similar to the already existing 'Authorized Technical Contacts' that we maintain in AirTable for submitting FreshDesk tickets.

```[tasklist]
### Tasks
- [x] Create entries in AirTable for github user names
- [x] Add github user names to Authortized Technical Contacts airtable interface
- [x] Follow up on https://2i2c.freshdesk.com/a/tickets/1371 (motivating ticket)
- [x] Communicate this information back to Engineering
```

(Issue originated on internal 2i2c slack: https://2i2c.slack.com/archives/C028WU9PFBN/p1710943211509839)

**Comment by yuvipanda** [comment]
We should also add a bunch of people for the NASA VEDA hubs (nasa-veda, ghg, esdis): `@batpad @freitagb @slesaad @wildintellect`

**Comment by jmunroe** [comment]
There now an AirTable interface available for GitHub IDs who are authorized to submit PRs against specific communities:

https://airtable.com/appbjBTRIbgRiElkr/pagIiRawilmebyHbQ

Likewise, our list of communities has a new field that lists GitHub IDs for which PRs are authorized:

https://airtable.com/appbjBTRIbgRiElkr/pagog9egWRpeLyLGW

PRs are authorized at the level of 'Community' rather than a specific hub. I am making the assumption that if someone is allowed to submit PRs for one hub in a community, it would be acceptable for them to submit PRs for any hub associated with that community. 

To add an 'Authorized PR Submitter' to a community, that individual first need to exist in our table of 'Contacts' and have the Github ID filled in.  From their either a Community Partner can be added that to contact. Or, an Authorized PR submitter can be added to the Community Partner. Either method is acceptable.

To complete this issue, this still needs to be documented in Team Compass.

**Comment by yuvipanda** [comment]
I opened https://github.com/2i2c-org/infrastructure/issues/3912 to track the documentation needed here. I don't think you need to fill out *all* the docs @jmunroe. I think next steps are for you to create a page in team-compass just documenting the airtable and work you've done, and the rest of the sections can be filled out later by engineering.

Thank you for working on this!

**Comment by jmunroe** [comment]
That works! I'll write something and place it in #3912 which will allow be to close this issue.
