### ISSUE TITLE
[EPIC] Billing Automation - Automation and data collection

### ISSUE THREAD

**Issue by Gman0909** [2i2c-org/infrastructure#3928]
This needs to be refined.

- [ ]  **Partially automate our manual invoicing process. This is still performed and validated by a human, but without any 'copy paste numbers from here to there' steps.**
  - [ ] Automate accurately determining the cloud costs for a community.
    - For communities with dedicated clusters
    - For communities on our shared clusters
  - [ ] Work with CS&S to understand how we can automate the sending of invoices. This is currently very unclear. This may involve the Xero API, but may involve something else too. Discovery is needed.
- [ ] Understand community needs for **explaining cloud costs**.
  - [ ] Work with a few pilot communities to understand what they would need in terms of understanding their cloud costs. This is currently underspecified and unclear. 
  - [ ] One possible need is for fully itemized cloud cost invoices, which can be integrated into our automatic system as needed if communities want that.

**Comment by yuvipanda** [comment]
I've downscoped this much more into https://github.com/2i2c-org/infrastructure/issues/3958

**Comment by yuvipanda** [comment]
Closing based on https://github.com/2i2c-org/meta/issues/1028#issuecomment-2087793473 and https://github.com/2i2c-org/meta/issues/1028#issuecomment-2089063971
