### ISSUE TITLE
[EPIC] k8s maintenance: get our k8s control planes to 1.28+ and node pools to at least 1.27+

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3955]
k8s 1.30 is being released tomorrow 17th April 2024, according to [our k8s upgrade policy](https://infrastructure.2i2c.org/howto/upgrade-cluster/#upgrade-policy), we should have our k8s control planes at k8s 1.28.x at least by tomorrow and node pools at k8s 1.27.x by then as well.

```[tasklist]
### Tasks
- [ ] https://github.com/2i2c-org/infrastructure/issues/4006
- [ ] https://github.com/2i2c-org/infrastructure/issues/4008
- [ ] https://github.com/2i2c-org/infrastructure/issues/4007
- [ ] https://github.com/2i2c-org/infrastructure/issues/4009
```

**Comment by haroldcampbell** [comment]
Next steps
- @consideRatio to split this card across control plane and cloud provider. Treat this as a pairing task.
- commit the control planes in the iteration planning, possibly starting with GCP.
- @yuvipanda to identify process for recurring task

**Comment by yuvipanda** [comment]
I think this is done!
