### ISSUE TITLE
[New Hub] Openscapes Workshop Hub (with dummy authenticator configured with global password)

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3984]
## Timeline information

| Type | Date |
| - | - | 
| Set-up by | May 21, 2024 |
| Event using hub running on | May 30, 2024 |
| Requested on | April 22, 2024 |

## Phase 1: Account setup (**NA**)

Not applicable, this will be an additional hub on the openscapes account.

## Phase 2: Cluster setup (**NA**)

Not applicable, this will be an additional hub on the openscapes cluster

## Phase 3 : Hub setup

There's going to be one hub.

#### Phase 3.1: Initial setup (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Name of the hub | workshop | |
| Dask gateway? | yes | |
| Splash image |  https://nasa-openscapes.github.io/images/nasa-openscapes.png |  |
| URL | https://nasa-openscapes.github.io/ |  | 
| Authentication Mechanism | shared password (aka `dummy`) | Password to be used found in https://2i2c.freshdesk.com/a/tickets/1524|
| Admin Users | NA | Because 'dummy' authentication will be used | 

#### Phase 3.2: Object storage access (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Scratch bucket enabled? |  Yes |  |
| Persistent bucket enabled? | yes |  |
| Requestor pays requests to external buckets allowed? | no | |  

#### Phase 3.3: Profile List (**READY**)

Same as openscapes prod hub
 
#### Phase 3.4: Authentication tuning (**NOT READY**)

| Question | Answer |
| - | - |
| Authentication Mechanism | shared-password |

#### Phase 3.5: Profile List finetuning (**NA**)

NA, as profile list is going to be same as openscapes prod hub.

**Comment by yuvipanda** [comment]
This was discussed during the 2i2c / Openscapes call 6 weeks ago with @jmunro, and again this monday with me.

**Comment by yuvipanda** [comment]
Before this can be considered ready to work on, we would need *2i2c* documentation on:

- [ ] How to set the shared password, with `sops` (similar to how we do for prometheus & grafana)
- [ ] How to handle support tickets where the community wants this password changed
- [ ] How to make sure the home page customizations are possible for this kind of authentication too.

**Comment by sgibson91** [comment]
@yuvipanda this also deviates from an (unwritten) policy that we tend to have a 1:1 mapping of clusters and staging hubs (2i2c GCP cluster being the exception but mostly for our demos, not serving communities). We should evolve that policy if multiple staging hubs per cluster is something we want to take on and codify it somewhere.

**Comment by BriannaLind** [comment]
@yuvipanda submitting freshdesk ticket now --- but workshop date is actually **May 30, 2024**

**Comment by yuvipanda** [comment]
@sgibson91 thanks for pointing it out. I'll create a separate issue to discuss that.

**Comment by yuvipanda** [comment]
@sgibson91 I've opened https://github.com/2i2c-org/infrastructure/issues/4018 for that. Do you believe it to be a blocker for getting this task done?

**Comment by consideRatio** [comment]
I think #4018 can't be made a blocker practically at this point in time because then we force ourselves to resolve it in short time to get this hub deployed.

I'm inclined to say go ahead for now since this is a dedicated cluster, but I think its incurring notable tech debt to not have assumptions cleary specified on what is meant with a `hubname-staging` hub in dedicated/shared clusters as commented about in #4018.

:+1: on moving ahead, but here are cavetas I'd like to raise since I worry this pattern propegates without more explicit assumptions and intent:
- This is a dedicated cluster - cost aspects are trivial in this case
- I'm not sure everyone knows this - but right now the CI/CD system won't block deploy of a `workshop` hub (or other cluster hubs) if a `workshop-staging` hub fails, so the `workshop-staging` is practically just like any other hub - its just its name that hints an intent on how its used. What is currently expected by us in engineering adding a `hubname-staging` hub or by the community isn't clear to me.

**Comment by haroldcampbell** [comment]
@sgibson91 and/or @GeorgianaElena can either of you take this task?

**Comment by yuvipanda** [comment]
I've downscoped this to not have a staging hub, so that can be prioritized and discussed in #4018 as needed. Not having a staging hub restricts us a little bit, but that's ok and I'll communicate this to the community.

**Comment by sgibson91** [comment]
> @sgibson91 and/or @GeorgianaElena can either of you take this task?

I would feel confident taking this on once the documentation outlined in https://github.com/2i2c-org/infrastructure/issues/3984#issuecomment-2073983582 exists

**Comment by GeorgianaElena** [comment]
I can take this one too. @sgibson91 want to pair on it? Not sure what pairing means for this issue yet but we can figure it out together tomorrow?

**Comment by sgibson91** [comment]
> Not sure what pairing means for this issue

Maybe it's you driving and I can take notes to fill in those documentation gaps? My calendar is open, feel free to drop something in :)

**Comment by GeorgianaElena** [comment]
@yuvipanda can you help me validate my understanding about the desired implementation of authentication for this hub?

Is it that we want to use the [DummyAuthenticator with a global password](https://github.com/jupyterhub/jupyterhub/blob/4e7936056744cdad31d608388a349207196efa56/jupyterhub/auth.py#L1122C7-L1122C25) or do we wish to use a dummy authentication mechanism like tmp authenticator + the basic auth feature documented at https://infrastructure.2i2c.org/howto/features/ephemeral/#optional-shared-systemwide-password-setup?

The existing info is a bit confusing as the title mentions dummy authenticator, but then it assumes info like splash image will not be needed as there won't be a home page, which I think it's not the case for the dummy authenticator, but for the tmp one. Also, maybe it would have been useful to have a section in the issue to link to any existing prior conversations that could provide more context maybe? (if any of course). Thank you!

**Comment by yuvipanda** [comment]
There's also a partial summarization of the historic problems with GitHub auth for this community in https://hackmd.io/tWfqVai4SDC1CbQ4mhfIbw

**Comment by yuvipanda** [comment]
@GeorgianaElena because the same password can allow anyone to log in as *any other user*. So once you know the *names* of an admin user, you can just log in as them. Since we don't have ways to have separate kinds of users with different passwords, it's best to not have admin users with dummy authenticator.

**Comment by GeorgianaElena** [comment]
Ah, right! Thank you! 🚀

**Comment by GeorgianaElena** [comment]
### Update

The hub is now up and running at https://workshop.openscapes.2i2c.cloud 🎉 I've asked @BriannaLind on freshdesk for confirmation that the hub works as expected. Once we get the confirmation I suggest closing this issue and tracking the internal documentation of this new authentication mechanism in a new issue (cc @sgibson91).

I will go ahead and create one now and add it to the board so we can plan around it accordingly.

**Comment by GeorgianaElena** [comment]
Done. Opened it at #4081 and added it to the committed queue as it's my understanding that we've committed to get it done during this sprint via this issue, right? @sgibson91, please feel free to self-assign if you agree

**Comment by yuvipanda** [comment]
The community has confirmed this works ok, so am going to close this. #4081 tracks what is left to be done.
