### ISSUE TITLE
[Decommission Hub] go-bgc

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#4120]
### Summary

This hub was never used by the community nor was a service agreement signed. The hub should be decommissioned.

There should be no user data on this hub.

### Info

- **Community Representative:** N/A (never in use by a community)
- **Link to New Hub issue:** https://github.com/2i2c-org/infrastructure/issues/2877
- **Proposed end date:**  N/A
 
#### Phase I

- [ ] ~~Confirm with Community Representative that the hub is no longer in use and it's safe to decommission~~
- [x] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
    - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration
  - [x] If no, confirm it is ok to delete all the data stored in the user home directories

#### Phase II - Hub Removal

(These steps are described in more detail in the docs at https://infrastructure.2i2c.org/en/latest/hub-deployment-guide/hubs/other-hub-ops/delete-hub.html)

- [ ] ~~Manage existing home directory data (migrate data from the hub or delete it)~~
- [ ] ~~Manage existing cloud bucket data (migrate data, or delete it)~~
- [x] Delete the hub's authentication application on GitHub or CILogon (note CILogon removal requires the hub config in place)
- [x] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.
- [x] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [x] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
  - TIP: Run `deployer use-cluster-credentials <cluster_name>` before running the above commands

####  **[NOT APPLICABLE]** Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [ ] Remove the cluster's datasource from the central Grafana with:
  - `deployer grafana central-ds remove <cluster_name>`
- [ ] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [ ] Delete the terraform workspace: `terraform workspace delete <NAME>`
- [ ] Delete the terraform values file under the `projects` folder associated with the relevant cloud provider (e.g. `terraform/gcp/projects/` for GCP)
- [ ] Remove the associated `config/clusters/<cluster_name>` directory and all its contents
- Remove the cluster from CI:
  - [ ] [`deploy-hubs.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-hubs.yaml)
  - [ ] [`deploy-grafana-dashboards.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-grafana-dashboards.yaml)
- [ ] Remove A record from Namecheap account

**Comment by sgibson91** [comment]
I used `deployer exec homes` to check the homes directory for any data, and there are only folders for Erik and and the deployment health check service. The `_shared` folder is also empty.

```
root@2i2c-aws-us-go-bgc-shell:/# ls
bin   dev  home  lib32  libx32  mnt  proc  run   srv  tmp  var
boot  etc  lib   lib64  media   opt  root  sbin  sys  usr
root@2i2c-aws-us-go-bgc-shell:/# cd home/
root@2i2c-aws-us-go-bgc-shell:/home# ls
_shared  consideratio  deployment-2dservice-2dcheck
root@2i2c-aws-us-go-bgc-shell:/home# ls _shared/
root@2i2c-aws-us-go-bgc-shell:/home# 
```

I believe this is a strong indicator that there is no data for migration before decommissioning.
