### ISSUE TITLE
[Support] Tag all 2i2c managed resources in Earthscope AWS account

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4149]
### The Freshdesk ticket link

https://2i2c.freshdesk.com/a/tickets/1460

### Ticket request type

Feature Request

### Ticket impact

🟨 Medium

### Short ticket description

For partners that provide us with their own AWS account, it would be very useful to *tag* the resources we create in them. This helps them track cost of 2i2c infrastructure separate from anything they may have. 

We should add tags just stating who this resources is owned by (`2i2c`) to everything.

### Tasks

- [x] Decide what the name of the tag should be
- [x] Tag all AWS resources managed by us in terraform
- [x] Tag all AWS nodegroups via `eksctl` (requires recreation of nodes)
- [x] Check with the community if they want us to tag their cluster as well - this requires cluster recreation. Ask about scheduling if the answer is 'yes'. Note that their `$HOME` will be retained, but prometheus data will be wiped (communicate via the linked ticket)
- [ ] If so, tag the cluster and recreate it
- [ ] Write a short document on how to do this for communities that *do* want this

### Reference 

https://docs.aws.amazon.com/tag-editor/latest/userguide/tagging.html has more information on tagging AWS resources

**Comment by yuvipanda** [comment]
I've checked with Giuliano and this is reasonable for us to do, but it's not a 'product feature' so should be prioritized as 'tech support' (which I have done)

**Comment by sgibson91** [comment]
I will be picking this up once I have finished work in #3908

**Comment by sgibson91** [comment]
I'm going to propose that the tag be the following:

```
key = managed_by
value = 2i2c
```

**Comment by sgibson91** [comment]
> Write a short document on how to do this for communities that _do_ want this

So far in #4208, I've written the code as if we're just going to add tags to everything for every new cluster we deploy going forward, and turned it off for the clusters that currently exist (except for earthscope) - this point is now making me doubt that course of action though?

**Comment by yuvipanda** [comment]
@sgibson91 ah, the way you've proposed to do that is also fine.

**Comment by sgibson91** [comment]
@yuvipanda I know we talked about the terraform tags being safe to apply to all clusters and to just go ahead and do it. With the first cluster I tried `2i2c-aws-us`, I just hit a bunch of errors about reading state and access denied etc (I did set my credentials). I don't think it's worth me spending time debugging every case of state drift for all our clusters, and why some projects still exist [here](https://2i2c.awsapps.com/start/#/?tab=accounts) and as a workspace but there's no file in the repo anymore (e.g. `bican`). So I'm gonna go ahead with my original plan to just turn this on for Earthscope and all future clusters.

**Comment by sgibson91** [comment]
Most stuff for Earthscope is now tagged. I have emailed them via Freshdesk regarding tagging the cluster and am awaiting a response.

**Comment by sgibson91** [comment]
I have merged my PR and will open another one when Alex at Earthscope gets back to me, to minimise drift from `main` branch

**Comment by sgibson91** [comment]
Alex asked for an extra 2 tags to be added to the earthscope resources for their billing procedures. They also do want the cluster tagging, so I'll aim to recreate that in my AM tomorrow as they are more westerly so should still be asleep while I do that work.

**Comment by sgibson91** [comment]
I have moved this back to Committed as there are more pressing things to work on before the end of the week, but I'll pick it back up next week for the cluster recreation downtime.

**Comment by sgibson91** [comment]
All redeployed and I tested that I could get a server on the staging hub
