### ISSUE TITLE
[Initiative] Home directory storage notifications

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4159]
# Description

## What is the Problem?

Some users are spending a large amount of time notifying and talking to users who store large amounts of data (sometimes over 600GB) in their local storage. This can cost a lot of money - a single intern accidentally storing 20TB will cost a community 6-7k  usd a month. And this can happen for many months before it's caught by our current systems.

##  "But should we not just enforce quotas?"

A "quota" system that will *enforce limits* is what is ultimately needed, and we will spec out work on that. However, in the meantime, we need a default emergency monitoring system as well that alerts hub admins that they may eventually get a big bill.

## What is the benefit of solving the problem?

Reduced anxiety and labour for community leaders.

## How will we know when the problem has been solved?

Admins will be notified if the amount of storage they are using exceeds a pre-set quota, and community leaders will be empowered to enforce said quota.

## How could we measure the impact or benefit of the solution?

Reduced instances of individuals exceeding storage allocation quotas being caught much later in time.

# How will this work?

- There is a single quota per hub for storage. Defaults to say 10GB but can be changed by hub admins, currently by emailing 2i2c support
- When any user goes over this quota, we have a system that automatically notifies admins of the hub
- The admins have to now manually reach out to end users to help them 'fix' the issue.

The goal here is to automate what we are manually doing.

# Tasks
- [ ] Provision a Grafana dashboard that lists a table of users with their disk usage, filterable for each hub
- [ ] Implement ability to email people via Grafana Alerts
- [ ] Automatically create an alert when any individual user goes over 10GB (default quota)
- [ ] Notify communities we are going to implement this, and that default 'technical contacts' will be automatically alerted now. They can change who it goes to, or opt out - but describe with warnings
- [ ] For completion of automation, allow hub admins to change this alert threshold in grafana while making sure we don't screw up their overrides.

# Definition of Done

Checklist of items that MUST be completed before this Feature can be considered complete.
- [ ] Community champions know there is an alerting system for default quotas
- [ ] Alerts go out whenever users are over quota
- [ ] We have a documented process for how to change the alerting threshold when a hub admin asks us to
