### ISSUE TITLE
[EPIC] Collect and submit billing data for Q2 (Deadline Jul 9th)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4184]
After each quarter, we need to populate billing data for CS&S to submit quarterly invoices. This epic represents collecting that data for Q2 no later than July 9th.

```[tasklist]
- [ ] https://github.com/2i2c-org/infrastructure/issues/4287
- [ ] https://github.com/2i2c-org/infrastructure/issues/4288
```

<details>
<summary>Outdated plans</summary>

After each quarter, we need to populate billing data for CS&S to submit quarterly invoices. This epic represents collecting that data for Q2 in early July no later than July 6th.

Note that data for June need to be collected no earlier than July 2nd as billing data needs a bit of time to get processed a bit first by the cloud provider. It may be that its not fully stable by July 2nd, but its likely stable enough.

## To complete early June

Yuvi has historically collected shared billing data, and most recently also Erik. To spread awareness about this before the time sensitive collection in August, we should trial collecting shared billing data for May already in early June.

```[tasklist]
- [ ] https://github.com/2i2c-org/infrastructure/issues/4185
- [ ] https://github.com/2i2c-org/infrastructure/issues/4186
```

## To complete between Jul 2-4 (EDIT: mistake, was written Aug before)

```[tasklist]
- [ ] https://github.com/2i2c-org/infrastructure/issues/4201
- [ ] https://github.com/2i2c-org/infrastructure/issues/4255
- [ ] https://github.com/2i2c-org/infrastructure/issues/4202
- [ ] https://github.com/2i2c-org/infrastructure/issues/4256
- [ ] https://github.com/2i2c-org/infrastructure/issues/4282
- [ ] https://github.com/2i2c-org/infrastructure/issues/4283
```

</details>

**Comment by consideRatio** [comment]
i saw i made a mistake here --- Q2 is april-june, so the data needs to be collected july 2nd-6th, not aug 2nd-6th.

**Comment by consideRatio** [comment]
I also saw that switching from Aug to July, July 6th is a saturday and we need to provide info to CS&S in the first week of the month - so by getting it done by July 4th we get it done by Thursday and they have at least Friday left of the week.

Ideally, we get it done July 2nd or 3rd though.

**Comment by Gman0909** [comment]
How is this impacted or related to #3958

**Comment by sgibson91** [comment]
@Gman0909 We're trying to figure out how to close that out, it has been discussed a few times at different planning meetings, but we have not reached a path to closing it yet. I don't know much else myself.

**Comment by consideRatio** [comment]
> How is this impacted by or related to https://github.com/2i2c-org/infrastructure/issues/3958

I understand the linked issue to be about process and less about handling individual quarter's billing chores, while this issue is about handling Q2s billing chores specifically (which is time sensitive!).

**Comment by Gman0909** [comment]
Well, the epic that issue belongs to is very much about making this type of time-sensitive situation a near non-event.

**Comment by consideRatio** [comment]
Yes - I linked to this and #3958 from https://github.com/2i2c-org/infrastructure/issues/4114 which is a key piece to tie things together I think.

**Comment by consideRatio** [comment]
@sgibson91 @haroldcampbell @yuvipanda based on discussions in backlog refinment meet and 1on1 with Yuvi I've now coalesced remaining open issues into just two.

The deadline is shifted to July 9th, where whats said in `#billing` is atm the source of truth for that.
