### ISSUE TITLE
Collect all Q2 billing data of all dedicated clusters AWS

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4201]
### Info

Due first week of July

### Resources

[Dedicated AWS billing instructions](https://infrastructure.2i2c.org/howto/bill/#get-a-community-dedicated-aws-accounts-s-costs)

---

```[tasklist]
### Tasks
- [x] @sgibson91 to find someone to pair with on this that has not been involved in the process yet
- [x] Define "Q2" in months (probably April to June)
- [x] Process in above linked docs is followed for a PRACTICE RUN (skip notifying CSS at the end of the docs)
```
The second part of this issue is tracked in [Collect all Q2 billing data of all dedicated clusters AWS - Part 2 #4255](https://github.com/2i2c-org/infrastructure/issues/4255)

**Comment by sgibson91** [comment]
@sgibson91 and @GeorgianaElena have scheduled a dry run of this on 25th June, and will complete on 2nd July

**Comment by sgibson91** [comment]
Our dry run got rescheduled to today and I made sure Georgiana could follow the instructions. Other than a typo in the docs, there were no issues.

Georgiana's holiday now overlaps with when we are due to send this to CS&S, so I will just complete that task. The important thing is that the knowledge share has happened and Georgiana is confident to do this in the future if required.
