### ISSUE TITLE
Collect all Q2 billing data of all dedicated clusters GCP

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4202]
### Info

Due first week of July

### Resources

[Dedicated GCP billing instructions](https://infrastructure.2i2c.org/howto/bill/#get-a-community-dedicated-gcp-projects-costs)

---

```[tasklist]
### Tasks
- [x] @sgibson91 to find someone to pair with on this that has not been involved in the process yet
- [x] Define "Q2" in months (probably April to June)
- [x] Process in above linked docs is followed for a PRACTICE RUN (no need to ping CSS at the end of the docs)
```

The second half of this work is being tracked in https://github.com/2i2c-org/infrastructure/issues/4256

**Comment by sgibson91** [comment]
@sgibson91 and @GeorgianaElena have scheduled a dry run of this on 25th June, and will complete on 2nd July

**Comment by haroldcampbell** [comment]
@sgibson91 good to close?
