### ISSUE TITLE
Coalesce Daskhub into basehub

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4242]
The outcome of the #4087 was the draft PR #4240, which has been determined to be a viable path forward. We want to finish this migration so we can  enable dask-gateway in ephemeral hub related installations more easily.
```[tasklist]
### Tasks
- [x] Remove all references to daskhub in our deployer code.
- [x] Make appropriate config changes for all existing `daskhub` installations
- [x] Document that we'll have some `daskhub` leftovers in the future, even though it's a no-op
- [x] Change documentation for setting up dask-gateway in new hub turnup
```
