### ISSUE TITLE
[Decommission Hub, meom-ige] SWOT Ocean Pangeo Team

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/infrastructure#4254]
### Summary

This hub should have been decommissioned July 2022. AirTable currently lists this hub as active. Not to be confused with the [DRAKKAR workshop](https://github.com/2i2c-org/leads/issues/189)) in Feb 2023.

**References:**
- https://2i2c.freshdesk.com/a/tickets/1726
- https://github.com/2i2c-org/infrastructure/issues/1423

### Info

- **Community Representative:** @lesommer 
- **Link to New Hub issue:** https://github.com/2i2c-org/infrastructure/issues/207 (I think it's this one – the DRAKKAR workshop hub has [already been torn down](https://github.com/2i2c-org/infrastructure/issues/2570))
- **Proposed end date:** 30 June – we have not been able to get a response from the hub champion through FreshDesk (since the contract finished in Jul 2022!), so this seems like a good enough buffer time
  - Very likely that we cannot complete Phase I below as a result. 

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
  We tried but failed - the contract has ended in 2022 though so we are moving ahead.
- [x] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
    - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration
  - [x] If no, confirm it is ok to delete all the data stored in the user home directories
    We tried but failed.

#### Phase II - Hub Removal

(These steps are described in more detail in the docs at https://infrastructure.2i2c.org/hub-deployment-guide/hubs/delete-hub/)

- [x] Manage existing home directory data (migrate data from the hub or delete it)
- [x] Manage existing cloud bucket data (migrate data, or delete it)
- [x] Delete the hub's authentication application on GitHub or CILogon (note CILogon removal requires the hub config in place)
- [x] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.
- [x] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [x] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
  - TIP: Run `deployer use-cluster-credentials <cluster_name>` before running the above commands

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [x] Remove the cluster's datasource from the central Grafana with:
  - `deployer grafana central-ds remove <cluster_name>`
- [x] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [x] Delete the terraform workspace: `terraform workspace delete <NAME>`
- [x] Delete the terraform values file under the `projects` folder associated with the relevant cloud provider (e.g. `terraform/gcp/projects/` for GCP)
- [x] Remove the associated `config/clusters/<cluster_name>` directory and all its contents
- Remove the cluster from CI:
  - [x] [`deploy-hubs.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-hubs.yaml)
  - [x] [`deploy-grafana-dashboards.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-grafana-dashboards.yaml)
- [x] Remove A record from Namecheap account

**Comment by AIDEA775** [comment]
If I understand correctly, we will decommission the staging and prod hub and the cluster too, right?

I have this ERROR when I try to delete homes:
```
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=403, message=This API method requires billing to be enabled. Please enable billing on project #meom-ige-cnrs by visiting https://console.developers.google.com/billing/enable?project=meom-ige-cnrs then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry.
[...]
CalledProcessError: Command '['gcloud', 'container', 'clusters', '--zone=us-central1-b', '--project=meom-ige-cnrs', 'get-credentials', 'meom-ige-cluster']' returned non-zero exit status 
1.
```

When I enter the GCP console, I see this:

![Image](https://github.com/2i2c-org/infrastructure/assets/12158718/ddf1b946-382c-4897-b4c5-656841560a16)

![Image](https://github.com/2i2c-org/infrastructure/assets/12158718/e950589a-21ec-40bc-9242-44f1bae38f61)

It's okay if I select any option? I can't run `deployer use-cluster-credentials $CLUSTER_NAME` either.

**Comment by consideRatio** [comment]
@AIDEA775 reading the support ticket, it seems indeed that staging / prod representing "SWOT Ocean Pangeo Team ([staging|prod])" should be deleted, and that everything should go - especially considering now that the contract ended 2022.

I think the course of action is to attach it to our billing account and then proceed to tear down as you plan, and its OK to do so.

**Comment by consideRatio** [comment]
Note that deleting home directory data can be done as part of deleting all cloud infra provisioned as everything is to go, so you can ignore that for the step of deleting things for any individual hub.

**Comment by consideRatio** [comment]
@AIDEA775 I checked the checkboxes that I perceive to be irrelevant if we also will do phase 3 that deletes everything - not just an individual hub. In "Phase 2" there is only one left about `Delete the hub's authentication application on GitHub or CILogon (note CILogon removal requires the hub config in place)`

**Comment by AIDEA775** [comment]
Okey, now when I run `deployer cilogon-client delete --client-id cilogon:/client_id/... meom-ige staging` I got:

`CILogon records are different than the client app stored in the configuration file. Consider updating the file.`

**Comment by consideRatio** [comment]
> Okey, now when I run `deployer cilogon-client delete --client-id cilogon:/client_id/... meom-ige staging` I got:
> 
> `CILogon records are different than the client app stored in the configuration file. Consider updating the file.`

I have no knowledge on this :/ i think it could be ok to proceed, we may end up with a remnant thing, but it could be acceptable i think

**Comment by sgibson91** [comment]
@AIDEA775 You could also decrypt the secrets file for the staging hub, that will contain the Client ID too. Try providing that to the command and see if that gives you a different output?

**Comment by AIDEA775** [comment]
Oh! Yes! In this commit https://github.com/consideRatio/pilot-hubs/commit/ee87fc7ff8322c9a27ab6e4302d7997ddd876958 the auth was migrated to GitHubOAuthenticator without removing the CILogon client. Rolling back to the old secrets did the trick.
