### ISSUE TITLE
[Decommission Hub] [Deadline: 31 Aug 2024] Linked Earth

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4270]
### Summary

https://github.com/2i2c-org/leads/issues/318 has more info

### Info

- **Community Representative:** @khider
- **Link to New Hub issue:** https://github.com/2i2c-org/infrastructure/issues/1418
- **Date users will have removed data by:** Aug 25 2024
- **Proposed end date:** Aug 31 2024

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [ ] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
    - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration
  - [x] If no, confirm it is ok to delete all the data stored in the user home directories

#### Phase II - Hub Removal

(These steps are described in more detail in the docs at https://infrastructure.2i2c.org/hub-deployment-guide/hubs/delete-hub/)

- [x] Manage existing home directory data (migrate data from the hub or delete it)
- [ ] Manage existing cloud bucket data (migrate data, or delete it)
- [x] Delete the hub's authentication application on GitHub or CILogon (note CILogon removal requires the hub config in place)
- [x] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.
- [ ] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [x] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
  - TIP: Run `deployer use-cluster-credentials <cluster_name>` before running the above commands

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [x] Remove the cluster's datasource from the central Grafana with:
  - `deployer grafana central-ds remove <cluster_name>`
- [x] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [x] Delete the terraform workspace: `terraform workspace delete <NAME>`
- [x] Delete the terraform values file under the `projects` folder associated with the relevant cloud provider (e.g. `terraform/gcp/projects/` for GCP)
- [x] Remove the associated `config/clusters/<cluster_name>` directory and all its contents
- Remove the cluster from CI:
  - [ ] [`deploy-hubs.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-hubs.yaml)
  - [ ] [`deploy-grafana-dashboards.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-grafana-dashboards.yaml)
- [x] Remove A record from Namecheap account

**Comment by jnywong** [comment]
The community representative has been in touch via FreshDesk and I have asked them to confirm whether any data needs to be migrated before decommissioning https://2i2c.freshdesk.com/a/tickets/2014

**Comment by khider** [comment]
I'll email the Hub users and tell them to remove all their data by August 25th. Would that give enough time for everything else?

**Comment by jnywong** [comment]
That should be fine, we will assume we can decommission the hub after Aug 25. Thank you for your response @khider

**Comment by sgibson91** [comment]
I have updated the top comment to reflect until when the users can have access to retrieve their data and that we won't be saving/migrating this data after that date when we decommission.

**Comment by khider** [comment]
Everything should be out. Also how do I stop cloud billing for the account?

**Comment by sgibson91** [comment]
@khider This may be useful for you https://cloud.google.com/billing/docs/how-to/close-or-reopen-billing-account

**Comment by khider** [comment]
Thank you!
