### ISSUE TITLE
[EPIC] Collect analytics information from all our binderhub ui installations

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4365]
To be collectively refined (EDIT: Done!) by me and @consideRatio after the outcome of https://github.com/2i2c-org/infrastructure/issues/4309

## Refined text

The goal with this work is ensure an ability in the future to internally produce reports that can summarize launch events over time from any of our binderhub-ui hubs.

To accomplish this, the plan is to configure all existing and future binderhub-ui based hubs to submit launch events into a centralized Google service and retained for at least a year there.

```[tasklist]
### Tasks
- [ ] https://github.com/2i2c-org/binderhub-service/issues/121
- [ ] https://github.com/2i2c-org/binderhub-service/issues/123
- [ ] https://github.com/2i2c-org/infrastructure/issues/4406
- [ ] https://github.com/2i2c-org/infrastructure/issues/4407
- [ ] https://github.com/2i2c-org/infrastructure/issues/4408
```

**Comment by consideRatio** [comment]
Draft refinment notes, to be refined a bit further by Erik before iteration planning meeting Jul 10th.

GOAL:
- internally produce reports for use when asked, so quick collection is required

task 1
  - collect to stackdriver, within a dedicated GCP project within the 2i2c.org GCP organization
  - using the cloud webconsole, not using terraform
  - project, creds, enabling stackdriver api etc

task 2
  - update binderhub-ui hub's config to have an event sink to submit information to the centralized stackdriver
  - provide credentials for binderhub-ui hub's to submit data like this, mimicing how curvenote/ovh does it in mybidner.org-deploy
  - confirm data is being collected

task 3
  - document that this needs to be done for all binderhub-ui hubs

**Comment by consideRatio** [comment]
I identified more complexity @yuvipanda, so refining this properly takes a bit of time for me. The complexity was that:
- we need google-cloud-logging in the binderhub-service image,
- and that providing credentials the mybinder.org way style is done by extraVolume and extraVolumeMounts (not available in binderhub-service),
- and that the k8s Secret to mount was not creatable via either binderhub-service chart or basehub chart

Adding google-cloud-logging is simple, but the other parts led me to think. We could go for adding extraVolume and adding the creation of a k8s Secret in basehub with misc info to mount in binderhub-service - but - since we anyhow add google-cloud-logging we can reasonably also setup chart config to consume google credentials in binderhub-service as well.

I think adding this to binderhub-service is the right call, so I'm now refining things towards that.

**Comment by consideRatio** [comment]
Refinement complete!

**Comment by consideRatio** [comment]
![image](https://github.com/user-attachments/assets/87668a93-8b40-4589-82b4-fc9f344601f6)

Success for all five binderhub-ui enabled hubs we have running!

**Comment by colliand** [comment]
This is so cool! I am intrigued to build some kind of aggregator to identify which repos are launched most often.
