### ISSUE TITLE
[Platform Initiative] Setup a system for automated GCP filestore backups

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4391]
Part of https://github.com/2i2c-org/infrastructure/issues/4390

## The Problem 

Unlike AWS and Azure, GCP doesn't have a way to automatically schedule backups of Filestore. Google's own [suggested solution](https://cloud.google.com/filestore/docs/scheduling-backups) is pretty halfbaked, and seems to be focused on 'how many GCP specific features can we throw together?'. The python code [they provide](https://cloud.google.com/filestore/docs/scheduling-backups#create-backup-function) to do backups is particularly bad, with no error handling nor retention policies.

## Scope

Filestore has been the least nice of all managed home directory systems. My suspicion is that GCP is aware of this massive missing piece, and hopefully within a few years we will have an automated solution. So the goal here is to focus on doing the *least possible* we can to make sure we have *some* backups we can trust.

```[tasklist]
### Tasks
- [ ] https://github.com/2i2c-org/infrastructure/issues/4393
- [ ] https://github.com/2i2c-org/infrastructure/issues/4394
- [ ] https://github.com/2i2c-org/infrastructure/issues/4395
- [ ] https://github.com/2i2c-org/infrastructure/issues/4396
- [ ] https://github.com/2i2c-org/infrastructure/issues/4397
- [ ] https://github.com/2i2c-org/infrastructure/issues/4449
- [ ] https://github.com/2i2c-org/infrastructure/issues/4536
- [ ] https://github.com/2i2c-org/infrastructure/issues/4611
- [ ] https://github.com/2i2c-org/infrastructure/issues/4683
- [ ] https://github.com/2i2c-org/infrastructure/issues/4664
- [ ] https://github.com/2i2c-org/infrastructure/issues/5462
```

### Definition of Done

- [x] It has been added to our product menu: https://docs.google.com/forms/d/1Gx3v-KaruL6K9VanuwatKEr3qOLJi8ezrcsvGDtZDEQ/edit and https://docs.google.com/spreadsheets/d/1qy_ozom5QBSiDDedzmxHUsBWlEot44gl3qPWfvMYiEA/edit?usp=sharing

**Comment by sgibson91** [comment]
Yes. I feel like there was an extra "communicate to communities" step at one point that seems to have disappeared from the task list?

**Comment by sgibson91** [comment]
Both #4683 and #5462 have a Definition of Done so this is ready to be brought on deck next sprint

**Comment by sgibson91** [comment]
Another one done!
