### ISSUE TITLE
Set SCRATCH_BUCKET env on dask worker pods.

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#442]
# Summary

When dask-gateway is used to create a dask worker, we don't pass set the SCRATCH_BUCKET environment variable which is probably very relevant also to have set on worker pods.

# User Stories

- I want to initialize/finalize my dask worker work by downloading/uploading data from/to a scratch bucket.

# Acceptance criteria

- SCRATCH_BUCKET and PANGEO_BUCKET environment variables (they have the same value) are set on worker pods also.

# Tasks to complete

- [x] Figure out a way to set the SCRATCH_BUCKET environment variable.
- [x] Do it for JMTE
- [ ] Do it for 2i2c-org/infrastructure (#855)

**Comment by consideRatio** [comment]
We have configuration like this for our singleuser environment. I was hoping that we can influence DaskGateway to take a default value in its configuration of the environment like we have done for image. But well... image is a string and environment is a dict/mapping so I think that made this attempt fail.

```yaml
      extraEnv:
        # The default worker image matches the singleuser image.
        DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE: '{JUPYTER_IMAGE_SPEC}'
        DASK_GATEWAY__CLUSTER__OPTIONS__ENVIRONMENT: 'SCRATCH_BUCKET={SCRATCH_BUCKET}'
        DASK_DISTRIBUTED__DASHBOARD_LINK: '/user/{JUPYTERHUB_USER}/proxy/{port}/status'
        DASK_LABEXTENSION__FACTORY__MODULE: 'dask_gateway'
        DASK_LABEXTENSION__FACTORY__CLASS: 'GatewayCluster'
```

**Comment by consideRatio** [comment]
### References
- [Dask general documentation about its configuration system](https://docs.dask.org/en/latest/configuration.html)
  - `DASK_` prefixed environment variables are loaded into config.
    - `ast.literal_eval` is used to evaluate the environment variable value, so strings can become Python dictionaries if they want.
  - [`dask.config.expand_environment_variables`](https://github.com/dask/dask/blob/b4b0142d0f6ae89af87f6a1e04f55de0d5029a7c/dask/config.py#L515) expands nested values also, but turns out it is never invoked.
    - [`DASK_INTERNAL_INHERIT_CONFIG`](https://github.com/dask/dask/blob/b4b0142d0f6ae89af87f6a1e04f55de0d5029a7c/dask/config.py#L170) was a side track I tried, but it also didn't invoke variable expansion.
- Dask Gateway also have variable expansion (`{MY_ENV}` syntax) via [`format_template`](https://github.com/dask/dask-gateway/blob/c81c71fa6e1e1f2257e43261e7965849f2e6cb7a/dask-gateway/dask_gateway/client.py#L491-L493).
  - `format_template` doesn't expand nested values like we have for our environment dictionary we want to set.
- Kubernetes can expand as well!
  `DASK_GATEWAY__CLUSTER__OPTIONS__ENVIRONMENT: '{"SCRATCH_BUCKET": "$(SCRATCH_BUCKET)"}'

**Comment by yuvipanda** [comment]
Thanks for digging into this, @consideRatio. If the pangeo images set PANGEO_SCRATCH in their entrypoint, rather than via dask gateway, does this work?

**Comment by consideRatio** [comment]
Set it and point to juoyterhub_username?

I dislike the idea of onr more workaround now, kubespawner should order envs to prefer ending up with expanded env vars since we use a dict to set them rather than a list.

This is not the first time i run into this, and it costed me plenty of time both times. Other users will also run into this.

**Comment by yuvipanda** [comment]
Yeah, this variable expansion will continue to be a thing we'll have to deal with.

**Comment by yuvipanda** [comment]
For reference, https://github.com/2i2c-org/pilot-hubs/blob/76c15bf6496071e32b7c3da60be936e772047af6/hub-templates/basehub/values.yaml#L304 is how SCRATCH_BUCKET is set on the notebook pods when it's enabled via the config-connector

**Comment by consideRatio** [comment]
With JupyterHub 1.1.3 and this issue resolved in KubeSpawner, this is now resolved for the JMTE hub.

![image](https://user-images.githubusercontent.com/3837114/143474297-90be91e0-3b73-49a1-807f-a5ffd04525cc.png)

This is the logic used that works for us now.

```yaml
      extraEnv:
        # About DASK_ prefixed variables we set:
        #
        # 1. k8s native variable expansion is applied with $(MY_ENV) syntax. The
        #    order variables are defined matters though and we are under the
        #    mercy of how KubeSpawner renders our passed dictionaries.
        #
        # 2. Dask loads local YAML config.
        #
        # 3. Dask loads environment variables prefixed DASK_.
        #    - DASK_ is stripped
        #    - Capitalization is ignored
        #    - Double underscore means a nested configuration
        #    - `ast.literal_eval` is used to parse values
        #
        # 4. dask-gateway and dask-distributed looks at its config and expands
        #    expressions in {} again, sometimes only with the environment
        #    variables as context but sometimes also with additional variables.
        #
        # References:
        # - K8s expansion:     https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/
        # - KubeSpawner issue: https://github.com/jupyterhub/kubespawner/issues/491
        # - Dask config:       https://docs.dask.org/en/latest/configuration.html
        # - Exploration issue: https://github.com/2i2c-org/pilot-hubs/issues/442
        #
        DASK_GATEWAY__CLUSTER__OPTIONS__IMAGE: '{JUPYTER_IMAGE_SPEC}'
        DASK_GATEWAY__CLUSTER__OPTIONS__ENVIRONMENT: '{"SCRATCH_BUCKET": "$(SCRATCH_BUCKET)"}'
        DASK_DISTRIBUTED__DASHBOARD_LINK: '/user/{JUPYTERHUB_USER}/proxy/{port}/status'
        DASK_LABEXTENSION__FACTORY__MODULE: 'dask_gateway'
        DASK_LABEXTENSION__FACTORY__CLASS: 'GatewayCluster'
```

**Comment by damianavila** [comment]
Do you want to do something else here, @consideRatio? Or we should just close it?

**Comment by consideRatio** [comment]
I figure I'll upstream the relevant parts it to all hubs, creating a PR now.
