### ISSUE TITLE
[Sub-Epic] Add an Athena datasource to openscapes' grafana instance

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4546]
Cost data for openscapes is being collected into its AWS accounts Athena instance. This is an epic to overview tasks adding an athena datasource to openscapes' grafana instance at https://grafana.openscapes.2i2c.cloud/.

```[tasklist]
### Tasks
- [ ] https://github.com/2i2c-org/infrastructure/issues/4547
- [ ] https://github.com/2i2c-org/infrastructure/issues/4548
- [ ] https://github.com/2i2c-org/infrastructure/issues/4549
- [ ] https://github.com/2i2c-org/infrastructure/issues/4550
```

**Comment by yuvipanda** [comment]
I believe this was completed
