### ISSUE TITLE
[Decommission Hub] tufts.2i2c.cloud

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#4580]
### Summary

Service agreement not renewed. See https://2i2c.freshdesk.com/a/tickets/1985 for context.

### Info

- **Community Representative:** 
- **Link to New Hub issue:** https://github.com/2i2c-org/infrastructure/issues/3470
- **Proposed end date:** 2024-08-06

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [x] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
    - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration
  - [x] If no, confirm it is ok to delete all the data stored in the user home directories (**Email confirmation received 2024-08-06**)

#### Phase II - Hub Removal

(These steps are described in more detail in the docs at https://infrastructure.2i2c.org/hub-deployment-guide/hubs/delete-hub/)

- [x] Manage existing home directory data (migrate data from the hub or delete it)
- [ ] Manage existing cloud bucket data (migrate data, or delete it)
- [x] Delete the hub's authentication application on GitHub or CILogon (note CILogon removal requires the hub config in place)
- [x] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.
- [x] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [ ] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
  - TIP: Run `deployer use-cluster-credentials <cluster_name>` before running the above commands

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [ ] Remove the cluster's datasource from the central Grafana with:
  - `deployer grafana central-ds remove <cluster_name>`
- [ ] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [ ] Delete the terraform workspace: `terraform workspace delete <NAME>`
- [ ] Delete the terraform values file under the `projects` folder associated with the relevant cloud provider (e.g. `terraform/gcp/projects/` for GCP)
- [ ] Remove the associated `config/clusters/<cluster_name>` directory and all its contents
- Remove the cluster from CI:
  - [ ] [`deploy-hubs.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-hubs.yaml)
  - [ ] [`deploy-grafana-dashboards.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-grafana-dashboards.yaml)
- [ ] Remove A record from Namecheap account

**Comment by colliand** [comment]
Thanks for the fast work creating this decommission request @jmunroe! 

Email trail to track the confirmation that it is ok to delete...

-------------

Confirmed!

---------------------------------

David Grogan
Senior Solutions Specialist
Tufts Technology Services – Educational Technology Services
617-627-2859
 

From: James Colliander <[colliand@2i2c.org](mailto:colliand@2i2c.org)>
Date: Tuesday, August 6, 2024 at 1:08 PM
To: Grogan, David <[David.Grogan@tufts.edu](mailto:David.Grogan@tufts.edu)>
Cc: 2i2c <[partnerships@2i2c.org](mailto:partnerships@2i2c.org)>, Fsp <[fsp@codeforsociety.org](mailto:fsp@codeforsociety.org)>, James Munroe <[jmunroe@2i2c.org](mailto:jmunroe@2i2c.org)>
Subject: Re: [External] Re: Possibility of extending contract to end of August?

...and a follow-up. Can you confirm whether we can shut down the hub and permanently delete all data, including data in user's home directories?

Best,

J.

On Tue, 6 Aug 2024 at 10:06, James Colliander <[colliand@2i2c.org](mailto:colliand@2i2c.org)> wrote:

    Thanks David. I am disappointed to learn that Tufts does not plan to renew service with 2i2c.

    Yes, I will be very interested to learn more about the outcomes of the pilot. Thanks in advance for sharing this information with us.

    Best regards,
    Jim Colliander

    On Tue, 6 Aug 2024 at 10:01, Grogan, David <[David.Grogan@tufts.edu](mailto:David.Grogan@tufts.edu)> wrote:

        Hi Jim,
        Apologies that this didn’t get followed up on sooner. We didn’t use 2i2c beyond the original contract and as of now have no plans to re-up going forward.

        I’ll follow up with our users to discuss a presentation of their findings and outcomes to share with you.    

        Best wishes,     

        David

         

        ---------------------------------

        David Grogan

        Senior Solutions Specialist

        Tufts Technology Services – Educational Technology Services

        617-627-2859

**Comment by sgibson91** [comment]
Phase 3 not required as Tufts is on a shared cluster
