### ISSUE TITLE
Upgrade jupyterhub-fancy-profiles version on sciencecore

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4635]
### Context

Following on from #4522 and #4585, we want to upgrade jupyterhub-fancy-profiles in the last hub we have it running: sciencecore.

### Task list

```[tasklist]
- [ ] Config changes in #4522 and/or #4585 are applied to the sciencecore hub
```

### Definition of Done

- [x] jupyterhub-fancy-profiles on sciencecore has a new version
- [x] dynamic image building, unlisted choice, and selecting an existing image all work

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed

**Comment by yuvipanda** [comment]
This should be blocked on #4689

**Comment by sgibson91** [comment]
#4689 has been resolved
