### ISSUE TITLE
[GCP] Fix the deployer command that generates the dedicated clusters costs

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#4636]
### Context

While working on https://github.com/2i2c-org/infrastructure/issues/4586, running the command on GCP raised the following error:

```bash
ValueError: Usecols do not match columns, columns expected but not found: ['Month']
```

This is because when computing the costs for a single month, grouping by "Month > Project" is not available, and grouping just by "Project" generates a csv that has a different format that the one expected by the command.

### Task list

```[tasklist]
- [ ] Update the https://github.com/2i2c-org/infrastructure/blob/main/deployer/commands/transform/cost_table.py#L118 command so that it doesn't assume that the `Month` column always exists
- [ ] Use the `Month` column when multiple months and possibly the tile of the table when that's not available
```

### Definition of Done

- [x] Running `deployer transform cost-table gcp` on a one Month report works

### Pre-defined Definition of Done

- [x] All the tasks have been completed
- [x] It has been tested to work and to not break any existing functionality
- [x] Documentation was added so other engineers can implement this in the future if needed
