### ISSUE TITLE
[EPIC] [DevelopmentSeed partnership] Integrate jupyterhub-home-nfs helm chart into 2i2c infrastructure

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4647]
This issue is being refined by @sgibson91 

### Original issue body

@sunu is working on https://github.com/NASA-IMPACT/veda-jupyterhub/issues/41, where he'll create a helm chart named `jupyterhub-home-nfs` (or something like that) to provide home directories with per-user quotas on JupyterHub.

This issue tracks @sgibson91 working with @sunu, @batpad and me in helping integrate this into our infrastructure repository and practices. We will meet soon to figure out what next steps are, and who is responsible for what.

### Context

A new helm chart is being developed by the devseed team which will provide home directories with per-user quotas on JupyterHub. This issue is tracking the tasks to complete so in order to integrate that helm chart into our infrastructure for reuse.

### Task List
```[tasklist]
- [ ] https://github.com/2i2c-org/infrastructure/issues/4724
- [ ] https://github.com/2i2c-org/infrastructure/issues/4725
- [ ] https://github.com/2i2c-org/infrastructure/issues/4726
- [ ] https://github.com/2i2c-org/infrastructure/issues/4735
- [ ] https://github.com/2i2c-org/infrastructure/issues/4794
- [ ] https://github.com/2i2c-org/infrastructure/issues/4728
- [ ] https://github.com/2i2c-org/infrastructure/issues/4729
- [ ] https://github.com/2i2c-org/infrastructure/issues/4730
```

TBD: Who is responsible for executing each task? Division of labour between 2i2c and devseed. UPDATE: Decided https://github.com/2i2c-org/infrastructure/issues/4647#issuecomment-2325761094

## Definition of Done

- [x] A helm chart enabling home directories with per-user storage quotas for JupyterHub exists
- [x] The staging veda hub has been migrated to use this new chart
- [x] There's documentation on how this can be enabled for other clusters in the 2i2c infrastructure repository

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed

**Comment by sgibson91** [comment]
In a meeting with Tarashish on Friday, it was agreed that he would be responsible for completing the technical work and I would be available for mentoring/answering questions/generally helping with the integration into the 2i2c/infrastructure repo.

**Comment by sgibson91** [comment]
Hey @sunu 👋🏻  I have broken up this epic into smaller task issues and tried to refine them. Can you take a look and let me know if anything's unclear? We should also try and set some deadlines for each of these tasks such that this whole epic can be wrapped up by Sep 20, could you let me know some estimates based on where you currently are with the work please?

**Comment by sunu** [comment]
Hi @sgibson91! Thanks so much for breaking it down down into smaller tasks!

I'm aiming to finish the first three tasks this week. Let's plan to get on a brief call early next week to discuss the data migration process. We can aim to get the data migrated and switch veda staging hub over to the in-cluster NFS server next week. We can keep the following week as buffer and use it to document the whole process. Does that sound reasonable to you?

**Comment by sgibson91** [comment]
Thank you for setting up the meeting, and I've added rough due dates to each of the tasks. I shall also get you write access to the repo so you can merge yourself. Here are our review and merge guidelines for your reference but I am happy to be pinged on anything you'd like to chat about: https://infrastructure.2i2c.org/contributing/code-review/

**Comment by sgibson91** [comment]
Done! 🎉

**Comment by yuvipanda** [comment]
@Gman0909 I think we should wait until at least https://github.com/2i2c-org/infrastructure/issues/4835 is done before closing the PB issue.
