### ISSUE TITLE
Confirm if there is any data to migrate for #4270 (Decomission Linked Earth)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4650]
We need to refine https://github.com/2i2c-org/infrastructure/issues/4270 so that we can go ahead with decomissioning. The deletion of data wasn't confirmed - this needs to be confirmed.

```[tasklist]
### Tasks
- [ ] Reach out to the community champion (as listed in relevant airtable) via freshdesk and ask if data can be deleted or not
```

### Definition of Done

- [ ] We know if data can be deleted or not from the Linked Earth hub
- [x] This information has been added to #4270

**Comment by sgibson91** [comment]
Users were told to remove their data from the hub by August 25th, hence We are not migrating the data. https://github.com/2i2c-org/infrastructure/issues/4270#issuecomment-2286667774
