### ISSUE TITLE
[EPIC] Separate out gcpFilestoreBackups from 2i2c support chart into it's own helm chart

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4664]
### Context

In https://github.com/2i2c-org/infrastructure/issues/4391, we set up a system to automatically create and clear out backups of GCP Filestore instances. This involved a Python script and a Docker container to run it, and was deployed as an opt-in section of the support chart.

This issue tracks separating that feature out into it's own helm chart.

### Task list

```[tasklist]
- [ ] https://github.com/2i2c-org/infrastructure/issues/4701
- [ ] https://github.com/2i2c-org/infrastructure/issues/4702
- [ ] https://github.com/2i2c-org/infrastructure/issues/4703
- [ ] https://github.com/2i2c-org/infrastructure/issues/4705
- [ ] https://github.com/2i2c-org/infrastructure/issues/4706
```

### Definition of Done

- A helm chart for GCP filestore backups exists and is automated with chartpress
- The support chart is configured to use the new chart as an opt-in dependency
- The 2i2c cluster is updated to make use of the new chart

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed

**Comment by yuvipanda** [comment]
I've prioritized #4683 above this one. Completing both should let us complete #4391

**Comment by yuvipanda** [comment]
To be refined and split up by @sgibson91. Once you split this up into smaller tasks, move them into the Refined column, remove this from 'up next' and unassign yourself.

**Comment by sgibson91** [comment]
Done!

**Comment by yuvipanda** [comment]
@sgibson91 is this done now?

**Comment by sgibson91** [comment]
Yes! 🎉
