### ISSUE TITLE
[EPIC] Understanding and observing the types of unplanned work engineering does

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4718]
### Context

In order to reduce unplanned work in the team, we first need to understand what unplanned work the team is performing and how it arises. To achieve this understanding we need to define what is unplanned work and create a process to surface it. This epic tracks those tasks.

The need for this epic was raised during a retrospective meeting.

### Task list

```[tasklist]
- [ ] Write up a definition of unplanned work and add it to the team compass
- [ ] Draft a policy to follow when unplanned work arises so that it is tracked within our overarching processes
- [ ] Draft a process for observing and resolving unplanned work within our existing ceremonies
```

### Definition of Done

- Documentation for the above items exists in the Engineering section of the Team Compass

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed
