### ISSUE TITLE
[devseed] Support activities to deploy jupyter-home-nfs to VEDA staging

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4795]
This work tracks supporting development work towards https://github.com/2i2c-org/infrastructure/issues/4647 Specifically, this will involve merging and deploying things where Tarashish does not have access to the infrastructure, e.g., within the AWS account.

### Tasks
```[tasklist]
- [x] Verify that `deployer exec homes` can optionally mount EBS volumes https://github.com/2i2c-org/infrastructure/issues/4794
- [x] Assist with data migration https://github.com/2i2c-org/infrastructure/issues/4728
```

### Definition of Done

- [ ] Data migration of the staging hub has been completed
- [ ] Any related tasks involving elevated access have been unblocked

**Comment by sgibson91** [comment]
I have also granted Tarashish just enough permissions on our google cloud account to get the SOPS decryption key so he can run deployer commands himself. This will reduce the amount of pair working I will need to do towards this project.
