### ISSUE TITLE
Unbreak the earthscope support deployment

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4810]
### Context

As a part of #4632, I tried to expand the size of the prometheus disk belonging to the earthscope cluster but ran into problems.

The error is:

```
Error: UPGRADE FAILED: cannot patch "support-prometheus-server" with kind PersistentVolumeClaim: persistentvolumeclaims "support-prometheus-server" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
```

I tried deleting just the pvc `support-prometheus-server` and rerun the support deploy, but that has left the pvc in a pending state (causing helm upgrade to timeout).

One thing that is not clear to me: Do we lose prometheus data by deleting the associated pv? I avoided doing that incase we would.

### Task list

```[tasklist]
- [x] Figure out how to restore the system so the PVC is no longer stuck in a pending state
```

### Definition of Done

- [ ] Deploying the support chart to earthscope no longer fails and prometheus is running

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed

**Comment by haroldcampbell** [comment]
@sgibson91 will pair with @yuvipanda on this issue

**Comment by sgibson91** [comment]
Yuvi and I just completed this! Earthscope support chart now successfully deploys!
