### ISSUE TITLE
Understand and document the steps to safely expand prometheus's disk size, and do so for Pangeo

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4811]
### Context

We sometimes need to increase the size of the prometheus disk to accommodate the amount of data we are generating. We should document the steps of how to do this _safely_ so any engineer can perform the task without worrying about running into errors such as below and needing to debug them.

```
Error: UPGRADE FAILED: cannot patch "support-prometheus-server" with kind PersistentVolumeClaim: persistentvolumeclaims "support-prometheus-server" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
```

When we have these steps, we should use them to merge PR #4808

### Task list

```[tasklist]
- [x] Figure out the steps needed to safely expand prometheus's disk size
- [x] Document the steps
- [x] Use the steps to merge #4808
```

### Definition of Done

- [x] #4808 is merged and running as expected
- [x] There is documentation for expanding prometheus' disk size that any engineer can follow

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed

**Comment by haroldcampbell** [comment]
Thi sis dependent on #4810

**Comment by sgibson91** [comment]
The reason that the steps for expanding the persistentVolume size were not required for pangeo-hubs, is because that cluster is GCP, and all the storage classes there have autoexpansion set to true by default.
