### ISSUE TITLE
Update our Global Prometheus Health grafana dashboard to show remaining disk size as a percentage

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4812]
### Context

Seeing that a disk has 300GB ish free is only useful if you know how big the disk is in the first place. For a 500GB disk, this is a lot, but for a 2.5TB disk, it's not that much. Humans brains work best with _relative_ sizes, so it is more intuitive to say a disk has 10% space remaining as that indicates we may wish to act soon.

I propose we update [this grafana dashboard](https://grafana.pilot.2i2c.cloud/d/d560fa89-38bc-4253-964e-82573ea91d57/global-prometheus-health?orgId=1) to show percentages rather than absolute numbers.

### Task list

Needs refinement

### Definition of Done

- [ ] The global prometheus health dashboard reports percentage of disk space remaining, not absolute value

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed

**Comment by sgibson91** [comment]
Could someone with more prometheus knowledge help finish refining this please?

**Comment by GeorgianaElena** [comment]
I did a read of this issue and I think I am able to refine this, so I'll assign myself to do this refinement tomorrow and remove Yuvi.

**Comment by GeorgianaElena** [comment]
@sgibson91, I ended up modifying the dashboard while trying to understand what needs to be done in order to refine it 😅 

However I did a short screen recording on where and how I did the changes, and [here](https://grafana.pilot.2i2c.cloud/d/d560fa89-38bc-4253-964e-82573ea91d57/global-prometheus-health?orgId=1&editview=versions) are the actual diffs because I did the recording after doing the actual changes.

https://github.com/user-attachments/assets/09903192-0af7-48e9-99b1-c0e5eb25e9c3

**Comment by sgibson91** [comment]
@GeorgianaElena you are a super star 🌟
