### ISSUE TITLE
Improve documentation for chartpress, particularly around publishing to GitHub pages

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4814]
### Context

chartpress can be used to publish helm charts to GitHub pages, however the documentation provided isn't very clear about 1) what chartpress actually provides for the publication (i.e. an automatically updated index.yaml file), or 2) what the user needs to do to properly setup gh-pages so that the website renders effectively (i.e. symlinked index.yaml to a _data subfolder, how to structure index.md, etc).

This issue track doing that upstream work to make chartpress a more beginner-friendly project.

### Task list

Needs refinement

### Definition of Done

- [ ] Well-defined steps for publishing to gh-pages with chartpress and all the setup are documented in the chartpress repo

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed
