### ISSUE TITLE
[Prof. Dev.] Sarah to prep for and take CNCF K8s Administrator Certification exam

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4815]
### Context

I completed the course content, and there's an opportunity to take an exam that will give me a certification of the skills I have learned. I will need to revise the course content, there is also a mock environment where I can practice.

### Task list

```[tasklist]
- [ ] Revise course material
- [ ] Practice in mock environment
- [ ] Take exam and resit, if required
```

### Definition of Done

- [ ] Sarah has attempted the K8s Administrator exam at least once

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed
