### ISSUE TITLE
Reuse and update slides for ReproducibiliTea talk (Uni. of Basel - remote)

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4816]
### Context

A while ago, Tim Head recommended me to the [ReproducibiliTea](https://reproducibilitea.org/) group at the University of Basel to give a talk on computational reproducibility and the Binder project. This is a remote talk so no travel is involved. I'm going to give a variation of my _Turing Way_ reproducibility with Binder talk, so I have a (well-used) slide deck already. I'm just going to tweak it a little and change some of the formatting around.

The talk is scheduled for November 21st.

### Task list

```[tasklist]
- [ ] Tweak previous talk slides on computational reproducibility and Binder
```

### Definition of Done

- [ ] Talk has been successfully given

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed

**Comment by sgibson91** [comment]
Let's not track this explicitly. I want to spend 30mins a day working on this between now and the talk date and it doesn't seem worth creating new issues to track this in every sprint.
