### ISSUE TITLE
Revert moving away from r5 instances on AWS

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4817]
We have too much other moving pieces and WIP which we should complete before starting new projects.

We should revert the work done as part of https://github.com/2i2c-org/infrastructure/issues/4750 for now. That work should be prioritized appropriately, a chunk of time allocated to it, and should be brought to completion. Otherwise we'll end up with yet another half complete config change.

## Subtasks

- [x] Revert the default change in the eksctl template
  https://github.com/2i2c-org/infrastructure/pull/4838
- [ ] Revert the config for the nmfs-openscapes hub in eksctl, use r5 instances like our other clusters
- [x] Revert the config for the nmfs-openscapes hub in profile list, use r5 instances like our other clusters

## Definition of done

- [x] r7i instances are not used in any of our clusters yet
