### ISSUE TITLE
[New Hub] [Phase 1] Cloud Account Setup - Queens University

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#4822]
### What is the 'ready to work' status of this phase?

READY

### Required information for setting up a cloud account for a new community on a dedicated cluster.

We have an opportunity with a Canadian university (Queen's University) to run a pilot hub under their campus Azure account.

Their technical contact (Chris Wood) is available and willing to assist us in the navigation of getting appropriate accounts set up.

Please see the conversation in https://2i2c.freshdesk.com/a/tickets/2134 for additional details.

**This is not a routine turnup phase 1 and will require some additional refinement but need engineering to be part of the conversation.**

Due date for hub deployment:  Sep 30, 2024

| Question | Answer | Notes |
| :--- | :--- | :--- |
| Cloud Provider | Azure | |
| Will 2i2c pay for cloud costs? | No | |
| Name of cloud account | | |
| Community Representative(s) (GitHub handles or email) | | |
| Have the Technical Contacts been added to the [AirTable](https://airtable.com/appbjBTRIbgRiElkr/pagD3XyZjqBunYMnC)? | `Yes/No` | |

Available runbooks:
- https://infrastructure.2i2c.org/hub-deployment-guide/runbooks/phase1/#available-runbooks
```[tasklist]
### Tasks
- [x] Contact Chris Wood (Queens) for additional information on their Azure account
- [x] Set up accounts for at least two engineering team members
- [x] Refine https://github.com/2i2c-org/infrastructure/issues/4823 (Hub Turnup Phase 2)
```

**Comment by haroldcampbell** [comment]
We want to bring @jmunroe into any conversation if there are any blockers

**Comment by haroldcampbell** [comment]
- This requires a conversation with a member of the community (Chris Wood) before kicking this off. 
- @haroldcampbell can support the AirTable work

**Comment by sgibson91** [comment]
I have emailed Chris to setup an Azure subscription and cc'd support so it can be tracked here: https://2i2c.freshdesk.com/a/tickets/2167

**Comment by sgibson91** [comment]
Status of this one so far:

Contact at Queens, Kurtis Rhiel (KR), asked if giving us a ready-made resource group (RG) with Owner permissions therein would be adequate.

SG brainstormed with JM: We may need to rewrite terraform code to accept existing RG and SG doesn't want to do that unless we're getting paid - JM agreed. SG remembers about `terraform import` after JM asked about 'tricking' terraform into thinking it had already created the RG it could see. Plan of action formed: Ask if there's a way we can deploy as we'd expect to, if not try `terraform import`, if that doesn't work then escalate back up to Jim Colliander that terms of work are not yet compatible with 2i2c Eng operations.

SG asked KR about path forward. Messages in freshdesk reflect that Queens contacts are looking at giving us user accounts that will have enough permissions to deploy what we need to, and these permissions will be scaled back to the RG we create after deployment. SG hopes that that won't be problematic for future terraform updates but we shall see.

**Comment by sgibson91** [comment]
Turns out "setting up user accounts" involves getting bespoke queens.ca accounts and providing home addresses and DOB of everyone involved. This is a BLOCKER for Eng. We should not be expected to manage separate email accounts and give personal information to deploy infrastructure.

I have not responded to to the ticket yet, but have pinged James and Jim for a sync chat when they are online to escalate back up to them and they can handle this.

**Comment by jmunroe** [comment]
I have written to Queen's to propose various attempts at unblocking us. See https://2i2c.freshdesk.com/a/tickets/2134 for details.

**Comment by sgibson91** [comment]
We received accounts for all engineers and I have forwarded thm on.
