### ISSUE TITLE
[Epic] New Hub - Queens University

### ISSUE THREAD

**Issue by haroldcampbell** [2i2c-org/infrastructure#4832]
These are the tasks that need to be complete for creating this hub
- [x] https://github.com/2i2c-org/infrastructure/issues/4822
- [x] https://github.com/2i2c-org/infrastructure/issues/4823
- [x] https://github.com/2i2c-org/infrastructure/issues/4824
