### ISSUE TITLE
[EPIC] New Hub Strudel

### ISSUE THREAD

**Issue by haroldcampbell** [2i2c-org/infrastructure#4833]
Tasks that need to be completed
- [x] https://github.com/2i2c-org/infrastructure/issues/4829
- [x] https://github.com/2i2c-org/infrastructure/issues/4830
- [x] https://github.com/2i2c-org/infrastructure/issues/4831

**Comment by colliand** [comment]
FYI. Copy/paste from the STRUDEL running notes:

GitHub organization
https://github.com/strudel-science
https://github.com/orgs/strudel-science/teams
