### ISSUE TITLE
[EPIC] New Hub - dubois

### ISSUE THREAD

**Issue by haroldcampbell** [2i2c-org/infrastructure#4834]
- [x] https://github.com/2i2c-org/infrastructure/issues/4825
- [x] https://github.com/2i2c-org/infrastructure/issues/4826
- [x] https://github.com/2i2c-org/infrastructure/issues/4827
