### ISSUE TITLE
Deploy jupyterhub-home-nfs to NASA VEDA production

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#4835]
Once https://github.com/2i2c-org/infrastructure/issues/4647 is complete, we should roll it out to the NASA VEDA production instance. We do not intend to roll this feature out retroactively to other communities unless asked.

## What to set the quota to?

To avoid co-ordination overhead, let's set it to 10% + whatever is the current largest single user's home directory usage.

## Timeline

There are 2 factors Sarah is balancing when deciding a timeline:

1) Most of the underlying technical work was completed as part of #4647 so this should "just" be turning things on
2) We will be migrating the prod home directories so we expect there to be a greater volume of data, and a lower tolerance to data loss/corruption

Considering these 2 factors, Sarah believes a timeline of 2 weeks is ample.

### Tasks

```[tasklist]
- [ ] https://github.com/2i2c-org/infrastructure/issues/5021
- [ ] https://github.com/2i2c-org/infrastructure/issues/4857
- [ ] https://github.com/2i2c-org/infrastructure/issues/4858
- [ ] https://github.com/2i2c-org/infrastructure/issues/4859
- [ ] https://github.com/2i2c-org/infrastructure/issues/4860
- [ ] https://github.com/2i2c-org/infrastructure/issues/4861
```

## Definition of Done

- [x] NASA VEDA production hub has per-user home directory quotas
- [ ] "Per user home directory quotas" is added to our service description of what is available for hubs (the product menu)
- [ ] The feature is communicated to our communities via a blog post

**Comment by Gman0909** [comment]
Once this is complete, the configuration option should also be added to the configurator form here: https://docs.google.com/forms/d/1Gx3v-KaruL6K9VanuwatKEr3qOLJi8ezrcsvGDtZDEQ/edit

**Comment by sgibson91** [comment]
FYI, I don't seem to have access to that form. I'm not sure if it's because the link is opening with my personal Google account authenticated first so I'm not being picked up as belonging to the org, or if something else funky is going on with permissions. There is unhelpfully no option for me to change user, and no `authuser=` showing up in the URL for me to manipulate to force it to see my 2i2c account. So as things presently stand, someone else will have to do the form updating, when the time is right.

**Comment by Gman0909** [comment]
@sgibson91 I've just invited you as an editor, you should now have full control of the form.

**Comment by sgibson91** [comment]
This has been completed! I don't think the last two bullets in the DoD are relevant since they were done as part of https://github.com/2i2c-org/infrastructure/issues/5010

**Comment by Gman0909** [comment]
Fantastic! Another one down. Thanks @sgibson91

**Comment by sgibson91** [comment]
@sunu did all the work on this one!

**Comment by Gman0909** [comment]
A massive thanks to @sunu for getting this over the line!

**Comment by sunu** [comment]
Thank you @sgibson91 for all the help and guidance to get this over the line!
