### ISSUE TITLE
Coordinate a maintenance window with VEDA for the storage switch

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4858]
Switching the storage backend for the VEDA prod hub will require some downtime of the hub. We should coordinate with someone in DevSeed and VEDA to establish a preferred maintenance window within which the switch can take place.

### Tasks

- [x] Establish a mutually preferential maintenance window between engineers and the VEDA users for the NFS switch
  - European AM will be good for Sarah and probably has a smaller number of active users on the hub
- [ ] Communicate the maintenance window with VEDA users

### Definition of Done

- [ ] Both engineers and VEDA users are aware of when disruptive maintenance caused by the NFS switch is due to take place
- [ ] VEDA users are also aware that changed made in their home directories during the window and in the few hours leading up to the window may be lost

**Comment by sgibson91** [comment]
FYI @yuvipanda, I removed Sanjay's name from this because I know his sabbatical starts very soon. Feel free to reach out to whoever you think is appropriate.

**Comment by sgibson91** [comment]
I'm moving this back to refined since we will move forward with other communities until VEDA have organised their home dirs a bit more
