### ISSUE TITLE
Preliminary migration of VEDA prod home dirs from EFS instance to EBS volume

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4859]
This task represents migrating the bulk of the home dirs on the VEDA prod hub from the EFS instance to the EBS volume.

### Tasks

- [x] Complete the steps in the docs to migrate the home dirs: https://infrastructure.2i2c.org/howto/features/storage-quota/#migrating-existing-home-directories
	- We may also want to use `screen` so this process can run in the background as I expect it to be much larger in terms of disk size than the staging migration

### Definition of Done

- [x] The home dirs of VEDA prod are present on the EBS volume
- [x] File/dir ownership, permissions, and modified time (`mtime`) have been preserved and verified

**Comment by sunu** [comment]
This is now done. We have a preliminary copy of the existing VEDA prod home directories on the newly created EBS volume.
