### ISSUE TITLE
[EPIC] Roll out a cost attribution system in all AWS clusters

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4872]
This EPIC captures the AWS part of https://github.com/2i2c-org/infrastructure/issues/4384:

## Quick intro

The AWS cost attribution system is a simple Python webserver accessing AWS Cost Explorer API to summarize information about an AWS accounts billing data. This summarized billing data is then exposed via a k8s Service, making a Grafana instance able to access it as a datasource. There is a datasource plugin used for this in Grafana called Infinity, as it helps parse the JSON response provided by the webserver. The openscapes grafana instance currently has this system deployed, and the Grafana instance has a Dashboard defined within it that we can re-use.

### Kinds of work involved

Most of the AWS specific parts have been done, so now working this epic will mostly involve less cloud specific parts, such as:
- terraform / eksctl
- grafana dashboard development like in jupyterhub/grafana-dashboards
- interaction and communication with openscapes and nasa-cryo community
- the deployer script (Python) and GitHub workflows
- public communication via a blog post

### As seen in openscapes

You can inspect the dashboard live at https://grafana.openscapes.2i2c.cloud/d/b4dbba938e548f10/cloud-cost-attribution?orgId=1

![openscapes-cost-attribution-is-up](https://github.com/user-attachments/assets/3ca0377b-66fd-4e91-b407-6b2e3f3c1873)

```[tasklist]
### Tasks
- [ ] https://github.com/2i2c-org/infrastructure/issues/4453
- [ ] https://github.com/2i2c-org/infrastructure/issues/4873
- [ ] https://github.com/2i2c-org/infrastructure/issues/4874
- [ ] https://github.com/2i2c-org/meta/issues/1467
- [ ] https://github.com/2i2c-org/infrastructure/issues/4875
- [ ] https://github.com/2i2c-org/infrastructure/issues/4944
- [ ] https://github.com/2i2c-org/infrastructure/issues/4876
- [ ] https://github.com/2i2c-org/infrastructure/issues/4919
- [ ] https://github.com/2i2c-org/infrastructure/issues/4925
- [ ] https://github.com/2i2c-org/infrastructure/issues/4926
- [ ] https://github.com/2i2c-org/infrastructure/issues/4927
- [ ] https://github.com/2i2c-org/infrastructure/issues/4928
- [ ] https://github.com/2i2c-org/infrastructure/issues/4991
- [ ] https://github.com/2i2c-org/infrastructure/issues/4962
- [ ] https://github.com/2i2c-org/infrastructure/issues/4878
- [ ] https://github.com/2i2c-org/infrastructure/issues/5047
- [ ] https://github.com/2i2c-org/infrastructure/issues/5000
- [ ] https://github.com/2i2c-org/infrastructure/issues/4879
- [ ] https://github.com/2i2c-org/infrastructure/issues/4941
- [ ] https://github.com/2i2c-org/infrastructure/pull/4951
- [ ] https://github.com/2i2c-org/infrastructure/issues/4948
```

**Comment by GeorgianaElena** [comment]
> Also, we still didn't get an answer from communities

@jnywong and @jmunroe, are you ok with me leaving the keeping an eye on those support tickets task on you and not open a separate tracking issue for that? I figure we can open its own tracking issue if they require additional assistance.

**Comment by jnywong** [comment]
Hey @GeorgianaElena ! We are both keeping an eye on the FreshDesk so there's no need to open another GH issue for that.

> Also, we still didn't get an answer from communities

There will be another couple of touchpoints to share docs with them and gather feedback in #4879 and https://github.com/2i2c-org/meta/issues/1569, so hopefully that stimulates engagement. Ultimately we can't force them to engage, but we can keep track and improve that over time.

**Comment by consideRatio** [comment]
I've unassigned myself from this effort, and want to highlight @GeorgianaElena's decisive leadership this recent sprint and is a natural candidate to be asked to pick it up officially!

**Comment by consideRatio** [comment]
Feature request not yet tracked: to have one or more of the panels in the dashboard convey costs from different node instance types, in practice breaking down the "compute component" further. It can be broken down based on node group name and/or instance type.
