### ISSUE TITLE
Update our quota documentation for GCP projects

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4880]
### Context

Our GCP quota documentation should be more explicit about _which_ quotas we are checking/updating, and _what_ they should be updated to.

- https://infrastructure.2i2c.org/hub-deployment-guide/runbooks/phase1/new-gcp-project/#checking-quotas-and-requesting-increases

### Task list

```[tasklist]
- [ ] Define what quotas we should examine and what value they should be set to, particularly for account creation
- [ ] Write that up
```

### Definition of Done

- An engineer setting up a new GCP project knows explicitly what to do with quotas at that point

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed

**Comment by yuvipanda** [comment]
Let's defer this for another sprint

**Comment by GeorgianaElena** [comment]
While I believe this is important, we also didn't  recently bump into the need to have improved docs around GCP quotas.
So, I'll close this one as unplanned and we can revisit the decision later. 
(anyone, feel free to reopen if you disagree)
