### ISSUE TITLE
[EVENT][October 10-18, 2024] OceanHackWeek

### ISSUE THREAD

**Issue by emiliom** [2i2c-org/infrastructure#4883]
### The link towards the Freshdesk ticket this event was reported

2i2c contract discussed via email with funding lead, Marian Peña Saenz, Spanish Institute of Oceanography (IEO / CSIC)

https://2i2c.freshdesk.com/a/tickets/2189

### The GitHub handle or name of the community representative

@emiliom

### The date when the event will start

October 10, 6am US/Pacific

### The date when the event will end

October 18, 4pm US/Pacific

### What hours of the day will participants be active? (e.g., 5am - 5pm US/Pacific)

7 - 12 US/Pacific, but individual use will likely continue after hours

### Are we three weeks before the start date of the event?

- [X] Yes
- [ ] No

### Number of attendees

50

### Make sure to add the event into the calendar

- [x] Done

### Does the hub already exist?

- [X] Yes
- [ ] No

### The URL of the hub that will be used for the event

https://oceanhackweek.2i2c.cloud

### Will this hub be decommissioned after the event is over?

- [ ] Yes
- [X] No

### Task list

- [ ] Was all the info filled in above?
- [ ] Quotas from the cloud provider are high-enough to handle expected usage?
- [ ]

### Definition of Done

- [ ] All the tasks have been completed
- [ ]

**Comment by emiliom** [comment]
Some additional information:

- I didn't have access to the calendar, so I didn't set the "Make sure to add the event into the calendar" checkbox 
- The period covered in the agreement (contract?) between 2i2c and IEO / CSIC is late September through December. During this period, there will be two events:
    1. This one, October 10 - 18. Actual days of live hub use will be Oct. 15 - 18, but we'll need to ensure everything is working properly a few days in advance, and instructors would like to use it during tutorial development starting next week.
    2. The main hackweek event, November 25 - 29. 
- The event will be in Spanish.
- The website for the OceanHackWeek-in-Spanish initiative is https://intercoonecta.github.io
- We will be changing the hub interface to Spanish, mostly following what we did for a preceding event in March 2023. See #2108. Specifically, we'll rewrite the hub main page and image selection page. FYI we also configure JupyterLab with the Spanish language pack, for users to switch it themselves.
- The October event follows on the heels of a recent (August 26-30) event by the broader OceanHackWeek group, #4469
- The hub should probably be "decommissioned" (torn down) once this agreement ends, after December. But let's have that decision be done in concert with the broader OceanHackWeek group.

**Comment by emiliom** [comment]
I'll keep track of individual tasks at https://github.com/oceanhackweek/Hub-Management/issues/6

**Comment by sgibson91** [comment]
Thanks for all this info @emiliom :) Have you tested the workflows you will be using during the event, and have you found the current CPU and memory limits sufficient?

**Comment by emiliom** [comment]
Thanks! We're still developing the tutorials, and we still plan to update the image with different Python and R dependencies. But I don't expect to change the CPU and memory limits. What we have has worked reasonably well for us in past events, and this particular event shouldn't be too taxing.

**Comment by emiliom** [comment]
I need to change the text in the landing page, as we did in our 2023 (February - March) event (see https://github.com/2i2c-org/infrastructure/issues/2108#issuecomment-1424467568). I know where to make the changes, in the `templates/login.html` file in https://github.com/2i2c-org/default-hub-homepage. But at that time, 2i2c created a branch, [2i2c-ohw](https://github.com/2i2c-org/default-hub-homepage/tree/2i2c-ohw)  for me to create a PR against. For the 2023 event, the PR I used to make changes was https://github.com/2i2c-org/default-hub-homepage/pull/20

How should I proceed this time? Should I still create PR's against that branch? The `2i2c-ohw` branch hasn't been updated since February 2023, so I imagine I'd first need to merge the latest from the `main` branch, right? 

Thanks!

**Comment by GeorgianaElena** [comment]
> How should I proceed this time? Should I still create PR's against that branch? The 2i2c-ohw branch hasn't been updated since February 2023, so I imagine I'd first need to merge the latest from the main branch, right?

@emiliom, yes, you are correct! I just updated the `2i2c-ohw` branch and merged `main` into it. It is now in sync with the main branch, but also has the changes from last year. If you need to do additional changes to it, please feel free to open a PR there and ping us for a merge.

Also, the hub is not using yet that branch. Let us know when it would be ok for the landing page to change to Spanish and we'll make the switch in this repository.

Thank you.

**Comment by emiliom** [comment]
I've created a PR, #4938, to update `ohw.values.yml`. Could someone review it and merge it if it's all good?

@GeorgianaElena thanks for your follow up! I plan to do a PR against that `default-hub-homepage` branch today. As for this:

> Also, the hub is not using yet that branch. Let us know when it would be ok for the landing page to change to Spanish and we'll make the switch in this repository.

Just for my own understanding, that's a change you make on your end (after I ask for it) and not one I request through a PR via a change in a configuration file, correct?

**Comment by sgibson91** [comment]
@emiliom It's probably easier if we make the PR just because we are adding config rather than changing what's already there. But you can check it out so you can open it yourself in the future!

**Comment by emiliom** [comment]
I've created a new PR, https://github.com/2i2c-org/infrastructure/pull/4950, to update the Python & R images in `ohw.values.yml`. Could someone review it and merge it if it's all good? No deployment failures this time!

**Comment by emiliom** [comment]
I've created a new PR, https://github.com/2i2c-org/infrastructure/pull/4958. Could someone review it and merge it if it's all good? Thanks.

**Comment by emiliom** [comment]
I've created a PR in the `default-hub-homepage` repo to update the `login.html` template. See https://github.com/2i2c-org/default-hub-homepage/pull/33. Could someone review it and merge it if it's all good? Hopefully I didn't break anything in the template.

Thanks!

**Comment by emiliom** [comment]
@sgibson91 thanks for merging https://github.com/2i2c-org/default-hub-homepage/pull/33. I see that our hub's landing page didn't update, but now I remember this comment from @GeorgianaElena, from last week:

> Also, the hub is not using yet that branch. Let us know when it would be ok for the landing page to change to Spanish and we'll make the switch in this repository.

Yes, please change the landing page to the `2i2c-ohw` branch!

**Comment by GeorgianaElena** [comment]
@emiliom, the changes should propagate in about 5min 🚀

**Comment by emiliom** [comment]
Thank you @GeorgianaElena ! The change is now live. FYI I made a mistake with an HTML tag, that I'll fix later (together with other updates) in a new PR.

**Comment by sgibson91** [comment]
@emiliom We don't have a good way to handle this yet. If a GitHub team has been removed from the values file, then member of that team will not be able to login again. However, this doesn't update JupyterHub's database which records users who have previously logged in. I also don't think that deleting the user manually will erase their home directory from storage either. Designing and implementing this system is something that is captured in our product process, but it is not available yet.

**Comment by emiliom** [comment]
@sgibson91 thanks for the explanation. Well, at least it's good to confirm that only members of the specified GitHub teams can log in.

**Comment by emiliom** [comment]
I've created a new PR, https://github.com/2i2c-org/infrastructure/pull/4965. Could someone review it and merge it if it's all good? Thanks.

**Comment by emiliom** [comment]
I've created a new PR #4967 Could someone review it and merge it if it's all good? Thanks.

**Comment by emiliom** [comment]
I've created another PR, https://github.com/2i2c-org/default-hub-homepage/pull/34, this time on the `default-hub-homepage` repo to update the `login.html` template. 

Thanks for handling both PR's.

**Comment by consideRatio** [comment]
#4976 merged and deployed!

**Comment by emiliom** [comment]
Thank you!

**Comment by GeorgianaElena** [comment]
@emiliom, hope you had some great events 🎉 Am I correct to believe that until November 25 there aren't any other planned event and we can close this issue? Or is it still one event planned to happen Thursday 24th of October?

Also, please feel free to open a new support request for the 25th of November one so we can get it through our planning processes. Thank you!

**Comment by emiliom** [comment]
@GeorgianaElena the event has ended, and the next one (and final one in the current series) will be November 25 - 29. We can close this issue. Everything went fairly smoothly.

I do have some follow ups from last week's event, to start researching improvements for the next event. Should I open individual, narrow issues to discuss these? They would be separate from the umbrella issue I'll open later on for the next event.

Thanks to you, @sgibson91 and @consideRatio for all your help!

**Comment by GeorgianaElena** [comment]
Yaaay 🎉 Then I will close this issue as completed 🚀 

> I do have some follow ups from last week's event, to start researching improvements for the next event. Should I open individual, narrow issues to discuss these? They would be separate from the umbrella issue I'll open later on for the next event.

@emiliom, our current process is to get through [support via Freshdesk](https://docs.2i2c.org/support/) for any question/request/event as that is constantly monitored and this way we don't risk to miss it, as it might happen with a GitHub notification.

So, for the new event I suggest opening a Freshdesk ticket instead where you can mention also the follow-up improvements, as they are related to the event as well if I understand correctly.

Based on the discussions there, we will open GitHub issues and get them to the appropriate project boards, so we can get them through our planning process and make sure they are ready in time.
