### ISSUE TITLE
[Support] Revert UCMerced's RAM bump at the end of their event

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4894]
UC Merced has users who use usually use < 1GB but occasionally use up to 2GB.

- [x] Add multiple profile options to support those two requests
- [x] Make a histogram of memory usage over all instances on this cluster for the last 90 days
- [x] Email UC Community Champion letting them know this change

----

### Context

We should revert #4893 when their event is over

### Task list

```[tasklist]
- [ ] Figure out when their event ends
- [ ] Revert #4893 
```

### Definition of Done

- #4893 is reverted

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed

**Comment by haroldcampbell** [comment]
We need to find out when the event ends. @jmunroe or @jnywong please provide some more context here?

**Comment by jmunroe** [comment]
It's not an event. This is related to a support issue: https://2i2c.freshdesk.com/a/tickets/2193

I will follow on on that thread to see if/when this needs to be reverted.

**Comment by jmunroe** [comment]
I think this community needs guidance if they should be using a 1G or 2G limit.  While it is ultimately their decision, we can assist by providing the following pieces of information:

- Information on historic ram usage
- Guidance on cloud cost projection 
- recommendation if they should continue with a 2G limit or revert to 1G

**Comment by jmunroe** [comment]
I need help with getting this to done.

**Comment by yuvipanda** [comment]
Had a chat with @jmunroe, I think he has enough information to proceed now.

**Comment by jmunroe** [comment]
This is a loose thread that I will try an tie up before the end of the week.

**Comment by jmunroe** [comment]
PR: https://github.com/2i2c-org/infrastructure/pull/5280
Email to community: https://2i2c.freshdesk.com/a/tickets/2576

> Hi Sai,
> 
> Earlier this fall we had boosted the RAM limits on ucmerced.2i2c.cloud to accommodate some students who occasionally where getting kernel crashes due to running out of RAM. The limit was original 1GB and we had bumped it to 2GB.
> 
> I've taken a look at the actually usage by all users over the last 90 days to review that RAM limit
> 
> Here's a time series of memory usage over all instances:
> 
> ![Image](https://github.com/user-attachments/assets/bb393a60-a00b-4d68-b0fb-3f9d42a9db2c)
> 
> We do see that occasionally users do use more than 1GB but not often.  I drilled into the data some more:
> 
> ![Image](https://github.com/user-attachments/assets/186de8f3-b716-407d-be53-01d3d1b3ad1d)
> 
> This histogram is counting the number user-instances where the memory hit a certain limit. While there are instances where more than 1GB of ram is used, it is only about 1% of the typically usage.
> 
> Since cloud costs are tied to RAM requested even if not used, I've changed the defaults for ucmerced.2i2c.cloud back to 1GB but added an additional option for those users who might need up to 2GB on occasion:
> 
> ![Image](https://github.com/user-attachments/assets/c9290e5f-b548-47e8-a2d5-b26dfb8f2029)
> 
> I hope the phrase 'Resource Allocation' and the options of '1GB RAM / 2GB RAM' make sense to you and your users.  The default is 1GB. This change to our Jupyter launcher UI was made possible by the roll out of the 'jupyter-fancy-profiles' we did a few weeks ago. You may want to email your instructors directly to inform them of this change in case for certain assessments more than 1GB of RAM is required.
> 
> No action is required from you but if there are any issues which this configuration change please us know at [support@2i2c.org](mailto:support@2i2c.org) .  My hope is that allows instructors and students to not be blocked by ram limitation while lower the overall cloud costs on the hub.
