### ISSUE TITLE
[EPIC] Automate the creation and management of recurrent tasks 

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#4906]
We have at least two types of recurrent tasks that we know when we need to do and we know hot to do them

- gathering billing info about clusters
- regenerating deployer credentials for smce clusters

Currently they are tracked by @yuvipanda I believe in [this calendar](https://www.google.com/url?q=https://calendar.google.com/calendar/embed?src%3Dc_62d7c67afde2b63bf53536f7923fcc59e7c1a6d8361f24385bd5c792e68f121b%2540group.calendar.google.com%26ctz%3DAmerica%252FLos_Angeles&sa=D&source=calendar&ust=1728096472965021&usg=AOvVaw1thSYLS4uFmpjYb4jvwGic)

### Proposal

While this is a great approach to not forget about them for long periods of time, there is still the risk of missing to open them in time to be prioritized. They also consists of a bunch of repetitive tasks that we need to do on the Engineering board, after their creation to make them ready to be worked on.

We should consider automating this efforts:
```[tasklist]
- [ ] Have alignment with Yuvi
- [ ] https://github.com/2i2c-org/infrastructure/issues/4903
- [ ] https://github.com/2i2c-org/infrastructure/issues/4904
- [ ] https://github.com/2i2c-org/infrastructure/issues/4905
```

**Comment by jmunroe** [comment]
Scheduling recurring tasks is something that was thinking about in https://github.com/2i2c-org/meta/issues/1498 .  While the overall procedure is out of scope for this epic, there are some GitHub issue scheduling subtasks that I think fit in this epic.

**Comment by GeorgianaElena** [comment]
This is actually done for the recurrent tasks that happen more frequently (see sub-issues), so closing
