### ISSUE TITLE
[Decommission Hub] [Oct 17] climatematch

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#4909]
### Summary

The community has decided to shutdown the hub until next year.  I have emailed the community to get confirmation that the associated data can be deleted.

- https://2i2c.freshdesk.com/a/tickets/2197

### Info

- **Community Representative:** 
- **Link to New Hub issue:** 
- **Proposed end date:** 

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [x] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
    - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration
  - [x] If no, confirm it is ok to delete all the data stored in the user home directories

#### Phase II - Hub Removal

(These steps are described in more detail in the docs at https://infrastructure.2i2c.org/hub-deployment-guide/hubs/delete-hub/)

- [x] Manage existing home directory data (migrate data from the hub or delete it)
- [ ] Manage existing cloud bucket data (migrate data, or delete it)
- [x] Delete the hub's authentication application on GitHub or CILogon (note CILogon removal requires the hub config in place)
- [x] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.
- [x] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [x] Remove the hub deployment
  - TIP: Run `deployer use-cluster-credentials <cluster_name>` before running the commands below
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`

### Definition of Done
_A non-specific, pre-defined list of tasks that should be considered before marking the task complete._
- [] All the tasks above have been completed
- [] Existing functionality was not broken

**Comment by sgibson91** [comment]
Hi @jmunroe is there a freshdesk ticket we can monitor for their response regarding data?

This would ideally be scheduled for the next sprint today, but that's hard to confirm without their response.

**Comment by jmunroe** [comment]
The thread is https://2i2c.freshdesk.com/a/tickets/2197 . I don't expect we will get a response during this iteration and I think we should plan on it being done in the next interation.

**Comment by sgibson91** [comment]
From the Freshdesk ticket:

> Our team does need a little time to get everything off the Hub. We will be all good to have it shut down by Thursday, October 17.

Folk ill be backing up their own data and we won't need to migrate anything.
