### ISSUE TITLE
Automate identifying/cleaning-up duplicated and/or unused CILogon clients

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4937]
### Context

CILogon is one of our default authentication providers, however our plan with them only permits us to have a maximum of 100 clients at a time. While deploying the Queen's University cluster, I ran into this limit and had to spend some time manually cleaning out clients before I could continue the deployment. The steps involved in this were very automatable.

### Value

- CILogon is a popular auth provider so maintaining good hygiene here means we can continue to support it as an option for our communities
- Automating this task protects engineers from busywork if/when we reach the limit

### Task list

- [ ] Develop a `deployer cilogon-client` sub-command that identifies duplicated and/or unused CILogon clients, verifies which client IDs are/are not in use, and optionally deletes them through providing a flag
  - See comment below for manual steps that I used

### Definition of Done

- An automated sub-command of the deployer exists for engineers to quickly clean-up any CILogon clients that are duplicates or unused

### Pre-defined Definition of Done

- [ ] All the tasks have been completed
- [ ] It has been tested to work and to not break any existing functionality
- [ ] Documentation was added so other engineers can implement this in the future if needed

**Comment by sgibson91** [comment]
1. I commented out everything in the `cilogon-client delete` command so that it only performed the delete call to the API. No checking the cluster.yaml file or deleting the encrypted secret file.
2. I piped the output of `cilogon-client get-all` to a json file and made sure it was correctly formatted
3. I wrote a little python script that read in the json file, used `jmespath` to get a list of all the name fields, then used `collections.Counter` to count how many times each name appeared, and filtered the resulting dict so that it only returned values for counts greater than 1.
4. For each hub in that returned dict, I piped `get-all` to `grep $HUB_NAME` so I could see all the client IDs, then decrypted the relevant secret files to see which ID was actually being used (it was here that I discovered some hubs with CILogon apps are actually using GitHub auth), and ran the modified `delete` command over all other IDs.
5. Once I'd gotten rid of duplicates, I piped `get-all` to a file again (just txt this time) and looked for any names of hubs/clusters that no longer existed, or had been throwaway apps for testing (e.g. test-test, local-testing etc) and deleted those too
