### ISSUE TITLE
[EPIC] [devseed] Set up alerting for an EBS volume getting close to full on AWS, and a runbook on how to resize it when needed

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#5004]
### Context

Previously using AWS EFS instances for home directories, they would be automatically resized when they got full. However, to provide home directory quotas, we had to migrate to EBS volumes which do not automatically expand. Therefore we need to develop a monitoring and alerting system that let's us know that these volumes are approaching full in good time to act before the service is disrupted.

### Task list

```[tasklist]
 - [ ] https://github.com/2i2c-org/infrastructure/issues/5005
 - [ ] https://github.com/2i2c-org/infrastructure/issues/5006
 - [ ] https://github.com/2i2c-org/infrastructure/issues/5062
```
