### ISSUE TITLE
[Spike: 2hrs] Investigate AWS alerting systems for EBS volumes and associated terraform config

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#5005]
### Tasks

- [ ] Investigate AWS-based alerting on size of EBS volumes and any associated terraform config
- [ ] Report on learnings (can be a comment on this issue)
- [ ] Refine and scope future tasks in the associated epic

### Definition of Done

- [ ] We understand what is required to provide alerting on full EBS volumes from the AWS/terraform perspective
- [ ] The tasks in https://github.com/2i2c-org/infrastructure/issues/5004 have been refined

**Comment by sunu** [comment]
After looking into this, I couldn't find a good built-in way to be alerted when an EBS instance is running out of space. We have the option to run [Cloudwatch Agent](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html) as a sidecar and use [Cloudwatch Alarm](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html) to trigger notifications based on disk usage level.

But since we are using [Prometheus](https://infrastructure.2i2c.org/topic/monitoring-alerting/prometheus/) already and don't use Cloudwatch at all for monitoring right now, I think we should use Prometheus metrics and Grafana alerts for this use case as well.

**Comment by sgibson91** [comment]
Closing since this is not a feasible path forward
