### ISSUE TITLE
[Optional Spike: 2hrs] Investigate prometheus monitoring and grafana alerting for EBS volumes approaching full

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#5006]
> [!warning]
> To be pursued if https://github.com/2i2c-org/infrastructure/issues/5005 fails

### Tasks

- [x] Investigate prometheus metrics to track the size of EBS volumes, if deployed
- [x] Investigate grafana alerting capabilities
- [x] Report on learnings (can be a comment on this issue)
- [x] Scope and refine future tasks in the associated epic

### Definition of Done

- [x] We understand what is required to provide alerting on EBS volume size from a prometheus and grafana perspective
- [x] Tasks in https://github.com/2i2c-org/infrastructure/issues/5004 have been refined

**Comment by sunu** [comment]
Yet to test this end-to-end, but I think we should be able to reuse the Prometheus metric exporter set up defined in https://github.com/2i2c-org/infrastructure/blob/main/helm-charts/basehub/templates/home-space-reporter.yaml by mounting the whole NFS disk as a volume mount.

**Comment by sgibson91** [comment]
Next steps defined in https://github.com/2i2c-org/infrastructure/issues/5062
