### ISSUE TITLE
Track and manage Grafana invitation links for communities

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/infrastructure#5009]
### Context

We currently have no formal process on how we manage access to Grafana with invitation links. This card represents the work to define this process as we roll out the hub scale usage monitoring feature to communities on request.

> [!note]
> This overlaps with work in https://github.com/2i2c-org/meta/issues/1569 -- refer to that issue for more context.

```[tasklist]
### Tasks
- [x] Figure out which communities are eligible, e.g. AWS, dedicated cluster in the first instance
- [ ] Share invitation link to Grafana with admin role to community hub admin
- [x] Record this somewhere in AirTable so other members of 2i2c can look this info up
```

### AirTable view

- [Link to AirTable](https://airtable.com/apptR4AXWIFNGkZMz/shrqZU7ET9RRDanQi) to track and manage Grafana invitation links for communities
- [Link to AirTable interface](https://airtable.com/apptR4AXWIFNGkZMz/paglOT0By6a8HHiVR) for curated list of community champions affected by this rollout

### References

- https://github.com/2i2c-org/infrastructure/issues/4991#issuecomment-2428976438

**Comment by jnywong** [comment]
See https://github.com/2i2c-org/meta/issues/1569#issuecomment-2483224684 for conversation on how to manage email contacts

**Comment by GeorgianaElena** [comment]
@jnywong do you think that it would make sense to close this issue in favour of https://github.com/2i2c-org/meta/issues/1569 where all the work is happening or there is still value in tracking it here?

**Comment by jnywong** [comment]
Yeah you're right, #1569 is the right place to track. Marking as closed.
