### ISSUE TITLE
[Decommission Hub][2024-10-30] nasa-esdis

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#5019]
### Summary

We been asked (https://2i2c.freshdesk.com/a/tickets/2362) to decommission the [NASA-ESDIS hub](https://github.com/2i2c-org/infrastructure/tree/main/config/clusters/nasa-esdis)

### Info

- **Community Representative:** @freitagb
- **Link to New Hub issue:** https://github.com/2i2c-org/infrastructure/issues/3068
- **Proposed end date:** Request received 2024-10-30. Ready to decommission.

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [x] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
    - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration
  - [x] If no, confirm it is ok to delete all the data stored in the user home directories

#### Phase II - Hub Removal

(These steps are described in more detail in the docs at https://infrastructure.2i2c.org/hub-deployment-guide/hubs/delete-hub/)

- [ ] Manage existing home directory data (migrate data from the hub or delete it)
- [ ] Manage existing cloud bucket data (migrate data, or delete it)
- [x] Delete the hub's authentication application on GitHub or CILogon (note CILogon removal requires the hub config in place)
- [ ] Remove the appropriate `config/clusters/<cluster_name>/<hub_name>.values.yaml` files. A complete list of relevant files can be found under the appropriate entry in the associated `cluster.yaml` file.
- [ ] Remove the associated hub entry from the `config/clusters/<cluster_name>/cluster.yaml` file.
- [ ] Remove the hub deployment
  - TIP: Run `deployer use-cluster-credentials <cluster_name>` before running the commands below
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [x] Remove the cluster's datasource from the central Grafana with:
  - `deployer grafana central-ds remove <cluster_name>`
- [x] Run `terraform plan -destroy` and `terraform apply` from the [appropriate workspace](https://infrastructure.2i2c.org/en/latest/topic/terraform.html#workspaces), to destroy the cluster
- [x] Delete the terraform workspace: `terraform workspace delete <NAME>`
- [x] Delete the terraform values file under the `projects` folder associated with the relevant cloud provider (e.g. `terraform/gcp/projects/` for GCP)
- [x] Remove the associated `config/clusters/<cluster_name>` directory and all its contents
- Remove the cluster from CI:
  - [x] [`deploy-hubs.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-hubs.yaml)
  - [x] [`deploy-grafana-dashboards.yaml`](https://github.com/2i2c-org/infrastructure/blob/HEAD/.github/workflows/deploy-grafana-dashboards.yaml)
- [x] Remove A record from Namecheap account

### Definition of Done
_A non-specific, pre-defined list of tasks that should be considered before marking the task complete._
- [] All the tasks above have been completed
- [] Existing functionality was not broken

**Comment by jmunroe** [comment]
I've requested confirmation that the user data is safe to delete.  No user files appear modified within the last 6 months.

Confirmation that this data is safe to delete:  https://2i2c.freshdesk.com/a/tickets/2362

**Comment by consideRatio** [comment]
The confirmation arrived. I decommissioned nasa-esdis fully, and messaged the community representative about deleting out AWS user's within their account which I lacked permissions to do myself.
