### ISSUE TITLE
[New Hub] [Due by: TBD] [Spike: 30mins] Sync chat to refine phases - NASA VEDA - MAAP

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#5020]
This is a refinement task to plan for a hub deployment for MAAP / VEDA

References:
- https://github.com/2i2c-org/meta/issues/1561
- https://github.com/2i2c-org/meta/issues/1368

### Tasks

```[tasklist]
- [ ] Schedule a 30min sync chat to refine the new hub requirements
- [ ] Refine the requirements for this new hub deployment
- [ ] Open the relevant Phase 1,2,3 issues with all of the required information
```

### Definition of Done

Each of the below phases for this new hub deployment should:
- have an open issue,
- have all the relevant information in the issue tables filled out and sections marked as READY,
- have been placed in the Refined column of the Engineering board.

- [ ] [Phase 1](https://github.com/2i2c-org/infrastructure/issues/new?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen&template=03_new-hub_phase-1.yaml)
- [ ] [Phase 2](https://github.com/2i2c-org/infrastructure/issues/new?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen&template=04_new-hub_phase-2.yaml)
- [ ] [Phase 3](https://github.com/2i2c-org/infrastructure/issues/new?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen&template=05_new-hub_phase-3.yaml)

**Comment by jmunroe** [comment]
Duplicate of #5142. Closing this one.
