### ISSUE TITLE
[EVENT][Nov 25 – 29] OceanHackWeek (Spanish)

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/infrastructure#5052]
### The link towards the Freshdesk ticket this event was reported

https://2i2c.freshdesk.com/a/tickets/2426

### The GitHub handle or name of the community representative

@emiliom

### The date when the event will start

Monday, Nov 25

### The date when the event will end

Friday, Nov 29

### What hours of the day will participants be active? (e.g., 5am - 5pm US/Pacific)

6 - 12 US/Pacific, but individual use will likely continue after hours

### Are we three weeks before the start date of the event?

- [ ] Yes
- [x] No

### Number of attendees

50

### Make sure to add the event into the calendar

- [x] Done

### Does the hub already exist?

- [x] Yes
- [ ] No

### The URL of the hub that will be used for the event

https://oceanhackweek.2i2c.cloud/

### Will this hub be decommissioned after the event is over?

- [ ] Yes
- [x] No

### Task list

- [ ] Was all the info filled in above?
- [ ] Quotas from the cloud provider are high-enough to handle expected usage?
- [ ]

### Definition of Done

- [ ] All the tasks have been completed
- [ ]

**Comment by jnywong** [comment]
Emilio is also asking if there was any follow up to embargo in certain regions: https://github.com/2i2c-org/infrastructure/issues/2108#issuecomment-1447101176

**Comment by emiliom** [comment]
A correction:

### What hours of the day will participants be active? (e.g., 5am - 5pm US/Pacific)

**6 - 12 US/Pacific**, but individual use will likely continue after hours

**Comment by emiliom** [comment]
@jnywong I've sent two replies to your Nov. 11 email from support@2i2c.freshdesk.com but I haven't heard back. I still don't know if email is the right avenue, or if we should be having those exchanges on a ticket system or here. So, I'll paste the exchanges here.

First I'm pasting what I submitted in my original ticket:

----------------

The second OceanHackWeek (OHW)-in-Spanish event is coming up, Nov 25-29. It follows the previous event from October (see https://github.com/2i2c-org/infrastructure/issues/4883). We have some issues that have came up now or in 2023 that I'd like to address:

#### Environment management for R image.
- The setup we've been using in OHW is complicated, relying on conda when an R package is available on conda-forge and Docker for packages from CRAN and GitHub. For the last two, we can't specify that dependencies be installed or upgraded automatically, so it takes a lot of extra legwork. Can you recommend improvements?
- We're using pretty old versions of RStudio and (in the conda env for R) python and pangeo-notebook, due to previous issues. Can you provide guidance for recent versions that are known to work?
- We ran into a problem where some packages that were already installed and used successfully in 2023 were not recognized (could not be loaded) on RStudio. We need help tracking this down

#### Specifics to use with Latin American audience
- In the Feb. 2023 event we ran into a limitation where participants from Cuba who could not log in to the hub. This must be related to the US embargo, but it's not obvious that US policy dictates such a limitation. Do we have options now to ensure this doesn't happen? See see https://github.com/2i2c-org/infrastructure/issues/2108#issuecomment-1446658760
- I don't expect to need to put much more effort into Spanish localization. But, with your recent experience with hubs for Spanish speaking audiences, do you have some recommendations or best practices?

**Comment by emiliom** [comment]
Regarding the **embargo** and **localization**:

> With the embargo, I do not believe there has been any progress since the previous event.

Too bad. I don't expect that we'll find a solution in the next two weeks, but it'd be really helpful if we could make some progress. Please see the brief exchange I pointed to in my request, from Feb. 2023 (starts [here](https://github.com/2i2c-org/infrastructure/issues/2108#issuecomment-1446658760)), especially the last comment from yuvipanda:

> @emiliom indeed, we can't tell either about what falls under and what does not. Clearly GitHub is accessible, and they don't make any mention of needing OFAC permission to allow it to be accessible in Cuba. I also can't seem to find any mention in Google Cloud of network restrictions being in place. colliand has gratefully offered to chat with CS&S (our fiscal sponsors) to try figure out how to get clarity around this.

Can you comment on at least avenues for exploration of the issue with blocked access in Cuba? Has this issue not come up in 2i2c's collaboration with Metadocencia (the [Catalyst project](https://catalystproject.cloud/))?

> For localisation, I can recommend a CI/CD workflow using GitHub and Crowdin. 

Can you point me to an example of a 2i2c hub that's using this workflow, where I can see the nuts and bolts of what's being localized and how?

We can let the questions about improvements to localization sit. What we've already done covers most of what we'd want, so it's a low priority. But given 2i2c's collaboration with Metadocencia on Catalyst hubs in Latin America, I hoped that there'd be best practices already in place that we could adopt or at least examine. BTW, I was pleased to discover the materials in Spanish already created by that project for "Hub Champion training",  https://catalystproject.cloud/hub-champion-training/es/. That's already helpful. Through that site I also found Catalyst hubs in Latin America that had a lot of boilerplate text on the login page already translated to Spanish.

**Comment by emiliom** [comment]
**Environment management for R image**

> Regarding your questions about environment management, are you using repo2docker? If so, then let me know the GitHub repo and I can take a quick look at your configuration.

We're not using repo2docker. But we do have GH actions that create a R docker image (and a separate Python image) when we update the environment. https://github.com/oceanhackweek/jupyter-image/
The configurations for the R environment are in the "r" directory, specifically in `r/environment.yml` and `r/Dockerfile`; `r/conda-linux-64.lock` is generated from `r/environment.yml`

Would you still be able to help or point us in the right direction? For example, can you point us to the repo of another 2i2c hub that has a full-fledged R environment, including RStudio?

I looked around 2i2c documentation vis a vis repo2docker, and landed here:
https://docs.2i2c.org/admin/howto/environment/
I'm struck that much of what's in the 2i2c base-image repo (https://github.com/2i2c-org/2i2c-hubs-image) is quite old. For example, in the Python requirements file, pandas is pinned to 1.3.5 -- ancient. The repo itself hasn't been updated in 18 months.

Our image building workflow was first created in 2021, when we first adopted a 2i2c hub. It's evolved over time, sometimes incrementally and sometimes in bigger steps. We use the GitHub container repository rather than [quay.io](http://quay.io/) ([quay.io](http://quay.io/) is recommended in the 2i2c docs). We don't use repo2docker, due to problems encountered early on.

The OceanHackWeek technical team is discussing some of the challenges with the R environment / image, including the background that led to it, at https://github.com/oceanhackweek/jupyter-image/issues/90. Feel free to chime in! In PR https://github.com/oceanhackweek/jupyter-image/pull/97 we've updated Python, `pangeo-notebook`, the miniconda3 image and the `rstudio-server` package. We ran into a bunch of issues with conda and libmamba (discussed there), but I think we've resolved them. The image builds w/o errors. **However, RStudio is not launching when clicking on the RStudio launcher in Jupyter Lab, in a local test.** After a wait of a few seconds, we get this screen:

![Image](https://github.com/user-attachments/assets/f955eb3b-3ceb-486d-bbc1-bceae37dbb71)

I'll be happy if we can just get this updated image to work. I've already found a way to make it easier to manage R package dependencies.

**Comment by jnywong** [comment]
I was able to pull [your most recent published R image](https://github.com/oceanhackweek/jupyter-image/pkgs/container/r) into a 2i2c hub and did not come across a 500 error.

![Image](https://github.com/user-attachments/assets/bbe7f497-fec9-4e04-a6cd-54c49b4d31d2)

You can see from the screenshot that the RStudio launcher is available and opens RStudio fine, and that `$JUPYTER_IMAGE=ghcr.io/oceanhackweek/r:41445c1`. 

I believe this version is missing a few upgrades that you are trying to add in https://github.com/oceanhackweek/jupyter-image/pull/97 but I am unfortunately unable to follow your custom image-building setup.

> Would you still be able to help or point us in the right direction? For example, can you point us to the repo of another 2i2c hub that has a full-fledged R environment, including RStudio?

I can point you in the direction of our community CryoCloud's RStudio configuration that follows our recommended repo2docker action: https://github.com/CryoInTheCloud/hub-Rstudio-image.

You can also try asking others on the Jupyter discourse and you are welcome to ask our other community members on our 2i2c Slack workspace.

**Comment by jnywong** [comment]
You're welcome!

I will try my best to see how we can progress on the embargo issue, as we are aware that this affects a few of our users.

I have sent you an invitation link back on the email thread that we have on the support desk 👍

**Comment by emiliom** [comment]
@jnywong I've submitted PR #5167 with updates to the R and Python images. That includes significant upgrades to core components in the R image. Thanks to you and Angus for the help!

**Comment by jnywong** [comment]
Hi @emiliom !

I hope your event went smoothly last week. I am going to mark this issue as closed now but feel free to let us know your comments in this thread if you wish.

Best wishes

**Comment by emiliom** [comment]
Sounds good. I'll try to follow up in a few days with feedback.

In the meantime, @jnywong could I ask you to merge one last PR to update the hub?  PR #5242

Thanks to you and others for all your help!

**Comment by jnywong** [comment]
Done. Thanks @emiliom !
