### ISSUE TITLE
Add retrolab to our user images

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#506]
https://github.com/jupyterlab/retrolab/ is a great option to replace classic notebook for educational use cases, and we should provide it in our images.

# Tasks

- [ ] Update [our user image requirements](https://github.com/2i2c-org/pilot-hubs/blob/master/images/user/requirements.txt) to install retrolab
- [ ] Document the use of retrolab in our Hub Administrator's guide
- [ ] Confirm that retrolab is available on the hubs using our default user image

**Comment by choldgraf** [comment]
I added a few tasks to this one so that the next steps are clear, lemme know if I missed something there

**Comment by yuvipanda** [comment]
retrolab is notebook 7 now.
