### ISSUE TITLE
Enable automated backups of EBS volumes on VEDA staging hub

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#5061]
### Context

We will be moving forward on automated backups for AWS EBS volumes using the [Data Lifecycle Manager](https://docs.aws.amazon.com/ebs/latest/userguide/snapshot-lifecycle.html) option. 

- Automatically create daily backups
- Retention period of 5 days
- Deploy and test on VEDA staging hub first

### Task list

```[tasklist]
- [x] Create an IAM role for DLM service in terraform
- [x] Apply the target tag to existing EBS volumes for which automated backup has to be enabled.
- [x] Set up a DLM lifecycle policy, that defines the time and interval of backup creation, retention period and a target tag for selection of EBS volumes for backing up, in terraform
- [x] Set `Backup = true` on the existing EBS volume for staging
- [x] Wait a day and see if a backup has been created
- [x] Investigate how to restore from backups
- [x] Document feature and how to restore from backup
```

### Definition of Done

- [ ] The feature/service is technically complete
- [ ] Deployed to staging hub
- [ ] The feature/service been tested with one or more users (if applicable)
- [ ] The feature/service is well documented, and the documentation is accessible for the target user base

**Comment by sgibson91** [comment]
#5189 applied successfully!

The policy will execute a backup snapshot at 23:45 UTC every day, so next items are:

- [ ] Check back tomorrow to see if a backup snapshot of the staging EBS volume has been created
- [ ] Check back in >5 days time to ensure we are only retaining 5 backup snapshots for the EBS volume

**Comment by sgibson91** [comment]
AWS's docs on restoring EBS volume from a snapshot https://docs.aws.amazon.com/prescriptive-guidance/latest/backup-recovery/restore.html#restore-snapshot

**Comment by sgibson91** [comment]
Gotcha: double check terraform state hasn't changed state due to the backup, see for example the GCP backup docs https://infrastructure.2i2c.org/howto/filesystem-backups/restore-filesystem/#gcp

**Comment by sgibson91** [comment]
Woohoo! Another piece completed!

**Comment by yuvipanda** [comment]
Great job, @sgibson91 and @sunu! 

Unfortunately I don't think this is quite complete yet. I've left a comment in https://github.com/2i2c-org/infrastructure/pull/5286/files#r1887447565.

**Comment by sgibson91** [comment]
Did we close this in the end? @yuvipanda @sunu

**Comment by yuvipanda** [comment]
@sgibson91 i am not sure! once either of you verify (via the aws console maybe?) feel free to close this if appropriate.

**Comment by sgibson91** [comment]
I think the comment you left on the PR was more about the docs to do recovery. But I will certainly click around in the console to ensure back-ups are enabled next week.

**Comment by sunu** [comment]
@yuvipanda @sgibson91 We have automated snapshots for both VEDA staging and prod hubs:

<img width="1213" alt="Image" src="https://github.com/user-attachments/assets/e4cfd659-05b2-407b-93ad-2edcf934ace5" />

And as Sarah mentioned, we have updated the deployer CLI to create a PV and PVC with the volume hosting the snapshot attached to do a copy and updated the documentation accordingly in https://github.com/2i2c-org/infrastructure/pull/5291

I think we can close this issue as completed.
