### ISSUE TITLE
Enable disk size alerting for AWS EBS volumes on VEDA staging hub

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#5062]
### Context

 - Default JupyterHub dashboards live in https://github.com/jupyterhub/grafana-dashboards
 - Start in the infra repo, then have a discussion about upstreaming

### Task list

```[tasklist]
- [x] Use [Prometheus metric exporter](https://github.com/2i2c-org/infrastructure/blob/main/helm-charts/basehub/templates/home-space-reporter.yaml) and mount the whole NFS disk as a volume
- [x] Verify the graphs that report disk size continue to make sense when referring to EBS volumes, and both staging and prod volumes are captured in a way that is distinguishable from on another
- [x] Investigate and enable Grafana alerting based on some threshold, alerts sent to support[at]2i2c.org (alerting was manually enabled)
- [x] Deploy to VEDA staging hub
- [x] Enable alerting via Prometheus AlertManager to PagerDuty
- [x] Test by setting the threshold to something really low and see if an alert is triggered
- [x] Document the feature, the notifications, and how to resize the EBS volume
```

### Definition of Done

- [x] The feature/service is technically complete
- [ ] The feature/service been tested with one or more users (if applicable)
- [x] Deployed to VEDA staging hub
- [x] Feature has been tested to fire an alert
- [ ] The feature/service is well documented, and the documentation is accessible for the target user base

**Comment by GeorgianaElena** [comment]
@sgibson91, raising here for visibility so you're not caught by surprise in case you haven't seen https://github.com/2i2c-org/infrastructure/pull/4923 (for more context https://2i2c.slack.com/archives/C055A1J1DRP/p1727942694562319)

**Comment by sgibson91** [comment]
Thank you @GeorgianaElena I did see it and did remember about it, but hadn't done the work digging it out yet! Thank you!

@sunu, https://github.com/2i2c-org/infrastructure/pull/4923 will need to be reverted for Grafana alerting :)

**Comment by sgibson91** [comment]
@sunu found it difficult to programatically enable grafana alerting via grafonnet. I have proposed that we add the enablement of alerts and a one-time manual step in our hub deployment guide for now to close this issue out. I will open an issue to track a spike investigating grafonnet further in the new year, maybe with more 2i2c folks helping him.

**Comment by sgibson91** [comment]
Grafana needs access to an SMTP server to send emails

**Comment by yuvipanda** [comment]
@sgibson91 let's send these alerts to pagerduty rather than use smtp directly. I think the integration will be more straightforward this way, given we already do that in https://github.com/2i2c-org/infrastructure/blob/main/terraform/uptime-checks/pagerduty.tf

**Comment by sgibson91** [comment]
Amazing, thank you for the suggestion @yuvipanda!

**Comment by yuvipanda** [comment]
Another simpler suggestion is to try to use [prometheus alertmanager](https://prometheus.io/docs/alerting/latest/alertmanager/). We already have it deployed, but disabled (https://github.com/2i2c-org/infrastructure/blob/ace761ca9613162d3570fc4708cb59571129e2f0/helm-charts/support/values.yaml#L72 (with an inline comment that is not true anymore)).

It should be easier than trying to automatically do this in grafana:

1. The pagerduty service key can be set in yaml config (https://prometheus.io/docs/alerting/latest/configuration/#pagerduty_config) in our secret config (https://github.com/2i2c-org/infrastructure/blob/main/helm-charts/support/enc-support.secret.values.yaml) as that's the same for all our clusters
2. Alerts are generated by prometheus itself, using YAML based alerting rules (https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/). This would go in our support chart config
3. The alert configuration itself is a prometheus expression, which is exactly the same as it is for grafana! So while what does the alerting and where it goes is different, the source of the data and how it's expressed is the same.

This would also allow us to add more alerting in the future without having to directly tie it to a grafana graph.

**Comment by yuvipanda** [comment]
> I have proposed that we add the enablement of alerts as a one-time manual step in our hub deployment guide for now to close this issue out.

These alerts may get overwritten when we deploy the grafana dashboard next, so will have to be checked to see if they persist.

**Comment by sunu** [comment]
> Another simpler suggestion is to try to use [prometheus alertmanager](https://prometheus.io/docs/alerting/latest/alertmanager/)

Yes, lets go with alertmanager if that's an option.

**Comment by sgibson91** [comment]
@sunu and I checked the grafana panel for disk free space today and all looks good, so I've checked off that task.

**Comment by sgibson91** [comment]
> 1. The pagerduty service key can be set in yaml config (https://prometheus.io/docs/alerting/latest/configuration/#pagerduty_config) in our secret config (https://github.com/2i2c-org/infrastructure/blob/main/helm-charts/support/enc-support.secret.values.yaml) as that's the same for all our clusters

@sunu I re-read this and realised we don't have a pagerduty key configured yet. I can create a new service integration on our pagerduty account and add the info into this file for you to use though.

**Comment by sgibson91** [comment]
#5234 adds the integration secrets. I followed this guide for what to do on pagerduty https://www.pagerduty.com/docs/guides/prometheus-integration-guide/ but I didn't do any of the steps recommended on the prometheus server.

I gave the secrets the top-level key name of `pagerduty-prometheus-integration`, but feel free to change this if needed.
