### ISSUE TITLE
[EPIC] Deploy jupyterhub-home-nfs to nmfs-openscapes

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#5066]
### Context

Deploy the jupyterhub-home-nfs project to the nmfs-openscapes cluster and migrate the home directories

### Task list

```[tasklist]
- [ ] https://github.com/2i2c-org/infrastructure/issues/5068
- [ ] https://github.com/2i2c-org/infrastructure/issues/5069
- [ ] https://github.com/2i2c-org/infrastructure/issues/5070
- [ ] https://github.com/2i2c-org/infrastructure/issues/5071
- [ ] https://github.com/2i2c-org/infrastructure/issues/5072
- [ ] https://github.com/2i2c-org/infrastructure/issues/5073
```

### Definition of Done

- [x] Both staging and prod hubs are now backed by EBS volumes for home dir storage
- [x] Both staging and prod hubs have per-user home dir quotas enforced
- [x] The original EFS instance has been cleaned up
