### ISSUE TITLE
Deploy jupyterhub-home-nfs to CryoCloud

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#5067]
### Context

Deploy the jupyterhub-home-nfs project to the CryoCloud cluster and migrate the home directories

- Relevant docs: https://infrastructure.2i2c.org/howto/features/storage-quota/

### Task list

```[tasklist]
- [x] Determine disk size and quota for staging hub
- [x] Create an in-cluster EBS volume for staging hub
- [x] Migrate staging hub home dirs from EFS to EBS volume
- [x] Determine migration window with CryoCloud community for prod
- [x] Determine disk size and quota for prod hub
- [x] [During migration window] Migrate CryoCloud prod hub home dirs from EFS to EBS
- [x] Decommission old EFS instance from CryoCloud
```

### Definition of Done

- [x] Both staging and prod hubs are now backed by EBS volumes for home dir storage
- [x] Both staging and prod hubs have per-user home dir quotas enforced
- [ ] The original EFS instance has been cleaned up

**Comment by sgibson91** [comment]
Since this is exactly the same work that I did for nmfs-openscapes, I took the opportunity to size this by: adding up all the points allocated to the nmfs-openscapes migration tasks, then choosing a number on our fibonacci scale closest to that sum.

**Comment by sgibson91** [comment]
I would also love for someone _not me_ to do this migration to spread the knowledge!

**Comment by sgibson91** [comment]
Based on https://grafana.cryointhecloud.2i2c.cloud/goto/VLzL7vVNg?orgId=1 the largest home dir is 321GB. Adding 10% would give a quota for prod of ~350GB

**Comment by sgibson91** [comment]
I am trying to do the transfer for prod using the workflow @yuvipanda laid out in

**Comment by sgibson91** [comment]
I will decommission the old filestore on Monday in case any issues crop up over the weekend

**Comment by yuvipanda** [comment]
Excellent work @sgibson91!

Let's set the decom date to next thursday instead, as i think most of the cryocloud folks are at agu
