### ISSUE TITLE
[New Hub] [Due by: 2024-12-06 ] [Spike: 30mins] Refine deployment phases - NASA-MAAP

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#5142]
A request (https://2i2c.freshdesk.com/a/tickets/2477) came in as part of NASA VEDA to deploy a new hub for MAAP:

>   We would like to stand up a new JupyterHub to support the Multi-Mission Algorithm and Analysis Platform (MAAP) project.  Below is relevant information I found referencing an earlier ticket
>  
> Community representative
> @wildintellect
> @freitagb
>  
> Hub important dates
> Target Start Date: 2024-12-06
> Required Start Date: 2025-01-06
>  
> Hub Authentication Type
> GitHub
>  
> First Hub Administrators
> Alex Mandel (@wildintellect)
> Brian Freitag (@freitagb)
>  
> Hub logo image URL
>  
> https://maap-project.org/wp-content/uploads/2021/10/nasamaaplogo3.png
>  
> Hub logo website URL
>  
> https://maap-project.org/
>  
> Extra features to enable
>  
> Please replicate the current VEDAHub infrastructure
>  
> Cloud Provider
> AWS
>  
> Cloud Region
> us-west-2
>  
> Billing and cloud account
> SMCE-MAAP account
>  
> Other relevant information
> This hub deployment request is part of 2i2c's ongoing NASA VEDA project. The ESDIS hub will be launched with configuration and image based on the VEDAHub. The hub should be deployed in the NASA SMD cluster where 2i2c is currently operating the NASA VEDA hub.

 
### Tasks

```[tasklist]
- [x] Refine the requirements for this new hub deployment
- [x] Open the relevant Phase 1,2,3 issues with all of the required information
```

### Definition of Done

Each of the below phases for this new hub deployment should:
- have an open issue,
- have all the relevant information in the issue tables filled out and sections marked as READY,
- have been placed in the Refined column of the Engineering board.

- [x] [Phase 1](https://github.com/2i2c-org/infrastructure/issues/new?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen&template=03_new-hub_phase-1.yaml)
- [x] [Phase 2](https://github.com/2i2c-org/infrastructure/issues/new?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen&template=04_new-hub_phase-2.yaml)
- [x] [Phase 3](https://github.com/2i2c-org/infrastructure/issues/new?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen&template=05_new-hub_phase-3.yaml)

**Comment by yuvipanda** [comment]
Note that there is two conflicting pieces of info here:

> The hub should be deployed in the NASA SMD cluster where 2i2c is currently operating the NASA VEDA hub.

and 

> Billing and cloud account
> SMCE-MAAP account

The VEDA hub is on the SMCE-VEDA account. None of us have access to the SMCE-MAAP account.

So part of Phase 1 would be that one person gets access, and then creates accounts for every other engineer.

**Comment by yuvipanda** [comment]
Note we also have additional documentation for dealing with NASA SMCE aws accounts https://infrastructure.2i2c.org/hub-deployment-guide/new-cluster/smce/

**Comment by wildintellect** [comment]
@yuvipanda which 2i2c engineers already have SMCE "training" and access to the VEDA SMCE, we can request access to the MAAP SMCE for those same engineers, or new ones who do the "training"

**Comment by yuvipanda** [comment]
Given all of us have SMCE VEDA access, I think it means all of us already have the training.

**Comment by wildintellect** [comment]
@freitagb I think you need to email SMCE for this request (cc: @jjfrench)

**Comment by sgibson91** [comment]
The following issues have been opened to track deployment of this new community, and prioritised accordingly in the Up Next column of the P&S board:

- https://github.com/2i2c-org/infrastructure/issues/5197
- https://github.com/2i2c-org/infrastructure/issues/5198
- https://github.com/2i2c-org/infrastructure/issues/5199

Please redirect any relevant conversation to the above issues
