### ISSUE TITLE
Test performance of EBS volumes as home directory storage

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#5187]
### Context

The main question we want to answer is:

> Is the default of 3000 IO/s and 125MB/s we get (with gp3 volumes) enough to provide users with their expected performance?

For comparison, EFS provides 90,000-250,000 IO/s and 10-60 GB/s (read) 1-5 GB/s (write) throughput (technically) so we will be almost an order of magnitude down using EBS and should understand how this will affect users.

### Relevant links

- https://aws.amazon.com/ebs/pricing/ (has performace and iops numbers for EBS)
- https://docs.aws.amazon.com/efs/latest/ug/performance.html#performance-overview (has numbers for EFS)
- https://fio.readthedocs.io/en/latest/fio_doc.html (alternative tooling)

### Task list

```[tasklist]
 - [ ] Decide what this 'standard activity' is: An example is "time taken for a `git clone https://github.com/torvalds/linux` to complete". We should put the repo in a local path in a container and clone from there to isolate confounding factors such as a network.
 - [ ] Design and implement infrastructure that allows us to to provide something to test the standard activity on and scale it to replicate many users
 - [ ] Record measurements on the NFS server (EBS)
 - [ ] Do 'standard activity' with increasing number of parallel clients, and record both how long the activity takes, and measurements on the server
```

### Definition of Done

- [ ] Simulate N number of users performing some standard activity on home directories to understand at what point the standard activity becomes unbearably slow.
