### ISSUE TITLE
[EVENT][{{ dates }}] {{ HUB NAME }}

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/infrastructure#5223]
### The link towards the Freshdesk ticket this event was reported

https://2i2c.freshdesk.com/a/tickets/2520

### The GitHub handle or name of the community representative

@hazemmahmoudnasa, Hazem Mahmoud

### The date when the event will start

January 10, 2025

### The date when the event will end

January 20, 2025

### What hours of the day will participants be active? (e.g., 5am - 5pm US/Pacific)

1:00pm - 5pm CST (New Orleans, USA)

### Are we three weeks before the start date of the event?

- [x] Yes
- [ ] No

### Number of attendees

30

### Make sure to add the event into the calendar

- [x] Done

### Does the hub already exist?

- [x] Yes
- [ ] No

### The URL of the hub that will be used for the event

https://workshop.openscapes.2i2c.cloud/

### Will this hub be decommissioned after the event is over?

- [ ] Yes
- [x] No

### Task list

- [ ] Was all the info filled in above?
- [ ] Quotas from the cloud provider are high-enough to handle expected usage?
- [ ] Shared password set up? (See FreshDesk ticket)

### Definition of Done

- [ ] All the tasks have been completed
- [ ]
