### ISSUE TITLE
Deploy jupyterhub-home-nfs to LEAP

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/infrastructure#5231]
### Context

Deploy the jupyterhub-home-nfs project to the LEAP cluster and migrate the home directories

- Relevant docs: https://infrastructure.2i2c.org/howto/features/storage-quota/

FreshDesk: https://2i2c.freshdesk.com/a/tickets/2525

### Task list

```[tasklist]
- [ ] Determine disk size and quota for staging hub
- [ ] Create an in-cluster EBS volume for staging hub
- [ ] Migrate staging hub home dirs from EFS to EBS volume
- [ ] Determine migration window with community for prod
- [ ] Determine disk size and quota for prod hub
- [ ] [During migration window] Migrate prod hub home dirs from EFS to EBS
- [ ] Decommission old EFS instance
```

### Definition of Done

- [ ] Both staging and prod hubs are now backed by EBS volumes for home dir storage
- [ ] Both staging and prod hubs have per-user home dir quotas enforced
- [ ] The original EFS instance has been cleaned up

**Comment by yuvipanda** [comment]
This is still open and separate from #5305

**Comment by jnywong** [comment]
Ah okay thought this was a duplicate! Thank you Yuvi

**Comment by jbusecke** [comment]
Hey folks, just wanted to check in on the status here. Do you think this is achievable before Jan 31st?

**Comment by yuvipanda** [comment]
@jbusecke I don't think this will happen before Jan 31st unfortunately, because we haven't deployed this on any GCP cluster yet :( but we can kick off planning for this before then.

**Comment by jbusecke** [comment]
Oh bummer. But hopefully this can be achieved without too much input from the LEAP side. What actions can we get finished up for now?

Lets discuss this more during the call?

**Comment by jnywong** [comment]
This issue is superseded by #5472 , #5473 , #5474 and #5476 . Closing as duplicate.
