### ISSUE TITLE
Set resource requests and limits on jupyterhub-nfs-home nfs-server pod

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#5285]
### Context

We should apply resource requests and limits (memory and cpu) to the NFS server pod running in jupyterhub-home-nfs enabled hubs.

Current deployments are:

- [ ] nmfs-openscapes: staging + prod
- [ ] nasa-cryo: staging + prod
- [ ] nasa-veda: staging

### Task list

```[tasklist]
- [ ] Apply some resource requests and limits to nfs server pod running in nasa-cryo
- [ ] Observe behaviour of nfs-server pod for some time (5 working days?) and make tweaks to requests and limits as needed
- [ ] When suitable requests and limits have been ascertained, roll these out to all hubs currently running jupyterhub-home-nfs
- [ ] Add ability to set resource contraints into jupyterhub-home-nfs chart
```

### Definition of Done

- [ ] The NFS server pod in all jupyterhub-home-nfs enabled hubs has some resource requests and limits for memory and cpu applied
- [ ] These requests and limits have been observed not to immediately break functionality
- [ ] Documentation has been updated to include setting the resource requests and limits

**Comment by sgibson91** [comment]
Next sprint: pairing session with Yuvi to solidify what needs to be done for monitoring to figure out the resource limits

**Comment by sgibson91** [comment]
Yuvi and I are pairing on this tomorrow (Wednesday 29th Jan)

**Comment by sgibson91** [comment]
I have created a dashboard on CryoCloud here: https://grafana.cryointhecloud.2i2c.cloud/goto/QpkKN3ONR?orgId=1

<img width="803" alt="Image" src="https://github.com/user-attachments/assets/6801d61e-0da5-499c-86d2-3f1864951a55" />

To me this would suggest the following guarantees/limits would be reasonable from the prod curves

Resource | Guarantee | Limit
CPU | 0.1 | 1
Memory (GB) | 3 | 9

**Comment by sgibson91** [comment]
Even if we wanted to set resource limits on just CryoCloud for now, currently the jupyterhub-home-nfs helm chart doesn't permit those values in the deployment template.

So we will need to add those values into jupyterhub-home-nfs, cut a new release, and pull in the new version from basehub.

**Comment by sgibson91** [comment]
I took a stab at a new set of grafana dashboards for resource usage https://grafana.cryointhecloud.2i2c.cloud/goto/lmdIuqOHR?orgId=1

**Comment by sgibson91** [comment]
I have updated the per container dashboard: https://grafana.cryointhecloud.2i2c.cloud/goto/gjT4gFFNg?orgId=1

For each container (there are 3), it looks at: (sum of the rate of) total cpu usage seconds, average over time of memory usage, and maximum over time of memory usage.

Therefore for CryoCloud, I propose:

| Container name | Resource | Request | Limit |
| :--- | :--- | ---: | ---: |
| nfs-server | CPU | 0.1 | 0.2 |
| | Memory (GB) | 30 | 32 |
| enforce-xfs-quota | CPU | 0.01 | 0.02 |
| | Memory (MB) | 10 | 11 |
| metrics-exporter | CPU | 0.01 | 0.02 |
| | Memory (MB) | 11 | 13 |

**Comment by sgibson91** [comment]
Draft PR here https://github.com/2i2c-org/infrastructure/pull/5487

I've deployed to CryoCloud staging and will observe for a day or so before merging

**Comment by sgibson91** [comment]
I resolved the issues with deploying the PR to CryoCloud staging, I will monitor for 24 hours then merge and close this tomorrow.
