### ISSUE TITLE
Remove ability to choose different backends when working with GCP terraform

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#5313]
### Context

This was a feature we needed for a project with restrictive access policies that has now been decommissioned. In the future, we should ensure that we can access projects with 2i2c emails so we don't need to be either signed into 2 google accounts, or creating a specific terraform state backend for the project we are using.

### Task list

```[tasklist]
 - [ ] Revert this commit https://github.com/2i2c-org/infrastructure/commit/7cc456e3b2737a7ac441863774cac54a15293e45
 - [ ] Remove any mention of backends in terraform docs
```

### Definition of Done

- [ ] There is no longer a separate backend storing terraform state
- [ ] Documentation has been updated to remove mentions of this feature
