### ISSUE TITLE
[Platform Initiative] Associate users with groups for usage and costs monitoring

### ISSUE THREAD

**Issue by Gman0909** [2i2c-org/infrastructure#5315]
# Description

We need to allow admins of hubs to see aggregated usage information based on what groups a user belongs to. This would allow them to have a better understanding of which groups are using how much resources, and advocate for better funding / cost recovery based on their own internal representations and needs.

Please review the insights in the original [Product Board initative](https://2i2c.productboard.com/roadmap/7947557-2i2c-roadmap/features/27195081/insights)

# Tasks

- Allow associating a single user with multiple groups they may belong to. This information must be externally managed, probably by whatever authentication provider is used. 
  - As a starting point for an MVP, let us use GitHub authentication, with groups indicated by membership in GitHub teams. But the implementation should be agnostic to the authentication mechanism used.
- Collect information on what kind of usage reports will be useful to admins. Our existing Grafana Dashboard may be used as a starting point.
- Add ability to filter based on group membership to usage reports grafana dashboards
- Find out how to handle the problem of overlapping groups.
  - For example, a user may be a member of both the statistics and physics departments. When they start a server and consume those resources, who should that be attributed to? What about storage, which is temporally different (it is 'used' as soon as a byte is written, whereas memory / cpu / GPU are only used when the user is actively using it). 

# Definition of Done

- [ ] The feature/service is technically complete
- [ ] It’s been tested with one or more users (if applicable)
- [ ] It’s been deployed to a production cluster
- [ ] It has been shown to be replicably deployable
- [ ] It is well documented
- [ ] It has been added to our product menu.
- [ ] Lessons learned have been documented
