### ISSUE TITLE
Rename this repository to `infrastructure`

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#570]
This repository is called `pilot-hubs`, which might make you think it deploys the hubs under `*.pilot.2i2c.cloud`. However, it actually deploys almost *all* the hubs we maintain - see list under https://github.com/2i2c-org/pilot-hubs/tree/master/config/hubs.

We should rename this repository to make that clearer.

How about just `infrastructure`?

### Tasks

- [x] Rename `pilot-hubs` to `infrastructure`
- [x] Update ReadTheDocs URLs
- [x] Point `infrastructure.2i2c.org` to these docs
- [x] Update references to `pilot-hubs.2i2c.org` or `devops.2i2c.org` to `infrastructure.2i2c.org`
  - [x] https://github.com/2i2c-org/team-compass/pull/267
  - [x] https://github.com/2i2c-org/2i2c-org.github.io/pull/81
  - [x] https://github.com/2i2c-org/pilot/pull/107
  - [x] https://github.com/2i2c-org/infrastructure/pull/758

**Comment by yuvipanda** [comment]
Also what exactly are we piloting? I think we should define that and use it only in appropriate places.

**Comment by choldgraf** [comment]
For renaming this repository, it sounds good to me. `infrastructure` is a little bit generic but also accurate, I think. Other options could be `deployments / deploy`, `cloud`, `hubs`?

For "what are we piloting?" I think the answer is that we are piloting a few things:

- At the highest level, we are piloting a model for a Managed Hub Service for 2i2c. This entails a few different things we're trying out as a part of the pilot:
  - CI/CD infrastructure to deploy multiple independent hubs from a single source (`pilot-hubs/` until we rename it)
  - Support mechanisms and processes for these hubs (e.g. FreshDesk, issues to create new hubs, etc)
  - Sales / contracting processes for bringing on new hubs
  - Sustainability models for generating resources that keeps this service running / growing
  - (not unique to the managed service): Team processes for coordinating and prioritizing our time

So in general, when I think "Our pilot", I mean the combination of things above.

**Comment by damianavila** [comment]
I like the `infrastructure` proposal.

> So in general, when I think "Our pilot", I mean the combination of things above.

I agree with this view... 
Although maybe we need to be a little bit more fine-grained and ask ourselves what we are piloting on *each* of those items...

**Comment by choldgraf** [comment]
# Proposal

Are there any objections to the following:

- We rename this repository to `infrastructure`
- We point `infrastructure.2i2c.org` to this documentation

?

**Comment by yuvipanda** [comment]
That sounds great, @choldgraf

**Comment by choldgraf** [comment]
this is now done!
