### ISSUE TITLE
Improve the hub health check in deployer

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#586]
# Summary

In CI/CD we are seeing a lot of failed deployments when we test a hub's health. The most common reason is that the tests triggered a node to be spun and up and things timed out before that node was ready to accept the test pods. Can we add some delays to our testing framework that allow the nodes enough time to be spun up and/or do something like the mybinder.org tests where 3 attempts are made before reporting failure?

https://github.com/jupyterhub/mybinder.org-deploy/blob/4e818778a4d6980427c6a519f99508dcfdbbc8ea/.github/workflows/cd.yml#L138-L144

### Tasks to complete

- [ ] Investigate the major causes of health check failures that should not be failures, identify one or two that we can design tests around
  - [ ] Comment here: https://github.com/2i2c-org/infrastructure/pull/819#issuecomment-964582997
- [ ] Update our health check infrastructure to be robust to these failures

**Comment by damianavila** [comment]
> Can we add some delays to our testing framework that allow the nodes enough time to be spun up and/or do something like the mybinder.org tests where 3 attempts are made before reporting failure?

I like the idea!!

**Comment by yuvipanda** [comment]
I opened https://github.com/catalyst-cooperative/pudl-examples/pull/4 to include dask-gateway in the catalyst coop image, so tests can pass for that.

**Comment by choldgraf** [comment]
@sgibson91 noted a weird error message we should investigate here: https://github.com/2i2c-org/infrastructure/pull/819#issuecomment-964582997

**Comment by sgibson91** [comment]
So I think there are 2 causes for node scale-up when we run our hub health checks:

1. The addition of the deployment-service-check pod (which is mimicking a user) triggers a scale up. We can try to make this more efficient by not timing out tests when the pod is in any other state than `Ready`, trying multiple times, adding delays as described above. But generally, we should eat this cost I think.
2. When we test a daskhub, we also test that a dask cluster can be requested and scaled up. This causes another scale-up of the dask nodepools. Is it really efficient to be testing that feature every time we deploy a hub? Could we not run that kind of test as a cron job in the cluster instead? And run it manually when we know we've triggered a change in the dask helm chart?

**Comment by damianavila** [comment]
> But generally, we should eat this cost I think.

👍 

> Could we not run that kind of test as a cron job in the cluster instead? And run it manually when we know we've triggered a change in the dask helm chart?

I would be OK with that, I think... 
In fact, I would love to have automatic running of dask tests when we change things that are dask-related, but not sure how realistic that request would be...

**Comment by choldgraf** [comment]
I think @sgibson91's proposals sound good on both points!

**Comment by sgibson91** [comment]
Linking another issue in here too as I think it's a sub-issue of this one (if we were to turn this into a project, for instance)

- https://github.com/2i2c-org/infrastructure/issues/971

**Comment by sgibson91** [comment]
Another avenue for testing is being discussed here https://github.com/2i2c-org/infrastructure/issues/1024#issuecomment-1054127147

**Comment by sgibson91** [comment]
For posterity, I also just received this warning from pytest

```
===================================================================== warnings summary ======================================================================
../../../../../../usr/local/Caskroom/miniconda/base/envs/pilot-hubs/lib/python3.9/site-packages/pytest_asyncio/plugin.py:191
  /usr/local/Caskroom/miniconda/base/envs/pilot-hubs/lib/python3.9/site-packages/pytest_asyncio/plugin.py:191: DeprecationWarning: The 'asyncio_mode' default value will change to 'strict' in future, please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest configuration file.
    config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)
```

**Comment by sgibson91** [comment]
PR #1185 separated the hub health check from the logic that deploys a hub. This separation will allow to implement retry logic on the hub health check without needing to redeploy a hub with every retry.

**Comment by sgibson91** [comment]
PR #1189 now means we retry the hub health check a maximum of 3 times with a timeout of 10 minutes before we declare a failure in CI

**Comment by sgibson91** [comment]
I believe we can also close this as well given recent work. @consideRatio would you mind writing up the remaining todos we had from our little sprint as new issues please?

**Comment by damianavila** [comment]
> @consideRatio would you mind writing up the remaining todos we had from our little sprint as new issues please?

Were those remaining todos already captured, @sgibson91 and @consideRatio?

**Comment by consideRatio** [comment]
I think we are good to move on, but I'm not sure - I didn't recognize the error linked out to the third checkox.

**Comment by sgibson91** [comment]
> Were those remaining todos already captured

@damianavila the issues are https://github.com/2i2c-org/infrastructure/issues/1206 and https://github.com/2i2c-org/infrastructure/issues/1232
