### ISSUE TITLE
Improve team documentation for debugging AWS clusters

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#590]
# Summary

In https://github.com/2i2c-org/pilot-hubs/issues/526 we discovered that there were a number of undocumented steps we needed to take in debugging the CarbonPlan AWS cluster. We should improve our pilot-hubs documentation with this information for the future.

# Tasks to complete

- [ ] Document how to `ssh` into a node in a `kops` cluster
- [ ] Document how to identify the appropriate autoscaling group for an instancegroup so you can look at its activity report.
- [ ] Document how to perform manual nodegroup scaling operations for each instancegroup via the AWS console.
