### ISSUE TITLE
Grant access to eks clusters to folks other than the user who first created the cluster

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#602]
# Summary

EKS auth is a strange beast - particularly, the [aws-auth configmap](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html). By default, only the user (or role) that created the EKS cluster has access to the cluster. In our case, this will be whichever engineer happens to create the cluster for the first time. We should explicitly list the AWS users who can have access to this cluster.

Alternatively, we can create a role for each cluster, and give rights to that role. Admin AWS users can then 'assume' this role for kubectl work, making things simpler.

# User Stories

- As a 2i2c engineer, I need `kubectl` access to k8s clusters so I can debug issues and deploy manually
- As a member of the hub community, I want `kubectl` access ot the k8s cluster so I can debug things and experiment with new functionality.

# Acceptance criteria

- AWS users can authenticate to kubernetes cluster with `kubectl` after doing `aws eks update-kubeconfig --name=carbonplanhub --region=us-west-2`
- List of these AWS users is maintained in config, and automatically kept in sync with `aws-auth` configmap

# Important information

It must contain an entry for each nodegroup created by [eksctl](https://eksctl.io/), so nodes in that nodegroup can talk to AWS to fetch information about themselves and connect to the k8s master. If you `mapRoles` for the nodegroups from the `aws-auth` configmap (as I did), the nodes will immeidately get too `NotReady` state. So this configmap *must* be managed by `eksctl`, with its [iamidentitymapping](https://eksctl.io/usage/iam-identity-mappings/) command. If we try to use helm to manage it, we might lose `mapRoles`, putting the cluster out of action.

# Tasks to complete

- [ ] Create an AWS role that can be assumed by AWS users to gain `kubectl` access to a cluster
- [ ] Add entry in `aws-auth` configmap to give admin access to this role
- [ ] Document how you can get `kubectl` access while using this role

**Comment by yuvipanda** [comment]
I just gave @jhamman access to the carbonplanhub cluster by manually adding his name to mapUsers. Using a role is the 'right' way to go though.

**Comment by yuvipanda** [comment]
This is documented now https://github.com/2i2c-org/infrastructure/blob/eb13f49266734b66871bd012419d809e2e580d31/docs/hub-deployment-guide/new-cluster/aws.md?plain=1#L271
