### ISSUE TITLE
Carbon Plan Dask worker improvements

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#607]
# Summary

In #291 we found that there were several optimizations to the Dask Workers / AWS setup in order to minimize costs. This is a tracking issue for the major things that we need to accomplish.

# Tasks to complete

- [x] https://github.com/2i2c-org/pilot-hubs/issues/490  
- [ ] Fix x1 instances, for both notebooks and dask
- [ ] Consider using mixed-instance types, to ensure better pricing & availability of nodes

**Comment by yuvipanda** [comment]
Carbonplan is no longer with us.
