### ISSUE TITLE
Status page for our clusters

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#609]
# Summary

There are many cases where our clusters might be down for one reason or another (e.g. upgrades, outages, etc). In those cases, it's helpful if there is a source of truth for "is 2i2c's infrastructure down, or is it just me?". We should have a place to point users to so that they can quickly answer this question.

# Important information

The most common service I've seen for this is [`statuspage.io`](https://www.atlassian.com/software/statuspage), which [even has a non-profit discount](https://support.atlassian.com/statuspage/docs/apply-for-a-community-open-source-or-academic-license/).

# Tasks to complete

- [ ] Decide what kind of service we'd like to use for a status page
- [ ] ...figure out steps to implement this
- [ ] Document the new status page in our user and team documentation

**Comment by abkfenris** [comment]
I've spent some time poking around status page options for some non JupyterHub infrastructure that my team runs, looking for free & low management options. 

- [Instatus](instatus.com/) has a pretty full featured free plan, and can integrate with various monitoring services (and is [adding their own monitoring soon](https://twitter.com/alisalahio/status/1426554270539821058))
- [Upptime](https://upptime.js.org/) for open source and Github Actions powered.
- I've been using UptimeRobot for monitoring, and while it can do a very simple status page, but you can't add incidents to it. 

I've been using UptimeRobot mainly as a [internal dashboard](https://stats.uptimerobot.com/gkYJ3HyMg) with my team, but seeing this issue inspired me to get around to [configure Instatus](https://neracoos-data-systems.instatus.com/) as a more public page with both UptimeRobot and Healthchecks.io reporting in to it.

**Comment by choldgraf** [comment]
### Is it possible to get a minimal version of this with Grafana?

I'm noting that this issue hasn't had movement in quite a long time, even though it remains an important part of making our communities confident that the infrastructure we run is reliable (as well as helping them debug whether there's something wrong with just them or with everybody).

I note that for the mybinder.org service, we [simply use a Grafana graph](https://mybinder.readthedocs.io/en/latest/about/status.html) that shows uptime over the last several hours:

![image](https://user-images.githubusercontent.com/1839645/235675181-57ee7d83-03a6-4a0d-9e6d-8d02df66453c.png)

Could we design a similar kind of plot for either our main 2i2c cluster, or somehow as an aggregate across all clusters, that just showed something like "% user session launch successes"? I know it's not quite as good of a metric as it is for Binder, which has lots of shorter launches, but something like this could serve as a placeholder until we have a more robust system in place...
