### ISSUE TITLE
Enable home directory backups with Azure File backups

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#624]
We use Azure File storage for home directories on Azure. It offers a [built in backup solution](https://docs.microsoft.com/en-us/azure/backup/azure-file-share-backup-overview) which we should enable and configure for all our deployments.

## Configuration options

Given these are *disaster recovery backups*, let's start by keeping a 5 day *daily* backup.

So we:

1. backup daily
2. retain for 5 days
3. Specify window of 22:00:00 (UTC-07:00) (this matches the EFS default window)

There seem to be direct correlation with usable config properties in https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/backup_policy_file_share

```[tasklist]
### Tasks
- [x] Enable Azure File backups via Terraform (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/backup_policy_file_share)
- [x] Deploy this to the UToronto cluster
- [x] Deploy this to the pchub cluster
```

**Comment by sgibson91** [comment]
I am not sure if I have access to the Azure account the pchub is deployed to?

**Comment by yuvipanda** [comment]
@sgibson91 ah, sorry - password for that should be in bitwarden!

**Comment by sgibson91** [comment]
Done!
