### ISSUE TITLE
Automated cluster setup for AWS

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#627]
### Description

We use `eksctl` for setting up AWS clusters. The setup isn't fully automated yet, however. We should use a combination of documentation + any required helper scripts to automate the entire setup. 

### Benefit

Automating our AWS clusters will allow us to standardize and automate our infrastructure, which is an important part of scaling our infrastructure and ensuring that it behaves consistently across all of our clusters.

### Tasks to complete

- [x] https://github.com/2i2c-org/infrastructure/issues/431
- [x] https://github.com/2i2c-org/pilot-hubs/issues/381
- [ ] https://github.com/2i2c-org/pilot-hubs/issues/737

~Port over this code for authentication:~ 
~https://github.com/yuvipanda/hubploy/blob/dfc00254abb30d8887230472e83b405ff5872933/hubploy/auth.py#L107~

**Comment by yuvipanda** [comment]
This is done now - we have https://github.com/2i2c-org/infrastructure/blob/master/docs/howto/operate/new-cluster/aws.md. eksctl creates the cluster, and we have terraform for all other work. I'd say we can close this for now.

The next step would be to remove eksctl completely, but I think that requires https://github.com/aws/containers-roadmap/issues/724 to be solved.
