### ISSUE TITLE
Back up user home directories

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#641]
### Description

We should automatically back up user home directories for our hubs. This would involve backing up whatever filesystem / NFS setup we have for each hub.

### Value / benefit

User data is the most non-replaceable thing in our hubs, so we should make sure that it is backed up in case of a problem that results in data loss. This would potentially affect any user since it is hard to know when data loss would occur!

### Implementation details

This will depend on the setup for filesystems that we have on each hub. In most cases, we'll use the managed filesystem service, but in others we may want to run our own NFS.

Check out the decisions that were made in https://github.com/2i2c-org/pilot-hubs/issues/640 to understand what the setup for each provider is.

### Tasks to complete

- [ ] Wait for https://github.com/2i2c-org/pilot-hubs/issues/640 so we have automation set up
- [ ] AWS https://github.com/2i2c-org/pilot-hubs/issues/623
- [ ] Azure: https://github.com/2i2c-org/pilot-hubs/issues/624
- [ ] Google Cloud: none yet
