### ISSUE TITLE
Reduce the costs of Dask Gateway workers

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#642]
### Description

We should put in work to ensure that Dask Gateway workers are as inexpensive as possible across each of the cloud providers.

### Value / benefit

Dask Gateway workers can grow in number very quickly, and if they aren't optimized properly then they can result in really high costs.

### Tasks to complete

- [x] Google Cloud: completed already, unsure what issue to ref
- [ ] AWS
  - [x] CarbonPlan: #605 
  - [ ] Generalize to AWS hub automation
- [ ] Azure: https://github.com/2i2c-org/pilot-hubs/issues/621
