### ISSUE TITLE
Migrate home directories of Pangeo users to the 2i2c Hub

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#653]
### Description

There are many users that are currently on the old Pangeo JupyterHub (at https://us-central1-b.gcp.pangeo.io/). We should migrate their user home directories to the hub that we are deploying.	

### Value / benefit

This will minimize the disruption that these users feel when they migrate from one hub to the next.

### Implementation details

~~We should understand whether we need to simply **point** the old hub's user filesystem to our new hub, or if we will have to **move** those filesystems instead.~~ **Update 2021/10/06:** We will be copying contents from one filesystem to another.

We'll need to make sure that the new hub is "ready to go" when this happens, because it will force many users to use the new hub since that's where their work will be. **Update 2021-10-06:** Sarah plans to make posts in [Pangeo discourse](https://discourse.pangeo.io) which will detail when the domain name switch will happen and when the last data migration happened before that date (a gap she will try to minimise to the best of her ability).

Since the new hub (https://pangeo.2i2c.cloud) has current users, at the hub database step of the move we will need to take care to _merge_ the two databases rather than overwrite them, so no one's access is lost.

The old hub is at https://us-central1-b.gcp.pangeo.io/.

### Tasks to complete

- [x] Collate resources we already have on how to move user directories
- [ ] ~~Investigate how to merge SQLite databases so we don't overwrite any of the new hub's user data~~ Not required. See https://github.com/2i2c-org/infrastructure/issues/653#issuecomment-946497123
- [x] Perform a migration
- [x] Update domain name for **staging**
  - Allow some time to pass to check everything is working fine on staging
  - https://github.com/2i2c-org/infrastructure/pull/772
- [ ] Perform a second data migration, to ensure any changes during the observation period is captured
	- Scheduled for **5th November 2021**

### Updates

- **2021-10-19:** https://github.com/2i2c-org/infrastructure/issues/653#issuecomment-946497123

**Comment by rabernat** [comment]
This issue is a MUST HAVE for the migration of the Pangeo GCP production cluster.

**Comment by sgibson91** [comment]
Docs we already have on moving user directories: https://pilot-hubs.2i2c.org/en/latest/howto/operate/move-hub.html

Since the new hub is using Google Filestore, I will need to mount that to a VM to be able to carry out the transfer. Instructions here: https://cloud.google.com/filestore/docs/creating-instances

I'm keen to use `rsync` rather than `scp` as I think it allows a more elegant handling of when to overwrite files https://linuxize.com/post/how-to-transfer-files-with-rsync-over-ssh/

This StackOverflow answer provides a Python class to merge SQLite db's https://stackoverflow.com/a/61954182

**Comment by sgibson91** [comment]
@paigem there is a wrinkle with migrating the COESSING users home directories. Since the COESSING hub uses Google for auth and the Pangeo hub uses GitHub, the paths won't match up even if I do transfer the data because they'll contain their emails, not GitHub handles. Therefore, I **strongly recommend** they download their work locally to upload to the new hub when they switch is made (both hubs will be available simultaneously for a short while) since there'll be no way for me to map emails to github handles.

**Comment by scottyhq** [comment]
> @scottyhq if either of you have the time to go through the GCP hub's nfs storage with me, I'd really appreciate it! It's not setup how I was expecting. 

Sorry, but i have only worked on the AWS infrastructure, so won't be able to help here

**Comment by rabernat** [comment]
Here is how I look at the home directories

- Go to https://console.cloud.google.com/filestore/instances/locations/us-central1-b/id/pangeo-uscentral1b;tab=overview?project=pangeo-181919
- Copy down the server address: `10.126.142.50:/home`
- Create a vanilla VM instance
- SSH into it
- Follow directions for [mounting filestores](https://cloud.google.com/filestore/docs/mounting-fileshares)
  ```
  sudo apt-get -y update &&
  sudo apt-get install nfs-common
  sudo mkdir -p /mnt/filestore
  /mnt/filestore/uscentral1b
  ls # -> all the directories are there
  ```

I don't know what the VM instance `homedir-manager-2` is.

**Comment by sgibson91** [comment]
Thanks @rabernat, the above worked. I wasn't aware the old cluster was using a filestore (which is good as that's what the new cluster is also using!). I've got the directories now :)

> I don't know what the VM instance homedir-manager-2 is.

I actually think this is the VM for the last migration as it has `ocean.pangeo.io/` under `rpa` 😂

**Comment by damianavila** [comment]
@sgibson91, quick question, what are the permissions and ownership in the `.ssh` directories?
In the past, I have experienced "Permission denied" issues when the ownership and the permissions were not the expected ones... For instance, for the files under `/home/ubuntu/.ssh`, I would expect ownership by the `ubuntu:ubuntu` user/group, the `.ssh` directory with `chmod 700`, public keys with `chmod 644`, and private ones with `chmod 600`. 
From your description of the problem, it seems some ownership/permission issue is being the underlying cause, IMHO.

**Comment by sgibson91** [comment]
> @sgibson91, quick question, what are the permissions and ownership in the `.ssh` directories? In the past, I have experienced "Permission denied" issues when the ownership and the permissions were not the expected ones... For instance, for the files under `/home/ubuntu/.ssh`, I would expect ownership by the `ubuntu:ubuntu` user/group, the `.ssh` directory with `chmod 700`, public keys with `chmod 644`, and private ones with `chmod 600`, IIRC. From your description of the problem, it seems some ownership/permission issue is being the underlying cause, IMHO.

I tried you suggestion @damianavila still with no luck 😭

```
ubuntu@pangeo-migration-vm:~$ ls -al
total 28
drwxr-xr-x 3 ubuntu ubuntu 4096 Oct 11 12:30 .
drwxr-xr-x 4 root   root   4096 Oct  6 10:06 ..
-rw------- 1 ubuntu ubuntu 2003 Oct 11 14:44 .bash_history
-rw-r--r-- 1 ubuntu ubuntu  220 Feb 25  2020 .bash_logout
-rw-r--r-- 1 ubuntu ubuntu 3771 Feb 25  2020 .bashrc
-rw-r--r-- 1 ubuntu ubuntu  807 Feb 25  2020 .profile
drwx------ 2 ubuntu ubuntu 4096 Oct 11 14:01 .ssh
-rw-r--r-- 1 ubuntu ubuntu    0 Oct 11 11:47 .sudo_as_admin_successful
ubuntu@pangeo-migration-vm:~$ ls -al .ssh/
total 20
drwx------ 2 ubuntu ubuntu 4096 Oct 11 14:01 .
drwxr-xr-x 3 ubuntu ubuntu 4096 Oct 11 12:30 ..
-rw------- 1 ubuntu ubuntu    0 Oct  6 10:05 authorized_keys
-rw-r--r-- 1 ubuntu ubuntu  222 Oct 11 11:58 known_hosts
-rw------- 1 ubuntu ubuntu 2610 Oct 14 13:47 nfs-transfer-key
-rw-r--r-- 1 ubuntu ubuntu  580 Oct 14 13:47 nfs-transfer-key.pub
ubuntu@pangeo-migration-vm:~$ chmod 700 ~/.ssh/nfs-transfer-key.pub
ubuntu@pangeo-migration-vm:~$ chmod 644 ~/.ssh/nfs-transfer-key
ubuntu@pangeo-migration-vm:~$ scp -r -p -i ~/.ssh/nfs-transfer-key ubuntu@104.154.182.94:/mnt/filestore/uscentral1b/aaronspring/Climpred_demo.ipynb /mnt/filestore/staging/aaronspring/
ubuntu@104.154.182.94: Permission denied (publickey).
ubuntu@pangeo-migration-vm:~$
```

**Comment by sgibson91** [comment]
> I think a reasonable course of action would be to just exclude the `$HOME/.ssh` directory from the migration completely.

I am not trying to migrate the .ssh folder, I am trying to give the old VM a public ssh key from the new VM so that I can scp/rsync the folders across! At the minute I cannot transfer anything!

> Also, please do not clobber my home directory. I have the same username on both systems.

Ideally, I would like to use rsync so the 2 are merged rather than overwritten but I guess the only way for me to guarantee that your home directory is not clobbered would be for me to exclude it and for you to migrate it yourself?

**Comment by sgibson91** [comment]
Ok, I'm now at the stage where I've managed to migrate 1 user home dir, but it has not migrated with the correct ownership. It has migrated with ownership `ubuntu:root` rather than `ubuntu:ubuntu`. I'm not sure if this is because I had to use `sudo` so `rsync` had permissions to create directories. I guess the worst case scenario here is that we run a recursive `chown` command over the filestore.

**Comment by sgibson91** [comment]
I opened https://github.com/2i2c-org/pilot-hubs/pull/753 to better document this process

**Comment by sgibson91** [comment]
Kicked off the migration process into the `prod` folder on the filestore

**Comment by sgibson91** [comment]
Migration completed!
