### ISSUE TITLE
Debug why helm chart/config connector doesn't create a new service account

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#669]
### Description

While working on https://github.com/2i2c-org/pilot-hubs/pull/662, it came to light that this should already be automated as part of our helm chart by including the appropriate config in the hub config file. However, when I tried to enable this for the Pangeo cluster, the service account (`staging-user-sa@{{ pangeo project ID }}.iam.gserviceaccount.com`) doesn't get created as expected. We need to work out why so we can automate this.

Annoyingly, there's no error message to help debug - I know it's not working because I can see from the Google Cloud IAM page that the service account is not being created.

For now, requester pays access for Pangeo is manually enabled so this isn't a blocking issue.

### Value / benefit

Automating this deployment will save us a lot of manual busywork :)

### Tasks to complete

- [x] Try the deploying the config to a cluster in `two-eye-two-see-sandbox`. This will help us figure out if it's a bug due to the special-casing of Pangeo or if it's a more general broken piece of config
- [ ] Set up this infrastructure with Terraform as a stop-gap solution (rather than using config connector)
- [ ] IDENTIFY AND SQUASH THE BUG! Update this with more details when they're available
- [ ] ...
- [ ] Document how the config snippet that enables requester pays access

### Updates

- **2021-09-10:** I tried deploying this in `two-eye-two-see-sandbox` and the `test-user-sa@two-eye-two-see-sandbox.iam.gserviceaccount.com` service account is not created there either. So this is a general problem.
- **2021-11-24**: Decided to use terraform rather than Config Connector: https://github.com/2i2c-org/infrastructure/issues/669#issuecomment-978039992

**Comment by sgibson91** [comment]
I tried deploying this in two-eye-two-see-sandbox and the test-user-sa@two-eye-two-see-sandbox.iam.gserviceaccount.com service account is not created there either. So this is a **general problem**, not Pangeo-specific.

**Comment by damianavila** [comment]
Looking quickly at the pangeo yaml files:

* https://github.com/2i2c-org/pilot-hubs/blob/master/config/hubs/pangeo-hubs.cluster.yaml
* https://github.com/2i2c-org/pilot-hubs/blob/master/config/hubs/pangeo-181919.cluster.yaml

I do not see `scratchBucket` stuff 
```
scratchBucket:
  enabled: true
```
on those above yaml files as I see, for instance, in the 2i2c cluster one: https://github.com/2i2c-org/pilot-hubs/blob/master/config/hubs/2i2c.cluster.yaml#L63-L70)

And that "key" is expected to be `enabled` to create the service account and friends: https://github.com/2i2c-org/pilot-hubs/blob/master/hub-templates/basehub/templates/cloud-resources/gcp/service-account.yaml#L1

Am I missing some other Pangeo config file where `scratchBucket` was enabled?

**Comment by sgibson91** [comment]
Sorry, it is not yet in the config file in master. But when I DO deploy with that config present - it doesn't work.

**Comment by yuvipanda** [comment]
There should be pods in the `config-connector` namespace that actually make this work - so look at the logs there to see how those pods are doing? The pilot-hubs cluster also has this working, so we can use that to evaluate differences.

**Comment by sgibson91** [comment]
I have deployed the cluster and hub again. In the namespace `configconnector-operator-system` there is a pod called `configconnector-operator-0`. I have pasted the logs from the pod below. They were quite long so I've also included the logs after they have been piped through `grep serviceaccount`. They also exceed GitHub's comment character limit 😱  so I will add them in separate comments.

**Comment by sgibson91** [comment]
<details><summary>Log output grepped for `serviceaccount`</summary>

```
{"severity":"error","msg":"Unable to get resource","name":"cnrm-deletiondefender","error":"unable to get mapping for resource: serviceaccounts \"cnrm-deletiondefender\" not found"}
{"severity":"error","msg":"Unable to get resource","name":"cnrm-resource-stats-recorder","error":"unable to get mapping for resource: serviceaccounts \"cnrm-resource-stats-recorder\" not found"}
{"severity":"error","msg":"Unable to get resource","name":"cnrm-webhook-manager","error":"unable to get mapping for resource: serviceaccounts \"cnrm-webhook-manager\" not found"}
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender created
serviceaccount/cnrm-resource-stats-recorder created
serviceaccount/cnrm-webhook-manager created
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
customresourcedefinition.apiextensions.k8s.io/iamserviceaccountkeys.iam.cnrm.cloud.google.com configured
customresourcedefinition.apiextensions.k8s.io/iamserviceaccounts.iam.cnrm.cloud.google.com configured
serviceaccount/cnrm-deletiondefender unchanged
serviceaccount/cnrm-resource-stats-recorder unchanged
serviceaccount/cnrm-webhook-manager unchanged
```

</details>

**Comment by sgibson91** [comment]
Other things to think about to get this working on Pangeo cluster:

- We should move the creation of buckets out of Terraform and into `config_connector` so we get a scratch bucket per scratch-bucket-enabled hub
- Switch naming convention of scratch buckets to match the form `${gcp-project-id}-${helm-release-name}-scratch-bucket` as is expected here: https://github.com/2i2c-org/infrastructure/blob/1e249202eee10244cd3e6b8e1fe60cc139ddfcfb/hub-templates/basehub/values.yaml#L358
- The service accounts also need the `roles/storage.object.creator` permission in order to write to the bucket

**Comment by choldgraf** [comment]
### Update: plan to use Terraform

In a team meeting, we discussed our options here and decided that using Terraform is the right way to go rather than the GCP "ConfigConnector" service, because this will be easier to do quickly.

**Comment by yuvipanda** [comment]
This is done except for https://github.com/2i2c-org/infrastructure/issues/1153! \o/ Thank you for blazing the trail here, @sgibson91!
