### ISSUE TITLE
Migrate and Decommission the COESSING hub

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#679]
### Description

In https://github.com/2i2c-org/pilot-hubs/issues/473, the end date for the COESSING hub is stated as August 31st. This date has now passed and so we should confirm the hub is no longer in use and remove it, especially since this particular hub is running in the old Pangeo project that we are planning to migrate away from.

In discussion with @paigem, the Community Representative for COESSING` and @rabernat` the Community Representative for Pangeo, we have agreed to migrate the COESSING users to the new Pangeo prod deployment at the same time as the rest of the Pangeo community.

### Tasks to complete

- [x] Complete https://github.com/2i2c-org/pilot-hubs/issues/482
- [x] Confirm with Community Representative that the COESSING users can move hubs
- [x] Community Representative is happy with the results
- [x] Decommission old infrastructure: see https://github.com/2i2c-org/infrastructure/issues/679#issuecomment-972913671

### Updates

- **2021-09-22:** Agreed to migrate the COESSING users onto the new Pangeo prod deployment at the same time as the rest of the Pangeo community

**Comment by choldgraf** [comment]
I believe that the Community Representative (@paigem) had a few workshop attendees that were interested in using the hub infrastructure on an ongoing basis.

Paige - we are in the midst of setting up a new Pangeo hub on 2i2c infrastructure. Would it make sense to just migrate those folks to the Pangeo hub? Or is there a strong reason to keep them on a COESSING-dedicated hub?

**Comment by paigem** [comment]
Thanks @sgibson91 for starting this issue and @choldgraf for pinging me about this!

I think in an ideal world, it would be great to keep the COESSING hub running. I want to avoid the idea of providing a valuable resource during the school, and then promptly removing access to it, particularly since most attendees don't have regular access to computing resources beyond their laptops. 

However, I realize that running and maintaining the COESSING hub comes at a cost (of both time and money). I know very little about the cost breakdowns, but if it were the case that the costs were similar in keeping up the COESSING hub versus migrating a few (probably <20) users to Pangeo hub, then I would definitely push to keep the COESSING hub open. I assume that it would be much more cost-effective to migrate a few users over, in which case it probably makes the most sense to do this. It would be great to have @rabernat's view here.

Note that we plan to host another COESSING workshop at the same time next year, and would likely want to have a COESSING hub again at that time.

If we decide to decommission the COESSING hub, it would be great if I could have a week or two before the hub goes down to contact all attendees and gather a list of folks who want to be migrated to Pangeo hub.

**Comment by sgibson91** [comment]
Thanks @paigem. There is another option here providing this is ok by @rabernat. Currently the COESSING hub is running on it's own cluster in the `pangeo-181919` project. That whole project is in the processing of being decommissioned as part of the migration to 2i2c. We now have a new cluster up-and-running with a hub that Ryan is using for his classes. We could migrate the COESSING hub to that cluster which would reduce costs since it's sharing a cluster with the main Pangeo project.

If we can't migrate it to the new Pangeo cluster, @choldgraf could we migrate the hub to one of our other dask-enabled clusters and work out a cost breakdown with Paige?

**Comment by rabernat** [comment]
> We could migrate the COESSING hub to that cluster which would reduce costs since it's sharing a cluster with the main Pangeo project.

Going forward, "that cluster" (i.e. the one we are using for my class) will become the main, public Pangeo cluster, replacing https://us-central1-b.gcp.pangeo.io/. I propose we leave the COESSING hub up and running on `pangeo-181919` until we are ready to announce the general migration to https://pangeo.2i2c.cloud/. At that time the COESSING users can migrate along with everyone else.

👍 ?

**Comment by sgibson91** [comment]
@paigem what do you think? :point_up:

**Comment by choldgraf** [comment]
I like @rabernat's proposal, provided that @paigem has no objections!

**Comment by paigem** [comment]
This sounds like a great plan! 

I assume that the COESSING users can have their files automatically transferred to the new hub when the time comes? (Just wondering if I need to give much warning to COESSING folks to back anything up, etc.)

**Comment by sgibson91** [comment]
@paigem yes we can do that!

**Comment by sgibson91** [comment]
I have updated the top comment to reflect the next steps we've agreed upon. We won't action anything on the COESSING hub until Pangeo prod has matured.

**Comment by sgibson91** [comment]
@paigem our timeline got pushed back and I now plan to tear down old infrastructure on **22nd November** - is that ok for the COESSING users?

**Comment by paigem** [comment]
Yes @sgibson91 that time frame will work just fine! Sorry for the delayed response.

I have made all participants aware of the switch, and written out instructions for how to join the Pangeo deployment. I have heard very little feedback, so my guess is that most people will not make the switch right now, but at least they now have instructions for how to get access to the Pangeo Hub in the future if they so choose! Thanks so much for keeping me in the loop about all this.

**Comment by sgibson91** [comment]
Great, thanks @paigem!

**Comment by sgibson91** [comment]
### Task List

#### Phase I

- [ ] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [ ] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
  - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration

#### Phase II - Hub Removal

- [ ] ~~(Optional) Migrate data from the hub~~
- [ ] Remove hub entry from the appropriate `*.cluster.yaml` file
- [ ] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [ ] Delete the hub's authentication application on auth0 or GitHub

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [ ] Run `terraform plan -destroy` and `terraform apply` to destroy the cluster
- [ ] Remove the following files from the repository:
  - The associated `*.cluster.yaml` file
  - The associated CI deployer key in `secrets/`
  - Remove the name of the cluster from [CI](https://github.com/2i2c-org/infrastructure/tree/master/.github/workflows/deploy-hubs.yaml)

**Comment by sgibson91** [comment]
The cluster is now torn down, folk should be using `us-central1-b.gcp.pangeo.io` instead. I will wait a few days before deleting the NFS server, just in case.

**Comment by choldgraf** [comment]
Shall we close this once the NFS server is deleted?

**Comment by sgibson91** [comment]
Yeah, that was my plan. I just didn't want to purge the NFS straightaway in case any panicked messages from users came in. If I don't hear anything by Monday, I'll delete the NFS server and close this.

**Comment by sgibson91** [comment]
The NFS server has now been deleted! 🎉
