### ISSUE TITLE
Team process for monitoring hub resource limits and whether we will hit them

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#709]
### Description

In https://github.com/2i2c-org/pilot-hubs/issues/708, an outage occurred because our NFS server for CloudBank hit its limit. We fixed it by simply in creasing the NFS size and then expanding the home directory disk to use the extra space.

This kind of thing will happen again in the future as our hub usage grows - maybe with NFS, maybe with other kinds of resources.

We should define a team process, or team mechanisms, to check up on the major resources that a hub needs, and ensure that the cloud infrastructure is providing enough. 

### Value / benefit

Processes like this would allow us to make intentional changes to the infrastructure, to get ahead of "resource limit" issues before we hit them. This will make it less likely that we have hub outages. It'll also give us peace of mind that we know more about what is going on in the clusters.

### Implementation details

I think as a first step we'll need to decide what are the major kinds of resources we should monitor. Some that come to mind (in part from our experiences with mybinder.org):

- Number of nodes in a cluster, and whether we are hitting a maximum soon
- NFS filesystem size
- Resources (RAM, CPU, etc) for critical pods (like the hub pod)
- Pod limits for nodes

And more generally, I suspect that [many of the incident reports from Binder](https://mybinder-sre.readthedocs.io/en/latest/incident-reports/index.html#incident-history) would be useful for us to consider as well.

### Tasks to complete

- [ ] Discuss and agree on what kinds of infrastructure limits / metrics we should pay attention to at a minimum
- [ ] Define a team process or a mechanism to track these limits
- [ ] ...figure out next steps from there
