### ISSUE TITLE
Deploy to a staging hub during our CI/CD

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#722]
### Description

Our hub deployment infrastructure currently does not do any "testing deploys" as a part of our PR workflow. This means that unpredictable things can happen when we make new changes to `main` on our pilot hubs. We should add in some testing that mimics what will happen when our hubs are actually deployed or updated as a part of our CI/CD.

### Value / benefit

There are a few benefits that this would have:

1. We will know more about what will happen when a PR is merged (e.g. unexpected YAML validation errors)
2. We will feel more confident in making changes to our pilot-hubs infrastructure, because we know the steps have been followed as a part of our tests
3. This will likely lead to more errors caught earlier on, and thus more stable infrastructure in general.

### Implementation details

We discussed pieces to this, here were a few ideas:

1. Keep a staging cluster that is constantly running. We use this cluster as part of our testing infrastructure. A PR will create a new hub and deploy changes to this cluster, and run some kind of test suite as well.
2. Keep a staging **hub** that is constantly running on one of our clusters. We use this hub to deploy changes each time they're made, and run tests on it.

See [this comment from yuvi](https://github.com/2i2c-org/pilot-hubs/pull/157#issuecomment-753937471) from a previous conversation around this.

### Tasks to complete

- [ ] Decide whether we want to deploy a "new staging hub" for each PR, or whether to deploy to a pre-existing one
- [ ] Confirm that there's not a generally better way of doing this
- [ ] Decide next steps and implement

**Comment by damianavila** [comment]
> Keep a staging hub that is constantly running on one of our clusters. We use this hub to deploy changes each time they're made, and run tests on it.

Since we are always deploying `staging` to our different clusters, why not pushing stuff to all the `staging`s (in each of our clusters) when we submit a PR?

In that way we test in all the different cluster we own (from different cloud providers) and we do not spend money in a dedicated stating cluster (that I think it is actually needed but since lower infra change less frequently, we may not need to have that one always up, right?).

**Comment by sgibson91** [comment]
> Since we are always deploying `staging` to our different clusters, why not pushing stuff to all the `staging`s (in each of our clusters) when we submit a PR?

This is how I envisaged implementing this

**Comment by damianavila** [comment]
> my inbox gets filled with notifications 

Jaja... btw, I am totally OK with the `test-this-pr` approach, that is how envisaged your envision 😉 .

**Comment by sgibson91** [comment]
> that is how envisaged your envision

Tbf, my dream workflow is to have bots working on my behalf so I can _really_ be on a beach somewhere

**Comment by damianavila** [comment]
![beach](https://user-images.githubusercontent.com/1640669/135914370-233b3321-0fd0-4ade-bc66-76d7c4c9187e.png)

**Comment by damianavila** [comment]
I could not resist the temptation 😜

**Comment by yuvipanda** [comment]
We do this now!
