### ISSUE TITLE
Convert AWS cluster deployment workflow to `eksctl`

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#737]
### Description

Our current process for deploying AWS clusters is to use `kops` (e.g., [docs on how to deploy an AWS cluster with `kops`](https://devops.2i2c.org/en/latest/howto/operate/new-cluster/aws.html)). However, in https://github.com/2i2c-org/infrastructure/issues/431#issuecomment-968495599 we've provided a rationale for **moving from `kops` to `eksctl`**. This issue will track that migration.

### Value / benefit

See https://github.com/2i2c-org/infrastructure/issues/431#issuecomment-968495599 for the rationale about "why `eksctl`" but more generally if we standardize on a single system for deploying clusters on AWS, it will help us reduce complexity and standardize our team practices, which will reduce uncertainty and information silos.

### Tasks to complete

- [x] Implement features needed to deploy a new cluster with `EKS`
  - [x] https://github.com/2i2c-org/infrastructure/issues/622
- [x] Document how to deploy a cluster with `eksctl`: https://github.com/2i2c-org/infrastructure/pull/885
- [ ] Migrate the hubs that use `kops` to instead use `eksctl`
  - [x] OpenScapes
  - [ ] Farallon https://github.com/2i2c-org/infrastructure/issues/737

(probably needs to be done by either @yuvipanda or @damianavila)

### Updates

- **2021-11-23**: We've re-scoped this to focus on migrating to `eksctl`

**Comment by damianavila** [comment]
@yuvipanda, do you have any notes from the `eksctl`-based deployment for the Carbonplan cluster?
IIRC you did the transition from kops into EKS, so maybe you already have some notes available to use as seed for the docs.

**Comment by yuvipanda** [comment]
This is done! https://github.com/2i2c-org/infrastructure/blob/master/docs/howto/operate/new-cluster/aws.md. However, I think farallon still needs to be moved.
