### ISSUE TITLE
Configure a single general purpose and more permissive network policy

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#741]
### Issue update

We currently look to try block all outbound egress besides to local IP ranges and the cloud metadata server.

---

@sgibson91 and I debugged a failure to make an outbound access from a user pod to an FTP server exposed via port 21.

We pinpointed the issue to be that we override the z2jh Helm chart's default value for `singleuser.networkPolicy.egress`. The Z2JH default is [very permissive](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/b6688f5482d0f1282afe1586ea52d85f89bae935/jupyterhub/values.yaml#L333-L344), it allows all outbound traffic except for traffic to a specific IP (169.254.169.254) associated with a so called cloud metadata server.

By overriding `singleuser.networkPolicy.egress`, we are reducing the egress permissions to exclude outbound FTP access.

## Discussion points

1. Do we want to retain this opt-in system to allow ports?
   1. If we want to retain this opt-in system to allow more egress ports, how to we make users aware about this, and how to we manage such opt-in requests?

### Reference

- [Z2JH: User pods NetworkPolicy resource's Helm template](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/b6688f5482d0f1282afe1586ea52d85f89bae935/jupyterhub/templates/singleuser/netpol.yaml#L63-L83)
- [Z2JH: Default values for the template above](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/values.yaml#L333-L344)
- [2i2c-org/pilot-hubs: basehub's default values (overrides z2jh defaults)](https://github.com/2i2c-org/pilot-hubs/blob/70c967d50cc14055e70f2cc5cb817347bec8b0d2/hub-templates/basehub/values.yaml#L153-L168)
- [2i2c-org/pilot-hubs: daskhub's default values (overrides basehub's defaults)](https://github.com/2i2c-org/pilot-hubs/blob/70c967d50cc14055e70f2cc5cb817347bec8b0d2/hub-templates/daskhub/values.yaml#L21-L44)
- [2i2c-org/pilot-hubs: pangeo hub's default values (overrides daskhub's defaults)](https://github.com/2i2c-org/pilot-hubs/pull/744)

### Tasks

- [x] https://github.com/2i2c-org/infrastructure/pull/774
- [x] https://github.com/2i2c-org/infrastructure/pull/782
- [x] https://github.com/2i2c-org/infrastructure/pull/788
- Document our network policies:
  - [x] for Hub Administrators: https://github.com/2i2c-org/pilot/pull/109
  - [x] and for 2i2c Hub Engineers: https://github.com/2i2c-org/infrastructure/pull/783

### Discussion captured from video conv

- @choldgraf mention it will be perceived as something is broken by users who doesn't understand this ahead of time.

**Comment by yuvipanda** [comment]
https://github.com/berkeley-dsep-infra/datahub/issues/2825 has more details on the FTP situation, and in https://github.com/berkeley-dsep-infra/datahub/issues/2825 there's discussion about just removing the outbound port restrictions. I think my inclination is that as long as we don't allow arbitrary access *inside* the cluster (where the user server can just hit the prometheus server, for example!) port restrictions are pointless. So if we can allow unrestricted access to the *internet* but not local cluster network we're all good.

**Comment by choldgraf** [comment]
> So if we can allow unrestricted access to the internet but not local cluster network we're all good.

This sounds like a good approach to me - most people that users assume that "everything is possible", so if we restrict things then it'll usually be confusing to folks. So I'd be +1 on making most outbound traffic possible by default and the action would be a community rep asking for something to be restricted for some reason.

**Comment by sgibson91** [comment]
> So if we can allow unrestricted access to the _internet_ but not local cluster network we're all good.

If I understand correctly, this is z2jh's default setting. So the implementation of this would look like a PR that removes all the `networkPolicy` keys from under `singleuser` in `basehub` and `daskhub`, right?

**Comment by yuvipanda** [comment]
@sgibson91 I think an easier way is to just test this on the pilot hubs cluster by locally doing a deploy just to the staging hub, starting a server there, and trying to access the prometheus server. Even better would be to run `nmap` from inside the user server, and scan everywhere to see what it can hit.

**Comment by sgibson91** [comment]
The config I locally deployed to 2i2c-staging to test this is represented in this draft PR: https://github.com/2i2c-org/pilot-hubs/pull/746

I then spun up my user server, opened a terminal and tried to `ssh` to the prometheus server IP address (that I got from `kubectl -n support get svc`). The result was that the connection timed out.

<img width="588" alt="Screenshot 2021-10-08 at 09 57 13" src="https://user-images.githubusercontent.com/44771837/136529590-5f0ffa41-4759-49a0-96ec-055c48cee4d7.png">

I also tried to run `nmap` as well but it wasn't available and I had trouble installing it.

<img width="1120" alt="Screenshot 2021-10-08 at 10 06 23" src="https://user-images.githubusercontent.com/44771837/136529771-cc602d94-70fd-48b0-b92e-b6428bd9edd2.png">

**Comment by damianavila** [comment]
> So one idea is to set a netpol saying allow 0.0.0.0/0 (all) except: and list 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 (private ip ranges) and the cloud metadata server also listed in thr z2jh defaults (169.254.169.254). Thats a simple rule that may work reliably without exceptions, or not.

This is an interesting idea...

**Comment by yuvipanda** [comment]
Thanks for testing this, @sgibson91! 

I looked at which ports the prometheus *service* exposes with `k -n support get svc`:

```
support-prometheus-server                    ClusterIP      10.0.21.196   <none>         80/TCP                       2y40d
```

so that's port 80, while ssh only tests port 22. So you can test it with `curl`, which I think should be installed - `curl http://<service-ip>:80`. 

We should also check if we can access the pod directly! By looking at `k -n support get pod -l component=server,app=prometheus -o yaml`, I can get its IP (`.status.podIP`) as well as the container port where the server is exposed (in this case, 9090). So you can test access to it with `curl http://<pod-ip>:9090` as well.

Sorry if my use of the word 'access' caused confusion here - I just meant network access, not ssh!

**Comment by choldgraf** [comment]
Is this issue also something that we could test as a part of CI/CD? (e.g., via https://github.com/2i2c-org/pilot-hubs/issues/722 + some test suite that were run on a new hub?). It would be really nice if we could tell our user communities that things like "security policies for the hubs" are also tested as part of our deployments, so we could have tests that did thins like "spin up a server, try to do something hub admins generally don't want people to do, confirm that it isn't possible in the staging hub"

**Comment by sgibson91** [comment]
I think we should look into this tool for security testing https://github.com/armosec/kubescape

**Comment by damianavila** [comment]
> I think we should look into this tool for security testing https://github.com/armosec/kubescape

💯

**Comment by sgibson91** [comment]
> I looked at which ports the prometheus _service_ exposes with `k -n support get svc`:
> 
> ```
> support-prometheus-server                    ClusterIP      10.0.21.196   <none>         80/TCP                       2y40d
> ```
> 
> so that's port 80, while ssh only tests port 22. So you can test it with `curl`, which I think should be installed - `curl http://<service-ip>:80`.
> 
> We should also check if we can access the pod directly! By looking at `k -n support get pod -l component=server,app=prometheus -o yaml`, I can get its IP (`.status.podIP`) as well as the container port where the server is exposed (in this case, 9090). So you can test access to it with `curl http://<pod-ip>:9090` as well.

<img width="621" alt="Screenshot 2021-10-11 at 17 40 57" src="https://user-images.githubusercontent.com/44771837/136825593-3d3fe22a-4dca-47d9-ac4c-e6488ebd10e1.png">

@yuvipanda yup, both of those are reachable
