### ISSUE TITLE
Bump version of dask-gateway helm chart we use to 0.9.1 or higher

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#745]
### Description

In https://github.com/2i2c-org/pilot-hubs/pull/743 I add a comment to the daskhub values file pointing out that disabling network policies that target the hub pod is a hack to allow us to use the dask-gateway helm chart. However, that hack is no longer required if we bump the version of dask-gateway to version 0.9.1 or higher.

### Value / benefit

- Config without workarounds/hacks is a step towards a robust and reliable service :)

### Tasks to complete

- [x] Decide on action to take.
- [ ] Wait for a Dask Gateway release >= 0.9.1 (https://github.com/dask/dask-gateway/releases)
- [ ] Bump to that version here 
- [ ] At the same time, [fix this networkpolicy section](https://github.com/2i2c-org/pilot-hubs/blob/ae862f09b536250588fb68f9dc32ce9f61d0ec6f/hub-templates/daskhub/values.yaml#L57-L59)

**Comment by damianavila** [comment]
@sgibson91 do you have more details on why this is not needed anymore in 0.9.1 or higher?

**Comment by sgibson91** [comment]
> @sgibson91 do you have more details on why this is not needed anymore in 0.9.1 or higher?

Ping @consideRatio since he is pretty confident in this

**Comment by consideRatio** [comment]
Yes, its fixed in unreleased dask-gateway helm chart by a PR of me, i added a label to a pod in that pr. No release has been made since.

On mobile, cant find link atm.

**Comment by damianavila** [comment]
Thanks for the links folks, the bumping idea LGTM when the dask-gateway helm chart containing this fix is released.

**Comment by damianavila** [comment]
And take care of [this one](https://github.com/sgibson91/pilot-hubs/blob/master/hub-templates/daskhub/values.yaml#L57-L59), right 😉  ?

**Comment by yuvipanda** [comment]
Definitely bumped up now, thanks to @consideRatio for making the releases!
