### ISSUE TITLE
[Decommission Hub] Wageningen University and Research

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#752]
### Summary

We've been running the WUR hub for the last year for @Chiil - he was using it for teaching and was advocating internally with WUR to use 2i2c for their hubs. They've recently decided to use national supercomputing facilities instead, so @Chiil will use that facility from now on, and will no longer use the WUR hub.

### Info

- **Community Representative:** @Chiil   
- **Link to New Hub issue:** #21 
- **Proposed end date:** 11/01/2021

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [x] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to
  - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration

#### Phase II - Hub Removal

- [x] ~(Optional) Migrate data from the hub~
- [x] Remove hub entry from the appropriate `*.cluster.yaml` file
- [x] Remove the hub deployment
  - `helm delete --namespace HUB_NAME HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [ ] Delete user home directory data

**Comment by choldgraf** [comment]
@chiil can you confirm that November 1st is an acceptable date to decommission the hub?

**Comment by Chiil** [comment]
Yes, the hub can be decommissioned immediately. We stopped using after our course ended in January.

**Comment by damianavila** [comment]
@Chiil, is there any data you or other users may want to migrate/backup before the decommission?

**Comment by Chiil** [comment]
All data can be removed.

**Comment by yuvipanda** [comment]
I've decomissioned the hub, but haven't deleted the data from the home directories yet.

**Comment by Chiil** [comment]
It was, I hope to return at one point!
