### ISSUE TITLE
Use sops for all our secrets

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#755]
### Description

Currently, we use `sops` for most of our secrets, but not all.

<img width="460" alt="image" src="https://user-images.githubusercontent.com/30430/137743175-60f9b35f-d793-4785-8d38-1b1fac688aa2.png">

These are all still GitHub secrets.

I think we should put *everything* in sops, *except* `GCP_KMS_DECRYPTOR_KEY` - as that is used by `sops`. So that GitHub secret bootstraps sops.

`

### Value / benefit

The primary advantage here is that secrets we manage with `sops` are version controlled, while github secrets are not

### Tasks to complete

- [x] Check each GitHub secret to see if it is still used. Remove unused ones
- [x] Move the auth0 secrets to be read from a common secrets file. 
- [ ] Document this as our secrets policy

### Updates

- [x] Remove `GKE_SA_KEY` - stopped being used in a967b9d031f62abe634bfd608c86027faa9f8a97
- [x] Remove `AUTH0_MANAGEMENT_CLIENT_SECRET, `AUTH0_MANAGEMENT_CLIENT_ID`, `PROXY_SECRET_KEY` - stopped being used in d6fc272b88eedebd257184b70230c1b34709b0ff

**Comment by yuvipanda** [comment]
We use `sops` for all our secrets, and this is ok now I think.
