### ISSUE TITLE
EVENT: OpenScapes NASA cloud hackathon in November

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#767]
### Description

OpenScapes is running their first cloud hackathon for the NASA community from November 15th through 19th. During that time they will have ~40 people accessing the OpenScapes instance, and then they will have access for the next 3 months.

### Value / benefit

This is just an issue so that we know to expect extra activity during the event.

### Tasks to complete

- [x] Update the OpenScapes environment to include Dask
- [ ] Pre-cook nodes before this event, following similar steps to what we did with [the paleohack cluster](https://github.com/2i2c-org/infrastructure/pull/789/files)
- [ ] Confirm event is over
- [ ] Scale cluster back down

**Comment by choldgraf** [comment]
superceded by https://github.com/2i2c-org/infrastructure/issues/810
