### ISSUE TITLE
Provide Pangeo users with documentation that is not maintained by the Pangeo community

### ISSUE THREAD

**Issue by rabernat** [2i2c-org/infrastructure#781]
### Description

To go along with #482, I would like to shut down https://pangeo.io/cloud.html and just point users at https://docs.2i2c.org/ instead. We should have one authoritative source of documentation for the hubs.

### Value / benefit

- Maintaining two documentation sites is extra work and could lead to user confusion
- There may be some useful tidbits in the Pangeo docs which will improve the 2i2c docs

### Implementation details

Ideally we would just put a link on https://pangeo.io/cloud.html which points to https://docs.2i2c.org/.

### Tasks to complete

- [ ] Someone read both documentation sites thoroughly and enumerate which items from the Pangeo docs are not covered by the 2i2c docs.
  - The [data 2i2c data management docs](https://docs.2i2c.org/en/latest/admin/howto/data.html) say nothing about working with object storage, while Pangeo docs have lots of detail about this.
  - 2i2c docs say nothing about Dask
  - Probably several others
- [ ] Someone makes a PR to https://github.com/2i2c-org/pilot with the documentation updates
- [ ] Someone makes a PR to https://github.com/pangeo-data/pangeo/blob/master/docs/cloud.rst redirecting to 2i2c docs.

**Comment by rabernat** [comment]
I think this is a great proposal Sarah. Something like this would be really valuable for 2i2c.

One challenge would be how to reconcile these docs with @choldgraf [self-declared pet peeve](https://twitter.com/choldgraf/status/1462253242226655233):

> A pet peeve: when I see blogs and online courses with better learning material than the documentation of a package. We need more people making upstream improvements to docs! That well-written blog post could be a PR to the package!

What would be the boundary between these 2i2c docs and the general jupyterhub docs?

My personal opinion is that, if 2i2c is offering a paid service, it should have dedicated, semi-standalone documentation about how to use that service, rather than just linking out to upstream docs.

**Comment by sgibson91** [comment]
Yeah, it's a fine line to walk. Linking out to upstream means the docs are less likely to go stale, reduces our maintenance burden and embodies the value of 2i2c in supporting open source tools. I think if we also want it to be generalisable and reusable across many types of communities, then the only thing we can do is provide the minimal basics to get people up and running and then say "if you're interested, here's a link that shows you how to do the really cool stuff".

If it's being delivered to a user community as part of a broader onboarding with other domain-specific/"this is how you do data science" aspects _not_ provided by 2i2c, it probably needs to be scoped quite tightly so as to not overwhelm the users in terms of info-dump too.

**Comment by choldgraf** [comment]
I agree with the content that is in @sgibson91's list. My main question is how this differs from docs.2i2c.org. For example:

- Logging on / off (missing)
- How to start / stop a server: https://docs.2i2c.org/en/latest/admin/howto/control-user-server.html#stop-or-start-a-user-s-server
- Selecting environments (profile-list options): https://docs.2i2c.org/en/latest/admin/howto/environment.html#create-multiple-environments-for-users-to-select
- Navigating jupyterlab (missing, more or less)
- Install a package at runtime: https://docs.2i2c.org/en/latest/admin/howto/environment.html#temporarily-install-packages-for-a-session
- Using nbgitpuller: https://docs.2i2c.org/en/latest/admin/howto/content.html#distribute-content-with-nbgitpuller

Is there something about the content at docs.2i2c.org that makes it seem not scoped for the kind of use-case we have in mind? Maybe we need to change the structure of those docs?

Or, maybe those docs *should* be in a separate place like **learn.2i2c.org**, and **docs.2i2c.org** would be focused on "about the service" style stuff?

**Comment by sgibson91** [comment]
(super quick response because I'm on my phone) I think the main difference is audience. The docs we have currently are aimed at people who have admin privileges on the hub, what about the users who don't have admin access and are being exposed to JupyterHub for the very first time through a 2i2c-operated hub? I think there could be some value in having a 2i2c-cheatsheet for how to get up and running with all of these things and then point them to Jupyter* docs for more advanced usage patterns.

(I think we're overloading the word user in this conversation related to a chat we had the other week: Users of JupyterHub the package are actually sysadmins and their users are another node down on the tree relative to us, the engineers who are thinking on a Kubernetes level.)

**Comment by choldgraf** [comment]
Right - so is this a good summary of the current thinking:

- docs.2i2c.org is for **hub administrators**, and for people who are trying to learn more about the service in general
- learn.2i2c.org would be for **hub users and hub administrators**
- the content currently at docs.2i2c.org is a combination of both user-personas right now, and there would be value in cleanly separating them.

**Comment by sgibson91** [comment]
I think learn.2i2c.org could be like a module that hub admins distribute to their users alongside some domain-specific info.

**Comment by choldgraf** [comment]
yeah that makes sense to me - basically learn.2i2c.org could be similar content to what is at 

I'm pretty sure that you're contractually obligated to use the phrase "Train the trainers" if you put a Carpentries hat on 😄

**Comment by sgibson91** [comment]
Yeah, I agree, which is why I think we should curate the minimum to get people going and then link out for anything more complex.
