### ISSUE TITLE
Document process for pre-warming a hub for an event

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#787]
### Description

Just before a hackathon starts, it's very helpful to 'pre-warm' a hub so users don't have to wait for new nodes to come up as they start the event. This is very important as losing 10-15 minutes to pods starting up can throw off the schedule of a workshop.

While z2jh has user placeholders, in practice we've found they aren't actually of much help. Instead, we should just create a new nodepool dedicated to the event and set minimum node count for the autoscaler on that.

### Value / benefit

Users don't have to wait for their pods to start, and can get started on their workshop right away.

### Implementation details

We should document how to create a new node pool and set a hub to use just that (https://github.com/2i2c-org/infrastructure/pull/573 is an example), and set minimum node count for that. In the long run, I think the right thing to do is to extract the google calendar based node placeholder (https://github.com/berkeley-dsep-infra/datahub/tree/staging/node-placeholder) from the Berkeley setup and use that.

We should also document a process for reducing the cluster after the event is over.

### Tasks to complete

- [x] https://github.com/2i2c-org/infrastructure/pull/811
- [x] Document our policy for how soon before an event we require notification in order to promise we'll have the infrastructure ready https://docs.2i2c.org/community/events/#notify-the-2i2c-team-about-the-event
- [ ] Document how to set up a node pool in each of the 3 cloud providers we support 
- [ ] Document this process for hub administrators in the 2i2c docs - see [this comment for one explanation](https://github.com/2i2c-org/infrastructure/issues/810#issuecomment-963779870)

**Comment by choldgraf** [comment]
Is it realistic to document a rough process before the OpenScapes event in 2 weeks? If so, perhaps we could write down a rough draft, and then follow it for OpenScapes to refine it further.

Another thing that we should do is document how/when to *scale down* a cluster, so that we aren't paying for a bunch of nodes we don't need.

**Comment by yuvipanda** [comment]
> This makes me wonder if it'd be useful to have an issue template specifically for events, so that we could have a task list to follow + fields for specific dates when the event is over etc

+1 I think it would be very helpful.

> Is it realistic to document a rough process before the OpenScapes event in 2 weeks? If so, perhaps we could write down a rough draft, and then follow it for OpenScapes to refine it further.

Yeah, I think this can be something we can glean from https://github.com/2i2c-org/infrastructure/issues/790 once that's complete

**Comment by damianavila** [comment]
> This makes me wonder if it'd be useful to have an issue template specifically for events, so that we could have a task list to follow + fields for specific dates when the event is over etc

Yep, let's do that!

> Is it realistic to document a rough process before the OpenScapes event in 2 weeks? If so, perhaps we could write down a rough draft, and then follow it for OpenScapes to refine it further.

Something to keep in mind... OpenScapes is AWS-based, so the warming process would be different since it would involve kops stuff instead of terraform, although conceptually, they should be similar, AFAIK (and if I am not missing some specificity).

**Comment by choldgraf** [comment]
@damianavila ah that's a good point - any chance you are willing to try out the pre-warming process for OpenScapes so that we can document it as well? I am happy to write the docs if I can follow along w/ what you do

**Comment by damianavila** [comment]
> any chance you are willing to try out the pre-warming process for OpenScapes

Sure, I will be happy to try it in the next few days and see how that works out.
I will update this issue once I have looked at it.

**Comment by choldgraf** [comment]
cool - I'll try and write up an issue template in the meantime!

**Comment by sgibson91** [comment]
We should also document how calculate how many nodes you'll need to scale-up to
