### ISSUE TITLE
Migrate Pangeo prod's URL

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#799]
### Summary

To complete the migration of the hub, Pangeo prod's URL needs to be redirected to the `pangeo.io` address from `2i2c.cloud`.

### Tasks to Complete

- [x] Create a CNAME record in `pangeo.io` that points to `pangeo.2i2c.cloud`
- [x] Update GitHub OAuth app to use `pangeo.io` URL
- [ ] https://github.com/2i2c-org/infrastructure/pull/812
