### ISSUE TITLE
Add libgfortran to the Toronto Hub

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#814]
### Description

We've been requested to add libgfortran to the U Toronto hub

### Value / benefit

This is a support request for a hub's community

### Implementation details

it should be add-able from conda forge with this recipe:

https://anaconda.org/conda-forge/libgfortran

here's the hub repo: https://github.com/utoronto-2i2c/jupyterhub-deploy

### Tasks to complete

- [x] Update staging with libgfortran
- [ ] Respond to FreshDesk ticket asking them to try this on staging
- [ ] Confirm that it works for them
- [ ] Merge into prod

**Comment by choldgraf** [comment]
cc'ing @consideRatio on this since he's the support steward currently - though I went ahead and gave a shot at implementing in https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/126 as well - maybe this just needs a review+merge

**Comment by GeorgianaElena** [comment]
Let's close this once the changes get into the production hub.

**Comment by choldgraf** [comment]
### Update from team meeting

This issue has been deployed to staging. We should deploy to production and then notify the person that opened the support ticket to tell them it should work now. Updated the top comment with these steps

**Comment by GeorgianaElena** [comment]
* Deployed to prod here :arrow_right:  https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/128
* Freshdesk ticked updated and resolved  :arrow_right: https://2i2c.freshdesk.com/a/tickets/39
* :tada:
