### ISSUE TITLE
Setting up read/write access to blob storage for Azure

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#840]
### Description

In our GCP and AWS deployments, we enable read/write access to object storage with _cloud_ service accounts that are assigned to _kubernetes_ service accounts. We should implement a similar connection on our Azure deployments.

Relates to: https://github.com/2i2c-org/infrastructure/issues/800
Initial discussion: https://github.com/2i2c-org/infrastructure/pull/838#issuecomment-972967683

### Value / benefit

We should have as similar as possible services/capabilities across the major cloud providers where possible

### Tasks to complete

**In terraform:**

- [ ] Create a service principal: https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals
  - https://github.com/2i2c-org/infrastructure/pull/864
- [ ] Assign blob storage read/write role to the service principal on behalf of the kubernetes application: https://docs.microsoft.com/en-us/azure/storage/blobs/assign-azure-role-data-access
- [ ] Create the blob storage

**Then:**

- [ ] Do further research around linking Azure roles and kubernetes service accounts
  - Some details here: https://docs.microsoft.com/en-us/azure/aks/manage-azure-rbac#create-role-assignments-for-users-to-access-cluster
- [ ] Add more tasks as they arise here

**Comment by sgibson91** [comment]
I think Azure's version of GCP's Config Connector is called Service Operator https://cloudblogs.microsoft.com/opensource/2020/06/25/announcing-azure-service-operator-kubernetes/
