### ISSUE TITLE
Automating deployments to Azure hubs

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#841]
### Description

Add deployer and CI support to automatically deploy upgrades to Azure-hosted hubs. This will complete the trifecta of automated deployments to the three major cloud providers we support.

### Value / benefit

- All major cloud deployments can be deployed automatically

### Tasks to complete

- [x] Update Azure Terraform config to create Service Principals for authentication beyond a raw kubeconfig files: https://github.com/2i2c-org/infrastructure/pull/864
- [x] Update the deployer to support Azure as an auth provider
- [x] Update the hub config's general schema to support Azure as a provider
- [ ] Update CI workflow to include Azure tools and deploy Azure hubs
  - Azure CLI is already available in GitHub-hosted runners, so this didn't need to be addressed: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#cli-tools

**Comment by choldgraf** [comment]
yesss 💯 

this is one that you'd like to prioritize soon, is that right @sgibson91 ? 

(oh I see it is already on the sprint board so I guess the answer is yes haha)

**Comment by sgibson91** [comment]
PR opened #865
