### ISSUE TITLE
[New Hub] CSU shared demo hub

### ISSUE THREAD

**Issue by ericvd-ucb** [2i2c-org/infrastructure#861]
### Hub Description

I would like to  build a new Demo hub for CSU
this one would be for CSU instructors
we could get them to try it out , do something light
with the caveat that if they want a full class load they should request their own hub

### Community Representative(s)

@sea

### Important dates

Spring 2022 we will have a workshop
Winter 2022 we will would let people know about it

### Target start date

 jan 2022

### Preferred Cloud Provider

No preference (default)

### Do you have your own billing account?

- [ ] Yes, I have my own billing account.

### Hub Authentication Type

GitHub Authentication (e.g., @mygithubhandle)

### Extra features you'd like to enable

- [ ] Dedicated Scalable Dask Cluster with [Dask Gateway](https://gateway.dask.org/)

### Hub Cluster

cloudbank

### Hub Template

basic

### Tasks to deploy the hub

- [ ] Engineer who will deploy the hub is assigned
- [ ] Deploy information filled in above
- [ ] Initial Hub deployment PR: <link to PR>
- [ ] Administrators able to log on
- [ ] Community Representative satisfied with hub environment
- [ ] Hub now in steady-state

**Comment by choldgraf** [comment]
pinging @sean-morris since this would be a cloudbank hub. have you two synced on this one already?

**Comment by sean-morris** [comment]
just syncing on this -- 9 days ago. My workflow in terms of catching these messages is not up to par!

**Comment by sean-morris** [comment]
@ericvd-ucb 
- did you mean github authentication? I was going with google-oauth2?
- I used csu.cloudbank.2i2c.cloud - do you want demo thrown in there? csu-demo.cloudbank.2i2c.cloud

**Comment by yuvipanda** [comment]
you can also use password auth, like in demo.cloudbank.2i2c.cloud

**Comment by yuvipanda** [comment]
I think this one exists now.
