### ISSUE TITLE
Set limits & resource requests on all core pods

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#90]
### Description

*All* 'core' pods should have CPU & memory requests and limits set.

### Benefit

Setting explicit resources makes sure that critical processes / pods don't run out of resources and die, as has happened in cases like https://github.com/2i2c-org/pilot-hubs/issues/526. This helps prevent major disruptions to the service.

### Tasks to complete

- [ ] Make sure all components from support/ chart have requests and limits set
- [ ] Make sure all hub components have requests and limits set
- [ ] Make sure all dask-gateway components have requests and limits set
