### ISSUE TITLE
Define values.schema.yaml for each Helm chart we manage to validate its passed values

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#937]
### Background

The `helm` CLI can automatically validate passed values (`--values my-prod-config.yaml --values my-common-config.yaml`) against a JSON schema file (`values.schema.json`) whenever one use it to do `helm template`, `helm install`, `helm upgrade`.

I'd like us to make use of that as well, just like we have done in the official JupyterHub Helm chart. It allows us to catch several configuration errors quickly.

In practice, working with a `.json` file is troublesome compared to working with a `.yaml` file. Due to that, I suggest we define a `values.schema.yaml` file and automatically convert it to a `values.schema.json` file that isn't git version controlled but automatically generated by a Python script whenever we need it.

### Tasks

- [ ] Define a values.schema.yaml file for each Helm chart we manage
- [ ] Have a script to generate a values.schema.json file based on this
- [ ] .gitignore relevant values.schema.json
- [ ] Make the deployer script able to do a schema validation given passed values for a hub

### Related
- Z2JH's schema file: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/schema.yaml
- Z2JH Python script to generate a values.schema.json from a yaml file: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/tools/generate-json-schema.py

**Comment by choldgraf** [comment]
> Due to that, I suggest we define a values.schema.yaml file and automatically convert it to a values.schema.json file that isn't git version controlled but automatically generated by a Python script whenever we need it.

+1 from me, I agree that YAML is more readable. The main reason I sometimes worry about YAML is that it can behave unexpectedly, but since we are taking YAML -> JSON and then immediately putting it through a _validator_, I think that's not a problem :-)

**Comment by damianavila** [comment]
>since we are taking YAML -> JSON and then immediately putting it through a validator, I think that's not a problem :-)

Yep, I agree with @choldgraf!

**Comment by consideRatio** [comment]
I tracked down and figured out I had to make the following changes to #436 when rebasing current master.

That is an example of something that could have been spotted before deployment by having a Helm chart embedded schema file (`values.schema.json`). In this case it wasn't a YAML typo but rather a change in the helm chart's values.

![image](https://user-images.githubusercontent.com/3837114/151051447-daf71d36-96f5-4183-add7-7f5e260abc08.png)
