### ISSUE TITLE
[Decommission Hub] Justice Innovation Lab

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#990]
### Summary

The Justice Innovation Lab has three hubs running as well as a dedicated cluster. They no longer have use for these hubs, and so we can decommission them.

Hub URLs:

- https://justiceinnovationlab.pilot.2i2c.cloud/
- https://staging.justiceinnovationlab.2i2c.cloud/
- https://justiceinnovationlab.2i2c.cloud/

### Info

- **Community Representative:** @JILPulvino
- **Link to New Hub issue:** https://github.com/2i2c-org/infrastructure/issues/288
- **Proposed end date:** Feb 14th

#### Phase I

- [x] Confirm with Community Representative that the hub is no longer in use and it's safe to decommission
- [x] Confirm if there is any data to migrate from the hub before decommissioning
  - [ ] If yes, confirm where the data should be migrated to -> we don't delete the CR
  - [ ] Confirm a 2i2c Engineer has access to the destination in order to complete the data migration

#### Phase II - Hub Removal

1. Remove 2i2c hub
- [ ] (Optional) Migrate data from the hub
- [x] Remove hub entry from the appropriate `*.cluster.yaml` file
- [x] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [x] Delete the hub's authentication application on auth0 or GitHub

2. Remove justiceinnovationlab hubs (staging and prod)
- [ ] (Optional) Migrate data from the hub
- [ ] Remove hub entry from the appropriate `*.cluster.yaml` file
- [ ] Remove the hub deployment
  - `helm --namespace HUB_NAME delete HUB_NAME`
  - `kubectl delete namespace HUB_NAME`
- [ ] Delete the hub's authentication application on auth0 or GitHub

#### Phase III - Cluster Removal

_This phase is only necessary for single hub clusters._

- [x] Run `terraform plan -destroy` and `terraform apply` to destroy the cluster
- [x] Remove the following files from the repository:
  - The associated `*.cluster.yaml` file
  - The associated CI deployer key in `secrets/`
  - Remove the name of the cluster from [CI](https://github.com/2i2c-org/infrastructure/tree/HEAD/.github/workflows/deploy-hubs.yaml)

**Comment by choldgraf** [comment]
Hey @JILPulvino - could you confirm that there is no data on the hub that you need to migrate off? Once you confirm the questions in `Phase I` above, we can decommision the hub/cluster.

**Comment by JILPulvino** [comment]
Can you say a little more about what the hub actually consists of? We are
no longer using the hub, but do want to retain the container registry set
up on our Azure account.

**Comment by sgibson91** [comment]
We're mostly talking about if there's any data left in people's home drives on the NFS store that people may want back (although if it's not been missed before now, likely it's not critical :slightly_smiling_face: ). It should be fine to leave the Container Registry as it is, but we would pull down the Kubernetes cluster and anything else associated with that.

**Comment by yuvipanda** [comment]
@JILPulvino it looks like maybe my access was also revoked, so I can't actually access the Azure portal nor can I authenticate via the commandline (for my user yuvipanda@2i2c.org) - can you re-establish it so I can remove the currently running resources?

**Comment by JILPulvino** [comment]
Oh yep, sorry about that!

**Comment by JILPulvino** [comment]
added as an owner on the subscription which I think should give you the
correct privileges.

**Comment by yuvipanda** [comment]
I've deleted everything except the ACR!

**Comment by JILPulvino** [comment]
Great, thank you!

**Comment by damianavila** [comment]
I think we can close this one now.
