### ISSUE TITLE
[New Hub] Australia National University education pilot

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#991]
### Hub Description

A team at the Australia National University is interested in partnering with 2i2c to host a JupyterHub for a class this semester. The environment shouldn't be too complicated, and it can run on our shared GKE cluster.

The class is for econometrics and will have about 150 students in it (though likely not all will log on at once).

Opportunity issue: https://github.com/2i2c-org/leads/issues/69

### Community Representative(s)

- @mmcky will be the community representative on this one 👋 

### Important dates

Class start: Feb 21st (more regular use on the 28th)
Class stop: June 21st

### Target start date

Feb 14th if possible, to have time to experiment

### Preferred Cloud Provider

No preference (default)

### Do you have your own billing account?

- [ ] Yes, I have my own billing account.

### Hub Authentication Type

Other (may not be possible, please specify in comments)

### Extra features you'd like to enable

- [ ] Dedicated Scalable Dask Cluster with [Dask Gateway](https://gateway.dask.org/)

### Other relevant information

**Authentication**: They'd prefer CILogon if possible. (it's not in our dropdown menu yet)
**Environment**: @mmcky should set up an environment repo by [following the instructions in this environment template](https://github.com/2i2c-org/hub-user-image-template/blob/main/README.md)

### Hub ID

anu

### Hub Cluster

`pilot.2i2c.cloud`

### Hub URL

`anu.pilot.2i2c.cloud`

### Hub Type

`educational`

### Tasks to deploy the hub

- [x] Engineer who will deploy the hub is assigned
- [x] Deploy information filled in above
- [x] Initial Hub deployment PR: https://github.com/2i2c-org/infrastructure/pull/993
- [x] Administrators able to log on
- [x] Community Representative satisfied with hub environment
- [x] Hub now in steady-state

**Comment by choldgraf** [comment]
Hey @mmcky - could you help us fill in the information above to the best of your knowledge? That will help folks set up a hub for you.

**Comment by mmcky** [comment]
hey @choldgraf for sure. I'll update this now.

**Comment by mmcky** [comment]
> Configuration Repo

I have setup: https://github.com/QuantEcon/jupyterhub-anu-emet2007 and will populate it with configuration as I learn about the setup.

**Comment by choldgraf** [comment]
> OK whoever wrote the docs are absolute legends 🙏

That would be @GeorgianaElena :-D

**Comment by mmcky** [comment]
thanks @GeorgianaElena -- nice work indeed. 

@choldgraf I have now setup an initial confutation with R/RStudio 

https://github.com/QuantEcon/jupyterhub-anu-emet2007

re: `content` (i.e. notebooks, datasets etc.) would we add it to that configuration repository?

**Comment by choldgraf** [comment]
for notebooks, you can store those wherever you like (generally people have a different repository for their content, though you could re-use your image repository if you wish). Check out: https://docs.2i2c.org/en/latest/admin/howto/content.html#distribute-content-with-nbgitpuller

**Comment by mmcky** [comment]
Thanks @choldgraf -- oh I see. We will use the course repository for content then and use `nbgitpuller` -- that way `students` would only see the course files (rather than all the configuration files at the root level. The binder preview just brought in the repo (but that makes a lot of sense)

 I'll look at seeing how `nbgitpuller` works.

**Comment by choldgraf** [comment]
Hey @GeorgianaElena - I think we should just deploy it with CILogon for now and see how that goes. We can use this email for an admin: `matthew.mckay@anu.edu.au `!

**Comment by GeorgianaElena** [comment]
There is now a hub running at [anu.pilot.2i2c.cloud](https://anu.pilot.2i2c.cloud) :rocket:

@mmcky, if you'd like to test it out, it would be super nice to know that:
- the login through CILogon + ANU works 
- you were logged into the hub with the `matthew.mckay@anu.edu.au` username
- you are an admin

**Comment by mmcky** [comment]
Thanks so much @GeorgianaElena. It is pretty cool to have it linked to ANU login system.

I just went through the login and it links to the ANU identity manager but end up at a screen to link to ORCID(?) -- which I don't know much about. So will need to learn a bit more about this `CILogon` system before asking students to login through it. Is an `orcid` id a necessary step? Will students need to setup `ORCID`?

**Comment by mmcky** [comment]
Hi @GeorgianaElena thanks for setting this up. I setup my own `ORCID` account that is liked to my ANU account. However I am getting the following errors:

When using a `private` browser session

<img width="825" alt="Screen Shot 2022-02-14 at 11 53 23 am" src="https://user-images.githubusercontent.com/8263752/153783385-6de36a1a-8358-4aa8-9b68-1f9c5f0b07a4.png">

When using the original browser session that linked the `ORCID` and `anu` accounts

<img width="825" alt="Screen Shot 2022-02-14 at 11 54 05 am" src="https://user-images.githubusercontent.com/8263752/153783426-3aee6c76-6047-40d0-9698-dbd0d454efc1.png">

**Comment by GeorgianaElena** [comment]
Hmm, I wasn't expecting an orcid id to be required. Wondering if this is something university specific...

Unfortunately the logs don't show off a lot of info about all the redirects, so just to make sure I understand what's happening:
1. You select ANU identity provider in the CILogon list here:
![anu-idp](https://user-images.githubusercontent.com/7579677/153866241-3324f7a2-65a4-4519-b204-e536e42eda5f.png)

2. You are redirected to the orcid login page **after** successfully logging in with you ANU account here:
![anu-cilogon](https://user-images.githubusercontent.com/7579677/153865388-c0d4950e-489d-45ce-8b54-3b8972620c60.png)

Found [these docs](https://libguides.anu.edu.au/ORCID) from ANU about ORCID but don't seem to explain why it is required in this case. But I will look into it more. Thanks for helping me debug this @mmcky :blossom:

**Comment by mmcky** [comment]
> Unfortunately the logs don't show off a lot of info about all the redirects

Roger that. OK So I think initially the only option that came up was ORCID (as `default`). In `safari` the drop down menu didn't appear to show any other options when landing on the `CILogon` page but when you type `Aus...` then the University Login option comes up as an option.

- [ ] Would there be a way to make `Australian National University` the default? Understand this might be a `CILogon` thing.

I can now login via `safari` and it takes me through to the server 🥳 and I see two folders `shared` and `shared-readwrite`

However it is interesting when I use `private window` the login won't resolve and I end up at the `400: Bad Request`. Must be a private window restriction issue on redirects perhaps. 

I have also tried logging in now via `Vivaldi` and had no issues at all.

So I will write a little login guide so others don't make the same mistake I did re: `ORCID` and select ANU via (typing). 

So the process for adding students to the cluster is:

https://docs.2i2c.org/en/latest/admin/howto/manage-users.html#to-add-users

- [ ] Do I just need to add their `anu` email addresses? 

Thanks @GeorgianaElena for working with me on setting this up.

**Comment by mmcky** [comment]
thanks @GeorgianaElena for all your help in setting this up.

> Is this a new private window? Did you manage to enter your ANU credentials or you were just redirected to this?

Yes, this was a new private window. Often use private window to login as a different user for the same service :-). I entered the ANU credentials OK but after authentication it ends up as the OAuth error. This is fine -- just thought I would feed that back. 

> There are some docs around logging out that might be of help also 

Thanks!

> The ANU hub is configured to allow anyone with a @anu.edu.au to login.

OK this is great and will require less admin. So if anyone at ANU can login we won't have to upload the class list or provide access to specific students. In theory this also means non-class students can login to the system with the ANU email. I think this is fine -- is there a way to check usage (i.e. if cluster spins up > # of enrolled students we would get notified, or are we able to restrict the slots that are available)? 

I will need to add some datasets to the root level of the instance and from the docs it looks like I just add them to the `shared` folder and they will show up for everyone. I will test this out today.

**Comment by mmcky** [comment]
@GeorgianaElena -- the lecturer for the course (@juergenmeinecke) was able to give this a spin today. He had some great feedback that I just wanted to pass through.

It worked really well -- and he plans to use `rstudio` this semester.

> Would it be possible to call the "shared" folder "datasets" instead?

I see this `shared` folder is throughout the `2i2c` documentation so I have advised this is probably not possible. One way to achieve this though would be with `nbgitpuller` and fetch a `repo` that contained a folder with `datasets`. 

I will follow these instructions

https://docs.2i2c.org/en/latest/admin/howto/content.html

> What's the correct logout/shutdown hygiene? From RStudio select "Quit the current R session" which displays a window "R Session ended" (see screenshot) and then close the browser tab?  From JupyterHub select "logout"?

When using the `rstudio`  -- to actually close the session and detach from the cluster should we teach students to logout of the `jupyterhub` window? Not just the `rstudio` session right. 

Also jupyterhub typically uses a timeout feature for idle instances when students login. Is this value public?

**Comment by GeorgianaElena** [comment]
> It worked really well -- and he plans to use rstudio this semester.

Yuhuuuu! I'm very happy  :tada: 

>  is there a way to check usage (i.e. if cluster spins up > # of enrolled students we would get notified, or are we able to restrict the slots that are available)?

Checking the admin panel should be the way to go I believe. In that panel should be visible all the users that logged into the hub at some point and if they have a server running at that moment.

> I see this shared folder is throughout the 2i2c documentation so I have advised this is probably not possible. One way to achieve this though would be with nbgitpuller and fetch a repo that contained a folder with datasets

Yes, nbgitpuller would be the way to go here.

> When using the rstudio -- to actually close the session and detach from the cluster should we teach students to logout of the jupyterhub window? Not just the rstudio session right. Also jupyterhub typically uses a timeout feature for idle instances when students login. Is this value public?

I guess the recommended way would be `Close rstudio session` -> `close user notebook server` -> `logout`.

But, yes, the user servers will be stopped after a certain timeout period. The defaults are:
- after 60min of inactivity, the kernel will be killed
- after 60min of no activity on the server (this is usually after the kernel has been stopped by the user, or killed)

But, we can definitely modify these for the ANU hub if you consider it necessary @mmcky

**Comment by mmcky** [comment]
thanks @GeorgianaElena 

> Checking the admin panel should be the way to go I believe.

Roger that. I guess I was wondering if there was a `grafana` page but no worries if not. I'll monitor the status via the admin page to see how many students are signing up etc. 

> The defaults are:

> after 60min of inactivity, the kernel will be killed
> after 60min of no activity on the server (this is usually after the kernel has been stopped by the user, or killed)

Great Thanks. No modification needed -- just wanted to let the students know.

**Comment by mmcky** [comment]
thanks @choldgraf and @GeorgianaElena for getting this setup so quickly for us ❤️ 

This course will start tomorrow and students will be introduced to `JupyterHub` ... I am really happy to see this project off the ground at `ANU`.

**Comment by choldgraf** [comment]
### Update: some feedback from Matt

Just had a quick chat about how things are going with Matt, some rough notes here:

- In general the hub is going really well at ANU
- "Jurgen was just super stoked about it, he would have paid for the service out of pocket if we hadn't gotten our budget approved"
- They've run it with 20-30 students in classes. About 105 total students have logged in.
- Occasionally the start times are slow for the students. (6-8 minutes). Rarely, probably related to new nodes spinning up (though 6-8 minutes seems like a lot even for expected scale-ups)
- Really loves the image repo template, it was super useful in setting up their environment.
- Next steps might be to ask for buy-ins at the college level.
- They are fine with us sending them one invoice at the end of the semester.
